.include "macro.inc"

.section .data, "wa"

/* Generated by spimdisasm 1.42.4 */

nonmatching D_800B0C98

dlabel D_800B0C98
    /* A0C98 800B0C98 10930880 */ .word _GLOBAL__I_DoPause__14CPauseMessagesi
    /* A0C9C 800B0C9C D09B0880 */ .word _GLOBAL__I_Pad0
    /* A0CA0 800B0CA0 80AC0880 */ .word _GLOBAL__I_WHITER
    /* A0CA4 800B0CA4 D8500980 */ .word _GLOBAL__I_DatPool
    /* A0CA8 800B0CA8 C8560980 */ .word _GLOBAL__I_OVR_Open__Fv
    /* A0CAC 800B0CAC 00DB0980 */ .word _GLOBAL__I_ctrlflag
    /* A0CB0 800B0CB0 20420A80 */ .word _GLOBAL__I_gplayer
    /* A0CB4 800B0CB4 DC4E0A80 */ .word _GLOBAL__I_CutScr
    /* A0CB8 800B0CB8 88EF0A80 */ .word _GLOBAL__I_DrawHelp__Fv
    /* A0CBC 800B0CBC 78750380 */ .word _GLOBAL__I_DrawLevelUpFlag
    /* A0CC0 800B0CC0 64E90480 */ .word _GLOBAL__I_QBack
    /* A0CC4 800B0CC4 4C290580 */ .word _GLOBAL__I_deltaload
    /* A0CC8 800B0CC8 14920680 */ .word _GLOBAL__I_questlog
    /* A0CCC 800B0CCC 50430780 */ .word _GLOBAL__I_pSTextBoxCels
    /* A0CD0 800B0CD0 A0B00780 */ .word _GLOBAL__I_flyflag
enddlabel D_800B0C98
