.include "macro.inc"

.section .data, "wa"

/* Generated by spimdisasm 1.42.4 */

nonmatching D_800E3BCC

dlabel D_800E3BCC
    /* D3BCC 800E3BCC 39000000 */ .word 0x00000039
    /* D3BD0 800E3BD0 3B000000 */ .word 0x0000003B
    /* D3BD4 800E3BD4 3D000000 */ .word 0x0000003D
    /* D3BD8 800E3BD8 3F000000 */ .word 0x0000003F
enddlabel D_800E3BCC

nonmatching D_800E3BDC

dlabel D_800E3BDC
    /* D3BDC 800E3BDC 28000000 */ .word 0x00000028
    /* D3BE0 800E3BE0 28000000 */ .word 0x00000028
    /* D3BE4 800E3BE4 28000000 */ .word 0x00000028
    /* D3BE8 800E3BE8 28000000 */ .word 0x00000028
enddlabel D_800E3BDC

nonmatching portal

dlabel portal
    /* D3BEC 800E3BEC */ .byte 0x00
    /* D3BED 800E3BED */ .byte 0x00
    /* D3BEE 800E3BEE */ .byte 0x00
    /* D3BEF 800E3BEF */ .byte 0x00
    /* D3BF0 800E3BF0 */ .byte 0x00
    /* D3BF1 800E3BF1 */ .byte 0x00
    /* D3BF2 800E3BF2 */ .byte 0x00
    /* D3BF3 800E3BF3 */ .byte 0x00
    /* D3BF4 800E3BF4 */ .byte 0x00
    /* D3BF5 800E3BF5 */ .byte 0x00
    /* D3BF6 800E3BF6 */ .byte 0x00
    /* D3BF7 800E3BF7 */ .byte 0x00
    /* D3BF8 800E3BF8 */ .byte 0x00
    /* D3BF9 800E3BF9 */ .byte 0x00
    /* D3BFA 800E3BFA */ .byte 0x00
    /* D3BFB 800E3BFB */ .byte 0x00
    /* D3BFC 800E3BFC */ .byte 0x00
    /* D3BFD 800E3BFD */ .byte 0x00
    /* D3BFE 800E3BFE */ .byte 0x00
    /* D3BFF 800E3BFF */ .byte 0x00
    /* D3C00 800E3C00 */ .byte 0x00
    /* D3C01 800E3C01 */ .byte 0x00
    /* D3C02 800E3C02 */ .byte 0x00
    /* D3C03 800E3C03 */ .byte 0x00
    /* D3C04 800E3C04 */ .byte 0x00
    /* D3C05 800E3C05 */ .byte 0x00
    /* D3C06 800E3C06 */ .byte 0x00
    /* D3C07 800E3C07 */ .byte 0x00
    /* D3C08 800E3C08 */ .byte 0x00
    /* D3C09 800E3C09 */ .byte 0x00
    /* D3C0A 800E3C0A */ .byte 0x00
    /* D3C0B 800E3C0B */ .byte 0x00
    /* D3C0C 800E3C0C */ .byte 0x00
    /* D3C0D 800E3C0D */ .byte 0x00
    /* D3C0E 800E3C0E */ .byte 0x00
    /* D3C0F 800E3C0F */ .byte 0x00
    /* D3C10 800E3C10 */ .byte 0x00
    /* D3C11 800E3C11 */ .byte 0x00
    /* D3C12 800E3C12 */ .byte 0x00
    /* D3C13 800E3C13 */ .byte 0x00
    /* D3C14 800E3C14 */ .byte 0x00
    /* D3C15 800E3C15 */ .byte 0x00
    /* D3C16 800E3C16 */ .byte 0x00
    /* D3C17 800E3C17 */ .byte 0x00
    /* D3C18 800E3C18 */ .byte 0x00
    /* D3C19 800E3C19 */ .byte 0x00
    /* D3C1A 800E3C1A */ .byte 0x00
    /* D3C1B 800E3C1B */ .byte 0x00
enddlabel portal
