.include "macro.inc"

.section .data, "wa"

/* Generated by spimdisasm 1.42.4 */

nonmatching TownConv

dlabel TownConv
    /* A8B80 800B8B80 00070106 */ .word 0x06010700
    /* A8B84 800B8B84 0204030B */ .word 0x0B030402
    /* A8B88 800B8B88 04080505 */ .word 0x05050804
    /* A8B8C 800B8B8C 060C070A */ .word 0x0A070C06
    /* A8B90 800B8B90 08090903 */ .word 0x03090908
enddlabel TownConv
