.include "macro.inc"

.section .data, "wa"

/* Generated by spimdisasm 1.42.4 */

nonmatching MsgStrings

dlabel MsgStrings
    /* C1A40 800D1A40 FA040000 */ .word 0x000004FA
    /* C1A44 800D1A44 CA020000 */ .word 0x000002CA
    /* C1A48 800D1A48 FA040000 */ .word 0x000004FA
    /* C1A4C 800D1A4C FA040000 */ .word 0x000004FA
    /* C1A50 800D1A50 FA040000 */ .word 0x000004FA
    /* C1A54 800D1A54 FA040000 */ .word 0x000004FA
    /* C1A58 800D1A58 D0020000 */ .word 0x000002D0
    /* C1A5C 800D1A5C FA040000 */ .word 0x000004FA
    /* C1A60 800D1A60 FA040000 */ .word 0x000004FA
    /* C1A64 800D1A64 FA040000 */ .word 0x000004FA
    /* C1A68 800D1A68 5A020000 */ .word 0x0000025A
    /* C1A6C 800D1A6C 8B030000 */ .word 0x0000038B
    /* C1A70 800D1A70 E5030000 */ .word 0x000003E5
    /* C1A74 800D1A74 B4020000 */ .word 0x000002B4
    /* C1A78 800D1A78 86040000 */ .word 0x00000486
    /* C1A7C 800D1A7C 74040000 */ .word 0x00000474
    /* C1A80 800D1A80 D1040000 */ .word 0x000004D1
    /* C1A84 800D1A84 6A040000 */ .word 0x0000046A
    /* C1A88 800D1A88 89040000 */ .word 0x00000489
    /* C1A8C 800D1A8C 71020000 */ .word 0x00000271
    /* C1A90 800D1A90 CC040000 */ .word 0x000004CC
    /* C1A94 800D1A94 1E020000 */ .word 0x0000021E
    /* C1A98 800D1A98 1B000000 */ .word 0x0000001B
    /* C1A9C 800D1A9C 33040000 */ .word 0x00000433
    /* C1AA0 800D1AA0 D8000000 */ .word 0x000000D8
    /* C1AA4 800D1AA4 34020000 */ .word 0x00000234
    /* C1AA8 800D1AA8 1C010000 */ .word 0x0000011C
    /* C1AAC 800D1AAC CD040000 */ .word 0x000004CD
    /* C1AB0 800D1AB0 2F010000 */ .word 0x0000012F
    /* C1AB4 800D1AB4 6B030000 */ .word 0x0000036B
    /* C1AB8 800D1AB8 CE040000 */ .word 0x000004CE
    /* C1ABC 800D1ABC 59000000 */ .word 0x00000059
    /* C1AC0 800D1AC0 5A040000 */ .word 0x0000045A
    /* C1AC4 800D1AC4 1A040000 */ .word 0x0000041A
    /* C1AC8 800D1AC8 4F040000 */ .word 0x0000044F
    /* C1ACC 800D1ACC 7D040000 */ .word 0x0000047D
    /* C1AD0 800D1AD0 81030000 */ .word 0x00000381
    /* C1AD4 800D1AD4 AC020000 */ .word 0x000002AC
    /* C1AD8 800D1AD8 85040000 */ .word 0x00000485
    /* C1ADC 800D1ADC 7D010000 */ .word 0x0000017D
    /* C1AE0 800D1AE0 F2040000 */ .word 0x000004F2
    /* C1AE4 800D1AE4 F0040000 */ .word 0x000004F0
    /* C1AE8 800D1AE8 F1040000 */ .word 0x000004F1
    /* C1AEC 800D1AEC 1C000000 */ .word 0x0000001C
enddlabel MsgStrings

nonmatching msgtable

dlabel msgtable
    /* C1AF0 800D1AF0 */ .byte 0x00
    /* C1AF1 800D1AF1 */ .byte 0x00
    /* C1AF2 800D1AF2 */ .byte 0x00
    /* C1AF3 800D1AF3 */ .byte 0x00
    /* C1AF4 800D1AF4 */ .byte 0x00
    /* C1AF5 800D1AF5 */ .byte 0x00
    /* C1AF6 800D1AF6 */ .byte 0x00
    /* C1AF7 800D1AF7 */ .byte 0x00
    /* C1AF8 800D1AF8 */ .byte 0x00
    /* C1AF9 800D1AF9 */ .byte 0x00
    /* C1AFA 800D1AFA */ .byte 0x00
    /* C1AFB 800D1AFB */ .byte 0x00
    /* C1AFC 800D1AFC */ .byte 0x00
    /* C1AFD 800D1AFD */ .byte 0x00
    /* C1AFE 800D1AFE */ .byte 0x00
    /* C1AFF 800D1AFF */ .byte 0x00
    /* C1B00 800D1B00 */ .byte 0x00
    /* C1B01 800D1B01 */ .byte 0x00
    /* C1B02 800D1B02 */ .byte 0x00
    /* C1B03 800D1B03 */ .byte 0x00
    /* C1B04 800D1B04 */ .byte 0x00
    /* C1B05 800D1B05 */ .byte 0x00
    /* C1B06 800D1B06 */ .byte 0x00
    /* C1B07 800D1B07 */ .byte 0x00
    /* C1B08 800D1B08 */ .byte 0x00
    /* C1B09 800D1B09 */ .byte 0x00
    /* C1B0A 800D1B0A */ .byte 0x00
    /* C1B0B 800D1B0B */ .byte 0x00
    /* C1B0C 800D1B0C */ .byte 0x00
    /* C1B0D 800D1B0D */ .byte 0x00
    /* C1B0E 800D1B0E */ .byte 0x00
    /* C1B0F 800D1B0F */ .byte 0x00
    /* C1B10 800D1B10 */ .byte 0x00
    /* C1B11 800D1B11 */ .byte 0x00
    /* C1B12 800D1B12 */ .byte 0x00
    /* C1B13 800D1B13 */ .byte 0x00
    /* C1B14 800D1B14 */ .byte 0x00
    /* C1B15 800D1B15 */ .byte 0x00
    /* C1B16 800D1B16 */ .byte 0x00
    /* C1B17 800D1B17 */ .byte 0x00
    /* C1B18 800D1B18 */ .byte 0x00
    /* C1B19 800D1B19 */ .byte 0x00
    /* C1B1A 800D1B1A */ .byte 0x00
    /* C1B1B 800D1B1B */ .byte 0x00
    /* C1B1C 800D1B1C */ .byte 0x00
    /* C1B1D 800D1B1D */ .byte 0x00
    /* C1B1E 800D1B1E */ .byte 0x00
    /* C1B1F 800D1B1F */ .byte 0x00
    /* C1B20 800D1B20 */ .byte 0x00
    /* C1B21 800D1B21 */ .byte 0x00
    /* C1B22 800D1B22 */ .byte 0x00
    /* C1B23 800D1B23 */ .byte 0x00
    /* C1B24 800D1B24 */ .byte 0x00
    /* C1B25 800D1B25 */ .byte 0x00
    /* C1B26 800D1B26 */ .byte 0x00
    /* C1B27 800D1B27 */ .byte 0x00
    /* C1B28 800D1B28 */ .byte 0x00
    /* C1B29 800D1B29 */ .byte 0x00
    /* C1B2A 800D1B2A */ .byte 0x00
    /* C1B2B 800D1B2B */ .byte 0x00
    /* C1B2C 800D1B2C */ .byte 0x00
    /* C1B2D 800D1B2D */ .byte 0x00
    /* C1B2E 800D1B2E */ .byte 0x00
    /* C1B2F 800D1B2F */ .byte 0x00
    /* C1B30 800D1B30 */ .byte 0x00
    /* C1B31 800D1B31 */ .byte 0x00
    /* C1B32 800D1B32 */ .byte 0x00
    /* C1B33 800D1B33 */ .byte 0x00
    /* C1B34 800D1B34 */ .byte 0x00
    /* C1B35 800D1B35 */ .byte 0x00
    /* C1B36 800D1B36 */ .byte 0x00
    /* C1B37 800D1B37 */ .byte 0x00
    /* C1B38 800D1B38 */ .byte 0x00
    /* C1B39 800D1B39 */ .byte 0x00
    /* C1B3A 800D1B3A */ .byte 0x00
    /* C1B3B 800D1B3B */ .byte 0x00
    /* C1B3C 800D1B3C */ .byte 0x00
    /* C1B3D 800D1B3D */ .byte 0x00
    /* C1B3E 800D1B3E */ .byte 0x00
    /* C1B3F 800D1B3F */ .byte 0x00
enddlabel msgtable
