.include "macro.inc"

.section .data, "wa"

/* Generated by spimdisasm 1.42.4 */

nonmatching LevPals

dlabel LevPals
    /* A9A58 800B9A58 */ .byte 0x00
    /* A9A59 800B9A59 */ .byte 0x01
    /* A9A5A 800B9A5A */ .byte 0x03
    /* A9A5B 800B9A5B */ .byte 0x04
    /* A9A5C 800B9A5C */ .byte 0x00
    /* A9A5D 800B9A5D */ .byte 0x01
    /* A9A5E 800B9A5E */ .byte 0x02
    /* A9A5F 800B9A5F */ .byte 0x04
    /* A9A60 800B9A60 */ .byte 0x00
    /* A9A61 800B9A61 */ .byte 0x01
    /* A9A62 800B9A62 */ .byte 0x03
    /* A9A63 800B9A63 */ .byte 0x04
    /* A9A64 800B9A64 */ .byte 0x00
    /* A9A65 800B9A65 */ .byte 0x01
    /* A9A66 800B9A66 */ .byte 0x02
    /* A9A67 800B9A67 */ .byte 0x03
    /* A9A68 800B9A68 */ .byte 0x00
enddlabel LevPals

nonmatching D_800B9A69

/* Automatically generated and unreferenced pad */
dlabel D_800B9A69
    /* A9A69 800B9A69 */ .byte 0x00
    /* A9A6A 800B9A6A */ .byte 0x00
    /* A9A6B 800B9A6B */ .byte 0x00
enddlabel D_800B9A69
