.include "macro.inc"

.section .data, "wa"

/* Generated by spimdisasm 1.42.4 */

.align 2
nonmatching D_800CC68C

dlabel D_800CC68C
    /* BC68C 800CC68C */ .asciz ":"
    /* 3A000000 */
.align 2
.align 2
    /* BC690 800CC690 */ .asciz "W"
    /* 57000000 */
.align 2
.align 2
    /* BC694 800CC694 */ .asciz ""
    /* 00000000 */
.align 2
    /* BC698 800CC698 1D000000 */ .word 0x0000001D
    /* BC69C 800CC69C 74000000 */ .word 0x00000074
    /* BC6A0 800CC6A0 91000000 */ .word 0x00000091
enddlabel D_800CC68C

nonmatching D_800CC6A4

dlabel D_800CC6A4
    /* BC6A4 800CC6A4 B9FFFFFF */ .word 0xFFFFFFB9
    /* BC6A8 800CC6A8 B8000000 */ .word 0x000000B8
    /* BC6AC 800CC6AC B8000000 */ .word 0x000000B8
    /* BC6B0 800CC6B0 B8000000 */ .word 0x000000B8
    /* BC6B4 800CC6B4 B8000000 */ .word 0x000000B8
    /* BC6B8 800CC6B8 B8000000 */ .word 0x000000B8
enddlabel D_800CC6A4
