.include "macro.inc"

.section .rodata, "a"

/* Generated by spimdisasm 1.42.4 */

nonmatching ClassStrTbl

dlabel ClassStrTbl
    /* 9A00 801435F8 BE040000 */ .word 0x000004BE
    /* 9A04 801435FC 75030000 */ .word 0x00000375
    /* 9A08 80143600 E8030000 */ .word 0x000003E8
enddlabel ClassStrTbl
