.include "macro.inc"

.section .rodata, "a"

/* Generated by spimdisasm 1.42.4 */

nonmatching VARCH40

dlabel VARCH40
    /* 7778 80141370 02040200 */ .word 0x00020402
    /* 777C 80141374 03080304 */ .word 0x04030803
    /* 7780 80141378 000F8E00 */ .word 0x008E0F00
    /* 7784 8014137C 332A2F2C */ .word 0x2C2F2A33
    /* 7788 80141380 00000000 */ .word 0x00000000
