.include "macro.inc"

.section .rodata, "a"

/* Generated by spimdisasm 1.42.4 */

nonmatching VARCH2

dlabel VARCH2
    /* 74A0 80141098 02040300 */ .word 0x00030402
    /* 74A4 8014109C 03010304 */ .word 0x04030103
    /* 74A8 801410A0 00083000 */ .word 0x00300800
    /* 74AC 801410A4 33272F2C */ .word 0x2C2F2733
    /* 74B0 801410A8 00000000 */ .word 0x00000000
