.include "macro.inc"

.section .rodata, "a"

/* Generated by spimdisasm 1.42.4 */

nonmatching HARCH17

dlabel HARCH17
    /* 788C 80141484 03020103 */ .word 0x03010203
    /* 7890 80141488 00080509 */ .word 0x09050800
    /* 7894 8014148C 8C2E002B */ .word 0x2B002E8C
    /* 7898 80141490 2D000000 */ .word 0x0000002D
