.include "macro.inc"

.section .rodata, "a"

/* Generated by spimdisasm 1.42.4 */

nonmatching VARCH19

dlabel VARCH19
    /* 75EC 801411E4 02030207 */ .word 0x07020302
    /* 75F0 801411E8 03040006 */ .word 0x06000403
    /* 75F4 801411EC 8D272F2C */ .word 0x2C2F278D
    /* 75F8 801411F0 00000000 */ .word 0x00000000
