.include "macro.inc"

.section .rodata, "a"

/* Generated by spimdisasm 1.42.4 */

nonmatching BIG9

dlabel BIG9
    /* 7ABC 801416B4 02020103 */ .word 0x03010202
    /* 7AC0 801416B8 01038587 */ .word 0x87850301
    /* 7AC4 801416BC 84860000 */ .word 0x00008684
