.include "macro.inc"

.section .rodata, "a"

/* Generated by spimdisasm 1.42.4 */

nonmatching VARCH26

dlabel VARCH26
    /* 7660 80141258 02040300 */ .word 0x00030402
    /* 7664 8014125C 03040301 */ .word 0x01030403
    /* 7668 80141260 00083000 */ .word 0x00300800
    /* 766C 80141264 33272F2C */ .word 0x2C2F2733
    /* 7670 80141268 00000000 */ .word 0x00000000
