.include "macro.inc"

.section .rodata, "a"

/* Generated by spimdisasm 1.42.4 */

nonmatching HARCH37

dlabel HARCH37
    /* 79CC 801415C4 03020103 */ .word 0x03010203
    /* 79D0 801415C8 0009050F */ .word 0x0F050900
    /* 79D4 801415CC 8C2E0028 */ .word 0x28002E8C
    /* 79D8 801415D0 2D000000 */ .word 0x0000002D
