.include "macro.inc"

.section .rodata, "a"

/* Generated by spimdisasm 1.42.4 */

nonmatching VARCH15

dlabel VARCH15
    /* 75A4 8014119C 02040300 */ .word 0x00030402
    /* 75A8 801411A0 03080304 */ .word 0x04030803
    /* 75AC 801411A4 00103000 */ .word 0x00301000
    /* 75B0 801411A8 332A2F2C */ .word 0x2C2F2A33
    /* 75B4 801411AC 00000000 */ .word 0x00000000
