.include "macro.inc"

.section .rodata, "a"

/* Generated by spimdisasm 1.42.4 */

nonmatching HARCH19

dlabel HARCH19
    /* 78AC 801414A4 03020103 */ .word 0x03010203
    /* 78B0 801414A8 00080508 */ .word 0x08050800
    /* 78B4 801414AC 8C2E002B */ .word 0x2B002E8C
    /* 78B8 801414B0 2D000000 */ .word 0x0000002D
