.include "macro.inc"

.section .rodata, "a"

/* Generated by spimdisasm 1.42.4 */

nonmatching HARCH36

dlabel HARCH36
    /* 79BC 801415B4 03020103 */ .word 0x03010203
    /* 79C0 801415B8 00090507 */ .word 0x07050900
    /* 79C4 801415BC 8C2E0028 */ .word 0x28002E8C
    /* 79C8 801415C0 2D000000 */ .word 0x0000002D
