.include "macro.inc"

.section .rodata, "a"

/* Generated by spimdisasm 1.42.4 */

nonmatching VARCH27

dlabel VARCH27
    /* 7674 8014126C 02040300 */ .word 0x00030402
    /* 7678 80141270 03040301 */ .word 0x01030403
    /* 767C 80141274 00063000 */ .word 0x00300600
    /* 7680 80141278 33272F2C */ .word 0x2C2F2733
    /* 7684 8014127C 00000000 */ .word 0x00000000
