.include "macro.inc"

.section .rodata, "a"

/* Generated by spimdisasm 1.42.4 */

nonmatching HARCH32

dlabel HARCH32
    /* 797C 80141574 03020303 */ .word 0x03030203
    /* 7980 80141578 0005020E */ .word 0x0E020500
    /* 7984 8014157C 312E0028 */ .word 0x28002E31
    /* 7988 80141580 2D000000 */ .word 0x0000002D
