.include "macro.inc"

.section .rodata, "a"

/* Generated by spimdisasm 1.42.4 */

nonmatching L3ConvTbl

dlabel L3ConvTbl
    /* EAEC 801486E4 */ .byte 0x08
    /* EAED 801486E5 */ .byte 0x0B
    /* EAEE 801486E6 */ .byte 0x03
    /* EAEF 801486E7 */ .byte 0x0A
    /* EAF0 801486E8 */ .byte 0x01
    /* EAF1 801486E9 */ .byte 0x09
    /* EAF2 801486EA */ .byte 0x0C
    /* EAF3 801486EB */ .byte 0x0C
    /* EAF4 801486EC */ .byte 0x06
    /* EAF5 801486ED */ .byte 0x0D
    /* EAF6 801486EE */ .byte 0x04
    /* EAF7 801486EF */ .byte 0x0D
    /* EAF8 801486F0 */ .byte 0x02
    /* EAF9 801486F1 */ .byte 0x0E
    /* EAFA 801486F2 */ .byte 0x05
    /* EAFB 801486F3 */ .byte 0x07
enddlabel L3ConvTbl

nonmatching L3UP

dlabel L3UP
    /* EAFC 801486F4 03030808 */ .word 0x08080303
    /* EB00 801486F8 000A0A00 */ .word 0x000A0A00
    /* EB04 801486FC 07070033 */ .word 0x33000707
    /* EB08 80148700 32003031 */ .word 0x31300032
    /* EB0C 80148704 00000000 */ .word 0x00000000
enddlabel L3UP

nonmatching L3DOWN

dlabel L3DOWN
    /* EB10 80148708 03030809 */ .word 0x09080303
    /* EB14 8014870C 07080907 */ .word 0x07090807
    /* EB18 80148710 00000000 */ .word 0x00000000
    /* EB1C 80148714 2F00002E */ .word 0x2E00002F
    /* EB20 80148718 00000000 */ .word 0x00000000
enddlabel L3DOWN

nonmatching L3HOLDWARP

dlabel L3HOLDWARP
    /* EB24 8014871C 03030808 */ .word 0x08080303
    /* EB28 80148720 000A0A00 */ .word 0x000A0A00
    /* EB2C 80148724 0707007D */ .word 0x7D000707
    /* EB30 80148728 7D007D7D */ .word 0x7D7D007D
    /* EB34 8014872C 00000000 */ .word 0x00000000
enddlabel L3HOLDWARP

nonmatching L3TITE1

dlabel L3TITE1
    /* EB38 80148730 04040707 */ .word 0x07070404
    /* EB3C 80148734 07070707 */ .word 0x07070707
    /* EB40 80148738 07070707 */ .word 0x07070707
    /* EB44 8014873C 07070707 */ .word 0x07070707
    /* EB48 80148740 07070000 */ .word 0x00000707
    /* EB4C 80148744 00000039 */ .word 0x39000000
    /* EB50 80148748 3A000038 */ .word 0x3800003A
    /* EB54 8014874C 37000000 */ .word 0x00000037
    /* EB58 80148750 00000000 */ .word 0x00000000
