.include "macro.inc"

.section .rodata, "a"

/* Generated by spimdisasm 1.42.4 */

nonmatching VARCH25

dlabel VARCH25
    /* 764C 80141244 02040300 */ .word 0x00030402
    /* 7650 80141248 03040301 */ .word 0x01030403
    /* 7654 8014124C 00073000 */ .word 0x00300700
    /* 7658 80141250 33272F2C */ .word 0x2C2F2733
    /* 765C 80141254 00000000 */ .word 0x00000000
