.include "macro.inc"

.section .rodata, "a"

/* Generated by spimdisasm 1.42.4 */

nonmatching VARCH20

dlabel VARCH20
    /* 75FC 801411F4 02030207 */ .word 0x07020302
    /* 7600 801411F8 03040009 */ .word 0x09000403
    /* 7604 801411FC 8D272F2C */ .word 0x2C2F278D
    /* 7608 80141200 00000000 */ .word 0x00000000
