.include "macro.inc"

.section .rodata, "a"

/* Generated by spimdisasm 1.42.4 */

nonmatching HARCH2

dlabel HARCH2
    /* 779C 80141394 03020303 */ .word 0x03030203
    /* 77A0 80141398 00020506 */ .word 0x06050200
    /* 77A4 8014139C 312E0028 */ .word 0x28002E31
    /* 77A8 801413A0 2D000000 */ .word 0x0000002D
