.include "macro.inc"

.section .rodata, "a"

/* Generated by spimdisasm 1.42.4 */

nonmatching VARCH21

dlabel VARCH21
    /* 760C 80141204 02030207 */ .word 0x07020302
    /* 7610 80141208 0304000E */ .word 0x0E000403
    /* 7614 8014120C 8D272F2C */ .word 0x2C2F278D
    /* 7618 80141210 00000000 */ .word 0x00000000
