.include "macro.inc"

.section .rodata, "a"

/* Generated by spimdisasm 1.42.4 */

nonmatching VARCH16

dlabel VARCH16
    /* 75B8 801411B0 02040300 */ .word 0x00030402
    /* 75BC 801411B4 03080304 */ .word 0x04030803
    /* 75C0 801411B8 000F3000 */ .word 0x00300F00
    /* 75C4 801411BC 332A2F2C */ .word 0x2C2F2A33
    /* 75C8 801411C0 00000000 */ .word 0x00000000
