.include "macro.inc"

.section .rodata, "a"

/* Generated by spimdisasm 1.42.4 */

nonmatching STAIRSUP

dlabel STAIRSUP
    /* 6FC 8013A2F4 04040D0D */ .word 0x0D0D0404
    /* 700 8013A2F8 0D0D0202 */ .word 0x02020D0D
    /* 704 8013A2FC 02020D0D */ .word 0x0D0D0202
    /* 708 8013A300 0D0D0D0D */ .word 0x0D0D0D0D
    /* 70C 8013A304 0D0D0042 */ .word 0x42000D0D
    /* 710 8013A308 06003F40 */ .word 0x403F0006
    /* 714 8013A30C 41000043 */ .word 0x43000041
    /* 718 8013A310 44000000 */ .word 0x00000044
    /* 71C 8013A314 00000000 */ .word 0x00000000
