.include "macro.inc"

.section .rodata, "a"

/* Generated by spimdisasm 1.42.4 */

nonmatching VARCH14

dlabel VARCH14
    /* 7590 80141188 02040300 */ .word 0x00030402
    /* 7594 8014118C 03080304 */ .word 0x04030803
    /* 7598 80141190 000D3000 */ .word 0x00300D00
    /* 759C 80141194 332A2F2C */ .word 0x2C2F2A33
    /* 75A0 80141198 00000000 */ .word 0x00000000
