.include "macro.inc"

.section .rodata, "a"

/* Generated by spimdisasm 1.42.4 */

nonmatching HARCH16

dlabel HARCH16
    /* 787C 80141474 03020303 */ .word 0x03030203
    /* 7880 80141478 0008050E */ .word 0x0E050800
    /* 7884 8014147C 312E002B */ .word 0x2B002E31
    /* 7888 80141480 2D000000 */ .word 0x0000002D
