.include "macro.inc"

.section .rodata, "a"

/* Generated by spimdisasm 1.42.4 */

nonmatching VARCH13

dlabel VARCH13
    /* 757C 80141174 02040300 */ .word 0x00030402
    /* 7580 80141178 03080304 */ .word 0x04030803
    /* 7584 8014117C 000E3000 */ .word 0x00300E00
    /* 7588 80141180 332A2F2C */ .word 0x2C2F2A33
    /* 758C 80141184 00000000 */ .word 0x00000000
