.include "macro.inc"

.section .rodata, "a"

/* Generated by spimdisasm 1.42.4 */

nonmatching HARCH4

dlabel HARCH4
    /* 77BC 801413B4 03020303 */ .word 0x03030203
    /* 77C0 801413B8 00020507 */ .word 0x07050200
    /* 77C4 801413BC 312E0028 */ .word 0x28002E31
    /* 77C8 801413C0 2D000000 */ .word 0x0000002D
