.include "macro.inc"

.section .rodata, "a"

/* Generated by spimdisasm 1.42.4 */

nonmatching L3ISLE5

dlabel L3ISLE5
    /* EC60 80148858 0202050E */ .word 0x0E050202
    /* EC64 8014885C 0D0C0707 */ .word 0x07070C0D
    /* EC68 80148860 07070000 */ .word 0x00000707
