.include "macro.inc"

.section .rodata, "a"

/* Generated by spimdisasm 1.42.4 */

nonmatching LAMPS

dlabel LAMPS
    /* 760 8013A358 02020D00 */ .word 0x000D0202
    /* 764 8013A35C 0D0D8100 */ .word 0x00810D0D
    /* 768 8013A360 82800000 */ .word 0x00008082
