.include "macro.inc"

.section .rodata, "a"

/* Generated by spimdisasm 1.42.4 */

nonmatching HARCH28

dlabel HARCH28
    /* 793C 80141534 03020303 */ .word 0x03030203
    /* 7940 80141538 00050207 */ .word 0x07020500
    /* 7944 8014153C 312E0028 */ .word 0x28002E31
    /* 7948 80141540 2D000000 */ .word 0x0000002D
