.include "macro.inc"

.section .rodata, "a"

/* Generated by spimdisasm 1.42.4 */

nonmatching VARCH6

dlabel VARCH6
    /* 74F0 801410E8 02040300 */ .word 0x00030402
    /* 74F4 801410EC 03010304 */ .word 0x04030103
    /* 74F8 801410F0 000D3000 */ .word 0x00300D00
    /* 74FC 801410F4 33272F2C */ .word 0x2C2F2733
    /* 7500 801410F8 00000000 */ .word 0x00000000
