.include "macro.inc"

.section .rodata, "a"

/* Generated by spimdisasm 1.42.4 */

nonmatching L3TITE2

dlabel L3TITE2
    /* EB5C 80148754 04040707 */ .word 0x07070404
    /* EB60 80148758 07070707 */ .word 0x07070707
    /* EB64 8014875C 07070707 */ .word 0x07070707
    /* EB68 80148760 07070707 */ .word 0x07070707
    /* EB6C 80148764 07070000 */ .word 0x00000707
    /* EB70 80148768 0000003D */ .word 0x3D000000
    /* EB74 8014876C 3E00003C */ .word 0x3C00003E
    /* EB78 80148770 3B000000 */ .word 0x0000003B
    /* EB7C 80148774 00000000 */ .word 0x00000000
