.include "macro.inc"

.section .rodata, "a"

/* Generated by spimdisasm 1.42.4 */

.align 2
nonmatching D_80139C24

dlabel D_80139C24
    /* 2C 80139C24 */ .asciz "psxsrc/gman.h"
    /* 7073787372632F676D616E2E68000000 */
.align 2
enddlabel D_80139C24

.align 2
nonmatching D_80139C34

dlabel D_80139C34
    /* 3C 80139C34 */ .asciz "rnd6.DUN"
    /* 726E64362E44554E00000000 */
.align 2
enddlabel D_80139C34

.align 2
nonmatching D_80139C40

dlabel D_80139C40
    /* 48 80139C40 */ .asciz "SKngDO.DUN"
    /* 534B6E67444F2E44554E0000 */
.align 2
enddlabel D_80139C40

.align 2
nonmatching D_80139C4C

dlabel D_80139C4C
    /* 54 80139C4C */ .asciz "Banner2.DUN"
    /* 42616E6E6572322E44554E00 */
.align 2
enddlabel D_80139C4C
