.include "macro.inc"

.section .rodata, "a"

/* Generated by spimdisasm 1.42.4 */

nonmatching HARCH18

dlabel HARCH18
    /* 789C 80141494 03020103 */ .word 0x03010203
    /* 78A0 80141498 00080506 */ .word 0x06050800
    /* 78A4 8014149C 8C2E002B */ .word 0x2B002E8C
    /* 78A8 801414A0 2D000000 */ .word 0x0000002D
