.include "macro.inc"

.section .rodata, "a"

/* Generated by spimdisasm 1.42.4 */

nonmatching VARCH1

dlabel VARCH1
    /* 748C 80141084 02040300 */ .word 0x00030402
    /* 7490 80141088 03010304 */ .word 0x04030103
    /* 7494 8014108C 00073000 */ .word 0x00300700
    /* 7498 80141090 33272F2C */ .word 0x2C2F2733
    /* 749C 80141094 00000000 */ .word 0x00000000
