.include "macro.inc"

.section .rodata, "a"

/* Generated by spimdisasm 1.42.4 */

nonmatching VARCH29

dlabel VARCH29
    /* 769C 80141294 02040300 */ .word 0x00030402
    /* 76A0 80141298 03040301 */ .word 0x01030403
    /* 76A4 8014129C 000E3000 */ .word 0x00300E00
    /* 76A8 801412A0 33272F2C */ .word 0x2C2F2733
    /* 76AC 801412A4 00000000 */ .word 0x00000000
