.include "macro.inc"

.section .rodata, "a"

/* Generated by spimdisasm 1.42.4 */

nonmatching HARCH34

dlabel HARCH34
    /* 799C 80141594 03020103 */ .word 0x03010203
    /* 79A0 80141598 00090506 */ .word 0x06050900
    /* 79A4 8014159C 8C2E0028 */ .word 0x28002E8C
    /* 79A8 801415A0 2D000000 */ .word 0x0000002D
