.include "macro.inc"

.section .rodata, "a"

/* Generated by spimdisasm 1.42.4 */

nonmatching spawntable

dlabel spawntable
    /* EABC 801486B4 */ .byte 0x00
    /* EABD 801486B5 */ .byte 0x0A
    /* EABE 801486B6 */ .byte 0x43
    /* EABF 801486B7 */ .byte 0x05
    /* EAC0 801486B8 */ .byte 0x2C
    /* EAC1 801486B9 */ .byte 0x06
    /* EAC2 801486BA */ .byte 0x09
    /* EAC3 801486BB */ .byte 0x00
    /* EAC4 801486BC */ .byte 0x00
    /* EAC5 801486BD */ .byte 0x1C
    /* EAC6 801486BE */ .byte 0x83
    /* EAC7 801486BF */ .byte 0x06
    /* EAC8 801486C0 */ .byte 0x09
    /* EAC9 801486C1 */ .byte 0x0A
    /* EACA 801486C2 */ .byte 0x05
enddlabel spawntable
    /* EACB 801486C3 */ .byte 0x00
