.include "macro.inc"

.section .rodata, "a"

/* Generated by spimdisasm 1.42.4 */

nonmatching VARCH31

dlabel VARCH31
    /* 76C4 801412BC 02040300 */ .word 0x00030402
    /* 76C8 801412C0 03040301 */ .word 0x01030403
    /* 76CC 801412C4 00103000 */ .word 0x00301000
    /* 76D0 801412C8 33272F2C */ .word 0x2C2F2733
    /* 76D4 801412CC 00000000 */ .word 0x00000000
