.include "macro.inc"

.section .rodata, "a"

/* Generated by spimdisasm 1.42.4 */

nonmatching VARCH32

dlabel VARCH32
    /* 76D8 801412D0 02040300 */ .word 0x00030402
    /* 76DC 801412D4 03040301 */ .word 0x01030403
    /* 76E0 801412D8 000F3000 */ .word 0x00300F00
    /* 76E4 801412DC 33272F2C */ .word 0x2C2F2733
    /* 76E8 801412E0 00000000 */ .word 0x00000000
