.include "macro.inc"

.section .rodata, "a"

/* Generated by spimdisasm 1.42.4 */

nonmatching VARCH3

dlabel VARCH3
    /* 74B4 801410AC 02040300 */ .word 0x00030402
    /* 74B8 801410B0 03010304 */ .word 0x04030103
    /* 74BC 801410B4 00063000 */ .word 0x00300600
    /* 74C0 801410B8 33272F2C */ .word 0x2C2F2733
    /* 74C4 801410BC 00000000 */ .word 0x00000000
