.include "macro.inc"

.section .rodata, "a"

/* Generated by spimdisasm 1.42.4 */

nonmatching HARCH22

dlabel HARCH22
    /* 78DC 801414D4 03020103 */ .word 0x03010203
    /* 78E0 801414D8 00080510 */ .word 0x10050800
    /* 78E4 801414DC 8C2E002B */ .word 0x2B002E8C
    /* 78E8 801414E0 2D000000 */ .word 0x0000002D
