.include "macro.inc"

.section .rodata, "a"

/* Generated by spimdisasm 1.42.4 */

nonmatching VARCH23

dlabel VARCH23
    /* 762C 80141224 02030207 */ .word 0x07020302
    /* 7630 80141228 03040010 */ .word 0x10000403
    /* 7634 8014122C 8D272F2C */ .word 0x2C2F278D
    /* 7638 80141230 00000000 */ .word 0x00000000
