.include "macro.inc"

.section .rodata, "a"

/* Generated by spimdisasm 1.42.4 */

nonmatching HARCH9

dlabel HARCH9
    /* 780C 80141404 03020303 */ .word 0x03030203
    /* 7810 80141408 00080509 */ .word 0x09050800
    /* 7814 8014140C 312E002B */ .word 0x2B002E31
    /* 7818 80141410 2D000000 */ .word 0x0000002D
