.include "macro.inc"

.section .rodata, "a"

/* Generated by spimdisasm 1.42.4 */

nonmatching spawntable_801486c4

dlabel spawntable_801486c4
    /* EACC 801486C4 */ .byte 0x00
    /* EACD 801486C5 */ .byte 0x0A
    /* EACE 801486C6 */ .byte 0x03
    /* EACF 801486C7 */ .byte 0x05
    /* EAD0 801486C8 */ .byte 0x0C
    /* EAD1 801486C9 */ .byte 0x06
    /* EAD2 801486CA */ .byte 0x09
    /* EAD3 801486CB */ .byte 0x00
    /* EAD4 801486CC */ .byte 0x00
    /* EAD5 801486CD */ .byte 0x0C
    /* EAD6 801486CE */ .byte 0x03
    /* EAD7 801486CF */ .byte 0x06
    /* EAD8 801486D0 */ .byte 0x09
    /* EAD9 801486D1 */ .byte 0x0A
    /* EADA 801486D2 */ .byte 0x05
enddlabel spawntable_801486c4
    /* EADB 801486D3 */ .byte 0x00
