.include "macro.inc"

.section .rodata, "a"

/* Generated by spimdisasm 1.42.4 */

.align 2
nonmatching D_8014D7F8

dlabel D_8014D7F8
    /* 13C00 8014D7F8 */ .asciz "psxsrc/gman.h"
    /* 7073787372632F676D616E2E68000000 */
.align 2
enddlabel D_8014D7F8

.align 2
nonmatching D_8014D808

dlabel D_8014D808
    /* 13C10 8014D808 */ .asciz "Warlord.DUN"
    /* 5761726C6F72642E44554E00 */
.align 2
enddlabel D_8014D808

.align 2
nonmatching D_8014D814

dlabel D_8014D814
    /* 13C1C 8014D814 */ .asciz "Vile14.DUN"
    /* 56696C6531342E44554E0000 */
.align 2
enddlabel D_8014D814

.align 2
nonmatching D_8014D820

dlabel D_8014D820
    /* 13C28 8014D820 */ .asciz "diab1.DUN"
    /* 64696162312E44554E000000 */
.align 2
enddlabel D_8014D820

.align 2
nonmatching D_8014D82C

dlabel D_8014D82C
    /* 13C34 8014D82C */ .asciz "diab2b.DUN"
    /* 6469616232622E44554E0000 */
.align 2
enddlabel D_8014D82C

.align 2
nonmatching D_8014D838

dlabel D_8014D838
    /* 13C40 8014D838 */ .asciz "diab2a.DUN"
    /* 6469616232612E44554E0000 */
.align 2
enddlabel D_8014D838

.align 2
nonmatching D_8014D844

dlabel D_8014D844
    /* 13C4C 8014D844 */ .asciz "diab3b.DUN"
    /* 6469616233622E44554E0000 */
.align 2
enddlabel D_8014D844

.align 2
nonmatching D_8014D850

dlabel D_8014D850
    /* 13C58 8014D850 */ .asciz "diab3a.DUN"
    /* 6469616233612E44554E0000 */
.align 2
enddlabel D_8014D850

.align 2
nonmatching D_8014D85C

dlabel D_8014D85C
    /* 13C64 8014D85C */ .asciz "diab4b.DUN"
    /* 6469616234622E44554E0000 */
.align 2
enddlabel D_8014D85C

.align 2
nonmatching D_8014D868

dlabel D_8014D868
    /* 13C70 8014D868 */ .asciz "diab4a.DUN"
    /* 6469616234612E44554E0000 */
.align 2
enddlabel D_8014D868
