.include "macro.inc"

.section .rodata, "a"

/* Generated by spimdisasm 1.42.4 */

nonmatching HARCH24

dlabel HARCH24
    /* 78FC 801414F4 03020103 */ .word 0x03010203
    /* 7900 801414F8 0008050E */ .word 0x0E050800
    /* 7904 801414FC 8C2E002B */ .word 0x2B002E8C
    /* 7908 80141500 2D000000 */ .word 0x0000002D
