.include "macro.inc"

.section .rodata, "a"

/* Generated by spimdisasm 1.42.4 */

nonmatching VARCH39

dlabel VARCH39
    /* 7764 8014135C 02040200 */ .word 0x00020402
    /* 7768 80141360 03080304 */ .word 0x04030803
    /* 776C 80141364 00108E00 */ .word 0x008E1000
    /* 7770 80141368 332A2F2C */ .word 0x2C2F2A33
    /* 7774 8014136C 00000000 */ .word 0x00000000
