.include "macro.inc"

.section .rodata, "a"

/* Generated by spimdisasm 1.42.4 */

nonmatching L3ISLE3

dlabel L3ISLE3
    /* EC40 80148838 0203050E */ .word 0x0E050302
    /* EC44 8014883C 04090D0C */ .word 0x0C0D0904
    /* EC48 80148840 1D1E191C */ .word 0x1C191E1D
    /* EC4C 80148844 1F200000 */ .word 0x0000201F
