.include "macro.inc"

.section .rodata, "a"

/* Generated by spimdisasm 1.42.4 */

.align 2
nonmatching D_801486A4

dlabel D_801486A4
    /* EAAC 801486A4 */ .asciz "psxsrc/gman.h"
    /* 7073787372632F676D616E2E68000000 */
.align 2
enddlabel D_801486A4

nonmatching spawntable

dlabel spawntable
    /* EABC 801486B4 */ .byte 0x00
    /* EABD 801486B5 */ .byte 0x0A
    /* EABE 801486B6 */ .byte 0x43
    /* EABF 801486B7 */ .byte 0x05
    /* EAC0 801486B8 */ .byte 0x2C
    /* EAC1 801486B9 */ .byte 0x06
    /* EAC2 801486BA */ .byte 0x09
    /* EAC3 801486BB */ .byte 0x00
    /* EAC4 801486BC */ .byte 0x00
    /* EAC5 801486BD */ .byte 0x1C
    /* EAC6 801486BE */ .byte 0x83
    /* EAC7 801486BF */ .byte 0x06
    /* EAC8 801486C0 */ .byte 0x09
    /* EAC9 801486C1 */ .byte 0x0A
    /* EACA 801486C2 */ .byte 0x05
enddlabel spawntable

dlabel native_pad_801486C3
    /* EACB 801486C3 */ .byte 0x00
enddlabel native_pad_801486C3

.include "macro.inc"

.section .rodata, "a"

/* Generated by spimdisasm 1.42.4 */

nonmatching spawntable_801486c4

dlabel spawntable_801486c4
    /* EACC 801486C4 */ .byte 0x00
    /* EACD 801486C5 */ .byte 0x0A
    /* EACE 801486C6 */ .byte 0x03
    /* EACF 801486C7 */ .byte 0x05
    /* EAD0 801486C8 */ .byte 0x0C
    /* EAD1 801486C9 */ .byte 0x06
    /* EAD2 801486CA */ .byte 0x09
    /* EAD3 801486CB */ .byte 0x00
    /* EAD4 801486CC */ .byte 0x00
    /* EAD5 801486CD */ .byte 0x0C
    /* EAD6 801486CE */ .byte 0x03
    /* EAD7 801486CF */ .byte 0x06
    /* EAD8 801486D0 */ .byte 0x09
    /* EAD9 801486D1 */ .byte 0x0A
    /* EADA 801486D2 */ .byte 0x05
enddlabel spawntable_801486c4

dlabel native_pad_801486D3
    /* EADB 801486D3 */ .byte 0x00
enddlabel native_pad_801486D3

.include "macro.inc"

.section .rodata, "a"

/* Generated by spimdisasm 1.42.4 */

nonmatching poolsub

dlabel poolsub
    /* EADC 801486D4 */ .byte 0x00
    /* EADD 801486D5 */ .byte 0x23
    /* EADE 801486D6 */ .byte 0x1A
    /* EADF 801486D7 */ .byte 0x24
    /* EAE0 801486D8 */ .byte 0x19
    /* EAE1 801486D9 */ .byte 0x1D
    /* EAE2 801486DA */ .byte 0x22
    /* EAE3 801486DB */ .byte 0x07
    /* EAE4 801486DC */ .byte 0x21
    /* EAE5 801486DD */ .byte 0x1C
    /* EAE6 801486DE */ .byte 0x1B
    /* EAE7 801486DF */ .byte 0x25
    /* EAE8 801486E0 */ .byte 0x20
    /* EAE9 801486E1 */ .byte 0x1F
    /* EAEA 801486E2 */ .byte 0x1E
enddlabel poolsub

dlabel native_pad_801486E3
    /* EAEB 801486E3 */ .byte 0x00
enddlabel native_pad_801486E3
