.include "macro.inc"

.section .rodata, "a"

/* Generated by spimdisasm 1.42.4 */

nonmatching VARCH9

dlabel VARCH9
    /* 752C 80141124 02040300 */ .word 0x00030402
    /* 7530 80141128 03080304 */ .word 0x04030803
    /* 7534 8014112C 00073000 */ .word 0x00300700
    /* 7538 80141130 332A2F2C */ .word 0x2C2F2A33
    /* 753C 80141134 00000000 */ .word 0x00000000
