.include "macro.inc"

.section .rodata, "a"

/* Generated by spimdisasm 1.42.4 */

nonmatching HARCH13

dlabel HARCH13
    /* 784C 80141444 03020303 */ .word 0x03030203
    /* 7850 80141448 0008050F */ .word 0x0F050800
    /* 7854 8014144C 312E002B */ .word 0x2B002E31
    /* 7858 80141450 2D000000 */ .word 0x0000002D
