.include "macro.inc"

.section .rodata, "a"

/* Generated by spimdisasm 1.42.4 */

nonmatching VARCH8

dlabel VARCH8
    /* 7518 80141110 02040300 */ .word 0x00030402
    /* 751C 80141114 03010304 */ .word 0x04030103
    /* 7520 80141118 000F3000 */ .word 0x00300F00
    /* 7524 8014111C 33272F2C */ .word 0x2C2F2733
    /* 7528 80141120 00000000 */ .word 0x00000000
