.include "macro.inc"

.section .rodata, "a"

/* Generated by spimdisasm 1.42.4 */

nonmatching VARCH37

dlabel VARCH37
    /* 773C 80141334 02040200 */ .word 0x00020402
    /* 7740 80141338 03080304 */ .word 0x04030803
    /* 7744 8014133C 000E8E00 */ .word 0x008E0E00
    /* 7748 80141340 332A2F2C */ .word 0x2C2F2A33
    /* 774C 80141344 00000000 */ .word 0x00000000
