.include "macro.inc"

.section .rodata, "a"

/* Generated by spimdisasm 1.42.4 */

nonmatching USTAIRS

dlabel USTAIRS
    /* 7A0C 80141604 04040303 */ .word 0x03030404
    /* 7A10 80141608 03030303 */ .word 0x03030303
    /* 7A14 8014160C 03030303 */ .word 0x03030303
    /* 7A18 80141610 03030303 */ .word 0x03030303
    /* 7A1C 80141614 03030000 */ .word 0x00000303
    /* 7A20 80141618 00000048 */ .word 0x48000000
    /* 7A24 8014161C 4D00004C */ .word 0x4C00004D
    /* 7A28 80141620 00000000 */ .word 0x00000000
    /* 7A2C 80141624 00000000 */ .word 0x00000000
