.include "macro.inc"

.section .data, "wa"

/* Generated by spimdisasm 1.42.4 */

nonmatching D_800B0CD4

dlabel D_800B0CD4
    /* A0CD4 800B0CD4 E8920880 */ .word _GLOBAL__D_DoPause__14CPauseMessagesi
    /* A0CD8 800B0CD8 80500980 */ .word _GLOBAL__D_DatPool
    /* A0CDC 800B0CDC D8DA0980 */ .word _GLOBAL__D_ctrlflag
    /* A0CE0 800B0CE0 F8410A80 */ .word _GLOBAL__D_gplayer
    /* A0CE4 800B0CE4 B44E0A80 */ .word _GLOBAL__D_CutScr
    /* A0CE8 800B0CE8 48EF0A80 */ .word _GLOBAL__D_DrawHelp__Fv
    /* A0CEC 800B0CEC 50750380 */ .word _GLOBAL__D_DrawLevelUpFlag
    /* A0CF0 800B0CF0 3CE90480 */ .word _GLOBAL__D_QBack
    /* A0CF4 800B0CF4 24290580 */ .word _GLOBAL__D_deltaload
    /* A0CF8 800B0CF8 EC910680 */ .word _GLOBAL__D_questlog
    /* A0CFC 800B0CFC 28430780 */ .word _GLOBAL__D_pSTextBoxCels
enddlabel D_800B0CD4
