.include "macro.inc"

.section .rodata, "a"

/* Generated by spimdisasm 1.42.4 */

nonmatching D_8014274C

dlabel D_8014274C
    /* 8B54 8014274C 00008290 */ .word 0x90820000
    /* 8B58 80142750 000083A0 */ .word 0xA0830000
    /* 8B5C 80142754 010082A0 */ .word 0xA0820001
    /* 8B60 80142758 01008424 */ .word 0x24840001
enddlabel D_8014274C

nonmatching D_8014275C

dlabel D_8014275C
    /* 8B64 8014275C 01008424 */ .word 0x24840001
    /* 8B68 80142760 2A108500 */ .word 0x0085102A
    /* 8B6C 80142764 F4FF4014 */ .word 0x1440FFF4
    /* 8B70 80142768 00000000 */ .word 0x00000000
enddlabel D_8014275C

nonmatching D_8014276C

dlabel D_8014276C
    /* 8B74 8014276C 0800E003 */ .word 0x03E00008
    /* 8B78 80142770 00000000 */ .word 0x00000000
enddlabel D_8014276C
