.include "macro.inc"

.section .rodata, "a"

/* Generated by spimdisasm 1.42.4 */

nonmatching D_80140EF4

dlabel D_80140EF4
    /* 72FC 80140EF4 3000B48F */ .word 0x8FB40030
    /* 7300 80140EF8 2C00B38F */ .word 0x8FB3002C
    /* 7304 80140EFC 2800B28F */ .word 0x8FB20028
    /* 7308 80140F00 2400B18F */ .word 0x8FB10024
    /* 730C 80140F04 2000B08F */ .word 0x8FB00020
    /* 7310 80140F08 3800BD27 */ .word 0x27BD0038
    /* 7314 80140F0C 0800E003 */ .word 0x03E00008
    /* 7318 80140F10 00000000 */ .word 0x00000000
enddlabel D_80140EF4
