.include "macro.inc"

.section .rodata, "a"

/* Generated by spimdisasm 1.42.4 */

nonmatching D_8011773C

dlabel D_8011773C
    /* 10773C 8011773C 70737873 */ .word 0x73787370
    /* 107740 80117740 72632F67 */ .word 0x672F6372
    /* 107744 80117744 6D616E2E */ .word 0x2E6E616D
    /* 107748 80117748 68000B80 */ .word 0x800B0068
enddlabel D_8011773C
