.include "macro.inc"

.section .rodata, "a"

/* Generated by spimdisasm 1.42.4 */

nonmatching D_801100AC

dlabel D_801100AC
    /* 1000AC 801100AC 70737873 */ .word 0x73787370
    /* 1000B0 801100B0 72632F67 */ .word 0x672F6372
    /* 1000B4 801100B4 6D616E2E */ .word 0x2E6E616D
    /* 1000B8 801100B8 68000400 */ .word 0x00040068
enddlabel D_801100AC
