.include "macro.inc"

.section .rodata, "a"

/* Generated by spimdisasm 1.42.4 */

.align 2
nonmatching D_80119490

dlabel D_80119490
    /* 109490 80119490 */ .asciz "psxsrc/gman.h"
    /* 7073787372632F676D616E2E68000000 */
.align 2
    /* 1094A0 801194A0 70737873 */ .word 0x73787370
    /* 1094A4 801194A4 72632F63 */ .word 0x632F6372
    /* 1094A8 801194A8 706C6179 */ .word 0x79616C70
    /* 1094AC 801194AC 65722E68 */ .word 0x682E7265
    /* 1094B0 801194B0 00D56800 */ .word 0x0068D500
enddlabel D_80119490
