.include "macro.inc"

.section .rodata, "a"

/* Generated by spimdisasm 1.42.4 */

.align 2
nonmatching D_80110F84

dlabel D_80110F84
    /* 100F84 80110F84 */ .asciz "psxsrc/gman.h"
    /* 7073787372632F676D616E2E68000000 */
.align 2
    /* 100F94 80110F94 70737873 */ .word 0x73787370
    /* 100F98 80110F98 72632F63 */ .word 0x632F6372
    /* 100F9C 80110F9C 706C6179 */ .word 0x79616C70
    /* 100FA0 80110FA0 65722E68 */ .word 0x682E7265
    /* 100FA4 80110FA4 00FBC500 */ .word 0x00C5FB00
enddlabel D_80110F84
