.include "macro.inc"

.section .rodata, "a"

/* Generated by spimdisasm 1.42.4 */

nonmatching D_80110BBC

dlabel D_80110BBC
    /* 100BBC 80110BBC 70737873 */ .word 0x73787370
    /* 100BC0 80110BC0 72632F67 */ .word 0x672F6372
    /* 100BC4 80110BC4 6D616E2E */ .word 0x2E6E616D
    /* 100BC8 80110BC8 68000400 */ .word 0x00040068
enddlabel D_80110BBC
