.include "macro.inc"

.section .rodata, "a"

/* Generated by spimdisasm 1.42.4 */

.align 2
nonmatching D_801103C0

dlabel D_801103C0
    /* 1003C0 801103C0 */ .asciz "psxsrc/gman.h"
    /* 7073787372632F676D616E2E68000000 */
.align 2
enddlabel D_801103C0

nonmatching _vt_17CTempPauseMessage

dlabel _vt_17CTempPauseMessage
    /* 1003D0 801103D0 00000000 */ .word 0x00000000
    /* 1003D4 801103D4 00000000 */ .word 0x00000000
    /* 1003D8 801103D8 00000000 */ .word 0x00000000
    /* 1003DC 801103DC C0920880 */ .word ___17CTempPauseMessage
    /* 1003E0 801103E0 00000000 */ .word 0x00000000
    /* 1003E4 801103E4 508E0880 */ .word InitPrintQuitMessage__17CTempPauseMessage
    /* 1003E8 801103E8 00000000 */ .word 0x00000000
    /* 1003EC 801103EC 588E0880 */ .word PrintQuitMessage__17CTempPauseMessagei
    /* 1003F0 801103F0 00000000 */ .word 0x00000000
    /* 1003F4 801103F4 D08F0880 */ .word LeavePrintQuitMessage__17CTempPauseMessagei
    /* 1003F8 801103F8 00000000 */ .word 0x00000000
    /* 1003FC 801103FC D88F0880 */ .word InitPrintAreYouSure__17CTempPauseMessage
    /* 100400 80110400 00000000 */ .word 0x00000000
    /* 100404 80110404 E08F0880 */ .word PrintAreYouSure__17CTempPauseMessagei
    /* 100408 80110408 00000000 */ .word 0x00000000
    /* 10040C 8011040C 58910880 */ .word LeavePrintAreYouSure__17CTempPauseMessagei
    /* 100410 80110410 00000000 */ .word 0x00000000
    /* 100414 80110414 60910880 */ .word InitPrintPaused__17CTempPauseMessage
    /* 100418 80110418 00000000 */ .word 0x00000000
    /* 10041C 8011041C 68910880 */ .word PrintPaused__17CTempPauseMessage
    /* 100420 80110420 00000000 */ .word 0x00000000
    /* 100424 80110424 B8920880 */ .word LeavePrintPaused__17CTempPauseMessage
enddlabel _vt_17CTempPauseMessage

nonmatching D_80110428

dlabel D_80110428
    /* 100428 80110428 00000000 */ .word 0x00000000
    /* 10042C 8011042C 00000000 */ .word 0x00000000
    /* 100430 80110430 00000000 */ .word 0x00000000
    /* 100434 80110434 7C930880 */ .word ___14CPauseMessages
    /* 100438 80110438 00000000 */ .word 0x00000000
    /* 10043C 8011043C 5C120180 */ .word __pure_virtual
    /* 100440 80110440 00000000 */ .word 0x00000000
    /* 100444 80110444 5C120180 */ .word __pure_virtual
    /* 100448 80110448 00000000 */ .word 0x00000000
    /* 10044C 8011044C 5C120180 */ .word __pure_virtual
    /* 100450 80110450 00000000 */ .word 0x00000000
    /* 100454 80110454 5C120180 */ .word __pure_virtual
    /* 100458 80110458 00000000 */ .word 0x00000000
    /* 10045C 8011045C 5C120180 */ .word __pure_virtual
    /* 100460 80110460 00000000 */ .word 0x00000000
    /* 100464 80110464 5C120180 */ .word __pure_virtual
    /* 100468 80110468 00000000 */ .word 0x00000000
    /* 10046C 8011046C 5C120180 */ .word __pure_virtual
    /* 100470 80110470 00000000 */ .word 0x00000000
    /* 100474 80110474 5C120180 */ .word __pure_virtual
    /* 100478 80110478 00000000 */ .word 0x00000000
    /* 10047C 8011047C 5C120180 */ .word __pure_virtual
enddlabel D_80110428
