.include "macro.inc"

.section .rodata, "a"

/* Generated by spimdisasm 1.42.4 */

.align 2
nonmatching D_80110FC0

dlabel D_80110FC0
    /* 100FC0 80110FC0 */ .asciz "psxsrc/gman.h"
    /* 7073787372632F676D616E2E68000000 */
.align 2
.align 2
    /* 100FD0 80110FD0 */ .asciz "psxsrc/cplayer.h"
    /* 7073787372632F63706C617965722E6800000000 */
.align 2
.align 2
    /* 100FE4 80110FE4 */ .asciz "psxsrc/FE.CPP"
    /* 7073787372632F46452E435050000000 */
.align 2
.align 2
    /* 100FF4 80110FF4 */ .asciz "EACLOGO.MOV"
    /* 4541434C4F474F2E4D4F5600 */
.align 2
    /* 101000 80111000 60C61380 */ .word 0x8013C660
    /* 101004 80111004 B0C61380 */ .word 0x8013C6B0
    /* 101008 80111008 E0C61380 */ .word 0x8013C6E0
    /* 10100C 8011100C ECC61380 */ .word 0x8013C6EC
    /* 101010 80111010 F8C61380 */ .word 0x8013C6F8
    /* 101014 80111014 20C71380 */ .word 0x8013C720
    /* 101018 80111018 58C81380 */ .word 0x8013C858
enddlabel D_80110FC0
