.include "macro.inc"

.section .rodata, "a"

/* Generated by spimdisasm 1.42.4 */

.align 2
nonmatching D_80110B98

dlabel D_80110B98
    /* 100B98 80110B98 */ .asciz "psxsrc/gman.h"
    /* 7073787372632F676D616E2E68000000 */
.align 2
    /* 100BA8 80110BA8 70737873 */ .word 0x73787370
    /* 100BAC 80110BAC 72632F63 */ .word 0x632F6372
    /* 100BB0 80110BB0 706C6179 */ .word 0x79616C70
    /* 100BB4 80110BB4 65722E68 */ .word 0x682E7265
    /* 100BB8 80110BB8 00DC0400 */ .word 0x0004DC00
enddlabel D_80110B98
