.include "macro.inc"

.section .rodata, "a"

/* Generated by spimdisasm 1.42.4 */

.align 2
nonmatching D_80110204

dlabel D_80110204
    /* 100204 80110204 */ .asciz "psxsrc/gman.h"
    /* 7073787372632F676D616E2E68000000 */
.align 2
enddlabel D_80110204

nonmatching D_80110214

dlabel D_80110214
    /* 100214 80110214 70737873 */ .word 0x73787370
    /* 100218 80110218 72632F43 */ .word 0x432F6372
    /* 10021C 8011021C 44494F2E */ .word 0x2E4F4944
    /* 100220 80110220 43505000 */ .word 0x00505043
enddlabel D_80110214

.align 2
nonmatching D_80110224

dlabel D_80110224
    /* 100224 80110224 */ .asciz "LUMP.BIN"
    /* 4C554D502E42494E00000000 */
.align 2
.align 2
    /* 100230 80110230 */ .asciz ""
    /* 00000000 */
.align 2
enddlabel D_80110224

nonmatching _vt_4CdIO

dlabel _vt_4CdIO
    /* 100234 80110234 00000000 */ .word 0x00000000
    /* 100238 80110238 00000000 */ .word 0x00000000
    /* 10023C 8011023C 00000000 */ .word 0x00000000
    /* 100240 80110240 846C0880 */ .word ___4CdIO
    /* 100244 80110244 00000000 */ .word 0x00000000
    /* 100248 80110248 DC6C0880 */ .word FileExists__4CdIOPCc
    /* 10024C 8011024C 00000000 */ .word 0x00000000
    /* 100250 80110250 006D0880 */ .word LoReadFileAtAddr__4CdIOPCcPUci
    /* 100254 80110254 00000000 */ .word 0x00000000
    /* 100258 80110258 9C6D0880 */ .word GetFileLength__4CdIOPCc
    /* 10025C 8011025C 00000000 */ .word 0x00000000
    /* 100260 80110260 C06D0880 */ .word LoSave__4CdIOPCcPUci
    /* 100264 80110264 00000000 */ .word 0x00000000
    /* 100268 80110268 E46E0880 */ .word LoStreamFile__4CdIOPCciPFPUciib_bii
enddlabel _vt_4CdIO
