.include "macro.inc"

.section .rodata, "a"

/* Generated by spimdisasm 1.42.4 */

nonmatching D_8010FFB4

dlabel D_8010FFB4
    /* FFFB4 8010FFB4 70737873 */ .word 0x73787370
    /* FFFB8 8010FFB8 72632F47 */ .word 0x472F6372
    /* FFFBC 8010FFBC 5055512E */ .word 0x2E515550
    /* FFFC0 8010FFC0 43505000 */ .word 0x00505043
enddlabel D_8010FFB4
