.include "macro.inc"

.section .rodata, "a"

/* Generated by spimdisasm 1.42.4 */

nonmatching D_80117928

dlabel D_80117928
    /* 107928 80117928 70737873 */ .word 0x73787370
    /* 10792C 8011792C 72632F67 */ .word 0x672F6372
    /* 107930 80117930 6D616E2E */ .word 0x2E6E616D
    /* 107934 80117934 68006C00 */ .word 0x006C0068
enddlabel D_80117928
