.include "macro.inc"

.section .rodata, "a"

/* Generated by spimdisasm 1.42.4 */

.align 2
nonmatching D_801189FC

dlabel D_801189FC
    /* 1089FC 801189FC */ .asciz "psxsrc/gman.h"
    /* 7073787372632F676D616E2E68000000 */
.align 2
enddlabel D_801189FC

nonmatching D_80118A0C

dlabel D_80118A0C
    /* 108A0C 80118A0C 736F7572 */ .word 0x72756F73
    /* 108A10 80118A10 63652F53 */ .word 0x532F6563
    /* 108A14 80118A14 4F554E44 */ .word 0x444E554F
    /* 108A18 80118A18 2E637070 */ .word 0x7070632E
    /* 108A1C 80118A1C 00CA6900 */ .word 0x0069CA00
enddlabel D_80118A0C
