.include "macro.inc"

.section .rodata, "a"

/* Generated by spimdisasm 1.42.4 */

.align 2
nonmatching D_801104B8

dlabel D_801104B8
    /* 1004B8 801104B8 */ .asciz "psxsrc/gman.h"
    /* 7073787372632F676D616E2E68000000 */
.align 2
enddlabel D_801104B8

nonmatching D_801104C8

dlabel D_801104C8
    /* 1004C8 801104C8 70737873 */ .word 0x73787370
    /* 1004CC 801104CC 72632F50 */ .word 0x502F6372
    /* 1004D0 801104D0 52494E54 */ .word 0x544E4952
    /* 1004D4 801104D4 592E4350 */ .word 0x50432E59
    /* 1004D8 801104D8 50000400 */ .word 0x00040050
enddlabel D_801104C8
