.include "macro.inc"

.section .rodata, "a"

/* Generated by spimdisasm 1.42.4 */

.align 2
nonmatching D_801188BC

dlabel D_801188BC
    /* 1088BC 801188BC */ .asciz "psxsrc/gman.h"
    /* 7073787372632F676D616E2E68000000 */
.align 2
.align 2
    /* 1088CC 801188CC */ .asciz "psxsrc/cplayer.h"
    /* 7073787372632F63706C617965722E6800000000 */
.align 2
enddlabel D_801188BC

.align 2
nonmatching D_801188E0

dlabel D_801188E0
    /* 1088E0 801188E0 */ .asciz "TOWN.TIL"
    /* 544F574E2E54494C00000000 */
.align 2
enddlabel D_801188E0

.align 2
nonmatching D_801188EC

dlabel D_801188EC
    /* 1088EC 801188EC */ .asciz "Sector1s.DUN"
    /* 536563746F7231732E44554E00000000 */
.align 2
enddlabel D_801188EC

.align 2
nonmatching D_801188FC

dlabel D_801188FC
    /* 1088FC 801188FC */ .asciz "Sector2s.DUN"
    /* 536563746F7232732E44554E00000000 */
.align 2
enddlabel D_801188FC

.align 2
nonmatching D_8011890C

dlabel D_8011890C
    /* 10890C 8011890C */ .asciz "Sector3s.DUN"
    /* 536563746F7233732E44554E00000000 */
.align 2
enddlabel D_8011890C

.align 2
nonmatching D_8011891C

dlabel D_8011891C
    /* 10891C 8011891C */ .asciz "Sector4s.DUN"
    /* 536563746F7234732E44554E00000000 */
.align 2
enddlabel D_8011891C

nonmatching D_8011892C

dlabel D_8011892C
    /* 10892C 8011892C 736F7572 */ .word 0x72756F73
    /* 108930 80118930 63652F54 */ .word 0x542F6563
    /* 108934 80118934 4F574E2E */ .word 0x2E4E574F
    /* 108938 80118938 63707000 */ .word 0x00707063
enddlabel D_8011892C
