.include "macro.inc"

.section .rodata, "a"

/* Generated by spimdisasm 1.42.4 */

.align 2
nonmatching D_80110078

dlabel D_80110078
    /* 100078 80110078 */ .asciz "psxsrc/gman.h"
    /* 7073787372632F676D616E2E68000000 */
.align 2
    /* 100088 80110088 70737873 */ .word 0x73787370
    /* 10008C 8011008C 72632F63 */ .word 0x632F6372
    /* 100090 80110090 706C6179 */ .word 0x79616C70
    /* 100094 80110094 65722E68 */ .word 0x682E7265
    /* 100098 80110098 00D10400 */ .word 0x0004D100
enddlabel D_80110078
