.include "macro.inc"

.section .rodata, "a"

/* Generated by spimdisasm 1.42.4 */

.align 2
nonmatching D_80110588

dlabel D_80110588
    /* 100588 80110588 */ .asciz "psxsrc/gman.h"
    /* 7073787372632F676D616E2E68000000 */
.align 2
enddlabel D_80110588

nonmatching D_80110598

dlabel D_80110598
    /* 100598 80110598 70737873 */ .word 0x73787370
    /* 10059C 8011059C 72632F47 */ .word 0x472F6372
    /* 1005A0 801105A0 4D414E2E */ .word 0x2E4E414D
    /* 1005A4 801105A4 43505000 */ .word 0x00505043
enddlabel D_80110598

nonmatching D_801105A8

dlabel D_801105A8
    /* 1005A8 801105A8 70737873 */ .word 0x73787370
    /* 1005AC 801105AC 72632F70 */ .word 0x702F6372
    /* 1005B0 801105B0 72696D70 */ .word 0x706D6972
    /* 1005B4 801105B4 6F6F6C2E */ .word 0x2E6C6F6F
    /* 1005B8 801105B8 68000400 */ .word 0x00040068
enddlabel D_801105A8
