.include "macro.inc"

.section .rodata, "a"

/* Generated by spimdisasm 1.42.4 */

nonmatching D_801100E0

dlabel D_801100E0
    /* 1000E0 801100E0 70737873 */ .word 0x73787370
    /* 1000E4 801100E4 72632F46 */ .word 0x462F6372
    /* 1000E8 801100E8 494C4549 */ .word 0x49454C49
    /* 1000EC 801100EC 4F2E4350 */ .word 0x50432E4F
    /* 1000F0 801100F0 50000000 */ .word 0x00000050
    /* 1000F4 801100F4 00000000 */ .word 0x00000000
enddlabel D_801100E0

nonmatching _vt_6FileIO

dlabel _vt_6FileIO
    /* 1000F8 801100F8 00000000 */ .word 0x00000000
    /* 1000FC 801100FC 00000000 */ .word 0x00000000
    /* 100100 80110100 00000000 */ .word 0x00000000
    /* 100104 80110104 CC580880 */ .word ___6FileIO
    /* 100108 80110108 00000000 */ .word 0x00000000
    /* 10010C 8011010C 5C120180 */ .word __pure_virtual
    /* 100110 80110110 00000000 */ .word 0x00000000
    /* 100114 80110114 5C120180 */ .word __pure_virtual
    /* 100118 80110118 00000000 */ .word 0x00000000
    /* 10011C 8011011C 5C120180 */ .word __pure_virtual
    /* 100120 80110120 00000000 */ .word 0x00000000
    /* 100124 80110124 5C120180 */ .word __pure_virtual
    /* 100128 80110128 00000000 */ .word 0x00000000
    /* 10012C 8011012C 5C120180 */ .word __pure_virtual
enddlabel _vt_6FileIO
