.include "macro.inc"

.section .rodata, "a"

/* Generated by spimdisasm 1.42.4 */

.align 2
nonmatching D_80110130

dlabel D_80110130
    /* 100130 80110130 */ .asciz "Can't init PC FS"
    /* 43616E277420696E697420504320465300000000 */
.align 2
enddlabel D_80110130

nonmatching D_80110144

dlabel D_80110144
    /* 100144 80110144 70737873 */ .word 0x73787370
    /* 100148 80110148 72632F50 */ .word 0x502F6372
    /* 10014C 8011014C 43494F2E */ .word 0x2E4F4943
    /* 100150 80110150 43505000 */ .word 0x00505043
enddlabel D_80110144

.align 2
nonmatching D_80110154

dlabel D_80110154
    /* 100154 80110154 */ .asciz "SLICERAM"
    /* 534C49434552414D00000000 */
.align 2
enddlabel D_80110154

nonmatching _vt_4PCIO

dlabel _vt_4PCIO
    /* 100160 80110160 00000000 */ .word 0x00000000
    /* 100164 80110164 00000000 */ .word 0x00000000
    /* 100168 80110168 00000000 */ .word 0x00000000
    /* 10016C 8011016C 1C610880 */ .word ___4PCIO
    /* 100170 80110170 00000000 */ .word 0x00000000
    /* 100174 80110174 74610880 */ .word FileExists__4PCIOPCc
    /* 100178 80110178 00000000 */ .word 0x00000000
    /* 10017C 8011017C B8610880 */ .word LoReadFileAtAddr__4PCIOPCcPUci
    /* 100180 80110180 00000000 */ .word 0x00000000
    /* 100184 80110184 7C620880 */ .word GetFileLength__4PCIOPCc
    /* 100188 80110188 00000000 */ .word 0x00000000
    /* 10018C 8011018C 34630880 */ .word LoSave__4PCIOPCcPUci
    /* 100190 80110190 00000000 */ .word 0x00000000
    /* 100194 80110194 08640880 */ .word LoStreamFile__4PCIOPCciPFPUciib_bii
enddlabel _vt_4PCIO
