.include "macro.inc"

.section .rodata, "a"

/* Generated by spimdisasm 1.42.4 */

.align 2
nonmatching D_80119B18

dlabel D_80119B18
    /* 109B18 80119B18 */ .asciz "psxsrc/gman.h"
    /* 7073787372632F676D616E2E68000000 */
.align 2
.align 2
    /* 109B28 80119B28 */ .asciz "psxsrc/cplayer.h"
    /* 7073787372632F63706C617965722E6800000000 */
.align 2
.align 2
    /* 109B3C 80119B3C */ .asciz "Warlord2.DUN"
    /* 5761726C6F7264322E44554E00000000 */
.align 2
.align 2
    /* 109B4C 80119B4C */ .asciz "Bonestr1.DUN"
    /* 426F6E65737472312E44554E00000000 */
.align 2
.align 2
    /* 109B5C 80119B5C */ .asciz "Banner1.DUN"
    /* 42616E6E6572312E44554E00 */
.align 2
.align 2
    /* 109B68 80119B68 */ .asciz "Blind1.DUN"
    /* 426C696E64312E44554E0000 */
.align 2
.align 2
    /* 109B74 80119B74 */ .asciz "Blood2.DUN"
    /* 426C6F6F64322E44554E0000 */
.align 2
    /* 109B80 80119B80 B0F31580 */ .word 0x8015F3B0
    /* 109B84 80119B84 18F41580 */ .word 0x8015F418
    /* 109B88 80119B88 F0F31580 */ .word 0x8015F3F0
    /* 109B8C 80119B8C 04F41580 */ .word 0x8015F404
    /* 109B90 80119B90 38F41580 */ .word 0x8015F438
    /* 109B94 80119B94 2CF41580 */ .word 0x8015F42C
    /* 109B98 80119B98 C0F31580 */ .word 0x8015F3C0
    /* 109B9C 80119B9C 38F41580 */ .word 0x8015F438
    /* 109BA0 80119BA0 D8F31580 */ .word 0x8015F3D8
enddlabel D_80119B18
