.include "macro.inc"

.section .rodata, "a"

/* Generated by spimdisasm 1.42.4 */

.align 2
nonmatching D_80110AC4

dlabel D_80110AC4
    /* 100AC4 80110AC4 */ .asciz "psxsrc/gman.h"
    /* 7073787372632F676D616E2E68000000 */
.align 2
.align 2
    /* 100AD4 80110AD4 */ .asciz "psxsrc/cplayer.h"
    /* 7073787372632F63706C617965722E6800000000 */
.align 2
enddlabel D_80110AC4

.align 2
nonmatching D_80110AE8

dlabel D_80110AE8
    /* 100AE8 80110AE8 */ .asciz "File:%s Line:%d\t%s\n"
    /* 46696C653A2573204C696E653A25640925730A00 */
.align 2
enddlabel D_80110AE8

.align 2
nonmatching D_80110AFC

dlabel D_80110AFC
    /* 100AFC 80110AFC */ .asciz "FADE OUT - MISSED %s %d"
    /* 46414445204F5554202D204D495353454420257320256400 */
.align 2
enddlabel D_80110AFC

.align 2
nonmatching D_80110B14

dlabel D_80110B14
    /* 100B14 80110B14 */ .asciz "psxsrc/TONY.CPP"
    /* 7073787372632F544F4E592E43505000 */
.align 2
enddlabel D_80110B14

nonmatching D_80110B24

dlabel D_80110B24
    /* 100B24 80110B24 44454D4F */ .word 0x4F4D4544
    /* 100B28 80110B28 */ .byte 0x50
    /* 100B29 80110B29 */ .byte 0x41
    /* 100B2A 80110B2A */ .byte 0x44
enddlabel D_80110B24

nonmatching D_80110B2B

dlabel D_80110B2B
    /* 100B2B 80110B2B */ .byte 0x30
    /* 100B2C 80110B2C 2E444154 */ .word 0x5441442E
    /* 100B30 80110B30 */ .byte 0x00
enddlabel D_80110B2B

/* Preserved alignment bytes outside the source pool. */
dlabel tony_rodata_padding
    /* 100B31 80110B31 */ .byte 0x00
    /* 100B32 80110B32 */ .byte 0x00
    /* 100B33 80110B33 */ .byte 0x00
enddlabel tony_rodata_padding
