.include "macro.inc"

.section .rodata, "a"

/* Generated by spimdisasm 1.42.4 */

nonmatching D_80110A50

dlabel D_80110A50
    /* 100A50 80110A50 70737873 */ .word 0x73787370
    /* 100A54 80110A54 72632F67 */ .word 0x672F6372
    /* 100A58 80110A58 6D616E2E */ .word 0x2E6E616D
    /* 100A5C 80110A5C 68006700 */ .word 0x00670068
enddlabel D_80110A50
