.include "macro.inc"

.section .rodata, "a"

/* Generated by spimdisasm 1.42.4 */

.align 2
nonmatching D_80119BC8

dlabel D_80119BC8
    /* 109BC8 80119BC8 */ .asciz "psxsrc/gman.h"
    /* 7073787372632F676D616E2E68000000 */
.align 2
.align 2
    /* 109BD8 80119BD8 */ .asciz "psxsrc/cplayer.h"
    /* 7073787372632F63706C617965722E6800000000 */
.align 2
.align 2
    /* 109BEC 80119BEC */ .asciz "source/PREAUTO.cpp"
    /* 736F757263652F5052454155544F2E6370700000 */
.align 2
enddlabel D_80119BC8
