.include "macro.inc"

.section .rodata, "a"

/* Generated by spimdisasm 1.42.4 */

.align 2
nonmatching D_80110FA8

dlabel D_80110FA8
    /* 100FA8 80110FA8 */ .asciz "You shouldn't get here"
    /* 596F752073686F756C646E27742067657420686572650000 */
.align 2
enddlabel D_80110FA8
