.include "macro.inc"

.section .rodata, "a"

/* Generated by spimdisasm 1.42.4 */

.align 2
nonmatching D_80110480

dlabel D_80110480
    /* 100480 80110480 */ .asciz "psxsrc/gman.h"
    /* 7073787372632F676D616E2E68000000 */
.align 2
enddlabel D_80110480

nonmatching D_80110490

dlabel D_80110490
    /* 100490 80110490 46696E69 */ .word 0x696E6946
    /* 100494 80110494 73686564 */ .word 0x64656873
    /* 100498 80110498 20526563 */ .word 0x63655220
    /* 10049C 8011049C 6F726469 */ .word 0x6964726F
    /* 1004A0 801104A0 6E67070A */ .word 0x0A07676E
    /* 1004A4 801104A4 00000000 */ .word 0x00000000
enddlabel D_80110490

.align 2
nonmatching D_801104A8

dlabel D_801104A8
    /* 1004A8 801104A8 */ .asciz "psxsrc/PADS.CPP"
    /* 7073787372632F504144532E43505000 */
.align 2
enddlabel D_801104A8
