.include "macro.inc"

.section .rodata, "a"

/* Generated by spimdisasm 1.42.4 */

nonmatching D_8010FFE0

dlabel D_8010FFE0
    /* FFFE0 8010FFE0 70737873 */ .word 0x73787370
    /* FFFE4 8010FFE4 72632F56 */ .word 0x562F6372
    /* FFFE8 8010FFE8 49442E43 */ .word 0x432E4449
    /* FFFEC 8010FFEC 50500000 */ .word 0x00005050
enddlabel D_8010FFE0
