.include "macro.inc"

.section .rodata, "a"

/* Generated by spimdisasm 1.42.4 */

.align 2
nonmatching D_8011A3A8

dlabel D_8011A3A8
    /* 10A3A8 8011A3A8 */ .asciz "psxsrc/gman.h"
    /* 7073787372632F676D616E2E68000000 */
.align 2
enddlabel D_8011A3A8
