.include "macro.inc"

.section .rodata, "a"

/* Generated by spimdisasm 1.42.4 */

.align 2
nonmatching D_80110E30

dlabel D_80110E30
    /* 100E30 80110E30 */ .asciz "psxsrc/gman.h"
    /* 7073787372632F676D616E2E68000000 */
.align 2
enddlabel D_80110E30

.align 2
nonmatching D_80110E40

dlabel D_80110E40
    /* 100E40 80110E40 */ .asciz "EACLOGO.MOV"
    /* 4541434C4F474F2E4D4F5600 */
.align 2
enddlabel D_80110E40

.align 2
nonmatching D_80110E4C

dlabel D_80110E4C
    /* 100E4C 80110E4C */ .asciz "DIABEND.MOV"
    /* 44494142454E442E4D4F5600 */
.align 2
enddlabel D_80110E4C

.align 2
nonmatching D_80110E58

dlabel D_80110E58
    /* 100E58 80110E58 */ .asciz "FPRST3.MOV"
    /* 4650525354332E4D4F560000 */
.align 2
enddlabel D_80110E58

.align 2
nonmatching D_80110E64

dlabel D_80110E64
    /* 100E64 80110E64 */ .asciz "DIABVIC1.MOV"
    /* 44494142564943312E4D4F5600000000 */
.align 2
enddlabel D_80110E64

.align 2
nonmatching D_80110E74

dlabel D_80110E74
    /* 100E74 80110E74 */ .asciz "DIABVIC2.MOV"
    /* 44494142564943322E4D4F5600000000 */
.align 2
enddlabel D_80110E74

.align 2
nonmatching D_80110E84

dlabel D_80110E84
    /* 100E84 80110E84 */ .asciz "DIABVIC3.MOV"
    /* 44494142564943332E4D4F5600000000 */
.align 2
enddlabel D_80110E84

.align 2
nonmatching D_80110E94

dlabel D_80110E94
    /* 100E94 80110E94 */ .asciz "BLIZZARD.MOV"
    /* 424C495A5A4152442E4D4F5600000000 */
.align 2
enddlabel D_80110E94

.align 2
nonmatching D_80110EA4

dlabel D_80110EA4
    /* 100EA4 80110EA4 */ .asciz "DIABLO1.MOV"
    /* 444941424C4F312E4D4F5600 */
.align 2
enddlabel D_80110EA4

.align 3
nonmatching jtbl_80110EB0

dlabel jtbl_80110EB0
    /* 100EB0 80110EB0 F0D00A80 */ .word .L800AD0F0
    /* 100EB4 80110EB4 C8D00A80 */ .word .L800AD0C8
    /* 100EB8 80110EB8 D8D00A80 */ .word .L800AD0D8
    /* 100EBC 80110EBC E8D00A80 */ .word .L800AD0E8
    /* 100EC0 80110EC0 F0D00A80 */ .word .L800AD0F0
enddlabel jtbl_80110EB0
