.include "macro.inc"

.section .rodata, "a"

/* Generated by spimdisasm 1.42.4 */

.align 2
nonmatching D_801169E0

dlabel D_801169E0
    /* 1069E0 801169E0 */ .asciz "psxsrc/gman.h"
    /* 7073787372632F676D616E2E68000000 */
.align 2
enddlabel D_801169E0

nonmatching ObjMasterLoadList

dlabel ObjMasterLoadList
    /* 1069F0 801169F0 */ .short 0x0000
    /* 1069F2 801169F2 */ .short 0x0001
    /* 1069F4 801169F4 */ .short 0x0003
    /* 1069F6 801169F6 */ .short 0x0001
    /* 1069F8 801169F8 */ .short 0x0018
    /* 1069FA 801169FA */ .short 0x0000
    /* 1069FC 801169FC */ .short 0x000F
    /* 1069FE 801169FE */ .short 0x0000
    /* 106A00 80116A00 */ .short 0x0011
    /* 106A02 80116A02 */ .short 0x0000
    /* 106A04 80116A04 */ .short 0x0010
    /* 106A06 80116A06 */ .short 0x0000
    /* 106A08 80116A08 */ .short 0x0001
    /* 106A0A 80116A0A */ .short 0x0001
    /* 106A0C 80116A0C */ .short 0x0003
    /* 106A0E 80116A0E */ .short 0x0000
    /* 106A10 80116A10 */ .short 0x0007
    /* 106A12 80116A12 */ .short 0x0001
    /* 106A14 80116A14 */ .short 0x0007
    /* 106A16 80116A16 */ .short 0x0001
    /* 106A18 80116A18 */ .short 0x0008
    /* 106A1A 80116A1A */ .short 0x0001
    /* 106A1C 80116A1C */ .short 0x0009
    /* 106A1E 80116A1E */ .short 0x0001
    /* 106A20 80116A20 */ .short 0x000D
    /* 106A22 80116A22 */ .short 0x0000
    /* 106A24 80116A24 */ .short 0x000E
    /* 106A26 80116A26 */ .short 0x0000
    /* 106A28 80116A28 */ .short 0x0005
    /* 106A2A 80116A2A */ .short 0x0001
    /* 106A2C 80116A2C */ .short 0x0012
    /* 106A2E 80116A2E */ .short 0x0000
    /* 106A30 80116A30 */ .short 0x0012
    /* 106A32 80116A32 */ .short 0x0000
    /* 106A34 80116A34 */ .short 0x0006
    /* 106A36 80116A36 */ .short 0x0000
    /* 106A38 80116A38 */ .short 0x0002
    /* 106A3A 80116A3A */ .short 0x0000
    /* 106A3C 80116A3C */ .short 0x001A
    /* 106A3E 80116A3E */ .short 0x0000
    /* 106A40 80116A40 */ .short 0x001A
    /* 106A42 80116A42 */ .short 0x0000
    /* 106A44 80116A44 */ .short 0x0004
    /* 106A46 80116A46 */ .short 0x0000
    /* 106A48 80116A48 */ .short 0x0005
    /* 106A4A 80116A4A */ .short 0x0000
    /* 106A4C 80116A4C */ .short 0x0004
    /* 106A4E 80116A4E */ .short 0x0000
    /* 106A50 80116A50 */ .short 0x0007
    /* 106A52 80116A52 */ .short 0x0001
    /* 106A54 80116A54 */ .short 0x0003
    /* 106A56 80116A56 */ .short 0x0001
    /* 106A58 80116A58 */ .short 0x0002
    /* 106A5A 80116A5A */ .short 0x0001
    /* 106A5C 80116A5C */ .short 0x0005
    /* 106A5E 80116A5E */ .short 0x0001
    /* 106A60 80116A60 */ .short 0x0002
    /* 106A62 80116A62 */ .short 0x0001
    /* 106A64 80116A64 */ .short 0x0001
    /* 106A66 80116A66 */ .short 0x0000
    /* 106A68 80116A68 */ .short 0x0001
    /* 106A6A 80116A6A */ .short 0x0000
    /* 106A6C 80116A6C */ .short 0x0004
    /* 106A6E 80116A6E */ .short 0x0001
    /* 106A70 80116A70 */ .short 0x0001
    /* 106A72 80116A72 */ .short 0x0001
    /* 106A74 80116A74 */ .short 0x0000
    /* 106A76 80116A76 */ .short 0x0001
    /* 106A78 80116A78 */ .short 0x000A
    /* 106A7A 80116A7A */ .short 0x0000
    /* 106A7C 80116A7C */ .short 0x001B
    /* 106A7E 80116A7E */ .short 0x0000
    /* 106A80 80116A80 */ .short 0x001B
    /* 106A82 80116A82 */ .short 0x0000
    /* 106A84 80116A84 */ .short 0x0009
    /* 106A86 80116A86 */ .short 0x0000
    /* 106A88 80116A88 */ .short 0x0000
    /* 106A8A 80116A8A */ .short 0x0000
    /* 106A8C 80116A8C */ .short 0x0016
    /* 106A8E 80116A8E */ .short 0x0000
    /* 106A90 80116A90 */ .short 0x0019
    /* 106A92 80116A92 */ .short 0x0000
    /* 106A94 80116A94 */ .short 0x000C
    /* 106A96 80116A96 */ .short 0x0000
    /* 106A98 80116A98 */ .short 0x0013
    /* 106A9A 80116A9A */ .short 0x0000
    /* 106A9C 80116A9C */ .short 0x0006
    /* 106A9E 80116A9E */ .short 0x0001
    /* 106AA0 80116AA0 */ .short 0x0000
    /* 106AA2 80116AA2 */ .short 0x0001
    /* 106AA4 80116AA4 */ .short 0x001D
    /* 106AA6 80116AA6 */ .short 0x0000
    /* 106AA8 80116AA8 */ .short 0x0008
    /* 106AAA 80116AAA */ .short 0x0000
    /* 106AAC 80116AAC */ .short 0x0014
    /* 106AAE 80116AAE */ .short 0x0000
    /* 106AB0 80116AB0 */ .short 0x0000
    /* 106AB2 80116AB2 */ .short 0x0001
    /* 106AB4 80116AB4 */ .short 0x0015
    /* 106AB6 80116AB6 */ .short 0x0000
    /* 106AB8 80116AB8 */ .short 0x001C
    /* 106ABA 80116ABA */ .short 0x0000
    /* 106ABC 80116ABC */ .short 0x0007
    /* 106ABE 80116ABE */ .short 0x0000
    /* 106AC0 80116AC0 */ .short 0x0006
    /* 106AC2 80116AC2 */ .short 0x0001
    /* 106AC4 80116AC4 */ .short 0x000B
    /* 106AC6 80116AC6 */ .short 0x0000
    /* 106AC8 80116AC8 */ .short 0x0001
    /* 106ACA 80116ACA */ .short 0x0001
    /* 106ACC 80116ACC */ .short 0x0017
    /* 106ACE 80116ACE */ .short 0x0000
enddlabel ObjMasterLoadList
