.include "macro.inc"

.section .rodata, "a"

/* Generated by spimdisasm 1.42.4 */

.align 2
nonmatching D_80110B34

dlabel D_80110B34
    /* 100B34 80110B34 */ .asciz "psxsrc/gman.h"
    /* 7073787372632F676D616E2E68000000 */
.align 2
.align 2
    /* 100B44 80110B44 */ .asciz "psxsrc/cplayer.h"
    /* 7073787372632F63706C617965722E6800000000 */
.align 2
enddlabel D_80110B34

nonmatching D_80110B58

dlabel D_80110B58
    /* 100B58 80110B58 70737873 */ .word 0x73787370
    /* 100B5C 80110B5C 72632F47 */ .word 0x472F6372
    /* 100B60 80110B60 4C55452E */ .word 0x2E45554C
    /* 100B64 80110B64 43505000 */ .word 0x00505043
enddlabel D_80110B58

nonmatching D_80110B68

dlabel D_80110B68
    /* 100B68 80110B68 */ .byte 0x4E
    /* 100B69 80110B69 */ .byte 0x55
    /* 100B6A 80110B6A */ .byte 0x53
    /* 100B6B 80110B6B */ .byte 0x44
    /* 100B6C 80110B6C */ .byte 0x42
    /* 100B6D 80110B6D */ .byte 0x41
    /* 100B6E 80110B6E */ .byte 0x4D
    /* 100B6F 80110B6F */ .byte 0x48
    /* 100B70 80110B70 */ .byte 0x54
    /* 100B71 80110B71 */ .byte 0x00
enddlabel D_80110B68

dlabel glue_rodata_padding
    /* 100B72 80110B72 */ .byte 0x00
    /* 100B73 80110B73 */ .byte 0x00
enddlabel glue_rodata_padding
