.include "macro.inc"

.section .rodata, "a"

/* Generated by spimdisasm 1.42.4 */

.align 2
nonmatching D_8011A738

dlabel D_8011A738
    /* 10A738 8011A738 */ .asciz "psxsrc/gman.h"
    /* 7073787372632F676D616E2E68000000 */
.align 2
.align 2
    /* 10A748 8011A748 */ .asciz "psxsrc/primpool.h"
    /* 7073787372632F7072696D706F6F6C2E68000000 */
.align 2
.align 2
    /* 10A75C 8011A75C */ .asciz ""
    /* 00000000 */
.align 2
    /* 10A760 8011A760 10231680 */ .word 0x80162310
    /* 10A764 8011A764 5C231680 */ .word 0x8016235C
    /* 10A768 8011A768 AC231680 */ .word 0x801623AC
    /* 10A76C 8011A76C F8231680 */ .word 0x801623F8
    /* 10A770 8011A770 DC211680 */ .word 0x801621DC
    /* 10A774 8011A774 28221680 */ .word 0x80162228
    /* 10A778 8011A778 74221680 */ .word 0x80162274
    /* 10A77C 8011A77C C0221680 */ .word 0x801622C0
enddlabel D_8011A738
