.include "macro.inc"

.section .rodata, "a"

/* Generated by spimdisasm 1.42.4 */

.align 2
nonmatching D_80110F44

dlabel D_80110F44
    /* 100F44 80110F44 */ .asciz "psxsrc/gman.h"
    /* 7073787372632F676D616E2E68000000 */
.align 2
.align 2
    /* 100F54 80110F54 */ .asciz "psxsrc/cplayer.h"
    /* 7073787372632F63706C617965722E6800000000 */
.align 2
enddlabel D_80110F44

.align 2
nonmatching D_80110F68

dlabel D_80110F68
    /* 100F68 80110F68 */ .asciz "%c + %c %s"
    /* 2563202B2025632025730000 */
.align 2
enddlabel D_80110F68
