.include "macro.inc"

.section .rodata, "a"

/* Generated by spimdisasm 1.42.4 */

.align 2
nonmatching D_801178E0

dlabel D_801178E0
    /* 1078E0 801178E0 */ .asciz "psxsrc/gman.h"
    /* 7073787372632F676D616E2E68000000 */
.align 2
    /* 1078F0 801178F0 70737873 */ .word 0x73787370
    /* 1078F4 801178F4 72632F63 */ .word 0x632F6372
    /* 1078F8 801178F8 706C6179 */ .word 0x79616C70
    /* 1078FC 801178FC 65722E68 */ .word 0x682E7265
    /* 107900 80117900 00076C00 */ .word 0x006C0700
enddlabel D_801178E0
