.include "macro.inc"

.section .rodata, "a"

/* Generated by spimdisasm 1.42.4 */

.align 2
nonmatching D_8011101C

dlabel D_8011101C
    /* 10101C 8011101C */ .asciz "You shouldn't get here"
    /* 596F752073686F756C646E27742067657420686572650000 */
.align 2
enddlabel D_8011101C
