.include "macro.inc"

.section .rodata, "a"

/* Generated by spimdisasm 1.42.4 */

nonmatching D_8011133C

dlabel D_8011133C
    /* 10133C 8011133C 70737873 */ .word 0x73787370
    /* 101340 80111340 72632F67 */ .word 0x672F6372
    /* 101344 80111344 6D616E2E */ .word 0x2E6E616D
    /* 101348 80111348 68006F00 */ .word 0x006F0068
enddlabel D_8011133C
