.include "macro.inc"

.section .rodata, "a"

/* Generated by spimdisasm 1.42.4 */

.align 2
nonmatching StrDate

dlabel StrDate
    /* A07C8 800B07C8 */ .asciz "May 29 1998"
    /* 4D6179203239203139393800 */
enddlabel StrDate
.align 2

.align 2
nonmatching StrTime

dlabel StrTime
    /* A07D4 800B07D4 */ .asciz "14:30:45"
    /* 31343A33303A343500000000 */
enddlabel StrTime
.align 2
