/* GLIBDEV/SOURCE/PSX/GDEBUG.C — linked skeleton generated by tools/gen_skeleton.py from DIABPSX.SYM (9 functions).
 * Each function: SYM signature/registers, INCLUDE_ASM of the retail oracle (links byte-identical),
 * then the m2c and Hex-Rays drafts under #if 0.  Replace one INCLUDE_ASM at a time with C. */
#include "common.h"

/* ---- 0x80020E54  DBG_OpenModule  GDEBUG.C:53-60  seg lib  fsize 0 ---- */
/* unsigned char DBG_OpenModule(void)
 */
/* linked from build/src/lib.c.o (segment lib mixes several source files) — INCLUDE_ASM("asm/nonmatchings/lib", DBG_OpenModule) */
#if 0 /* m2c */
s32 DBG_OpenModule(void) {
    return 1;
}
#endif

/* ---- 0x80020E5C  DBG_PollHost  GDEBUG.C:72-79  seg lib  fsize 0 ---- */
/* void DBG_PollHost(void)
 */
/* linked from build/src/lib.c.o (segment lib mixes several source files) — INCLUDE_ASM("asm/nonmatchings/lib", DBG_PollHost) */
#if 0 /* m2c */
void DBG_PollHost(void) {

}
#endif

/* ---- 0x80020E64  DBG_Halt  GDEBUG.C:88-92  seg lib  fsize 0 ---- */
/* void DBG_Halt(void)
 */
/* linked from build/src/lib.c.o (segment lib mixes several source files) — INCLUDE_ASM("asm/nonmatchings/lib", DBG_Halt) */
#if 0 /* m2c */
void DBG_Halt(void) {
    DBG_Halt();
}
#endif
#if 0 /* ida */
void __noreturn DBG_Halt()
{
  while ( 1 )
    ;
}
#endif

/* ---- 0x80020E6C  DBG_SendMessage  GDEBUG.C:108-126  seg lib  fsize 0 ---- */
/* void DBG_SendMessage(char *e)
 *   e=$a0
 */
/* linked from build/src/lib.c.o (segment lib mixes several source files) — INCLUDE_ASM("asm/nonmatchings/lib", DBG_SendMessage) */
#if 0 /* m2c */
void DBG_SendMessage(s32 arg0, M2C_UNK arg1, M2C_UNK arg2, M2C_UNK arg3) {

}
#endif
#if 0 /* ida */
void DBG_SendMessage()
{
  ;
}
#endif

/* ---- 0x80020E84  DBG_SetMessageHandler  GDEBUG.C:135-136  seg lib  fsize 0 ---- */
/* void DBG_SetMessageHandler(void (*Func)())
 *   Func=$a0
 */
/* linked from build/src/lib.c.o (segment lib mixes several source files) — INCLUDE_ASM("asm/nonmatchings/lib", DBG_SetMessageHandler) */
#if 0 /* m2c */
void DBG_SetMessageHandler(s32 arg0) {
    MsgFunc = arg0;
}
#endif

/* ---- 0x80020E94  DBG_Error  GDEBUG.C:146-160  seg lib  fsize 24 ---- */
/* void DBG_Error(char *Text, char *File, int Line)
 *   Text=$a0 File=$a1 Line=$a2
 */
/* linked from build/src/lib.c.o (segment lib mixes several source files) — INCLUDE_ASM("asm/nonmatchings/lib", DBG_Error) */
#if 0 /* m2c */
void DBG_Error(void) {
    if (ErrorFunc != NULL) {
        ErrorFunc();
    }
    DBG_Halt();
}
#endif
#if 0 /* ida */
void __noreturn DBG_Error()
{
  if ( MEMORY[0x8011CAB8] != nullptr )
    MEMORY[0x8011CAB8]();
  DBG_Halt();
}
#endif

/* ---- 0x80020EC8  DBG_SetErrorFunc  GDEBUG.C:166-167  seg lib  fsize 0 ---- */
/* void DBG_SetErrorFunc(void (*EFunc)())
 *   EFunc=$a0
 */
/* linked from build/src/lib.c.o (segment lib mixes several source files) — INCLUDE_ASM("asm/nonmatchings/lib", DBG_SetErrorFunc) */
#if 0 /* m2c */
void DBG_SetErrorFunc(s32 arg0) {
    ErrorFunc = arg0;
}
#endif
#if 0 /* ida */
void __fastcall DBG_SetErrorFunc(int a1)
{
  MEMORY[0x8011CAB8] = a1;
}
#endif

/* ---- 0x80020ED8  SendPsyqString  GDEBUG.C:177-181  seg lib  fsize 0 ---- */
/* void SendPsyqString(char *e)
 *   e=$a0
 */
/* linked from build/src/lib.c.o (segment lib mixes several source files) — INCLUDE_ASM("asm/nonmatchings/lib", SendPsyqString) */
#if 0 /* m2c */
void SendPsyqString(void) {

}
#endif

/* ---- 0x80020EE0  DBG_SetPollRoutine  GDEBUG.C:190-191  seg lib  fsize 0 ---- */
/* void DBG_SetPollRoutine(void (*Func)())
 *   Func=$a0
 */
/* linked from build/src/lib.c.o (segment lib mixes several source files) — INCLUDE_ASM("asm/nonmatchings/lib", DBG_SetPollRoutine) */
#if 0 /* m2c */
void DBG_SetPollRoutine(s32 arg0) {
    PollFunc = arg0;
}
#endif
#if 0 /* ida */
void __fastcall DBG_SetPollRoutine(int a1)
{
  MEMORY[0x8011CA88] = a1;
}
#endif
