/* GLIBDEV/SOURCE/PSX/VRIP.C — linked skeleton generated by tools/gen_skeleton.py from DIABPSX.SYM (2 functions).
 * Each function: SYM signature/registers, INCLUDE_ASM of the retail oracle (links byte-identical),
 * then the m2c and Hex-Rays drafts under #if 0.  Replace one INCLUDE_ASM at a time with C. */
#include "common.h"

/* ---- 0x80025538  vsprintf  VRIP.C:157-167  seg lib  fsize 56 ---- */
/* int vsprintf(char *str, char *fmt, char *ap)
 *   str=$a0 fmt=$a1 ap=$a2 f@sp-0x28
 *   blocks: {1 }11
 */
/* linked from build/src/lib.c.o (segment lib mixes several source files) — INCLUDE_ASM("asm/nonmatchings/lib", vsprintf) */
#if 0 /* m2c */
void vsprintf(s8 *arg0, M2C_UNK arg1, M2C_UNK arg2) {
    s32 sp10;
    s8 *sp14;
    s32 sp20;

    sp14 = arg0;
    sp20 = 0x110;
    sp10 = 0x7FFFFFFF;
    _doprnt(arg1, arg2, &sp10);
    *sp14 = 0;
}
#endif
#if 0 /* ida */
int __fastcall vsprintf(_BYTE *a1, _BYTE *a2, int a3)
{
  int result; // $v0
  int v4; // [sp+10h] [-20h] BYREF
  _BYTE *v5; // [sp+14h] [-1Ch]
  int v6; // [sp+20h] [-10h]

  v5 = a1;
  v6 = 272;
  v4 = 0x7FFFFFFF;
  result = _doprnt(a2, a3, &v4);
  *v5 = 0;
  return result;
}
#endif

/* ---- 0x80025584  _doprnt  VRIP.C:172-479  seg lib  fsize 104 ---- */
/* int _doprnt(char *fmt0, char *argp, struct FILE *fp)
 *   fmt0=$a0 argp=$s2 fp=$s5 fmt=$s6 ch=$a0 cnt@sp-0x58 n=$s0 t=$s1 _ulong=$v1 base=$a1 dprec@sp-0x50 fieldsz=$fp flags=$s3 fpprec@sp-0x48 prec=$s4 realsz=$s4 size=$s7 width@sp-0x40 sign=$a2 digs@sp-0x38 c=$v0 p=$v0
 *   blocks: {1 {95 }1 {112 }1 {173 }182 }308
 */
/* linked from build/src/lib.c.o (segment lib mixes several source files) — INCLUDE_ASM("asm/nonmatchings/lib", _doprnt) */
#if 0 /* m2c */
s32 _doprnt(s8 *arg0, void *arg1, void *arg2) {
    s32 sp10;
    s32 sp18;
    s32 sp20;
    s32 sp28;
    M2C_UNK *sp30;
    s32 sp38;
    s16 var_v1_3;
    s32 temp_a3;
    s32 temp_a3_2;
    s32 temp_a3_3;
    s32 temp_fp;
    s32 temp_v0;
    s32 temp_v1;
    s32 temp_v1_6;
    s32 var_a0_3;
    s32 var_a2;
    s32 var_a3;
    s32 var_s0;
    s32 var_s0_2;
    s32 var_s0_3;
    s32 var_s0_4;
    s32 var_s0_5;
    s32 var_s0_6;
    s32 var_s0_7;
    s32 var_s0_8;
    s32 var_s3;
    s32 var_s4;
    s32 var_s4_2;
    s32 var_s7;
    s32 var_v0;
    s32 var_v0_2;
    s32 var_v1;
    s32 var_v1_2;
    s8 *var_s1;
    s8 *var_s6;
    s8 temp_a0;
    s8 temp_v1_2;
    s8 temp_v1_3;
    s8 temp_v1_4;
    s8 var_a0;
    u32 temp_hi;
    u32 var_a1;
    u8 *var_s1_2;
    u8 temp_a0_2;
    u8 temp_v1_5;
    u8 var_a0_2;
    void *var_s2;

    temp_v1 = M2C_FIELD(arg2, s32 *, 0x10);
    var_s2 = arg1;
    if (temp_v1 & 0x200) {
        M2C_FIELD(arg2, s32 *, 0x10) = (s32) ((temp_v1 | 0x10) & ~0x48);
    }
    var_s6 = arg0;
    if (!(M2C_FIELD(arg2, s32 *, 0x10) & 0x10)) {
        return -1;
    }
    sp30 = &D_8010EB4C;
    sp10 = 0;
loop_5:
    var_s0 = M2C_FIELD(arg2, s32 *, 0);
    var_a0 = *var_s6;
    var_s1 = M2C_FIELD(arg2, s8 **, 4);
    if (var_a0 != 0) {
loop_7:
        if (var_a0 != 0x25) {
            var_s0 -= 1;
            if (((var_s0 < 0) && (!(M2C_FIELD(arg2, s32 *, 0x10) & 4) || (-var_s0 >= M2C_FIELD(arg2, s32 *, 0xC)))) || ((var_a0 == 0xA) && (M2C_FIELD(arg2, s32 *, 0x10) & 4))) {
                M2C_FIELD(arg2, s32 *, 0) = var_s0;
                var_s0 = M2C_FIELD(arg2, s32 *, 0);
                M2C_FIELD(arg2, s8 **, 4) = var_s1;
            } else {
                *var_s1 = var_a0;
                var_s1 += 1;
            }
            var_s6 += 1;
            var_a0 = *var_s6;
            sp10 += 1;
            if (var_a0 != 0) {
                goto loop_7;
            }
        }
    }
    M2C_FIELD(arg2, s32 *, 0) = var_s0;
    M2C_FIELD(arg2, s8 **, 4) = var_s1;
    if (var_a0 != 0) {
        var_s3 = 0;
        var_s4 = -1;
        var_a2 = 0;
        sp18 = 0;
        sp20 = 0;
        sp28 = 0;
loop_19:
        var_s6 += 1;
        temp_v1_2 = *var_s6;
        switch (temp_v1_2) {
        case 0x20:
            if (var_a2 == 0) {
                var_a2 = 0x20;
            }
            goto loop_19;
        case 0x23:
            var_s3 |= 8;
            goto loop_19;
        case 0x2A:
            var_s2 += 4;
            temp_a3 = M2C_FIELD(var_s2, s32 *, -4);
            sp28 = temp_a3;
            if (temp_a3 < 0) {
                sp28 = -temp_a3;
            case 0x2D:
                var_s3 |= 0x10;
            }
            goto loop_19;
        case 0x2B:
            var_a2 = 0x2B;
            goto loop_19;
        case 0x2E:
            var_s6 += 1;
            if (*var_s6 == 0x2A) {
                var_s2 += 4;
                var_s4 = M2C_FIELD(var_s2, s32 *, -4);
            } else {
                var_a0_2 = (u8) *var_s6;
                var_s0_2 = 0;
                if (var_a0_2 < 0x80U) {
loop_31:
                    if (*(&D_800B5DBD + var_a0_2) & 4) {
                        temp_v1_3 = (s8) *var_s6;
                        var_s6 += 1;
                        if (temp_v1_3 < 0x31) {
                            var_v1 = 0;
                        } else {
                            var_v1 = temp_v1_3 - 0x30;
                            if (temp_v1_3 >= 0x39) {
                                var_v1 = 9;
                            }
                        }
                        var_a0_2 = *var_s6;
                        var_s0_2 = (var_s0_2 * 0xA) + var_v1;
                        if (var_a0_2 < 0x80U) {
                            goto loop_31;
                        }
                    }
                }
                var_s6 -= 1;
                var_s4 = var_s0_2;
            }
            if (var_s4 < -1) {
                var_s4 = -1;
            }
            goto loop_19;
        case 0x30:
            var_s3 |= 0x20;
            goto loop_19;
        case 0x31:
        case 0x32:
        case 0x33:
        case 0x34:
        case 0x35:
        case 0x36:
        case 0x37:
        case 0x38:
        case 0x39:
            var_s0_3 = 0;
loop_42:
            temp_v1_4 = *var_s6;
            var_a0_3 = 0;
            if (temp_v1_4 >= 0x31) {
                var_a0_3 = temp_v1_4 - 0x30;
                if (temp_v1_4 >= 0x39) {
                    var_a0_3 = 9;
                }
            }
            var_s6 += 1;
            temp_v1_5 = *var_s6;
            var_s0_3 = (var_s0_3 * 0xA) + var_a0_3;
            if ((temp_v1_5 < 0x80U) && (*(&D_800B5DBD + temp_v1_5) & 4)) {
                goto loop_42;
            }
            sp28 = var_s0_3;
            var_s6 -= 1;
            goto loop_19;
        case 0x4C:
            var_s3 |= 2;
            goto loop_19;
        case 0x68:
            var_s3 |= 4;
            goto loop_19;
        case 0x6C:
            var_s3 |= 1;
            goto loop_19;
        case 0x63:
            var_s1_2 = &D_80133BB0;
            var_s2 += 4;
            var_s7 = 1;
            var_a2 = 0;
            D_80133BB0 = M2C_FIELD(var_s2, u8 *, -4);
block_96:
            var_a3 = sp20;
            var_s4_2 = sp18;
            temp_fp = var_s7 + var_a3;
            if (var_s4_2 < temp_fp) {
                var_s4_2 = temp_fp;
            }
            if (var_a2 != 0) {
                var_s4_2 += 1;
            }
            if (var_s3 & 0x40) {
                var_s4_2 += 2;
            }
            if (!(var_s3 & 0x30)) {
                var_a3 = sp28;
                if (var_a3 != 0) {
                    var_s0_4 = var_s4_2;
                    if (var_s4_2 < var_a3) {
                        do {
                            sp38 = var_a2;
                            putc(0x20, arg2, var_a2, var_a3);
                            var_s0_4 += 1;
                            var_a3 = sp28;
                        } while (var_s0_4 < var_a3);
                    }
                }
            }
            var_v0 = var_s3 & 0x40;
            if (var_a2 != 0) {
                putc(var_a2, arg2, var_a2, var_a3);
                var_v0 = var_s3 & 0x40;
            }
            if (var_v0 != 0) {
                putc(0x30, arg2);
                putc((s32) *var_s6, arg2);
            }
            if ((var_s3 & 0x30) == 0x20) {
                var_s0_5 = var_s4_2;
                if (var_s4_2 < sp28) {
                    do {
                        putc(0x30, arg2);
                        var_s0_5 += 1;
                    } while (var_s0_5 < sp28);
                }
            }
            var_s0_6 = temp_fp;
            if (var_s0_6 < sp18) {
                do {
                    putc(0x30, arg2);
                    var_s0_6 += 1;
                } while (var_s0_6 < sp18);
            }
            temp_v1_6 = M2C_FIELD(arg2, s32 *, 0) - var_s7;
            if ((temp_v1_6 >= 0) && !(M2C_FIELD(arg2, s32 *, 0x10) & 4)) {
                M2C_FIELD(arg2, s32 *, 0) = temp_v1_6;
                memcpy(M2C_FIELD(arg2, s8 **, 4), var_s1_2, var_s7, sp18);
                M2C_FIELD(arg2, s8 **, 4) = &M2C_FIELD(arg2, s8 **, 4)[var_s7];
            } else {
                var_s0_7 = var_s7 - 1;
                if (var_s0_7 >= 0) {
loop_121:
                    temp_a0 = (s8) *var_s1_2;
                    var_s1_2 += 1;
                    var_s0_7 -= 1;
                    putc((s32) temp_a0, arg2);
                    if (var_s0_7 >= 0) {
                        goto loop_121;
                    }
                }
            }
loop_124:
            temp_a3_2 = sp20 - 1;
            sp20 = temp_a3_2;
            if (temp_a3_2 >= 0) {
                putc(0x30, arg2);
                goto loop_124;
            }
            if (var_s3 & 0x10) {
                var_s0_8 = var_s4_2;
                if (var_s4_2 < sp28) {
                    do {
                        putc(0x20, arg2);
                        var_s0_8 += 1;
                    } while (var_s0_8 < sp28);
                }
            }
            var_v1_2 = sp28;
            var_s6 += 1;
            if (var_v1_2 < var_s4_2) {
                var_v1_2 = var_s4_2;
            }
            sp10 += var_v1_2;
            goto loop_5;
        case 0x44:
            var_s3 |= 1;
            /* fallthrough */
        case 0x64:
        case 0x69:
            if (!(var_s3 & 1) && (var_s3 & 4)) {
                var_s2 += 4;
                var_v1_3 = M2C_FIELD(var_s2, s16 *, -4);
            } else {
                var_s2 += 4;
                var_v1_3 = (s16) M2C_FIELD(var_s2, s32 *, -4);
            }
            var_a1 = 0xA;
            if (var_v1_3 < 0) {
                var_v1_3 = -var_v1_3;
                var_a2 = 0x2D;
            }
block_86:
            sp18 = var_s4;
            if (var_s4 >= 0) {
                var_s3 &= ~0x20;
            }
            var_s1_2 = &D_80134F30;
            if ((var_v1_3 != 0) || (sp18 != 0)) {
                do {
                    temp_hi = (u32) var_v1_3 % var_a1;
                    var_v1_3 = (s16) ((u32) var_v1_3 / var_a1);
                    temp_a0_2 = *(sp30 + temp_hi);
                    var_s1_2 -= 1;
                    *var_s1_2 = temp_a0_2;
                } while (var_v1_3 != 0);
                sp30 = &D_8010EB4C;
                if ((var_s3 & 8) && (var_a1 == 8) && ((s8) temp_a0_2 != 0x30)) {
                    var_s1_2 -= 1;
                    *var_s1_2 = 0x30;
                }
            }
            var_s7 = &D_80134F30 - var_s1_2;
            goto block_96;
        case 0x4F:
            var_s3 |= 1;
            /* fallthrough */
        case 0x6F:
            if (!(var_s3 & 1) && (var_a1 = 8, ((var_s3 & 4) != 0))) {
                var_s2 += 4;
                var_v1_3 = (s16) M2C_FIELD(var_s2, u16 *, -4);
            } else {
                var_s2 += 4;
                var_v1_3 = (s16) M2C_FIELD(var_s2, s32 *, -4);
                var_a1 = 8;
            }
block_85:
            var_a2 = 0;
            goto block_86;
        case 0x70:
            var_s2 += 4;
            var_v1_3 = (s16) M2C_FIELD(var_s2, s32 *, -4);
            var_a1 = 0x10;
            goto block_85;
        case 0x73:
            var_s2 += 4;
            var_s1_2 = M2C_FIELD(var_s2, u8 **, -4);
            if (var_s1_2 == NULL) {
                var_s1_2 = &D_800B63EC;
            }
            if (var_s4 >= 0) {
                temp_v0 = memchr(var_s1_2, 0, var_s4);
                var_a2 = 0;
                if ((temp_v0 == 0) || (var_s7 = temp_v0 - var_s1_2, ((var_s4 < var_s7) != 0))) {
                    var_s7 = var_s4;
                }
            } else {
                var_s7 = strlen(var_s1_2);
                var_a2 = 0;
            }
            goto block_96;
        case 0x55:
            var_s3 |= 1;
            /* fallthrough */
        case 0x75:
            if (!(var_s3 & 1) && (var_a1 = 0xA, ((var_s3 & 4) != 0))) {
                var_s2 += 4;
                var_v1_3 = (s16) M2C_FIELD(var_s2, u16 *, -4);
            } else {
                var_s2 += 4;
                var_v1_3 = (s16) M2C_FIELD(var_s2, s32 *, -4);
                var_a1 = 0xA;
            }
            goto block_85;
        case 0x58:
            sp30 = "0123456789ABCDEF";
            /* fallthrough */
        case 0x78:
            if (!(var_s3 & 1) && (var_v0_2 = var_s3 & 8, ((var_s3 & 4) != 0))) {
                var_s2 += 4;
                var_v1_3 = (s16) M2C_FIELD(var_s2, u16 *, -4);
            } else {
                var_s2 += 4;
                var_v1_3 = (s16) M2C_FIELD(var_s2, s32 *, -4);
                var_v0_2 = var_s3 & 8;
            }
            var_a1 = 0x10;
            if (var_v0_2 != 0) {
                var_a2 = 0;
                if (var_v1_3 != 0) {
                    var_s3 |= 0x40;
                    goto block_85;
                }
            } else {
                goto block_85;
            }
            goto block_86;
        default:
            temp_a3_3 = sp10 + 1;
            sp10 = temp_a3_3;
            putc((s32) *var_s6, arg2, var_a2, temp_a3_3);
            var_s6 += 1;
            goto loop_5;
        }
    }
    return sp10;
}
#endif
#if 0 /* ida */
int __fastcall _doprnt(_BYTE *a1, int a2, int *a3)
{
  int v4; // $v1
  int v8; // $s0
  int v9; // $a0
  _BYTE *i; // $s1
  int v11; // $s3
  int v12; // $s4
  int v13; // $a2
  int v14; // $a3
  unsigned int v15; // $a0
  int j; // $s0
  int v17; // $v1
  int v18; // $v1
  bool v19; // dc
  int v20; // $s0
  int v21; // $v1
  int v22; // $a0
  unsigned int v23; // $v1
  int v24; // $s1
  int v25; // $s7
  int v26; // $v1
  unsigned int v27; // $a1
  int v28; // $v0
  int v29; // $v0
  int v30; // $v0
  int v31; // $hi
  char v32; // $a0
  int v33; // $s4
  int k; // $s0
  int v35; // $v0
  int m; // $s0
  int n; // $s0
  int v38; // $v1
  int ii; // $s0
  int jj; // $s0
  int v41; // $v1
  int v42; // [sp+10h] [-30h]
  int v43; // [sp+18h] [-28h]
  int v44; // [sp+20h] [-20h]
  int v45; // [sp+28h] [-18h]
  const char *v46; // [sp+30h] [-10h]
  int v47; // [sp+38h] [-8h]

  v4 = a3[4];
  if ( (v4 & 0x200) != 0 )
    a3[4] = v4 & 0xFFFFFFA7 | 0x10;
  if ( (a3[4] & 0x10) == 0 )
    return -1;
  v46 = "0123456789abcdef";
  v42 = 0;
  while ( 1 )
  {
LABEL_6:
    v8 = *a3;
    v9 = (char)*a1;
    for ( i = (_BYTE *)a3[1]; *a1 != 0; ++v42 )
    {
      if ( v9 == 37 )
        break;
      if ( (--v8, v8 < 0) && ((a3[4] & 4) == 0 || -v8 >= a3[3]) || v9 == 10 && (a3[4] & 4) != 0 )
      {
        *a3 = v8;
        v8 = *a3;
        a3[1] = (int)i;
      }
      else
      {
        *i++ = v9;
      }
      v9 = (char)*++a1;
    }
    *a3 = v8;
    a3[1] = (int)i;
    if ( v9 == 0 )
      return v42;
    v11 = 0;
    v12 = -1;
    v13 = 0;
    v43 = 0;
    v44 = 0;
    v45 = 0;
    while ( 2 )
    {
      switch ( *++a1 )
      {
        case 0:
          return v42;
        case 0x20:
          if ( v13 == 0 )
            v13 = 32;
          continue;
        case 0x23:
          v11 |= 8u;
          continue;
        case 0x2A:
          a2 += 4;
          v14 = *(_DWORD *)(a2 - 4);
          v45 = v14;
          if ( v14 >= 0 )
            continue;
          v45 = -v14;
          goto LABEL_25;
        case 0x2B:
          v13 = 43;
          continue;
        case 0x2D:
LABEL_25:
          v11 |= 0x10u;
          continue;
        case 0x2E:
          if ( *++a1 == 42 )
          {
            a2 += 4;
            v12 = *(_DWORD *)(a2 - 4);
          }
          else
          {
            v15 = (unsigned __int8)*a1;
            for ( j = 0; v15 < 0x80; j = 10 * j + v18 )
            {
              if ( (byte_800B5DBD[v15] & 4) == 0 )
                break;
              v17 = (char)*a1++;
              if ( v17 >= 49 )
              {
                v19 = v17 < 57;
                v18 = v17 - 48;
                if ( !v19 )
                  v18 = 9;
              }
              else
              {
                v18 = 0;
              }
              v15 = (unsigned __int8)*a1;
            }
            --a1;
            v12 = j;
          }
          if ( v12 < -1 )
            v12 = -1;
          continue;
        case 0x30:
          v11 |= 0x20u;
          continue;
        case 0x31:
        case 0x32:
        case 0x33:
        case 0x34:
        case 0x35:
        case 0x36:
        case 0x37:
        case 0x38:
        case 0x39:
          v20 = 0;
          do
          {
            v21 = (char)*a1;
            v22 = 0;
            if ( v21 >= 49 )
            {
              v22 = v21 - 48;
              if ( v21 >= 57 )
                v22 = 9;
            }
            v23 = (unsigned __int8)*++a1;
            v20 = 10 * v20 + v22;
          }
          while ( v23 < 0x80 && (byte_800B5DBD[v23] & 4) != 0 );
          v45 = v20;
          --a1;
          continue;
        case 0x44:
          LOBYTE(v11) = v11 | 1;
          goto LABEL_52;
        case 0x4C:
          v11 |= 2u;
          continue;
        case 0x4F:
          LOBYTE(v11) = v11 | 1;
          goto LABEL_59;
        case 0x55:
          LOBYTE(v11) = v11 | 1;
          goto LABEL_72;
        case 0x58:
          v46 = "0123456789ABCDEF";
          goto LABEL_77;
        case 0x63:
          v24 = -2146223184;
          a2 += 4;
          v25 = 1;
          v13 = 0;
          MEMORY[0x80133BB0] = *(_BYTE *)(a2 - 4);
          goto LABEL_95;
        case 0x64:
        case 0x69:
LABEL_52:
          if ( (v11 & 1) != 0 || (v11 & 4) == 0 )
          {
            a2 += 4;
            v26 = *(_DWORD *)(a2 - 4);
          }
          else
          {
            a2 += 4;
            v26 = *(__int16 *)(a2 - 4);
          }
          v27 = 10;
          if ( v26 < 0 )
          {
            v26 = -v26;
            v13 = 45;
          }
          goto LABEL_85;
        case 0x68:
          v11 |= 4u;
          continue;
        case 0x6C:
          v11 |= 1u;
          continue;
        case 0x6F:
LABEL_59:
          if ( (v11 & 1) != 0 || (v27 = 8, (v11 & 4) == 0) )
          {
            a2 += 4;
            v26 = *(_DWORD *)(a2 - 4);
            v27 = 8;
          }
          else
          {
            a2 += 4;
            v26 = *(unsigned __int16 *)(a2 - 4);
          }
          goto LABEL_84;
        case 0x70:
          a2 += 4;
          v26 = *(_DWORD *)(a2 - 4);
          v27 = 16;
          goto LABEL_84;
        case 0x73:
          a2 += 4;
          v24 = *(_DWORD *)(a2 - 4);
          if ( v24 == 0 )
            v24 = (int)"(null)";
          if ( v12 < 0 )
          {
            strlen();
            v25 = v29;
            v13 = 0;
          }
          else
          {
            memchr();
            v13 = 0;
            if ( v28 == 0 || (v25 = v28 - v24, v12 < v28 - v24) )
              v25 = v12;
          }
          goto LABEL_95;
        case 0x75:
LABEL_72:
          if ( (v11 & 1) != 0 || (v27 = 10, (v11 & 4) == 0) )
          {
            a2 += 4;
            v26 = *(_DWORD *)(a2 - 4);
            v27 = 10;
          }
          else
          {
            a2 += 4;
            v26 = *(unsigned __int16 *)(a2 - 4);
          }
          goto LABEL_84;
        case 0x78:
LABEL_77:
          if ( (v11 & 1) != 0 || (v30 = v11 & 8, (v11 & 4) == 0) )
          {
            a2 += 4;
            v26 = *(_DWORD *)(a2 - 4);
            v30 = v11 & 8;
          }
          else
          {
            a2 += 4;
            v26 = *(unsigned __int16 *)(a2 - 4);
          }
          v27 = 16;
          if ( v30 == 0 )
            goto LABEL_84;
          v13 = 0;
          if ( v26 != 0 )
          {
            LOBYTE(v11) = v11 | 0x40;
LABEL_84:
            v13 = 0;
          }
LABEL_85:
          v43 = v12;
          if ( v12 >= 0 )
            LOBYTE(v11) = v11 & 0xDF;
          v24 = -2146218192;
          if ( v26 != 0 || v12 != 0 )
          {
            do
            {
              v31 = v26 % v27;
              v26 /= v27;
              v32 = v46[v31];
              *(_BYTE *)--v24 = v32;
            }
            while ( v26 != 0 );
            v46 = "0123456789abcdef";
            if ( (v11 & 8) != 0 && v27 == 8 && v32 != 48 )
              *(_BYTE *)--v24 = 48;
          }
          v25 = -2146218192 - v24;
LABEL_95:
          v33 = v43;
          if ( v43 < v25 )
            v33 = v25;
          if ( v13 != 0 )
            ++v33;
          if ( (v11 & 0x40) != 0 )
            v33 += 2;
          if ( (v11 & 0x30) == 0 && v45 != 0 )
          {
            for ( k = v33; k < v45; v13 = v47 )
            {
              v47 = v13;
              putc();
              ++k;
            }
          }
          v35 = v11 & 0x40;
          if ( v13 != 0 )
          {
            putc();
            v35 = v11 & 0x40;
          }
          if ( v35 != 0 )
          {
            putc();
            putc();
          }
          if ( (v11 & 0x30) == 0x20 )
          {
            for ( m = v33; m < v45; ++m )
              putc();
          }
          for ( n = v25; n < v43; ++n )
            putc();
          v38 = *a3 - v25;
          if ( v38 < 0 || (a3[4] & 4) != 0 )
          {
            for ( ii = v25 - 1; ii >= 0; --ii )
            {
              ++v24;
              putc();
            }
          }
          else
          {
            *a3 = v38;
            memcpy();
            a3[1] += v25;
          }
          while ( --v44 >= 0 )
            putc();
          if ( (v11 & 0x10) != 0 )
          {
            for ( jj = v33; jj < v45; ++jj )
              putc();
          }
          v41 = v45;
          ++a1;
          if ( v45 < v33 )
            v41 = v33;
          v42 += v41;
          break;
        default:
          ++v42;
          putc();
          ++a1;
          goto LABEL_6;
      }
      break;
    }
  }
}
#endif
