.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.42.4 */

nonmatching Wankpot, 0x4

glabel Wankpot
    /* 8 80010008 200F0180 */  lb         $at, 0xF20($zero)
endlabel Wankpot
