.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.42.4 */

/* Handwritten function */
nonmatching CreditsText, 0x2AC

glabel CreditsText
    /* 2F7C 8013CB74 01400000 */  .word      0x00004001                    # INVALID    $zero, $zero, 0x4001 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 2F80 8013CB78 01400000 */  .word      0x00004001                    # INVALID    $zero, $zero, 0x4001 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 2F84 8013CB7C 01400000 */  .word      0x00004001                    # INVALID    $zero, $zero, 0x4001 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 2F88 8013CB80 02400000 */  srl        $t0, $zero, 0
    /* 2F8C 8013CB84 01400000 */  .word      0x00004001                    # INVALID    $zero, $zero, 0x4001 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 2F90 8013CB88 03400000 */  sra        $t0, $zero, 0
    /* 2F94 8013CB8C 04400000 */  sllv       $t0, $zero, $zero
    /* 2F98 8013CB90 01400000 */  .word      0x00004001                    # INVALID    $zero, $zero, 0x4001 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 2F9C 8013CB94 05400000 */  .word      0x00004005                    # INVALID    $zero, $zero, 0x4005 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 2FA0 8013CB98 06400000 */  srlv       $t0, $zero, $zero
    /* 2FA4 8013CB9C 07400000 */  srav       $t0, $zero, $zero
    /* 2FA8 8013CBA0 08400000 */  .word      0x00004008                    # jr         $zero # 00004000 <InstrIdType: CPU_SPECIAL>
    /* 2FAC 8013CBA4 06400000 */   srlv      $t0, $zero, $zero
    /* 2FB0 8013CBA8 09400000 */  jalr       $t0, $zero
    /* 2FB4 8013CBAC 0A400000 */   movz      $t0, $zero, $zero
    /* 2FB8 8013CBB0 06400000 */  srlv       $t0, $zero, $zero
    /* 2FBC 8013CBB4 0B400000 */  movn       $t0, $zero, $zero
    /* 2FC0 8013CBB8 0C400000 */  syscall    256 /* handwritten instruction */
    /* 2FC4 8013CBBC 06400000 */  srlv       $t0, $zero, $zero
    /* 2FC8 8013CBC0 0D400000 */  break      0, 256
    /* 2FCC 8013CBC4 0E400000 */  .word      0x0000400E                    # INVALID    $zero, $zero, 0x400E # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 2FD0 8013CBC8 06400000 */  srlv       $t0, $zero, $zero
    /* 2FD4 8013CBCC 19400000 */  .word      0x00004019                    # multu      $zero, $zero # 00004000 <InstrIdType: CPU_SPECIAL>
    /* 2FD8 8013CBD0 1A400000 */  div        $t0, $zero, $zero
    /* 2FDC 8013CBD4 06400000 */  srlv       $t0, $zero, $zero
    /* 2FE0 8013CBD8 0F400000 */  .word      0x0000400F                    # sync # 00004000 <InstrIdType: CPU_SPECIAL>
    /* 2FE4 8013CBDC 10400000 */  mfhi       $t0
    /* 2FE8 8013CBE0 06400000 */  srlv       $t0, $zero, $zero
    /* 2FEC 8013CBE4 11400000 */  .word      0x00004011                    # mthi       $zero # 00004000 <InstrIdType: CPU_SPECIAL>
    /* 2FF0 8013CBE8 12400000 */  mflo       $t0
    /* 2FF4 8013CBEC 06400000 */  srlv       $t0, $zero, $zero
    /* 2FF8 8013CBF0 11400000 */  .word      0x00004011                    # mthi       $zero # 00004000 <InstrIdType: CPU_SPECIAL>
    /* 2FFC 8013CBF4 13400000 */  .word      0x00004013                    # mtlo       $zero # 00004000 <InstrIdType: CPU_SPECIAL>
    /* 3000 8013CBF8 06400000 */  srlv       $t0, $zero, $zero
    /* 3004 8013CBFC 14400000 */  dsllv      $t0, $zero, $zero
    /* 3008 8013CC00 15400000 */  .word      0x00004015                    # INVALID    $zero, $zero, 0x4015 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 300C 8013CC04 06400000 */  srlv       $t0, $zero, $zero
    /* 3010 8013CC08 16400000 */  dsrlv      $t0, $zero, $zero
    /* 3014 8013CC0C 17400000 */  dsrav      $t0, $zero, $zero
    /* 3018 8013CC10 06400000 */  srlv       $t0, $zero, $zero
    /* 301C 8013CC14 16400000 */  dsrlv      $t0, $zero, $zero
    /* 3020 8013CC18 18400000 */  .word      0x00004018                    # mult       $zero, $zero # 00004000 <InstrIdType: CPU_SPECIAL>
    /* 3024 8013CC1C 06400000 */  srlv       $t0, $zero, $zero
    /* 3028 8013CC20 1B400000 */  divu       $t0, $zero, $zero
    /* 302C 8013CC24 1C400000 */  .word      0x0000401C                    # dmult      $zero, $zero # 00004000 <InstrIdType: CPU_SPECIAL>
    /* 3030 8013CC28 06400000 */  srlv       $t0, $zero, $zero
    /* 3034 8013CC2C 1D400000 */  .word      0x0000401D                    # dmultu     $zero, $zero # 00004000 <InstrIdType: CPU_SPECIAL>
    /* 3038 8013CC30 1E400000 */  ddiv       $t0, $zero, $zero
    /* 303C 8013CC34 06400000 */  srlv       $t0, $zero, $zero
    /* 3040 8013CC38 1F400000 */  ddivu      $t0, $zero, $zero
    /* 3044 8013CC3C 20400000 */  add        $t0, $zero, $zero /* handwritten instruction */
    /* 3048 8013CC40 06400000 */  srlv       $t0, $zero, $zero
    /* 304C 8013CC44 21400000 */  addu       $t0, $zero, $zero
    /* 3050 8013CC48 22400000 */  neg        $t0, $zero /* handwritten instruction */
    /* 3054 8013CC4C 23400000 */  negu       $t0, $zero
    /* 3058 8013CC50 24400000 */  and        $t0, $zero, $zero
    /* 305C 8013CC54 25400000 */  or         $t0, $zero, $zero
    /* 3060 8013CC58 23400000 */  negu       $t0, $zero
    /* 3064 8013CC5C 26400000 */  xor        $t0, $zero, $zero
    /* 3068 8013CC60 27400000 */  not        $t0, $zero
    /* 306C 8013CC64 23400000 */  negu       $t0, $zero
    /* 3070 8013CC68 28400000 */  .word      0x00004028                    # INVALID    $zero, $zero, 0x4028 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 3074 8013CC6C 29400000 */  .word      0x00004029                    # INVALID    $zero, $zero, 0x4029 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 3078 8013CC70 23400000 */  negu       $t0, $zero
    /* 307C 8013CC74 2A400000 */  slt        $t0, $zero, $zero
    /* 3080 8013CC78 2B400000 */  sltu       $t0, $zero, $zero
    /* 3084 8013CC7C 23400000 */  negu       $t0, $zero
    /* 3088 8013CC80 2C400000 */  dadd       $t0, $zero, $zero
    /* 308C 8013CC84 2D400000 */  daddu      $t0, $zero, $zero
    /* 3090 8013CC88 23400000 */  negu       $t0, $zero
    /* 3094 8013CC8C 2E400000 */  dsub       $t0, $zero, $zero
    /* 3098 8013CC90 2F400000 */  dsubu      $t0, $zero, $zero
    /* 309C 8013CC94 23400000 */  negu       $t0, $zero
    /* 30A0 8013CC98 30400000 */  tge        $zero, $zero, 256 /* handwritten instruction */
    /* 30A4 8013CC9C 31400000 */  tgeu       $zero, $zero, 256 /* handwritten instruction */
    /* 30A8 8013CCA0 23400000 */  negu       $t0, $zero
    /* 30AC 8013CCA4 32400000 */  tlt        $zero, $zero, 256 /* handwritten instruction */
    /* 30B0 8013CCA8 33400000 */  tltu       $zero, $zero, 256 /* handwritten instruction */
    /* 30B4 8013CCAC 23400000 */  negu       $t0, $zero
    /* 30B8 8013CCB0 34400000 */  teq        $zero, $zero, 256 /* handwritten instruction */
    /* 30BC 8013CCB4 35400000 */  .word      0x00004035                    # INVALID    $zero, $zero, 0x4035 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 30C0 8013CCB8 36400000 */  tne        $zero, $zero, 256 /* handwritten instruction */
    /* 30C4 8013CCBC 37400000 */  .word      0x00004037                    # INVALID    $zero, $zero, 0x4037 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 30C8 8013CCC0 38400000 */  dsll       $t0, $zero, 0
    /* 30CC 8013CCC4 36400000 */  tne        $zero, $zero, 256 /* handwritten instruction */
    /* 30D0 8013CCC8 39400000 */  .word      0x00004039                    # INVALID    $zero, $zero, 0x4039 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 30D4 8013CCCC 3A400000 */  dsrl       $t0, $zero, 0
    /* 30D8 8013CCD0 36400000 */  tne        $zero, $zero, 256 /* handwritten instruction */
    /* 30DC 8013CCD4 3B400000 */  dsra       $t0, $zero, 0
    /* 30E0 8013CCD8 3C400000 */  dsll32     $t0, $zero, 0
    /* 30E4 8013CCDC 36400000 */  tne        $zero, $zero, 256 /* handwritten instruction */
    /* 30E8 8013CCE0 3D400000 */  .word      0x0000403D                    # INVALID    $zero, $zero, 0x403D # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 30EC 8013CCE4 3E400000 */  dsrl32     $t0, $zero, 0
    /* 30F0 8013CCE8 36400000 */  tne        $zero, $zero, 256 /* handwritten instruction */
    /* 30F4 8013CCEC 3D400000 */  .word      0x0000403D                    # INVALID    $zero, $zero, 0x403D # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 30F8 8013CCF0 3F400000 */  dsra32     $t0, $zero, 0
    /* 30FC 8013CCF4 36400000 */  tne        $zero, $zero, 256 /* handwritten instruction */
    /* 3100 8013CCF8 3D400000 */  .word      0x0000403D                    # INVALID    $zero, $zero, 0x403D # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 3104 8013CCFC 40400000 */  sll        $t0, $zero, 1
    /* 3108 8013CD00 36400000 */  tne        $zero, $zero, 256 /* handwritten instruction */
    /* 310C 8013CD04 3D400000 */  .word      0x0000403D                    # INVALID    $zero, $zero, 0x403D # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 3110 8013CD08 41400000 */  .word      0x00004041                    # INVALID    $zero, $zero, 0x4041 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 3114 8013CD0C 36400000 */  tne        $zero, $zero, 256 /* handwritten instruction */
    /* 3118 8013CD10 42400000 */  srl        $t0, $zero, 1
    /* 311C 8013CD14 43400000 */  sra        $t0, $zero, 1
    /* 3120 8013CD18 36400000 */  tne        $zero, $zero, 256 /* handwritten instruction */
    /* 3124 8013CD1C 44400000 */  .word      0x00004044                    # sllv       $t0, $zero, $zero # 00000040 <InstrIdType: CPU_SPECIAL>
    /* 3128 8013CD20 45400000 */  .word      0x00004045                    # INVALID    $zero, $zero, 0x4045 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 312C 8013CD24 36400000 */  tne        $zero, $zero, 256 /* handwritten instruction */
    /* 3130 8013CD28 46400000 */  .word      0x00004046                    # srlv       $t0, $zero, $zero # 00000040 <InstrIdType: CPU_SPECIAL>
    /* 3134 8013CD2C 47400000 */  .word      0x00004047                    # srav       $t0, $zero, $zero # 00000040 <InstrIdType: CPU_SPECIAL>
    /* 3138 8013CD30 36400000 */  tne        $zero, $zero, 256 /* handwritten instruction */
    /* 313C 8013CD34 46400000 */  .word      0x00004046                    # srlv       $t0, $zero, $zero # 00000040 <InstrIdType: CPU_SPECIAL>
    /* 3140 8013CD38 48400000 */  .word      0x00004048                    # jr         $zero # 00004040 <InstrIdType: CPU_SPECIAL>
    /* 3144 8013CD3C 53400000 */   .word     0x00004053                     # mtlo      $zero # 00004040 <InstrIdType: CPU_SPECIAL>
    /* 3148 8013CD40 54400000 */  .word      0x00004054                    # dsllv      $t0, $zero, $zero # 00000040 <InstrIdType: CPU_SPECIAL>
    /* 314C 8013CD44 55400000 */  .word      0x00004055                    # INVALID    $zero, $zero, 0x4055 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 3150 8013CD48 53400000 */  .word      0x00004053                    # mtlo       $zero # 00004040 <InstrIdType: CPU_SPECIAL>
    /* 3154 8013CD4C 56400000 */  .word      0x00004056                    # dsrlv      $t0, $zero, $zero # 00000040 <InstrIdType: CPU_SPECIAL>
    /* 3158 8013CD50 57400000 */  .word      0x00004057                    # dsrav      $t0, $zero, $zero # 00000040 <InstrIdType: CPU_SPECIAL>
    /* 315C 8013CD54 53400000 */  .word      0x00004053                    # mtlo       $zero # 00004040 <InstrIdType: CPU_SPECIAL>
    /* 3160 8013CD58 5A400000 */  .word      0x0000405A                    # div        $t0, $zero, $zero # 00000040 <InstrIdType: CPU_SPECIAL>
    /* 3164 8013CD5C 5B400000 */  .word      0x0000405B                    # divu       $t0, $zero, $zero # 00000040 <InstrIdType: CPU_SPECIAL>
    /* 3168 8013CD60 53400000 */  .word      0x00004053                    # mtlo       $zero # 00004040 <InstrIdType: CPU_SPECIAL>
    /* 316C 8013CD64 64400000 */  .word      0x00004064                    # and        $t0, $zero, $zero # 00000040 <InstrIdType: CPU_SPECIAL>
    /* 3170 8013CD68 65400000 */  .word      0x00004065                    # or         $t0, $zero, $zero # 00000040 <InstrIdType: CPU_SPECIAL>
    /* 3174 8013CD6C 53400000 */  .word      0x00004053                    # mtlo       $zero # 00004040 <InstrIdType: CPU_SPECIAL>
    /* 3178 8013CD70 64400000 */  .word      0x00004064                    # and        $t0, $zero, $zero # 00000040 <InstrIdType: CPU_SPECIAL>
    /* 317C 8013CD74 66400000 */  .word      0x00004066                    # xor        $t0, $zero, $zero # 00000040 <InstrIdType: CPU_SPECIAL>
    /* 3180 8013CD78 53400000 */  .word      0x00004053                    # mtlo       $zero # 00004040 <InstrIdType: CPU_SPECIAL>
    /* 3184 8013CD7C 64400000 */  .word      0x00004064                    # and        $t0, $zero, $zero # 00000040 <InstrIdType: CPU_SPECIAL>
    /* 3188 8013CD80 67400000 */  .word      0x00004067                    # not        $t0, $zero # 00000040 <InstrIdType: CPU_SPECIAL>
    /* 318C 8013CD84 53400000 */  .word      0x00004053                    # mtlo       $zero # 00004040 <InstrIdType: CPU_SPECIAL>
    /* 3190 8013CD88 58400000 */  .word      0x00004058                    # mult       $zero, $zero # 00004040 <InstrIdType: CPU_SPECIAL>
    /* 3194 8013CD8C 59400000 */  .word      0x00004059                    # multu      $zero, $zero # 00004040 <InstrIdType: CPU_SPECIAL>
    /* 3198 8013CD90 53400000 */  .word      0x00004053                    # mtlo       $zero # 00004040 <InstrIdType: CPU_SPECIAL>
    /* 319C 8013CD94 5C400000 */  .word      0x0000405C                    # dmult      $zero, $zero # 00004040 <InstrIdType: CPU_SPECIAL>
    /* 31A0 8013CD98 5D400000 */  .word      0x0000405D                    # dmultu     $zero, $zero # 00004040 <InstrIdType: CPU_SPECIAL>
    /* 31A4 8013CD9C 53400000 */  .word      0x00004053                    # mtlo       $zero # 00004040 <InstrIdType: CPU_SPECIAL>
    /* 31A8 8013CDA0 5E400000 */  .word      0x0000405E                    # ddiv       $t0, $zero, $zero # 00000040 <InstrIdType: CPU_SPECIAL>
    /* 31AC 8013CDA4 5F400000 */  .word      0x0000405F                    # ddivu      $t0, $zero, $zero # 00000040 <InstrIdType: CPU_SPECIAL>
    /* 31B0 8013CDA8 53400000 */  .word      0x00004053                    # mtlo       $zero # 00004040 <InstrIdType: CPU_SPECIAL>
    /* 31B4 8013CDAC 60400000 */  .word      0x00004060                    # add        $t0, $zero, $zero # 00000040 <InstrIdType: CPU_SPECIAL> /* handwritten instruction */
    /* 31B8 8013CDB0 61400000 */  .word      0x00004061                    # addu       $t0, $zero, $zero # 00000040 <InstrIdType: CPU_SPECIAL>
    /* 31BC 8013CDB4 53400000 */  .word      0x00004053                    # mtlo       $zero # 00004040 <InstrIdType: CPU_SPECIAL>
    /* 31C0 8013CDB8 62400000 */  .word      0x00004062                    # neg        $t0, $zero # 00000040 <InstrIdType: CPU_SPECIAL> /* handwritten instruction */
    /* 31C4 8013CDBC 63400000 */  .word      0x00004063                    # negu       $t0, $zero # 00000040 <InstrIdType: CPU_SPECIAL>
    /* 31C8 8013CDC0 49400000 */  .word      0x00004049                    # jalr       $t0, $zero # 00000040 <InstrIdType: CPU_SPECIAL>
    /* 31CC 8013CDC4 01400000 */   .word     0x00004001                     # INVALID   $zero, $zero, 0x4001 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 31D0 8013CDC8 4A400000 */  .word      0x0000404A                    # movz       $t0, $zero, $zero # 00000040 <InstrIdType: CPU_SPECIAL>
    /* 31D4 8013CDCC 49400000 */  .word      0x00004049                    # jalr       $t0, $zero # 00000040 <InstrIdType: CPU_SPECIAL>
    /* 31D8 8013CDD0 01400000 */   .word     0x00004001                     # INVALID   $zero, $zero, 0x4001 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 31DC 8013CDD4 4B400000 */  .word      0x0000404B                    # movn       $t0, $zero, $zero # 00000040 <InstrIdType: CPU_SPECIAL>
    /* 31E0 8013CDD8 49400000 */  .word      0x00004049                    # jalr       $t0, $zero # 00000040 <InstrIdType: CPU_SPECIAL>
    /* 31E4 8013CDDC 01400000 */   .word     0x00004001                     # INVALID   $zero, $zero, 0x4001 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 31E8 8013CDE0 4C400000 */  syscall    257 /* handwritten instruction */
    /* 31EC 8013CDE4 4D400000 */  break      0, 257
    /* 31F0 8013CDE8 01400000 */  .word      0x00004001                    # INVALID    $zero, $zero, 0x4001 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 31F4 8013CDEC 4E400000 */  .word      0x0000404E                    # INVALID    $zero, $zero, 0x404E # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 31F8 8013CDF0 4D400000 */  break      0, 257
    /* 31FC 8013CDF4 01400000 */  .word      0x00004001                    # INVALID    $zero, $zero, 0x4001 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 3200 8013CDF8 4F400000 */  .word      0x0000404F                    # sync # 00004040 <InstrIdType: CPU_SPECIAL>
    /* 3204 8013CDFC 4D400000 */  break      0, 257
    /* 3208 8013CE00 01400000 */  .word      0x00004001                    # INVALID    $zero, $zero, 0x4001 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 320C 8013CE04 50400000 */  .word      0x00004050                    # mfhi       $t0 # 00000040 <InstrIdType: CPU_SPECIAL>
    /* 3210 8013CE08 4D400000 */  break      0, 257
    /* 3214 8013CE0C 01400000 */  .word      0x00004001                    # INVALID    $zero, $zero, 0x4001 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 3218 8013CE10 51400000 */  .word      0x00004051                    # mthi       $zero # 00004040 <InstrIdType: CPU_SPECIAL>
    /* 321C 8013CE14 4D400000 */  break      0, 257
    /* 3220 8013CE18 01400000 */  .word      0x00004001                    # INVALID    $zero, $zero, 0x4001 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 3224 8013CE1C 52400000 */  .word      0x00004052                    # mflo       $t0 # 00000040 <InstrIdType: CPU_SPECIAL>
endlabel CreditsText

nonmatching CreditsTable, 0x380

glabel CreditsTable
    /* 3228 8013CE20 00000000 */  nop
    /* 322C 8013CE24 00000000 */  nop
    /* 3230 8013CE28 00000000 */  nop
    /* 3234 8013CE2C 00000000 */  nop
    /* 3238 8013CE30 00000000 */  nop
    /* 323C 8013CE34 00000000 */  nop
    /* 3240 8013CE38 00000000 */  nop
    /* 3244 8013CE3C 00000000 */  nop
    /* 3248 8013CE40 00000000 */  nop
    /* 324C 8013CE44 00000000 */  nop
    /* 3250 8013CE48 00000000 */  nop
    /* 3254 8013CE4C 00000000 */  nop
    /* 3258 8013CE50 00000000 */  nop
    /* 325C 8013CE54 00000000 */  nop
    /* 3260 8013CE58 00000000 */  nop
    /* 3264 8013CE5C 00000000 */  nop
    /* 3268 8013CE60 00000000 */  nop
    /* 326C 8013CE64 00000000 */  nop
    /* 3270 8013CE68 01000000 */  .word      0x00000001                    # INVALID    $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 3274 8013CE6C 01000000 */  .word      0x00000001                    # INVALID    $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 3278 8013CE70 01000000 */  .word      0x00000001                    # INVALID    $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 327C 8013CE74 01000000 */  .word      0x00000001                    # INVALID    $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 3280 8013CE78 01000000 */  .word      0x00000001                    # INVALID    $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 3284 8013CE7C 00000000 */  nop
    /* 3288 8013CE80 00000000 */  nop
    /* 328C 8013CE84 00000000 */  nop
    /* 3290 8013CE88 FFFFFFFF */  sd         $ra, -0x1($ra)
    /* 3294 8013CE8C FFFFFFFF */  sd         $ra, -0x1($ra)
    /* 3298 8013CE90 FFFFFFFF */  sd         $ra, -0x1($ra)
    /* 329C 8013CE94 FFFFFFFF */  sd         $ra, -0x1($ra)
    /* 32A0 8013CE98 FFFFFFFF */  sd         $ra, -0x1($ra)
    /* 32A4 8013CE9C 00000000 */  nop
    /* 32A8 8013CEA0 00000000 */  nop
    /* 32AC 8013CEA4 01000000 */  .word      0x00000001                    # INVALID    $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 32B0 8013CEA8 02000000 */  srl        $zero, $zero, 0
    /* 32B4 8013CEAC 02000000 */  srl        $zero, $zero, 0
    /* 32B8 8013CEB0 02000000 */  srl        $zero, $zero, 0
    /* 32BC 8013CEB4 02000000 */  srl        $zero, $zero, 0
    /* 32C0 8013CEB8 02000000 */  srl        $zero, $zero, 0
    /* 32C4 8013CEBC 01000000 */  .word      0x00000001                    # INVALID    $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 32C8 8013CEC0 00000000 */  nop
    /* 32CC 8013CEC4 FFFFFFFF */  sd         $ra, -0x1($ra)
    /* 32D0 8013CEC8 FEFFFFFF */  sd         $ra, -0x2($ra)
    /* 32D4 8013CECC FEFFFFFF */  sd         $ra, -0x2($ra)
    /* 32D8 8013CED0 FDFFFFFF */  sd         $ra, -0x3($ra)
    /* 32DC 8013CED4 FEFFFFFF */  sd         $ra, -0x2($ra)
    /* 32E0 8013CED8 FEFFFFFF */  sd         $ra, -0x2($ra)
    /* 32E4 8013CEDC FFFFFFFF */  sd         $ra, -0x1($ra)
    /* 32E8 8013CEE0 00000000 */  nop
    /* 32EC 8013CEE4 01000000 */  .word      0x00000001                    # INVALID    $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 32F0 8013CEE8 02000000 */  srl        $zero, $zero, 0
    /* 32F4 8013CEEC 03000000 */  sra        $zero, $zero, 0
    /* 32F8 8013CEF0 03000000 */  sra        $zero, $zero, 0
    /* 32FC 8013CEF4 03000000 */  sra        $zero, $zero, 0
    /* 3300 8013CEF8 02000000 */  srl        $zero, $zero, 0
    /* 3304 8013CEFC 01000000 */  .word      0x00000001                    # INVALID    $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 3308 8013CF00 00000000 */  nop
    /* 330C 8013CF04 FFFFFFFF */  sd         $ra, -0x1($ra)
    /* 3310 8013CF08 FEFFFFFF */  sd         $ra, -0x2($ra)
    /* 3314 8013CF0C FDFFFFFF */  sd         $ra, -0x3($ra)
    /* 3318 8013CF10 FDFFFFFF */  sd         $ra, -0x3($ra)
    /* 331C 8013CF14 FDFFFFFF */  sd         $ra, -0x3($ra)
    /* 3320 8013CF18 FEFFFFFF */  sd         $ra, -0x2($ra)
    /* 3324 8013CF1C FFFFFFFF */  sd         $ra, -0x1($ra)
    /* 3328 8013CF20 00000000 */  nop
    /* 332C 8013CF24 01000000 */  .word      0x00000001                    # INVALID    $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 3330 8013CF28 03000000 */  sra        $zero, $zero, 0
    /* 3334 8013CF2C 04000000 */  sllv       $zero, $zero, $zero
    /* 3338 8013CF30 04000000 */  sllv       $zero, $zero, $zero
    /* 333C 8013CF34 04000000 */  sllv       $zero, $zero, $zero
    /* 3340 8013CF38 03000000 */  sra        $zero, $zero, 0
    /* 3344 8013CF3C 01000000 */  .word      0x00000001                    # INVALID    $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 3348 8013CF40 00000000 */  nop
    /* 334C 8013CF44 FFFFFFFF */  sd         $ra, -0x1($ra)
    /* 3350 8013CF48 FDFFFFFF */  sd         $ra, -0x3($ra)
    /* 3354 8013CF4C FCFFFFFF */  sd         $ra, -0x4($ra)
    /* 3358 8013CF50 FBFFFFFF */  sd         $ra, -0x5($ra)
    /* 335C 8013CF54 FCFFFFFF */  sd         $ra, -0x4($ra)
    /* 3360 8013CF58 FDFFFFFF */  sd         $ra, -0x3($ra)
    /* 3364 8013CF5C FFFFFFFF */  sd         $ra, -0x1($ra)
    /* 3368 8013CF60 00000000 */  nop
    /* 336C 8013CF64 02000000 */  srl        $zero, $zero, 0
    /* 3370 8013CF68 04000000 */  sllv       $zero, $zero, $zero
    /* 3374 8013CF6C 05000000 */  .word      0x00000005                    # INVALID    $zero, $zero, 0x5 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 3378 8013CF70 05000000 */  .word      0x00000005                    # INVALID    $zero, $zero, 0x5 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 337C 8013CF74 05000000 */  .word      0x00000005                    # INVALID    $zero, $zero, 0x5 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 3380 8013CF78 04000000 */  sllv       $zero, $zero, $zero
    /* 3384 8013CF7C 02000000 */  srl        $zero, $zero, 0
    /* 3388 8013CF80 00000000 */  nop
    /* 338C 8013CF84 FEFFFFFF */  sd         $ra, -0x2($ra)
    /* 3390 8013CF88 FCFFFFFF */  sd         $ra, -0x4($ra)
    /* 3394 8013CF8C FBFFFFFF */  sd         $ra, -0x5($ra)
    /* 3398 8013CF90 FAFFFFFF */  sd         $ra, -0x6($ra)
    /* 339C 8013CF94 FBFFFFFF */  sd         $ra, -0x5($ra)
    /* 33A0 8013CF98 FCFFFFFF */  sd         $ra, -0x4($ra)
    /* 33A4 8013CF9C FEFFFFFF */  sd         $ra, -0x2($ra)
    /* 33A8 8013CFA0 00000000 */  nop
    /* 33AC 8013CFA4 02000000 */  srl        $zero, $zero, 0
    /* 33B0 8013CFA8 04000000 */  sllv       $zero, $zero, $zero
    /* 33B4 8013CFAC 06000000 */  srlv       $zero, $zero, $zero
    /* 33B8 8013CFB0 06000000 */  srlv       $zero, $zero, $zero
    /* 33BC 8013CFB4 06000000 */  srlv       $zero, $zero, $zero
    /* 33C0 8013CFB8 04000000 */  sllv       $zero, $zero, $zero
    /* 33C4 8013CFBC 02000000 */  srl        $zero, $zero, 0
    /* 33C8 8013CFC0 00000000 */  nop
    /* 33CC 8013CFC4 FEFFFFFF */  sd         $ra, -0x2($ra)
    /* 33D0 8013CFC8 FCFFFFFF */  sd         $ra, -0x4($ra)
    /* 33D4 8013CFCC FAFFFFFF */  sd         $ra, -0x6($ra)
    /* 33D8 8013CFD0 FAFFFFFF */  sd         $ra, -0x6($ra)
    /* 33DC 8013CFD4 FAFFFFFF */  sd         $ra, -0x6($ra)
    /* 33E0 8013CFD8 FCFFFFFF */  sd         $ra, -0x4($ra)
    /* 33E4 8013CFDC FEFFFFFF */  sd         $ra, -0x2($ra)
    /* 33E8 8013CFE0 00000000 */  nop
    /* 33EC 8013CFE4 03000000 */  sra        $zero, $zero, 0
    /* 33F0 8013CFE8 05000000 */  .word      0x00000005                    # INVALID    $zero, $zero, 0x5 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 33F4 8013CFEC 07000000 */  srav       $zero, $zero, $zero
    /* 33F8 8013CFF0 07000000 */  srav       $zero, $zero, $zero
    /* 33FC 8013CFF4 07000000 */  srav       $zero, $zero, $zero
    /* 3400 8013CFF8 05000000 */  .word      0x00000005                    # INVALID    $zero, $zero, 0x5 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 3404 8013CFFC 03000000 */  sra        $zero, $zero, 0
    /* 3408 8013D000 00000000 */  nop
    /* 340C 8013D004 FDFFFFFF */  sd         $ra, -0x3($ra)
    /* 3410 8013D008 FBFFFFFF */  sd         $ra, -0x5($ra)
    /* 3414 8013D00C F9FFFFFF */  sd         $ra, -0x7($ra)
    /* 3418 8013D010 F9FFFFFF */  sd         $ra, -0x7($ra)
    /* 341C 8013D014 F9FFFFFF */  sd         $ra, -0x7($ra)
    /* 3420 8013D018 FBFFFFFF */  sd         $ra, -0x5($ra)
    /* 3424 8013D01C FDFFFFFF */  sd         $ra, -0x3($ra)
    /* 3428 8013D020 00000000 */  nop
    /* 342C 8013D024 03000000 */  sra        $zero, $zero, 0
    /* 3430 8013D028 06000000 */  srlv       $zero, $zero, $zero
    /* 3434 8013D02C 08000000 */  jr         $zero
    /* 3438 8013D030 08000000 */   jr        $zero
    /* 343C 8013D034 08000000 */   jr        $zero
    /* 3440 8013D038 06000000 */   srlv      $zero, $zero, $zero
    /* 3444 8013D03C 03000000 */  sra        $zero, $zero, 0
    /* 3448 8013D040 00000000 */  nop
    /* 344C 8013D044 FDFFFFFF */  sd         $ra, -0x3($ra)
    /* 3450 8013D048 FAFFFFFF */  sd         $ra, -0x6($ra)
    /* 3454 8013D04C F8FFFFFF */  sd         $ra, -0x8($ra)
    /* 3458 8013D050 F7FFFFFF */  sd         $ra, -0x9($ra)
    /* 345C 8013D054 F8FFFFFF */  sd         $ra, -0x8($ra)
    /* 3460 8013D058 FAFFFFFF */  sd         $ra, -0x6($ra)
    /* 3464 8013D05C FDFFFFFF */  sd         $ra, -0x3($ra)
    /* 3468 8013D060 00000000 */  nop
    /* 346C 8013D064 03000000 */  sra        $zero, $zero, 0
    /* 3470 8013D068 07000000 */  srav       $zero, $zero, $zero
    /* 3474 8013D06C 09000000 */  jalr       $zero, $zero
    /* 3478 8013D070 09000000 */   jalr      $zero, $zero
    /* 347C 8013D074 09000000 */   jalr      $zero, $zero
    /* 3480 8013D078 07000000 */   srav      $zero, $zero, $zero
    /* 3484 8013D07C 03000000 */  sra        $zero, $zero, 0
    /* 3488 8013D080 00000000 */  nop
    /* 348C 8013D084 FDFFFFFF */  sd         $ra, -0x3($ra)
    /* 3490 8013D088 F9FFFFFF */  sd         $ra, -0x7($ra)
    /* 3494 8013D08C F7FFFFFF */  sd         $ra, -0x9($ra)
    /* 3498 8013D090 F6FFFFFF */  sd         $ra, -0xA($ra)
    /* 349C 8013D094 F7FFFFFF */  sd         $ra, -0x9($ra)
    /* 34A0 8013D098 F9FFFFFF */  sd         $ra, -0x7($ra)
    /* 34A4 8013D09C FDFFFFFF */  sd         $ra, -0x3($ra)
    /* 34A8 8013D0A0 00000000 */  nop
    /* 34AC 8013D0A4 04000000 */  sllv       $zero, $zero, $zero
    /* 34B0 8013D0A8 07000000 */  srav       $zero, $zero, $zero
    /* 34B4 8013D0AC 0A000000 */  movz       $zero, $zero, $zero
    /* 34B8 8013D0B0 0A000000 */  movz       $zero, $zero, $zero
    /* 34BC 8013D0B4 0A000000 */  movz       $zero, $zero, $zero
    /* 34C0 8013D0B8 07000000 */  srav       $zero, $zero, $zero
    /* 34C4 8013D0BC 04000000 */  sllv       $zero, $zero, $zero
    /* 34C8 8013D0C0 00000000 */  nop
    /* 34CC 8013D0C4 FCFFFFFF */  sd         $ra, -0x4($ra)
    /* 34D0 8013D0C8 F9FFFFFF */  sd         $ra, -0x7($ra)
    /* 34D4 8013D0CC F6FFFFFF */  sd         $ra, -0xA($ra)
    /* 34D8 8013D0D0 F5FFFFFF */  sd         $ra, -0xB($ra)
    /* 34DC 8013D0D4 F6FFFFFF */  sd         $ra, -0xA($ra)
    /* 34E0 8013D0D8 F9FFFFFF */  sd         $ra, -0x7($ra)
    /* 34E4 8013D0DC FCFFFFFF */  sd         $ra, -0x4($ra)
    /* 34E8 8013D0E0 00000000 */  nop
    /* 34EC 8013D0E4 04000000 */  sllv       $zero, $zero, $zero
    /* 34F0 8013D0E8 07000000 */  srav       $zero, $zero, $zero
    /* 34F4 8013D0EC 0A000000 */  movz       $zero, $zero, $zero
    /* 34F8 8013D0F0 0A000000 */  movz       $zero, $zero, $zero
    /* 34FC 8013D0F4 0A000000 */  movz       $zero, $zero, $zero
    /* 3500 8013D0F8 07000000 */  srav       $zero, $zero, $zero
    /* 3504 8013D0FC 04000000 */  sllv       $zero, $zero, $zero
    /* 3508 8013D100 00000000 */  nop
    /* 350C 8013D104 FCFFFFFF */  sd         $ra, -0x4($ra)
    /* 3510 8013D108 F9FFFFFF */  sd         $ra, -0x7($ra)
    /* 3514 8013D10C F6FFFFFF */  sd         $ra, -0xA($ra)
    /* 3518 8013D110 F5FFFFFF */  sd         $ra, -0xB($ra)
    /* 351C 8013D114 F6FFFFFF */  sd         $ra, -0xA($ra)
    /* 3520 8013D118 F9FFFFFF */  sd         $ra, -0x7($ra)
    /* 3524 8013D11C FCFFFFFF */  sd         $ra, -0x4($ra)
    /* 3528 8013D120 00000000 */  nop
    /* 352C 8013D124 04000000 */  sllv       $zero, $zero, $zero
    /* 3530 8013D128 07000000 */  srav       $zero, $zero, $zero
    /* 3534 8013D12C 0A000000 */  movz       $zero, $zero, $zero
    /* 3538 8013D130 0A000000 */  movz       $zero, $zero, $zero
    /* 353C 8013D134 0A000000 */  movz       $zero, $zero, $zero
    /* 3540 8013D138 07000000 */  srav       $zero, $zero, $zero
    /* 3544 8013D13C 04000000 */  sllv       $zero, $zero, $zero
    /* 3548 8013D140 00000000 */  nop
    /* 354C 8013D144 FCFFFFFF */  sd         $ra, -0x4($ra)
    /* 3550 8013D148 F9FFFFFF */  sd         $ra, -0x7($ra)
    /* 3554 8013D14C F6FFFFFF */  sd         $ra, -0xA($ra)
    /* 3558 8013D150 F5FFFFFF */  sd         $ra, -0xB($ra)
    /* 355C 8013D154 F6FFFFFF */  sd         $ra, -0xA($ra)
    /* 3560 8013D158 F9FFFFFF */  sd         $ra, -0x7($ra)
    /* 3564 8013D15C FCFFFFFF */  sd         $ra, -0x4($ra)
    /* 3568 8013D160 00000000 */  nop
    /* 356C 8013D164 04000000 */  sllv       $zero, $zero, $zero
    /* 3570 8013D168 07000000 */  srav       $zero, $zero, $zero
    /* 3574 8013D16C 0A000000 */  movz       $zero, $zero, $zero
    /* 3578 8013D170 0A000000 */  movz       $zero, $zero, $zero
    /* 357C 8013D174 0A000000 */  movz       $zero, $zero, $zero
    /* 3580 8013D178 07000000 */  srav       $zero, $zero, $zero
    /* 3584 8013D17C 04000000 */  sllv       $zero, $zero, $zero
    /* 3588 8013D180 00000000 */  nop
    /* 358C 8013D184 FCFFFFFF */  sd         $ra, -0x4($ra)
    /* 3590 8013D188 F9FFFFFF */  sd         $ra, -0x7($ra)
    /* 3594 8013D18C F6FFFFFF */  sd         $ra, -0xA($ra)
    /* 3598 8013D190 F5FFFFFF */  sd         $ra, -0xB($ra)
    /* 359C 8013D194 F6FFFFFF */  sd         $ra, -0xA($ra)
    /* 35A0 8013D198 F9FFFFFF */  sd         $ra, -0x7($ra)
    /* 35A4 8013D19C FCFFFFFF */  sd         $ra, -0x4($ra)
endlabel CreditsTable
