.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.42.4 */

nonmatching ClassStrTbl, 0xC

glabel ClassStrTbl
    /* 9A00 801435F8 BE040000 */  dsrl32     $zero, $zero, 18
    /* 9A04 801435FC 75030000 */  .word      0x00000375                    # INVALID    $zero, $zero, 0x375 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 9A08 80143600 E8030000 */  .word      0x000003E8                    # INVALID    $zero, $zero, 0x3E8 # 00000000 <InstrIdType: CPU_SPECIAL>
endlabel ClassStrTbl
