.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.42.4 */

nonmatching HARCH14, 0xE

glabel HARCH14
    /* 785C 80141454 03020303 */  .word      0x03030203                    # sra        $zero, $v1, 8 # 03000000 <InstrIdType: CPU_SPECIAL>
    /* 7860 80141458 00080510 */  beq        $zero, $a1, .L8014345C
    /* 7864 8014145C 312E002B */   slti      $zero, $t8, 0x2E31
    /* 7868 80141460 2D000000 */  daddu      $zero, $zero, $zero
