.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.42.4 */

nonmatching VARCH14, 0x12

glabel VARCH14
    /* 7590 80141188 02040300 */  srl        $zero, $v1, 16
    /* 7594 8014118C 03080304 */  bgezl      $zero, .L8014319C
    /* 7598 80141190 000D3000 */   .word     0x00300D00                     # sll       $at, $s0, 20 # 00200000 <InstrIdType: CPU_SPECIAL>
    /* 759C 80141194 332A2F2C */  sltiu      $t7, $at, 0x2A33
    /* 75A0 80141198 00000000 */  nop
