.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.42.4 */

nonmatching HARCH25, 0xE

glabel HARCH25
    /* 790C 80141504 03020303 */  .word      0x03030203                    # sra        $zero, $v1, 8 # 03000000 <InstrIdType: CPU_SPECIAL>
    /* 7910 80141508 00050209 */  j          func_84081400
    /* 7914 8014150C 312E0028 */   slti      $zero, $zero, 0x2E31
  .L80141510:
    /* 7918 80141510 2D000000 */  daddu      $zero, $zero, $zero
