.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.42.4 */

nonmatching VARCH9, 0x12

glabel VARCH9
    /* 752C 80141124 02040300 */  srl        $zero, $v1, 16
    /* 7530 80141128 03080304 */  bgezl      $zero, .L80143138
    /* 7534 8014112C 00073000 */   .word     0x00300700                     # sll       $zero, $s0, 28 # 00200000 <InstrIdType: CPU_SPECIAL>
    /* 7538 80141130 332A2F2C */  sltiu      $t7, $at, 0x2A33
    /* 753C 80141134 00000000 */  nop
