.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.42.4 */

nonmatching Dir_Xadd, 0x14

glabel Dir_Xadd
    /* 730C 80140F04 00000000 */  nop
    /* 7310 80140F08 00000000 */  nop
    /* 7314 80140F0C 01000000 */  .word      0x00000001                    # INVALID    $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 7318 80140F10 00000000 */  nop
    /* 731C 80140F14 FFFFFFFF */  sd         $ra, -0x1($ra)
endlabel Dir_Xadd

nonmatching Dir_Yadd, 0x14

glabel Dir_Yadd
    /* 7320 80140F18 00000000 */  nop
    /* 7324 80140F1C FFFFFFFF */  sd         $ra, -0x1($ra)
    /* 7328 80140F20 00000000 */  nop
    /* 732C 80140F24 01000000 */  .word      0x00000001                    # INVALID    $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 7330 80140F28 00000000 */  nop
endlabel Dir_Yadd

nonmatching SPATSL2, 0xE

glabel SPATSL2
    /* 7334 80140F2C 06030003 */  .word      0x03000306                    # srlv       $zero, $zero, $t8 # 00000300 <InstrIdType: CPU_SPECIAL>
    /* 7338 80140F30 30003209 */  j          func_84C800C0
    /* 733C 80140F34 03000330 */   andi      $v1, $zero, 0x3
    /* 7340 80140F38 00320000 */  sll        $a2, $zero, 8
