.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.42.4 */

nonmatching HARCH3, 0xE

glabel HARCH3
    /* 77AC 801413A4 03020303 */  .word      0x03030203                    # sra        $zero, $v1, 8 # 03000000 <InstrIdType: CPU_SPECIAL>
    /* 77B0 801413A8 00020508 */  j          .L80140800
    /* 77B4 801413AC 312E0028 */   slti      $zero, $zero, 0x2E31
    /* 77B8 801413B0 2D000000 */  daddu      $zero, $zero, $zero
