.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.42.4 */

nonmatching HARCH22, 0xE

glabel HARCH22
    /* 78DC 801414D4 03020103 */  .word      0x03010203                    # sra        $zero, $at, 8 # 03000000 <InstrIdType: CPU_SPECIAL>
    /* 78E0 801414D8 00080510 */  beq        $zero, $a1, .L801434DC
    /* 78E4 801414DC 8C2E002B */   slti      $zero, $t8, 0x2E8C
    /* 78E8 801414E0 2D000000 */  daddu      $zero, $zero, $zero
