.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.42.4 */

nonmatching HARCH32, 0xE

glabel HARCH32
    /* 797C 80141574 03020303 */  .word      0x03030203                    # sra        $zero, $v1, 8 # 03000000 <InstrIdType: CPU_SPECIAL>
    /* 7980 80141578 0005020E */  jal        func_88081400
    /* 7984 8014157C 312E0028 */   slti      $zero, $zero, 0x2E31
    /* 7988 80141580 2D000000 */  daddu      $zero, $zero, $zero
