.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.42.4 */

/* Handwritten function */
nonmatching poolsub, 0xF

glabel poolsub
    /* EADC 801486D4 00231A24 */  addiu      $k0, $zero, 0x2300 /* handwritten instruction */
    /* EAE0 801486D8 191D2207 */  bltzl      $t9, .L8014FB40
    /* EAE4 801486DC 211C1B25 */   addiu     $k1, $t0, 0x1C21 /* handwritten instruction */
    /* EAE8 801486E0 201F1E00 */  .word      0x001E1F20                    # add        $v1, $zero, $fp # 00000700 <InstrIdType: CPU_SPECIAL> /* handwritten instruction */
