.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.42.4 */

nonmatching HARCH9, 0xE

glabel HARCH9
    /* 780C 80141404 03020303 */  .word      0x03030203                    # sra        $zero, $v1, 8 # 03000000 <InstrIdType: CPU_SPECIAL>
    /* 7810 80141408 00080509 */  j          func_84142000
    /* 7814 8014140C 312E002B */   slti      $zero, $t8, 0x2E31
    /* 7818 80141410 2D000000 */  daddu      $zero, $zero, $zero
