.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.42.4 */

nonmatching VARCH12, 0x12

glabel VARCH12
    /* 7568 80141160 02040300 */  srl        $zero, $v1, 16
    /* 756C 80141164 03080304 */  bgezl      $zero, .L80143174
    /* 7570 80141168 00093000 */   .word     0x00300900                     # sll       $at, $s0, 4 # 00200000 <InstrIdType: CPU_SPECIAL>
    /* 7574 8014116C 332A2F2C */  sltiu      $t7, $at, 0x2A33
    /* 7578 80141170 00000000 */  nop
