.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.42.4 */

nonmatching VARCH6, 0x12

glabel VARCH6
    /* 74F0 801410E8 02040300 */  srl        $zero, $v1, 16
    /* 74F4 801410EC 03010304 */  bgezl      $zero, .L801414FC
    /* 74F8 801410F0 000D3000 */   .word     0x00300D00                     # sll       $at, $s0, 20 # 00200000 <InstrIdType: CPU_SPECIAL>
    /* 74FC 801410F4 33272F2C */  sltiu      $t7, $at, 0x2733
    /* 7500 801410F8 00000000 */  nop
