.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.42.4 */

nonmatching BTYPESL2, 0xA1

glabel BTYPESL2
    /* 7344 80140F3C 00010203 */  .word      0x03020100                    # sll        $zero, $v0, 4 # 03000000 <InstrIdType: CPU_SPECIAL>
    /* 7348 80140F40 04050607 */  .word      0x07060504                    # INVALID    $t8, $a2, 0x504 # 00000000 <InstrIdType: CPU_REGIMM>
    /* 734C 80140F44 08090000 */  .word      0x00000908                    # jr         $zero # 00000900 <InstrIdType: CPU_SPECIAL>
    /* 7350 80140F48 00000000 */   nop
    /* 7354 80140F4C 00111201 */  .word      0x01121100                    # sll        $v0, $s2, 4 # 01000000 <InstrIdType: CPU_SPECIAL>
    /* 7358 80140F50 01020201 */  .word      0x01020201                    # INVALID    $t0, $v0, 0x201 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 735C 80140F54 01010101 */  .word      0x01010101                    # INVALID    $t0, $at, 0x101 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 7360 80140F58 01020202 */  .word      0x02020201                    # INVALID    $s0, $v0, 0x201 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 7364 80140F5C 02020000 */  srl        $zero, $zero, 8
    /* 7368 80140F60 00000800 */  sll        $zero, $t0, 0
    /* 736C 80140F64 00000000 */  nop
    /* 7370 80140F68 00000000 */  nop
    /* 7374 80140F6C 00000000 */  nop
    /* 7378 80140F70 00000000 */  nop
    /* 737C 80140F74 00000000 */  nop
    /* 7380 80140F78 00000000 */  nop
    /* 7384 80140F7C 00000000 */  nop
    /* 7388 80140F80 01010100 */  .word      0x00010101                    # INVALID    $zero, $at, 0x101 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 738C 80140F84 00020202 */  .word      0x02020200                    # sll        $zero, $v0, 8 # 02000000 <InstrIdType: CPU_SPECIAL>
    /* 7390 80140F88 00000001 */  .word      0x01000000                    # sll        $zero, $zero, 0 # 01000000 <InstrIdType: CPU_SPECIAL>
    /* 7394 80140F8C 00000000 */  nop
    /* 7398 80140F90 00000000 */  nop
    /* 739C 80140F94 03030303 */  .word      0x03030303                    # sra        $zero, $v1, 12 # 03000000 <InstrIdType: CPU_SPECIAL>
    /* 73A0 80140F98 00000000 */  nop
    /* 73A4 80140F9C 00000000 */  nop
    /* 73A8 80140FA0 00000000 */  nop
    /* 73AC 80140FA4 00030303 */  .word      0x03030300                    # sll        $zero, $v1, 12 # 03000000 <InstrIdType: CPU_SPECIAL>
    /* 73B0 80140FA8 00030003 */  .word      0x03000300                    # sll        $zero, $zero, 12 # 03000000 <InstrIdType: CPU_SPECIAL>
    /* 73B4 80140FAC 00000000 */  nop
    /* 73B8 80140FB0 00000000 */  nop
    /* 73BC 80140FB4 00000000 */  nop
    /* 73C0 80140FB8 00000000 */  nop
    /* 73C4 80140FBC 00000000 */  nop
    /* 73C8 80140FC0 00000000 */  nop
    /* 73CC 80140FC4 00000000 */  nop
    /* 73D0 80140FC8 00000000 */  nop
    /* 73D4 80140FCC 00000000 */  nop
    /* 73D8 80140FD0 00000000 */  nop
    /* 73DC 80140FD4 00000000 */  nop
    /* 73E0 80140FD8 00000000 */  nop
    /* 73E4 80140FDC 00000000 */  nop
