.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.42.4 */

nonmatching HARCH13, 0xE

glabel HARCH13
    /* 784C 80141444 03020303 */  .word      0x03030203                    # sra        $zero, $v1, 8 # 03000000 <InstrIdType: CPU_SPECIAL>
    /* 7850 80141448 0008050F */  jal        func_8C142000
    /* 7854 8014144C 312E002B */   slti      $zero, $t8, 0x2E31
    /* 7858 80141450 2D000000 */  daddu      $zero, $zero, $zero
