.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.42.4 */

nonmatching HARCH24, 0xE

glabel HARCH24
    /* 78FC 801414F4 03020103 */  .word      0x03010203                    # sra        $zero, $at, 8 # 03000000 <InstrIdType: CPU_SPECIAL>
    /* 7900 801414F8 0008050E */  jal        func_88142000
  .L801414FC:
    /* 7904 801414FC 8C2E002B */   slti      $zero, $t8, 0x2E8C
    /* 7908 80141500 2D000000 */  daddu      $zero, $zero, $zero
