.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.42.4 */

nonmatching HARCH26, 0xE

glabel HARCH26
    /* 791C 80141514 03020303 */  .word      0x03030203                    # sra        $zero, $v1, 8 # 03000000 <InstrIdType: CPU_SPECIAL>
    /* 7920 80141518 00050206 */  bltzl      $s0, .L8014291C
    /* 7924 8014151C 312E0028 */   slti      $zero, $zero, 0x2E31
    /* 7928 80141520 2D000000 */  daddu      $zero, $zero, $zero
