.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.42.4 */

nonmatching HARCH12, 0xE

glabel HARCH12
    /* 783C 80141434 03020303 */  .word      0x03030203                    # sra        $zero, $v1, 8 # 03000000 <InstrIdType: CPU_SPECIAL>
  .L80141438:
    /* 7840 80141438 00080507 */  .word      0x07050800                    # INVALID    $t8, $a1, 0x800 # 00000000 <InstrIdType: CPU_REGIMM>
    /* 7844 8014143C 312E002B */  slti       $zero, $t8, 0x2E31
    /* 7848 80141440 2D000000 */  daddu      $zero, $zero, $zero
