.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.42.4 */

nonmatching HARCH6, 0xE

glabel HARCH6
    /* 77DC 801413D4 03020303 */  .word      0x03030203                    # sra        $zero, $v1, 8 # 03000000 <InstrIdType: CPU_SPECIAL>
    /* 77E0 801413D8 00020510 */  beq        $zero, $a1, .L80141BDC
    /* 77E4 801413DC 312E0028 */   slti      $zero, $zero, 0x2E31
    /* 77E8 801413E0 2D000000 */  daddu      $zero, $zero, $zero
