.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.42.4 */

nonmatching L3TITE2, 0x22

glabel L3TITE2
    /* EB5C 80148754 04040707 */  .word      0x07070404                    # INVALID    $t8, $a3, 0x404 # 00000000 <InstrIdType: CPU_REGIMM>
    /* EB60 80148758 07070707 */  .word      0x07070707                    # INVALID    $t8, $a3, 0x707 # 00000000 <InstrIdType: CPU_REGIMM>
    /* EB64 8014875C 07070707 */  .word      0x07070707                    # INVALID    $t8, $a3, 0x707 # 00000000 <InstrIdType: CPU_REGIMM>
    /* EB68 80148760 07070707 */  .word      0x07070707                    # INVALID    $t8, $a3, 0x707 # 00000000 <InstrIdType: CPU_REGIMM>
    /* EB6C 80148764 07070000 */  .word      0x00000707                    # srav       $zero, $zero, $zero # 00000700 <InstrIdType: CPU_SPECIAL>
    /* EB70 80148768 0000003D */  .word      0x3D000000                    # lui        $zero, (0x0 >> 16) # 01000000 <InstrIdType: CPU_NORMAL>
    /* EB74 8014876C 3E00003C */  lui        $zero, (0x3E0000 >> 16)
    /* EB78 80148770 3B000000 */  dsra       $zero, $zero, 0
    /* EB7C 80148774 00000000 */  nop
