.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.42.4 */

nonmatching VARCH30, 0x12

glabel VARCH30
    /* 76B0 801412A8 02040300 */  srl        $zero, $v1, 16
    /* 76B4 801412AC 03040301 */  .word      0x01030403                    # sra        $zero, $v1, 16 # 01000000 <InstrIdType: CPU_SPECIAL>
    /* 76B8 801412B0 000D3000 */  .word      0x00300D00                    # sll        $at, $s0, 20 # 00200000 <InstrIdType: CPU_SPECIAL>
    /* 76BC 801412B4 33272F2C */  sltiu      $t7, $at, 0x2733
    /* 76C0 801412B8 00000000 */  nop
