.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.42.4 */

nonmatching BIG2, 0xA

glabel BIG2
    /* 7A98 80141690 02020303 */  .word      0x03030202                    # srl        $zero, $v1, 8 # 03000000 <InstrIdType: CPU_SPECIAL>
    /* 7A9C 80141694 03037273 */  .word      0x73720303                    # INVALID    $k1, $s2, 0x303 # 00000000 <InstrIdType: CPU_NORMAL>
    /* 7AA0 80141698 00000000 */  nop
