.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.42.4 */

nonmatching HARCH17, 0xE

glabel HARCH17
    /* 788C 80141484 03020103 */  .word      0x03010203                    # sra        $zero, $at, 8 # 03000000 <InstrIdType: CPU_SPECIAL>
    /* 7890 80141488 00080509 */  j          func_84142000
    /* 7894 8014148C 8C2E002B */   slti      $zero, $t8, 0x2E8C
    /* 7898 80141490 2D000000 */  daddu      $zero, $zero, $zero
