.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.42.4 */

nonmatching HARCH34, 0xE

glabel HARCH34
    /* 799C 80141594 03020103 */  .word      0x03010203                    # sra        $zero, $at, 8 # 03000000 <InstrIdType: CPU_SPECIAL>
    /* 79A0 80141598 00090506 */  .word      0x06050900                    # INVALID    $s0, $a1, 0x900 # 00000000 <InstrIdType: CPU_REGIMM>
    /* 79A4 8014159C 8C2E0028 */  slti       $zero, $zero, 0x2E8C
    /* 79A8 801415A0 2D000000 */  daddu      $zero, $zero, $zero
