.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.42.4 */

nonmatching BIG5, 0xA

glabel BIG5
    /* 7AA4 8014169C 02020303 */  .word      0x03030202                    # srl        $zero, $v1, 8 # 03000000 <InstrIdType: CPU_SPECIAL>
    /* 7AA8 801416A0 0303787A */  .word      0x7A780303                    # INVALID    $s3, $t8, 0x303 # 00000000 <InstrIdType: CPU_NORMAL>
    /* 7AAC 801416A4 797B0000 */  .word      0x00007B79                    # INVALID    $zero, $zero, 0x7B79 # 00000000 <InstrIdType: CPU_SPECIAL>
