.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.42.4 */

nonmatching CRUSHCOL, 0x14

glabel CRUSHCOL
    /* 7A78 80141670 03030301 */  .word      0x01030303                    # sra        $zero, $v1, 12 # 01000000 <InstrIdType: CPU_SPECIAL>
    /* 7A7C 80141674 03020603 */  .word      0x03060203                    # sra        $zero, $a2, 8 # 03000000 <InstrIdType: CPU_SPECIAL>
    /* 7A80 80141678 03030300 */  sra        $zero, $v1, 12
    /* 7A84 8014167C 00000053 */  beql       $t8, $zero, .L80141680
  .L80141680:
    /* 7A88 80141680 00000000 */   nop
endlabel CRUSHCOL

/* Handwritten function */
nonmatching BIG1, 0xA

glabel BIG1
    /* 7A8C 80141684 02020303 */  .word      0x03030202                    # srl        $zero, $v1, 8 # 03000000 <InstrIdType: CPU_SPECIAL>
    /* 7A90 80141688 03037100 */  .word      0x00710303                    # sra        $zero, $s1, 12 # 00600000 <InstrIdType: CPU_SPECIAL>
    /* 7A94 8014168C 70000000 */  tge        $zero, $zero, 1 /* handwritten instruction */
