.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.42.4 */

nonmatching BSTYPESL2, 0xA1

glabel BSTYPESL2
    /* 73E8 80140FE0 00010203 */  .word      0x03020100                    # sll        $zero, $v0, 4 # 03000000 <InstrIdType: CPU_SPECIAL>
    /* 73EC 80140FE4 00000600 */  sll        $zero, $a2, 0
    /* 73F0 80140FE8 00090000 */  sll        $at, $zero, 4
    /* 73F4 80140FEC 00000000 */  nop
    /* 73F8 80140FF0 00000001 */  .word      0x01000000                    # sll        $zero, $zero, 0 # 01000000 <InstrIdType: CPU_SPECIAL>
    /* 73FC 80140FF4 01020201 */  .word      0x01020201                    # INVALID    $t0, $v0, 0x201 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 7400 80140FF8 01010101 */  .word      0x01010101                    # INVALID    $t0, $at, 0x101 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 7404 80140FFC 01020202 */  .word      0x02020201                    # INVALID    $s0, $v0, 0x201 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 7408 80141000 02020000 */  srl        $zero, $zero, 8
    /* 740C 80141004 00000006 */  bltz       $s0, .L80141008
  .L80141008:
    /* 7410 80141008 06060900 */   .word     0x00090606                     # srlv      $zero, $t1, $zero # 00000600 <InstrIdType: CPU_SPECIAL>
    /* 7414 8014100C 00000000 */  nop
    /* 7418 80141010 00000000 */  nop
    /* 741C 80141014 00000000 */  nop
    /* 7420 80141018 00000000 */  nop
    /* 7424 8014101C 00000000 */  nop
    /* 7428 80141020 00000000 */  nop
    /* 742C 80141024 01010100 */  .word      0x00010101                    # INVALID    $zero, $at, 0x101 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 7430 80141028 00020202 */  .word      0x02020200                    # sll        $zero, $v0, 8 # 02000000 <InstrIdType: CPU_SPECIAL>
    /* 7434 8014102C 00000001 */  .word      0x01000000                    # sll        $zero, $zero, 0 # 01000000 <InstrIdType: CPU_SPECIAL>
    /* 7438 80141030 01010106 */  bgez       $s0, .L80141438
    /* 743C 80141034 02020200 */   srl       $zero, $v0, 8
    /* 7440 80141038 03030303 */  .word      0x03030303                    # sra        $zero, $v1, 12 # 03000000 <InstrIdType: CPU_SPECIAL>
    /* 7444 8014103C 00000000 */  nop
    /* 7448 80141040 00000000 */  nop
    /* 744C 80141044 00000000 */  nop
    /* 7450 80141048 03030303 */  .word      0x03030303                    # sra        $zero, $v1, 12 # 03000000 <InstrIdType: CPU_SPECIAL>
    /* 7454 8014104C 03030303 */  .word      0x03030303                    # sra        $zero, $v1, 12 # 03000000 <InstrIdType: CPU_SPECIAL>
    /* 7458 80141050 03030303 */  .word      0x03030303                    # sra        $zero, $v1, 12 # 03000000 <InstrIdType: CPU_SPECIAL>
    /* 745C 80141054 01010202 */  .word      0x02020101                    # INVALID    $s0, $v0, 0x101 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 7460 80141058 03030303 */  .word      0x03030303                    # sra        $zero, $v1, 12 # 03000000 <InstrIdType: CPU_SPECIAL>
    /* 7464 8014105C 01010202 */  .word      0x02020101                    # INVALID    $s0, $v0, 0x101 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 7468 80141060 03030303 */  .word      0x03030303                    # sra        $zero, $v1, 12 # 03000000 <InstrIdType: CPU_SPECIAL>
    /* 746C 80141064 01010303 */  .word      0x03030101                    # INVALID    $t8, $v1, 0x101 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 7470 80141068 02020303 */  .word      0x03030202                    # srl        $zero, $v1, 8 # 03000000 <InstrIdType: CPU_SPECIAL>
    /* 7474 8014106C 00000000 */  nop
    /* 7478 80141070 00000000 */  nop
    /* 747C 80141074 00000000 */  nop
    /* 7480 80141078 00000000 */  nop
    /* 7484 8014107C 00000000 */  nop
    /* 7488 80141080 00000000 */  nop
