.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.42.4 */

nonmatching BIG9, 0xA

glabel BIG9
    /* 7ABC 801416B4 02020103 */  .word      0x03010202                    # srl        $zero, $at, 8 # 03000000 <InstrIdType: CPU_SPECIAL>
    /* 7AC0 801416B8 01038587 */  lh         $a1, %gp_rel(D_8011AA81)($gp)
    /* 7AC4 801416BC 84860000 */  .word      0x00008684                    # sllv       $s0, $zero, $zero # 00000680 <InstrIdType: CPU_SPECIAL>
