.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.42.4 */

nonmatching VARCH29, 0x12

glabel VARCH29
    /* 769C 80141294 02040300 */  srl        $zero, $v1, 16
    /* 76A0 80141298 03040301 */  .word      0x01030403                    # sra        $zero, $v1, 16 # 01000000 <InstrIdType: CPU_SPECIAL>
    /* 76A4 8014129C 000E3000 */  .word      0x00300E00                    # sll        $at, $s0, 24 # 00200000 <InstrIdType: CPU_SPECIAL>
    /* 76A8 801412A0 33272F2C */  sltiu      $t7, $at, 0x2733
    /* 76AC 801412A4 00000000 */  nop
