.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.42.4 */

nonmatching HARCH1, 0xE

glabel HARCH1
    /* 778C 80141384 03020303 */  .word      0x03030203                    # sra        $zero, $v1, 8 # 03000000 <InstrIdType: CPU_SPECIAL>
    /* 7790 80141388 00020509 */  j          func_84140800
    /* 7794 8014138C 312E0028 */   slti      $zero, $zero, 0x2E31
    /* 7798 80141390 2D000000 */  daddu      $zero, $zero, $zero
