.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.42.4 */

nonmatching VARCH32, 0x12

glabel VARCH32
    /* 76D8 801412D0 02040300 */  srl        $zero, $v1, 16
    /* 76DC 801412D4 03040301 */  .word      0x01030403                    # sra        $zero, $v1, 16 # 01000000 <InstrIdType: CPU_SPECIAL>
    /* 76E0 801412D8 000F3000 */  .word      0x00300F00                    # sll        $at, $s0, 28 # 00200000 <InstrIdType: CPU_SPECIAL>
    /* 76E4 801412DC 33272F2C */  sltiu      $t7, $at, 0x2733
    /* 76E8 801412E0 00000000 */  nop
