.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.42.4 */

nonmatching VARCH2, 0x12

glabel VARCH2
    /* 74A0 80141098 02040300 */  srl        $zero, $v1, 16
    /* 74A4 8014109C 03010304 */  bgezl      $zero, .L801414AC
    /* 74A8 801410A0 00083000 */   .word     0x00300800                     # sll       $at, $s0, 0 # 00200000 <InstrIdType: CPU_SPECIAL>
    /* 74AC 801410A4 33272F2C */  sltiu      $t7, $at, 0x2733
    /* 74B0 801410A8 00000000 */  nop
