.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.42.4 */

nonmatching L3TITE8, 0x14

glabel L3TITE8
    /* EBD0 801487C8 03030707 */  .word      0x07070303                    # INVALID    $t8, $a3, 0x303 # 00000000 <InstrIdType: CPU_REGIMM>
    /* EBD4 801487CC 07070707 */  .word      0x07070707                    # INVALID    $t8, $a3, 0x707 # 00000000 <InstrIdType: CPU_REGIMM>
    /* EBD8 801487D0 07070700 */  .word      0x00070707                    # srav       $zero, $a3, $zero # 00000700 <InstrIdType: CPU_SPECIAL>
    /* EBDC 801487D4 00000034 */  ori        $zero, $zero, 0x0
    /* EBE0 801487D8 00000000 */  nop
endlabel L3TITE8

nonmatching L3TITE9, 0x14

glabel L3TITE9
    /* EBE4 801487DC 03030707 */  .word      0x07070303                    # INVALID    $t8, $a3, 0x303 # 00000000 <InstrIdType: CPU_REGIMM>
    /* EBE8 801487E0 07070707 */  .word      0x07070707                    # INVALID    $t8, $a3, 0x707 # 00000000 <InstrIdType: CPU_REGIMM>
    /* EBEC 801487E4 07070700 */  .word      0x00070707                    # srav       $zero, $a3, $zero # 00000700 <InstrIdType: CPU_SPECIAL>
    /* EBF0 801487E8 00000035 */  ori        $zero, $t0, 0x0
    /* EBF4 801487EC 00000000 */  nop
endlabel L3TITE9

nonmatching L3TITE10, 0x14

glabel L3TITE10
    /* EBF8 801487F0 03030707 */  .word      0x07070303                    # INVALID    $t8, $a3, 0x303 # 00000000 <InstrIdType: CPU_REGIMM>
    /* EBFC 801487F4 07070707 */  .word      0x07070707                    # INVALID    $t8, $a3, 0x707 # 00000000 <InstrIdType: CPU_REGIMM>
    /* EC00 801487F8 07070700 */  .word      0x00070707                    # srav       $zero, $a3, $zero # 00000700 <InstrIdType: CPU_SPECIAL>
    /* EC04 801487FC 00000036 */  ori        $zero, $s0, 0x0
    /* EC08 80148800 00000000 */  nop
endlabel L3TITE10

/* Handwritten function */
nonmatching L3TITE11, 0x14

glabel L3TITE11
    /* EC0C 80148804 03030707 */  .word      0x07070303                    # INVALID    $t8, $a3, 0x303 # 00000000 <InstrIdType: CPU_REGIMM>
    /* EC10 80148808 07070707 */  .word      0x07070707                    # INVALID    $t8, $a3, 0x707 # 00000000 <InstrIdType: CPU_REGIMM>
    /* EC14 8014880C 07070700 */  .word      0x00070707                    # srav       $zero, $a3, $zero # 00000700 <InstrIdType: CPU_SPECIAL>
    /* EC18 80148810 00000043 */  .word      0x43000000                    # INVALID    $t8, $zero, 0x0 # 00000000 <InstrIdType: CPU_COP0> /* handwritten instruction */
    /* EC1C 80148814 00000000 */  nop
endlabel L3TITE11

nonmatching L3ISLE1, 0xE

glabel L3ISLE1
    /* EC20 80148818 0203050E */  jal        func_88140C08
    /* EC24 8014881C 04090D0C */   jal       func_80342410
    /* EC28 80148820 07070707 */   .word     0x07070707                     # INVALID   $t8, $a3, 0x707 # 00000000 <InstrIdType: CPU_REGIMM>
    /* EC2C 80148824 07070000 */  .word      0x00000707                    # srav       $zero, $zero, $zero # 00000700 <InstrIdType: CPU_SPECIAL>
