.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.42.4 */

nonmatching VARCH25, 0x12

glabel VARCH25
    /* 764C 80141244 02040300 */  srl        $zero, $v1, 16
    /* 7650 80141248 03040301 */  .word      0x01030403                    # sra        $zero, $v1, 16 # 01000000 <InstrIdType: CPU_SPECIAL>
    /* 7654 8014124C 00073000 */  .word      0x00300700                    # sll        $zero, $s0, 28 # 00200000 <InstrIdType: CPU_SPECIAL>
    /* 7658 80141250 33272F2C */  sltiu      $t7, $at, 0x2733
    /* 765C 80141254 00000000 */  nop
