.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.42.4 */

nonmatching HARCH16, 0xE

glabel HARCH16
    /* 787C 80141474 03020303 */  .word      0x03030203                    # sra        $zero, $v1, 8 # 03000000 <InstrIdType: CPU_SPECIAL>
    /* 7880 80141478 0008050E */  jal        func_88142000
    /* 7884 8014147C 312E002B */   slti      $zero, $t8, 0x2E31
    /* 7888 80141480 2D000000 */  daddu      $zero, $zero, $zero
