.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.42.4 */

nonmatching L3ISLE4, 0xE

glabel L3ISLE4
    /* EC50 80148848 03020502 */  .word      0x02050203                    # sra        $zero, $a1, 8 # 02000000 <InstrIdType: CPU_SPECIAL>
    /* EC54 8014884C 0E0D0A0C */  jal        func_80283438
    /* EC58 80148850 1D1A1E1F */   .word     0x1F1E1A1D                     # bgtz      $t8, .L8014F0C8 # 001E0000 <InstrIdType: CPU_NORMAL>
    /* EC5C 80148854 1B200000 */   divu      $a0, $zero, $zero
