.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.42.4 */

nonmatching HARCH29, 0xE

glabel HARCH29
    /* 794C 80141544 03020303 */  .word      0x03030203                    # sra        $zero, $v1, 8 # 03000000 <InstrIdType: CPU_SPECIAL>
    /* 7950 80141548 0005020F */  jal        func_8C081400
    /* 7954 8014154C 312E0028 */   slti      $zero, $zero, 0x2E31
    /* 7958 80141550 2D000000 */  daddu      $zero, $zero, $zero
