.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.42.4 */

nonmatching PANCREAS1, 0x20

glabel PANCREAS1
    /* 7AD4 801416CC 05030303 */  .word      0x03030305                    # INVALID    $t8, $v1, 0x305 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 7AD8 801416D0 03030303 */  .word      0x03030303                    # sra        $zero, $v1, 12 # 03000000 <InstrIdType: CPU_SPECIAL>
    /* 7ADC 801416D4 03030303 */  .word      0x03030303                    # sra        $zero, $v1, 12 # 03000000 <InstrIdType: CPU_SPECIAL>
    /* 7AE0 801416D8 03030303 */  .word      0x03030303                    # sra        $zero, $v1, 12 # 03000000 <InstrIdType: CPU_SPECIAL>
    /* 7AE4 801416DC 03000000 */  sra        $zero, $zero, 0
    /* 7AE8 801416E0 00000000 */  nop
    /* 7AEC 801416E4 6C000000 */  .word      0x0000006C                    # dadd       $zero, $zero, $zero # 00000040 <InstrIdType: CPU_SPECIAL>
    /* 7AF0 801416E8 00000000 */  nop
endlabel PANCREAS1

nonmatching PANCREAS2, 0x20

glabel PANCREAS2
    /* 7AF4 801416EC 05030303 */  .word      0x03030305                    # INVALID    $t8, $v1, 0x305 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 7AF8 801416F0 03030303 */  .word      0x03030303                    # sra        $zero, $v1, 12 # 03000000 <InstrIdType: CPU_SPECIAL>
    /* 7AFC 801416F4 03030303 */  .word      0x03030303                    # sra        $zero, $v1, 12 # 03000000 <InstrIdType: CPU_SPECIAL>
    /* 7B00 801416F8 03030303 */  .word      0x03030303                    # sra        $zero, $v1, 12 # 03000000 <InstrIdType: CPU_SPECIAL>
    /* 7B04 801416FC 03000000 */  sra        $zero, $zero, 0
    /* 7B08 80141700 00000000 */  nop
    /* 7B0C 80141704 6E000000 */  .word      0x0000006E                    # dsub       $zero, $zero, $zero # 00000040 <InstrIdType: CPU_SPECIAL>
    /* 7B10 80141708 00000000 */  nop
endlabel PANCREAS2

nonmatching CTRDOOR1, 0x14

glabel CTRDOOR1
    /* 7B14 8014170C 03030301 */  .word      0x01030303                    # sra        $zero, $v1, 12 # 01000000 <InstrIdType: CPU_SPECIAL>
    /* 7B18 80141710 03000400 */  sra        $zero, $a0, 0
    /* 7B1C 80141714 00090000 */  sll        $at, $zero, 4
    /* 7B20 80141718 04000001 */  sllv       $zero, $zero, $t0
    /* 7B24 8014171C 00000000 */  nop
endlabel CTRDOOR1

nonmatching CTRDOOR2, 0x14

glabel CTRDOOR2
    /* 7B28 80141720 03030301 */  .word      0x01030303                    # sra        $zero, $v1, 12 # 01000000 <InstrIdType: CPU_SPECIAL>
    /* 7B2C 80141724 03000400 */  sra        $zero, $a0, 0
    /* 7B30 80141728 00080000 */  sll        $at, $zero, 0
    /* 7B34 8014172C 04000001 */  sllv       $zero, $zero, $t0
    /* 7B38 80141730 00000000 */  nop
endlabel CTRDOOR2

nonmatching CTRDOOR3, 0x14

glabel CTRDOOR3
    /* 7B3C 80141734 03030301 */  .word      0x01030303                    # sra        $zero, $v1, 12 # 01000000 <InstrIdType: CPU_SPECIAL>
    /* 7B40 80141738 03000400 */  sra        $zero, $a0, 0
    /* 7B44 8014173C 00060000 */  sll        $zero, $zero, 24
    /* 7B48 80141740 04000001 */  sllv       $zero, $zero, $t0
    /* 7B4C 80141744 00000000 */  nop
endlabel CTRDOOR3

nonmatching CTRDOOR4, 0x14

glabel CTRDOOR4
    /* 7B50 80141748 03030301 */  .word      0x01030303                    # sra        $zero, $v1, 12 # 01000000 <InstrIdType: CPU_SPECIAL>
    /* 7B54 8014174C 03000400 */  sra        $zero, $a0, 0
    /* 7B58 80141750 00070000 */  sll        $zero, $zero, 28
    /* 7B5C 80141754 04000001 */  sllv       $zero, $zero, $t0
    /* 7B60 80141758 00000000 */  nop
endlabel CTRDOOR4

nonmatching CTRDOOR5, 0x14

glabel CTRDOOR5
    /* 7B64 8014175C 03030301 */  .word      0x01030303                    # sra        $zero, $v1, 12 # 01000000 <InstrIdType: CPU_SPECIAL>
    /* 7B68 80141760 03000400 */  sra        $zero, $a0, 0
    /* 7B6C 80141764 000F0000 */  sll        $at, $zero, 28
    /* 7B70 80141768 04000001 */  sllv       $zero, $zero, $t0
    /* 7B74 8014176C 00000000 */  nop
endlabel CTRDOOR5

nonmatching CTRDOOR6, 0x14

glabel CTRDOOR6
    /* 7B78 80141770 03030301 */  .word      0x01030303                    # sra        $zero, $v1, 12 # 01000000 <InstrIdType: CPU_SPECIAL>
    /* 7B7C 80141774 03000400 */  sra        $zero, $a0, 0
    /* 7B80 80141778 000D0000 */  sll        $at, $zero, 20
    /* 7B84 8014177C 04000001 */  sllv       $zero, $zero, $t0
    /* 7B88 80141780 00000000 */  nop
endlabel CTRDOOR6

nonmatching CTRDOOR7, 0x14

glabel CTRDOOR7
    /* 7B8C 80141784 03030301 */  .word      0x01030303                    # sra        $zero, $v1, 12 # 01000000 <InstrIdType: CPU_SPECIAL>
    /* 7B90 80141788 03000400 */  sra        $zero, $a0, 0
    /* 7B94 8014178C 00100000 */  sll        $v0, $zero, 0
    /* 7B98 80141790 04000001 */  sllv       $zero, $zero, $t0
    /* 7B9C 80141794 00000000 */  nop
endlabel CTRDOOR7

nonmatching CTRDOOR8, 0x14

glabel CTRDOOR8
    /* 7BA0 80141798 03030301 */  .word      0x01030303                    # sra        $zero, $v1, 12 # 01000000 <InstrIdType: CPU_SPECIAL>
    /* 7BA4 8014179C 03000400 */  sra        $zero, $a0, 0
    /* 7BA8 801417A0 000E0000 */  sll        $at, $zero, 24
    /* 7BAC 801417A4 04000001 */  sllv       $zero, $zero, $t0
    /* 7BB0 801417A8 00000000 */  nop
endlabel CTRDOOR8

/* Handwritten function */
nonmatching Patterns, 0xFA0

glabel Patterns
    /* 7BB4 801417AC 00000000 */  nop
    /* 7BB8 801417B0 00000000 */  nop
    /* 7BBC 801417B4 00000000 */  nop
    /* 7BC0 801417B8 00000000 */  nop
    /* 7BC4 801417BC 00000000 */  nop
    /* 7BC8 801417C0 00000000 */  nop
    /* 7BCC 801417C4 00000000 */  nop
    /* 7BD0 801417C8 00000000 */  nop
    /* 7BD4 801417CC 00000000 */  nop
    /* 7BD8 801417D0 03000000 */  sra        $zero, $zero, 0
    /* 7BDC 801417D4 00000000 */  nop
    /* 7BE0 801417D8 00000000 */  nop
    /* 7BE4 801417DC 00000000 */  nop
    /* 7BE8 801417E0 00000000 */  nop
    /* 7BEC 801417E4 02000000 */  srl        $zero, $zero, 0
    /* 7BF0 801417E8 00000000 */  nop
    /* 7BF4 801417EC 00000000 */  nop
    /* 7BF8 801417F0 00000000 */  nop
    /* 7BFC 801417F4 00000000 */  nop
    /* 7C00 801417F8 03000000 */  sra        $zero, $zero, 0
    /* 7C04 801417FC 00000000 */  nop
    /* 7C08 80141800 07000000 */  srav       $zero, $zero, $zero
    /* 7C0C 80141804 00000000 */  nop
    /* 7C10 80141808 00000000 */  nop
    /* 7C14 8014180C 01000000 */  .word      0x00000001                    # INVALID    $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 7C18 80141810 00000000 */  nop
    /* 7C1C 80141814 00000000 */  nop
    /* 7C20 80141818 05000000 */  .word      0x00000005                    # INVALID    $zero, $zero, 0x5 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 7C24 8014181C 00000000 */  nop
    /* 7C28 80141820 02000000 */  srl        $zero, $zero, 0
    /* 7C2C 80141824 00000000 */  nop
    /* 7C30 80141828 05000000 */  .word      0x00000005                    # INVALID    $zero, $zero, 0x5 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 7C34 8014182C 00000000 */  nop
    /* 7C38 80141830 00000000 */  nop
    /* 7C3C 80141834 01000000 */  .word      0x00000001                    # INVALID    $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 7C40 80141838 00000000 */  nop
    /* 7C44 8014183C 00000000 */  nop
    /* 7C48 80141840 07000000 */  srav       $zero, $zero, $zero
    /* 7C4C 80141844 00000000 */  nop
    /* 7C50 80141848 02000000 */  srl        $zero, $zero, 0
    /* 7C54 8014184C 00000000 */  nop
    /* 7C58 80141850 00000000 */  nop
    /* 7C5C 80141854 00000000 */  nop
    /* 7C60 80141858 07000000 */  srav       $zero, $zero, $zero
    /* 7C64 8014185C 01000000 */  .word      0x00000001                    # INVALID    $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 7C68 80141860 05000000 */  .word      0x00000005                    # INVALID    $zero, $zero, 0x5 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 7C6C 80141864 00000000 */  nop
    /* 7C70 80141868 00000000 */  nop
    /* 7C74 8014186C 00000000 */  nop
    /* 7C78 80141870 01000000 */  .word      0x00000001                    # INVALID    $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 7C7C 80141874 00000000 */  nop
    /* 7C80 80141878 00000000 */  nop
    /* 7C84 8014187C 00000000 */  nop
    /* 7C88 80141880 05000000 */  .word      0x00000005                    # INVALID    $zero, $zero, 0x5 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 7C8C 80141884 01000000 */  .word      0x00000001                    # INVALID    $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 7C90 80141888 07000000 */  srav       $zero, $zero, $zero
    /* 7C94 8014188C 00000000 */  nop
    /* 7C98 80141890 00000000 */  nop
    /* 7C9C 80141894 00000000 */  nop
    /* 7CA0 80141898 01000000 */  .word      0x00000001                    # INVALID    $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 7CA4 8014189C 00000000 */  nop
    /* 7CA8 801418A0 01000000 */  .word      0x00000001                    # INVALID    $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 7CAC 801418A4 00000000 */  nop
    /* 7CB0 801418A8 00000000 */  nop
    /* 7CB4 801418AC 03000000 */  sra        $zero, $zero, 0
    /* 7CB8 801418B0 00000000 */  nop
    /* 7CBC 801418B4 00000000 */  nop
    /* 7CC0 801418B8 01000000 */  .word      0x00000001                    # INVALID    $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 7CC4 801418BC 00000000 */  nop
    /* 7CC8 801418C0 04000000 */  sllv       $zero, $zero, $zero
    /* 7CCC 801418C4 00000000 */  nop
    /* 7CD0 801418C8 00000000 */  nop
    /* 7CD4 801418CC 00000000 */  nop
    /* 7CD8 801418D0 01000000 */  .word      0x00000001                    # INVALID    $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 7CDC 801418D4 03000000 */  sra        $zero, $zero, 0
    /* 7CE0 801418D8 01000000 */  .word      0x00000001                    # INVALID    $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 7CE4 801418DC 00000000 */  nop
    /* 7CE8 801418E0 00000000 */  nop
    /* 7CEC 801418E4 00000000 */  nop
    /* 7CF0 801418E8 05000000 */  .word      0x00000005                    # INVALID    $zero, $zero, 0x5 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 7CF4 801418EC 00000000 */  nop
    /* 7CF8 801418F0 06000000 */  srlv       $zero, $zero, $zero
    /* 7CFC 801418F4 00000000 */  nop
    /* 7D00 801418F8 06000000 */  srlv       $zero, $zero, $zero
    /* 7D04 801418FC 01000000 */  .word      0x00000001                    # INVALID    $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 7D08 80141900 00000000 */  nop
    /* 7D0C 80141904 00000000 */  nop
    /* 7D10 80141908 00000000 */  nop
    /* 7D14 8014190C 00000000 */  nop
    /* 7D18 80141910 06000000 */  srlv       $zero, $zero, $zero
    /* 7D1C 80141914 00000000 */  nop
    /* 7D20 80141918 06000000 */  srlv       $zero, $zero, $zero
    /* 7D24 8014191C 00000000 */  nop
    /* 7D28 80141920 00000000 */  nop
    /* 7D2C 80141924 01000000 */  .word      0x00000001                    # INVALID    $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 7D30 80141928 06000000 */  srlv       $zero, $zero, $zero
    /* 7D34 8014192C 00000000 */  nop
    /* 7D38 80141930 00000000 */  nop
    /* 7D3C 80141934 00000000 */  nop
    /* 7D40 80141938 09000000 */  jalr       $zero, $zero
    /* 7D44 8014193C 00000000 */   nop
    /* 7D48 80141940 00000000 */  nop
    /* 7D4C 80141944 00000000 */  nop
    /* 7D50 80141948 06000000 */  srlv       $zero, $zero, $zero
    /* 7D54 8014194C 01000000 */  .word      0x00000001                    # INVALID    $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 7D58 80141950 00000000 */  nop
    /* 7D5C 80141954 00000000 */  nop
    /* 7D60 80141958 06000000 */  srlv       $zero, $zero, $zero
    /* 7D64 8014195C 00000000 */  nop
    /* 7D68 80141960 07000000 */  srav       $zero, $zero, $zero
    /* 7D6C 80141964 00000000 */  nop
    /* 7D70 80141968 00000000 */  nop
    /* 7D74 8014196C 00000000 */  nop
    /* 7D78 80141970 00000000 */  nop
    /* 7D7C 80141974 01000000 */  .word      0x00000001                    # INVALID    $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 7D80 80141978 06000000 */  srlv       $zero, $zero, $zero
    /* 7D84 8014197C 00000000 */  nop
    /* 7D88 80141980 06000000 */  srlv       $zero, $zero, $zero
    /* 7D8C 80141984 00000000 */  nop
    /* 7D90 80141988 08000000 */  jr         $zero
    /* 7D94 8014198C 00000000 */   nop
    /* 7D98 80141990 06000000 */  srlv       $zero, $zero, $zero
    /* 7D9C 80141994 00000000 */  nop
    /* 7DA0 80141998 06000000 */  srlv       $zero, $zero, $zero
    /* 7DA4 8014199C 06000000 */  srlv       $zero, $zero, $zero
    /* 7DA8 801419A0 00000000 */  nop
    /* 7DAC 801419A4 08000000 */  jr         $zero
    /* 7DB0 801419A8 06000000 */   srlv      $zero, $zero, $zero
    /* 7DB4 801419AC 00000000 */  nop
    /* 7DB8 801419B0 07000000 */  srav       $zero, $zero, $zero
    /* 7DBC 801419B4 00000000 */  nop
    /* 7DC0 801419B8 06000000 */  srlv       $zero, $zero, $zero
    /* 7DC4 801419BC 08000000 */  jr         $zero
    /* 7DC8 801419C0 06000000 */   srlv      $zero, $zero, $zero
    /* 7DCC 801419C4 06000000 */  srlv       $zero, $zero, $zero
    /* 7DD0 801419C8 06000000 */  srlv       $zero, $zero, $zero
    /* 7DD4 801419CC 00000000 */  nop
    /* 7DD8 801419D0 00000000 */  nop
    /* 7DDC 801419D4 00000000 */  nop
    /* 7DE0 801419D8 09000000 */  jalr       $zero, $zero
    /* 7DE4 801419DC 00000000 */   nop
    /* 7DE8 801419E0 06000000 */  srlv       $zero, $zero, $zero
    /* 7DEC 801419E4 00000000 */  nop
    /* 7DF0 801419E8 00000000 */  nop
    /* 7DF4 801419EC 06000000 */  srlv       $zero, $zero, $zero
    /* 7DF8 801419F0 06000000 */  srlv       $zero, $zero, $zero
    /* 7DFC 801419F4 00000000 */  nop
    /* 7E00 801419F8 06000000 */  srlv       $zero, $zero, $zero
    /* 7E04 801419FC 08000000 */  jr         $zero
    /* 7E08 80141A00 08000000 */   jr        $zero
    /* 7E0C 80141A04 06000000 */   srlv      $zero, $zero, $zero
    /* 7E10 80141A08 06000000 */  srlv       $zero, $zero, $zero
    /* 7E14 80141A0C 06000000 */  srlv       $zero, $zero, $zero
    /* 7E18 80141A10 06000000 */  srlv       $zero, $zero, $zero
    /* 7E1C 80141A14 06000000 */  srlv       $zero, $zero, $zero
    /* 7E20 80141A18 06000000 */  srlv       $zero, $zero, $zero
    /* 7E24 80141A1C 00000000 */  nop
    /* 7E28 80141A20 06000000 */  srlv       $zero, $zero, $zero
    /* 7E2C 80141A24 00000000 */  nop
    /* 7E30 80141A28 08000000 */  jr         $zero
    /* 7E34 80141A2C 02000000 */   srl       $zero, $zero, 0
    /* 7E38 80141A30 06000000 */  srlv       $zero, $zero, $zero
    /* 7E3C 80141A34 06000000 */  srlv       $zero, $zero, $zero
    /* 7E40 80141A38 06000000 */  srlv       $zero, $zero, $zero
    /* 7E44 80141A3C 06000000 */  srlv       $zero, $zero, $zero
    /* 7E48 80141A40 06000000 */  srlv       $zero, $zero, $zero
    /* 7E4C 80141A44 00000000 */  nop
    /* 7E50 80141A48 06000000 */  srlv       $zero, $zero, $zero
    /* 7E54 80141A4C 00000000 */  nop
    /* 7E58 80141A50 08000000 */  jr         $zero
    /* 7E5C 80141A54 07000000 */   srav      $zero, $zero, $zero
    /* 7E60 80141A58 07000000 */  srav       $zero, $zero, $zero
    /* 7E64 80141A5C 07000000 */  srav       $zero, $zero, $zero
    /* 7E68 80141A60 06000000 */  srlv       $zero, $zero, $zero
    /* 7E6C 80141A64 06000000 */  srlv       $zero, $zero, $zero
    /* 7E70 80141A68 06000000 */  srlv       $zero, $zero, $zero
    /* 7E74 80141A6C 00000000 */  nop
    /* 7E78 80141A70 06000000 */  srlv       $zero, $zero, $zero
    /* 7E7C 80141A74 00000000 */  nop
    /* 7E80 80141A78 08000000 */  jr         $zero
    /* 7E84 80141A7C 06000000 */   srlv      $zero, $zero, $zero
    /* 7E88 80141A80 06000000 */  srlv       $zero, $zero, $zero
    /* 7E8C 80141A84 02000000 */  srl        $zero, $zero, 0
    /* 7E90 80141A88 06000000 */  srlv       $zero, $zero, $zero
    /* 7E94 80141A8C 06000000 */  srlv       $zero, $zero, $zero
    /* 7E98 80141A90 06000000 */  srlv       $zero, $zero, $zero
    /* 7E9C 80141A94 00000000 */  nop
    /* 7EA0 80141A98 06000000 */  srlv       $zero, $zero, $zero
    /* 7EA4 80141A9C 00000000 */  nop
    /* 7EA8 80141AA0 08000000 */  jr         $zero
    /* 7EAC 80141AA4 06000000 */   srlv      $zero, $zero, $zero
    /* 7EB0 80141AA8 02000000 */  srl        $zero, $zero, 0
    /* 7EB4 80141AAC 06000000 */  srlv       $zero, $zero, $zero
    /* 7EB8 80141AB0 06000000 */  srlv       $zero, $zero, $zero
    /* 7EBC 80141AB4 06000000 */  srlv       $zero, $zero, $zero
    /* 7EC0 80141AB8 06000000 */  srlv       $zero, $zero, $zero
    /* 7EC4 80141ABC 00000000 */  nop
    /* 7EC8 80141AC0 06000000 */  srlv       $zero, $zero, $zero
    /* 7ECC 80141AC4 00000000 */  nop
    /* 7ED0 80141AC8 08000000 */  jr         $zero
    /* 7ED4 80141ACC 02000000 */   srl       $zero, $zero, 0
    /* 7ED8 80141AD0 06000000 */  srlv       $zero, $zero, $zero
    /* 7EDC 80141AD4 06000000 */  srlv       $zero, $zero, $zero
    /* 7EE0 80141AD8 06000000 */  srlv       $zero, $zero, $zero
    /* 7EE4 80141ADC 06000000 */  srlv       $zero, $zero, $zero
    /* 7EE8 80141AE0 06000000 */  srlv       $zero, $zero, $zero
    /* 7EEC 80141AE4 00000000 */  nop
    /* 7EF0 80141AE8 06000000 */  srlv       $zero, $zero, $zero
    /* 7EF4 80141AEC 00000000 */  nop
    /* 7EF8 80141AF0 08000000 */  jr         $zero
    /* 7EFC 80141AF4 06000000 */   srlv      $zero, $zero, $zero
    /* 7F00 80141AF8 07000000 */  srav       $zero, $zero, $zero
    /* 7F04 80141AFC 07000000 */  srav       $zero, $zero, $zero
    /* 7F08 80141B00 06000000 */  srlv       $zero, $zero, $zero
    /* 7F0C 80141B04 06000000 */  srlv       $zero, $zero, $zero
    /* 7F10 80141B08 06000000 */  srlv       $zero, $zero, $zero
    /* 7F14 80141B0C 00000000 */  nop
    /* 7F18 80141B10 06000000 */  srlv       $zero, $zero, $zero
    /* 7F1C 80141B14 00000000 */  nop
    /* 7F20 80141B18 08000000 */  jr         $zero
    /* 7F24 80141B1C 04000000 */   sllv      $zero, $zero, $zero
    /* 7F28 80141B20 04000000 */  sllv       $zero, $zero, $zero
    /* 7F2C 80141B24 06000000 */  srlv       $zero, $zero, $zero
    /* 7F30 80141B28 06000000 */  srlv       $zero, $zero, $zero
    /* 7F34 80141B2C 06000000 */  srlv       $zero, $zero, $zero
    /* 7F38 80141B30 06000000 */  srlv       $zero, $zero, $zero
    /* 7F3C 80141B34 02000000 */  srl        $zero, $zero, 0
    /* 7F40 80141B38 06000000 */  srlv       $zero, $zero, $zero
    /* 7F44 80141B3C 02000000 */  srl        $zero, $zero, 0
    /* 7F48 80141B40 08000000 */  jr         $zero
    /* 7F4C 80141B44 02000000 */   srl       $zero, $zero, 0
    /* 7F50 80141B48 02000000 */  srl        $zero, $zero, 0
    /* 7F54 80141B4C 02000000 */  srl        $zero, $zero, 0
    /* 7F58 80141B50 02000000 */  srl        $zero, $zero, 0
    /* 7F5C 80141B54 06000000 */  srlv       $zero, $zero, $zero
    /* 7F60 80141B58 02000000 */  srl        $zero, $zero, 0
    /* 7F64 80141B5C 02000000 */  srl        $zero, $zero, 0
    /* 7F68 80141B60 06000000 */  srlv       $zero, $zero, $zero
    /* 7F6C 80141B64 02000000 */  srl        $zero, $zero, 0
    /* 7F70 80141B68 07000000 */  srav       $zero, $zero, $zero
    /* 7F74 80141B6C 02000000 */  srl        $zero, $zero, 0
    /* 7F78 80141B70 02000000 */  srl        $zero, $zero, 0
    /* 7F7C 80141B74 02000000 */  srl        $zero, $zero, 0
    /* 7F80 80141B78 02000000 */  srl        $zero, $zero, 0
    /* 7F84 80141B7C 06000000 */  srlv       $zero, $zero, $zero
    /* 7F88 80141B80 02000000 */  srl        $zero, $zero, 0
    /* 7F8C 80141B84 06000000 */  srlv       $zero, $zero, $zero
    /* 7F90 80141B88 06000000 */  srlv       $zero, $zero, $zero
    /* 7F94 80141B8C 06000000 */  srlv       $zero, $zero, $zero
    /* 7F98 80141B90 07000000 */  srav       $zero, $zero, $zero
    /* 7F9C 80141B94 02000000 */  srl        $zero, $zero, 0
    /* 7FA0 80141B98 02000000 */  srl        $zero, $zero, 0
    /* 7FA4 80141B9C 06000000 */  srlv       $zero, $zero, $zero
    /* 7FA8 80141BA0 02000000 */  srl        $zero, $zero, 0
    /* 7FAC 80141BA4 06000000 */  srlv       $zero, $zero, $zero
    /* 7FB0 80141BA8 06000000 */  srlv       $zero, $zero, $zero
    /* 7FB4 80141BAC 02000000 */  srl        $zero, $zero, 0
    /* 7FB8 80141BB0 02000000 */  srl        $zero, $zero, 0
    /* 7FBC 80141BB4 06000000 */  srlv       $zero, $zero, $zero
    /* 7FC0 80141BB8 09000000 */  jalr       $zero, $zero
    /* 7FC4 80141BBC 02000000 */   srl       $zero, $zero, 0
    /* 7FC8 80141BC0 06000000 */  srlv       $zero, $zero, $zero
    /* 7FCC 80141BC4 02000000 */  srl        $zero, $zero, 0
    /* 7FD0 80141BC8 02000000 */  srl        $zero, $zero, 0
    /* 7FD4 80141BCC 06000000 */  srlv       $zero, $zero, $zero
    /* 7FD8 80141BD0 02000000 */  srl        $zero, $zero, 0
    /* 7FDC 80141BD4 02000000 */  srl        $zero, $zero, 0
    /* 7FE0 80141BD8 02000000 */  srl        $zero, $zero, 0
  .L80141BDC:
    /* 7FE4 80141BDC 02000000 */  srl        $zero, $zero, 0
    /* 7FE8 80141BE0 06000000 */  srlv       $zero, $zero, $zero
    /* 7FEC 80141BE4 02000000 */  srl        $zero, $zero, 0
    /* 7FF0 80141BE8 02000000 */  srl        $zero, $zero, 0
    /* 7FF4 80141BEC 02000000 */  srl        $zero, $zero, 0
    /* 7FF8 80141BF0 02000000 */  srl        $zero, $zero, 0
    /* 7FFC 80141BF4 06000000 */  srlv       $zero, $zero, $zero
    /* 8000 80141BF8 06000000 */  srlv       $zero, $zero, $zero
    /* 8004 80141BFC 02000000 */  srl        $zero, $zero, 0
    /* 8008 80141C00 02000000 */  srl        $zero, $zero, 0
    /* 800C 80141C04 02000000 */  srl        $zero, $zero, 0
    /* 8010 80141C08 09000000 */  jalr       $zero, $zero
    /* 8014 80141C0C 02000000 */   srl       $zero, $zero, 0
    /* 8018 80141C10 02000000 */  srl        $zero, $zero, 0
    /* 801C 80141C14 02000000 */  srl        $zero, $zero, 0
    /* 8020 80141C18 06000000 */  srlv       $zero, $zero, $zero
    /* 8024 80141C1C 06000000 */  srlv       $zero, $zero, $zero
    /* 8028 80141C20 02000000 */  srl        $zero, $zero, 0
    /* 802C 80141C24 02000000 */  srl        $zero, $zero, 0
    /* 8030 80141C28 02000000 */  srl        $zero, $zero, 0
    /* 8034 80141C2C 02000000 */  srl        $zero, $zero, 0
    /* 8038 80141C30 06000000 */  srlv       $zero, $zero, $zero
    /* 803C 80141C34 02000000 */  srl        $zero, $zero, 0
    /* 8040 80141C38 02000000 */  srl        $zero, $zero, 0
    /* 8044 80141C3C 00000000 */  nop
    /* 8048 80141C40 02000000 */  srl        $zero, $zero, 0
    /* 804C 80141C44 06000000 */  srlv       $zero, $zero, $zero
    /* 8050 80141C48 06000000 */  srlv       $zero, $zero, $zero
    /* 8054 80141C4C 02000000 */  srl        $zero, $zero, 0
    /* 8058 80141C50 02000000 */  srl        $zero, $zero, 0
    /* 805C 80141C54 00000000 */  nop
    /* 8060 80141C58 09000000 */  jalr       $zero, $zero
    /* 8064 80141C5C 00000000 */   nop
    /* 8068 80141C60 00000000 */  nop
    /* 806C 80141C64 00000000 */  nop
    /* 8070 80141C68 00000000 */  nop
    /* 8074 80141C6C 04000000 */  sllv       $zero, $zero, $zero
    /* 8078 80141C70 00000000 */  nop
    /* 807C 80141C74 00000000 */  nop
    /* 8080 80141C78 00000000 */  nop
    /* 8084 80141C7C 00000000 */  nop
    /* 8088 80141C80 0C000000 */  syscall    0 /* handwritten instruction */
    /* 808C 80141C84 00000000 */  nop
    /* 8090 80141C88 01000000 */  .word      0x00000001                    # INVALID    $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 8094 80141C8C 00000000 */  nop
    /* 8098 80141C90 00000000 */  nop
    /* 809C 80141C94 01000000 */  .word      0x00000001                    # INVALID    $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 80A0 80141C98 04000000 */  sllv       $zero, $zero, $zero
    /* 80A4 80141C9C 00000000 */  nop
    /* 80A8 80141CA0 01000000 */  .word      0x00000001                    # INVALID    $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 80AC 80141CA4 00000000 */  nop
    /* 80B0 80141CA8 0A000000 */  movz       $zero, $zero, $zero
    /* 80B4 80141CAC 00000000 */  nop
    /* 80B8 80141CB0 00000000 */  nop
    /* 80BC 80141CB4 00000000 */  nop
    /* 80C0 80141CB8 01000000 */  .word      0x00000001                    # INVALID    $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 80C4 80141CBC 01000000 */  .word      0x00000001                    # INVALID    $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 80C8 80141CC0 01000000 */  .word      0x00000001                    # INVALID    $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 80CC 80141CC4 00000000 */  nop
    /* 80D0 80141CC8 04000000 */  sllv       $zero, $zero, $zero
    /* 80D4 80141CCC 00000000 */  nop
    /* 80D8 80141CD0 0B000000 */  movn       $zero, $zero, $zero
    /* 80DC 80141CD4 00000000 */  nop
    /* 80E0 80141CD8 00000000 */  nop
    /* 80E4 80141CDC 00000000 */  nop
    /* 80E8 80141CE0 06000000 */  srlv       $zero, $zero, $zero
    /* 80EC 80141CE4 01000000 */  .word      0x00000001                    # INVALID    $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 80F0 80141CE8 04000000 */  sllv       $zero, $zero, $zero
    /* 80F4 80141CEC 00000000 */  nop
    /* 80F8 80141CF0 01000000 */  .word      0x00000001                    # INVALID    $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 80FC 80141CF4 00000000 */  nop
    /* 8100 80141CF8 0E000000 */  .word      0x0000000E                    # INVALID    $zero, $zero, 0xE # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 8104 80141CFC 00000000 */  nop
    /* 8108 80141D00 06000000 */  srlv       $zero, $zero, $zero
    /* 810C 80141D04 00000000 */  nop
    /* 8110 80141D08 01000000 */  .word      0x00000001                    # INVALID    $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 8114 80141D0C 01000000 */  .word      0x00000001                    # INVALID    $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 8118 80141D10 00000000 */  nop
    /* 811C 80141D14 00000000 */  nop
    /* 8120 80141D18 04000000 */  sllv       $zero, $zero, $zero
    /* 8124 80141D1C 00000000 */  nop
    /* 8128 80141D20 10000000 */  mfhi       $zero
    /* 812C 80141D24 00000000 */  nop
    /* 8130 80141D28 06000000 */  srlv       $zero, $zero, $zero
    /* 8134 80141D2C 00000000 */  nop
    /* 8138 80141D30 00000000 */  nop
    /* 813C 80141D34 01000000 */  .word      0x00000001                    # INVALID    $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 8140 80141D38 01000000 */  .word      0x00000001                    # INVALID    $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 8144 80141D3C 00000000 */  nop
    /* 8148 80141D40 04000000 */  sllv       $zero, $zero, $zero
    /* 814C 80141D44 00000000 */  nop
    /* 8150 80141D48 0F000000 */  sync
    /* 8154 80141D4C 00000000 */  nop
    /* 8158 80141D50 00000000 */  nop
    /* 815C 80141D54 00000000 */  nop
    /* 8160 80141D58 00000000 */  nop
    /* 8164 80141D5C 01000000 */  .word      0x00000001                    # INVALID    $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 8168 80141D60 01000000 */  .word      0x00000001                    # INVALID    $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 816C 80141D64 00000000 */  nop
    /* 8170 80141D68 01000000 */  .word      0x00000001                    # INVALID    $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 8174 80141D6C 04000000 */  sllv       $zero, $zero, $zero
    /* 8178 80141D70 0D000000 */  break      0
    /* 817C 80141D74 08000000 */  jr         $zero
    /* 8180 80141D78 08000000 */   jr        $zero
    /* 8184 80141D7C 08000000 */   jr        $zero
    /* 8188 80141D80 08000000 */   jr        $zero
    /* 818C 80141D84 01000000 */   .word     0x00000001                     # INVALID   $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 8190 80141D88 01000000 */  .word      0x00000001                    # INVALID    $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 8194 80141D8C 00000000 */  nop
    /* 8198 80141D90 01000000 */  .word      0x00000001                    # INVALID    $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 819C 80141D94 01000000 */  .word      0x00000001                    # INVALID    $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 81A0 80141D98 0D000000 */  break      0
    /* 81A4 80141D9C 08000000 */  jr         $zero
    /* 81A8 80141DA0 08000000 */   jr        $zero
    /* 81AC 80141DA4 04000000 */   sllv      $zero, $zero, $zero
    /* 81B0 80141DA8 08000000 */  jr         $zero
    /* 81B4 80141DAC 01000000 */   .word     0x00000001                     # INVALID   $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 81B8 80141DB0 01000000 */  .word      0x00000001                    # INVALID    $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 81BC 80141DB4 00000000 */  nop
    /* 81C0 80141DB8 01000000 */  .word      0x00000001                    # INVALID    $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 81C4 80141DBC 01000000 */  .word      0x00000001                    # INVALID    $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 81C8 80141DC0 0A000000 */  movz       $zero, $zero, $zero
    /* 81CC 80141DC4 00000000 */  nop
    /* 81D0 80141DC8 00000000 */  nop
    /* 81D4 80141DCC 00000000 */  nop
  .L80141DD0:
    /* 81D8 80141DD0 01000000 */  .word      0x00000001                    # INVALID    $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 81DC 80141DD4 01000000 */  .word      0x00000001                    # INVALID    $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 81E0 80141DD8 01000000 */  .word      0x00000001                    # INVALID    $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 81E4 80141DDC 01000000 */  .word      0x00000001                    # INVALID    $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
  .L80141DE0:
    /* 81E8 80141DE0 01000000 */  .word      0x00000001                    # INVALID    $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 81EC 80141DE4 01000000 */  .word      0x00000001                    # INVALID    $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 81F0 80141DE8 0B000000 */  movn       $zero, $zero, $zero
    /* 81F4 80141DEC 01000000 */  .word      0x00000001                    # INVALID    $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
  .L80141DF0:
    /* 81F8 80141DF0 01000000 */  .word      0x00000001                    # INVALID    $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 81FC 80141DF4 01000000 */  .word      0x00000001                    # INVALID    $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 8200 80141DF8 01000000 */  .word      0x00000001                    # INVALID    $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 8204 80141DFC 01000000 */  .word      0x00000001                    # INVALID    $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
  .L80141E00:
    /* 8208 80141E00 01000000 */  .word      0x00000001                    # INVALID    $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 820C 80141E04 02000000 */  srl        $zero, $zero, 0
    /* 8210 80141E08 02000000 */  srl        $zero, $zero, 0
    /* 8214 80141E0C 08000000 */  jr         $zero
  .L80141E10:
    /* 8218 80141E10 02000000 */   srl       $zero, $zero, 0
    /* 821C 80141E14 00000000 */  nop
    /* 8220 80141E18 01000000 */  .word      0x00000001                    # INVALID    $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 8224 80141E1C 00000000 */  nop
  .L80141E20:
    /* 8228 80141E20 01000000 */  .word      0x00000001                    # INVALID    $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 822C 80141E24 01000000 */  .word      0x00000001                    # INVALID    $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 8230 80141E28 04000000 */  sllv       $zero, $zero, $zero
    /* 8234 80141E2C 01000000 */  .word      0x00000001                    # INVALID    $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
  .L80141E30:
    /* 8238 80141E30 01000000 */  .word      0x00000001                    # INVALID    $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 823C 80141E34 00000000 */  nop
    /* 8240 80141E38 10000000 */  mfhi       $zero
    /* 8244 80141E3C 00000000 */  nop
  .L80141E40:
    /* 8248 80141E40 00000000 */  nop
    /* 824C 80141E44 00000000 */  nop
    /* 8250 80141E48 01000000 */  .word      0x00000001                    # INVALID    $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 8254 80141E4C 01000000 */  .word      0x00000001                    # INVALID    $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 8258 80141E50 01000000 */  .word      0x00000001                    # INVALID    $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 825C 80141E54 01000000 */  .word      0x00000001                    # INVALID    $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 8260 80141E58 01000000 */  .word      0x00000001                    # INVALID    $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 8264 80141E5C 04000000 */  sllv       $zero, $zero, $zero
    /* 8268 80141E60 0B000000 */  movn       $zero, $zero, $zero
    /* 826C 80141E64 01000000 */  .word      0x00000001                    # INVALID    $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 8270 80141E68 01000000 */  .word      0x00000001                    # INVALID    $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 8274 80141E6C 04000000 */  sllv       $zero, $zero, $zero
    /* 8278 80141E70 01000000 */  .word      0x00000001                    # INVALID    $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 827C 80141E74 01000000 */  .word      0x00000001                    # INVALID    $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 8280 80141E78 01000000 */  .word      0x00000001                    # INVALID    $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 8284 80141E7C 00000000 */  nop
    /* 8288 80141E80 02000000 */  srl        $zero, $zero, 0
    /* 828C 80141E84 02000000 */  srl        $zero, $zero, 0
    /* 8290 80141E88 02000000 */  srl        $zero, $zero, 0
    /* 8294 80141E8C 01000000 */  .word      0x00000001                    # INVALID    $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 8298 80141E90 01000000 */  .word      0x00000001                    # INVALID    $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 829C 80141E94 01000000 */  .word      0x00000001                    # INVALID    $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 82A0 80141E98 01000000 */  .word      0x00000001                    # INVALID    $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 82A4 80141E9C 01000000 */  .word      0x00000001                    # INVALID    $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 82A8 80141EA0 01000000 */  .word      0x00000001                    # INVALID    $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 82AC 80141EA4 06000000 */  srlv       $zero, $zero, $zero
    /* 82B0 80141EA8 02000000 */  srl        $zero, $zero, 0
    /* 82B4 80141EAC 06000000 */  srlv       $zero, $zero, $zero
    /* 82B8 80141EB0 02000000 */  srl        $zero, $zero, 0
    /* 82BC 80141EB4 04000000 */  sllv       $zero, $zero, $zero
    /* 82C0 80141EB8 01000000 */  .word      0x00000001                    # INVALID    $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 82C4 80141EBC 01000000 */  .word      0x00000001                    # INVALID    $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 82C8 80141EC0 01000000 */  .word      0x00000001                    # INVALID    $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 82CC 80141EC4 01000000 */  .word      0x00000001                    # INVALID    $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 82D0 80141EC8 01000000 */  .word      0x00000001                    # INVALID    $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 82D4 80141ECC 06000000 */  srlv       $zero, $zero, $zero
    /* 82D8 80141ED0 02000000 */  srl        $zero, $zero, 0
    /* 82DC 80141ED4 06000000 */  srlv       $zero, $zero, $zero
    /* 82E0 80141ED8 02000000 */  srl        $zero, $zero, 0
    /* 82E4 80141EDC 02000000 */  srl        $zero, $zero, 0
    /* 82E8 80141EE0 02000000 */  srl        $zero, $zero, 0
    /* 82EC 80141EE4 02000000 */  srl        $zero, $zero, 0
    /* 82F0 80141EE8 01000000 */  .word      0x00000001                    # INVALID    $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 82F4 80141EEC 01000000 */  .word      0x00000001                    # INVALID    $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 82F8 80141EF0 01000000 */  .word      0x00000001                    # INVALID    $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 82FC 80141EF4 04000000 */  sllv       $zero, $zero, $zero
    /* 8300 80141EF8 01000000 */  .word      0x00000001                    # INVALID    $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 8304 80141EFC 01000000 */  .word      0x00000001                    # INVALID    $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 8308 80141F00 0B000000 */  movn       $zero, $zero, $zero
    /* 830C 80141F04 04000000 */  sllv       $zero, $zero, $zero
    /* 8310 80141F08 01000000 */  .word      0x00000001                    # INVALID    $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 8314 80141F0C 01000000 */  .word      0x00000001                    # INVALID    $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 8318 80141F10 01000000 */  .word      0x00000001                    # INVALID    $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 831C 80141F14 01000000 */  .word      0x00000001                    # INVALID    $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 8320 80141F18 01000000 */  .word      0x00000001                    # INVALID    $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 8324 80141F1C 02000000 */  srl        $zero, $zero, 0
    /* 8328 80141F20 02000000 */  srl        $zero, $zero, 0
    /* 832C 80141F24 02000000 */  srl        $zero, $zero, 0
    /* 8330 80141F28 02000000 */  srl        $zero, $zero, 0
    /* 8334 80141F2C 01000000 */  .word      0x00000001                    # INVALID    $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 8338 80141F30 01000000 */  .word      0x00000001                    # INVALID    $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 833C 80141F34 04000000 */  sllv       $zero, $zero, $zero
    /* 8340 80141F38 01000000 */  .word      0x00000001                    # INVALID    $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 8344 80141F3C 01000000 */  .word      0x00000001                    # INVALID    $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 8348 80141F40 01000000 */  .word      0x00000001                    # INVALID    $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 834C 80141F44 02000000 */  srl        $zero, $zero, 0
    /* 8350 80141F48 02000000 */  srl        $zero, $zero, 0
    /* 8354 80141F4C 01000000 */  .word      0x00000001                    # INVALID    $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 8358 80141F50 02000000 */  srl        $zero, $zero, 0
    /* 835C 80141F54 04000000 */  sllv       $zero, $zero, $zero
    /* 8360 80141F58 01000000 */  .word      0x00000001                    # INVALID    $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 8364 80141F5C 01000000 */  .word      0x00000001                    # INVALID    $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 8368 80141F60 01000000 */  .word      0x00000001                    # INVALID    $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 836C 80141F64 01000000 */  .word      0x00000001                    # INVALID    $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 8370 80141F68 01000000 */  .word      0x00000001                    # INVALID    $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 8374 80141F6C 01000000 */  .word      0x00000001                    # INVALID    $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 8378 80141F70 02000000 */  srl        $zero, $zero, 0
    /* 837C 80141F74 02000000 */  srl        $zero, $zero, 0
    /* 8380 80141F78 02000000 */  srl        $zero, $zero, 0
    /* 8384 80141F7C 02000000 */  srl        $zero, $zero, 0
    /* 8388 80141F80 02000000 */  srl        $zero, $zero, 0
    /* 838C 80141F84 06000000 */  srlv       $zero, $zero, $zero
    /* 8390 80141F88 01000000 */  .word      0x00000001                    # INVALID    $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 8394 80141F8C 01000000 */  .word      0x00000001                    # INVALID    $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 8398 80141F90 01000000 */  .word      0x00000001                    # INVALID    $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 839C 80141F94 04000000 */  sllv       $zero, $zero, $zero
    /* 83A0 80141F98 01000000 */  .word      0x00000001                    # INVALID    $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 83A4 80141F9C 01000000 */  .word      0x00000001                    # INVALID    $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 83A8 80141FA0 0B000000 */  movn       $zero, $zero, $zero
    /* 83AC 80141FA4 04000000 */  sllv       $zero, $zero, $zero
    /* 83B0 80141FA8 01000000 */  .word      0x00000001                    # INVALID    $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 83B4 80141FAC 01000000 */  .word      0x00000001                    # INVALID    $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 83B8 80141FB0 01000000 */  .word      0x00000001                    # INVALID    $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 83BC 80141FB4 01000000 */  .word      0x00000001                    # INVALID    $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 83C0 80141FB8 01000000 */  .word      0x00000001                    # INVALID    $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 83C4 80141FBC 02000000 */  srl        $zero, $zero, 0
    /* 83C8 80141FC0 02000000 */  srl        $zero, $zero, 0
    /* 83CC 80141FC4 06000000 */  srlv       $zero, $zero, $zero
    /* 83D0 80141FC8 02000000 */  srl        $zero, $zero, 0
    /* 83D4 80141FCC 01000000 */  .word      0x00000001                    # INVALID    $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 83D8 80141FD0 02000000 */  srl        $zero, $zero, 0
    /* 83DC 80141FD4 02000000 */  srl        $zero, $zero, 0
    /* 83E0 80141FD8 01000000 */  .word      0x00000001                    # INVALID    $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 83E4 80141FDC 01000000 */  .word      0x00000001                    # INVALID    $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 83E8 80141FE0 01000000 */  .word      0x00000001                    # INVALID    $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 83EC 80141FE4 04000000 */  sllv       $zero, $zero, $zero
    /* 83F0 80141FE8 01000000 */  .word      0x00000001                    # INVALID    $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 83F4 80141FEC 01000000 */  .word      0x00000001                    # INVALID    $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 83F8 80141FF0 0B000000 */  movn       $zero, $zero, $zero
    /* 83FC 80141FF4 00000000 */  nop
    /* 8400 80141FF8 01000000 */  .word      0x00000001                    # INVALID    $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 8404 80141FFC 01000000 */  .word      0x00000001                    # INVALID    $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
  .L80142000:
    /* 8408 80142000 00000000 */  nop
    /* 840C 80142004 01000000 */  .word      0x00000001                    # INVALID    $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 8410 80142008 01000000 */  .word      0x00000001                    # INVALID    $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 8414 8014200C 00000000 */  nop
    /* 8418 80142010 01000000 */  .word      0x00000001                    # INVALID    $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 841C 80142014 01000000 */  .word      0x00000001                    # INVALID    $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 8420 80142018 0A000000 */  movz       $zero, $zero, $zero
    /* 8424 8014201C 02000000 */  srl        $zero, $zero, 0
    /* 8428 80142020 01000000 */  .word      0x00000001                    # INVALID    $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 842C 80142024 01000000 */  .word      0x00000001                    # INVALID    $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 8430 80142028 03000000 */  sra        $zero, $zero, 0
    /* 8434 8014202C 01000000 */  .word      0x00000001                    # INVALID    $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 8438 80142030 01000000 */  .word      0x00000001                    # INVALID    $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 843C 80142034 02000000 */  srl        $zero, $zero, 0
    /* 8440 80142038 01000000 */  .word      0x00000001                    # INVALID    $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 8444 8014203C 01000000 */  .word      0x00000001                    # INVALID    $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 8448 80142040 0E000000 */  .word      0x0000000E                    # INVALID    $zero, $zero, 0xE # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 844C 80142044 01000000 */  .word      0x00000001                    # INVALID    $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 8450 80142048 01000000 */  .word      0x00000001                    # INVALID    $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 8454 8014204C 00000000 */  nop
    /* 8458 80142050 01000000 */  .word      0x00000001                    # INVALID    $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 845C 80142054 01000000 */  .word      0x00000001                    # INVALID    $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 8460 80142058 02000000 */  srl        $zero, $zero, 0
    /* 8464 8014205C 01000000 */  .word      0x00000001                    # INVALID    $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 8468 80142060 01000000 */  .word      0x00000001                    # INVALID    $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 846C 80142064 00000000 */  nop
    /* 8470 80142068 01000000 */  .word      0x00000001                    # INVALID    $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 8474 8014206C 00000000 */  nop
    /* 8478 80142070 04000000 */  sllv       $zero, $zero, $zero
    /* 847C 80142074 00000000 */  nop
    /* 8480 80142078 01000000 */  .word      0x00000001                    # INVALID    $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 8484 8014207C 01000000 */  .word      0x00000001                    # INVALID    $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 8488 80142080 01000000 */  .word      0x00000001                    # INVALID    $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 848C 80142084 00000000 */  nop
    /* 8490 80142088 01000000 */  .word      0x00000001                    # INVALID    $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 8494 8014208C 01000000 */  .word      0x00000001                    # INVALID    $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 8498 80142090 0E000000 */  .word      0x0000000E                    # INVALID    $zero, $zero, 0xE # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 849C 80142094 04000000 */  sllv       $zero, $zero, $zero
    /* 84A0 80142098 01000000 */  .word      0x00000001                    # INVALID    $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 84A4 8014209C 00000000 */  nop
    /* 84A8 801420A0 01000000 */  .word      0x00000001                    # INVALID    $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 84AC 801420A4 01000000 */  .word      0x00000001                    # INVALID    $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 84B0 801420A8 00000000 */  nop
    /* 84B4 801420AC 01000000 */  .word      0x00000001                    # INVALID    $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 84B8 801420B0 01000000 */  .word      0x00000001                    # INVALID    $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 84BC 801420B4 00000000 */  nop
    /* 84C0 801420B8 01000000 */  .word      0x00000001                    # INVALID    $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 84C4 801420BC 00000000 */  nop
    /* 84C8 801420C0 01000000 */  .word      0x00000001                    # INVALID    $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 84CC 801420C4 00000000 */  nop
    /* 84D0 801420C8 04000000 */  sllv       $zero, $zero, $zero
    /* 84D4 801420CC 01000000 */  .word      0x00000001                    # INVALID    $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 84D8 801420D0 01000000 */  .word      0x00000001                    # INVALID    $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 84DC 801420D4 00000000 */  nop
    /* 84E0 801420D8 01000000 */  .word      0x00000001                    # INVALID    $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 84E4 801420DC 01000000 */  .word      0x00000001                    # INVALID    $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 84E8 801420E0 0F000000 */  sync
    /* 84EC 801420E4 01000000 */  .word      0x00000001                    # INVALID    $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 84F0 801420E8 01000000 */  .word      0x00000001                    # INVALID    $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 84F4 801420EC 01000000 */  .word      0x00000001                    # INVALID    $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 84F8 801420F0 01000000 */  .word      0x00000001                    # INVALID    $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 84FC 801420F4 01000000 */  .word      0x00000001                    # INVALID    $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 8500 801420F8 01000000 */  .word      0x00000001                    # INVALID    $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 8504 801420FC 00000000 */  nop
    /* 8508 80142100 02000000 */  srl        $zero, $zero, 0
    /* 850C 80142104 02000000 */  srl        $zero, $zero, 0
    /* 8510 80142108 02000000 */  srl        $zero, $zero, 0
    /* 8514 8014210C 00000000 */  nop
    /* 8518 80142110 01000000 */  .word      0x00000001                    # INVALID    $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 851C 80142114 01000000 */  .word      0x00000001                    # INVALID    $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 8520 80142118 02000000 */  srl        $zero, $zero, 0
    /* 8524 8014211C 01000000 */  .word      0x00000001                    # INVALID    $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 8528 80142120 01000000 */  .word      0x00000001                    # INVALID    $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 852C 80142124 02000000 */  srl        $zero, $zero, 0
    /* 8530 80142128 01000000 */  .word      0x00000001                    # INVALID    $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 8534 8014212C 04000000 */  sllv       $zero, $zero, $zero
    /* 8538 80142130 0A000000 */  movz       $zero, $zero, $zero
    /* 853C 80142134 02000000 */  srl        $zero, $zero, 0
    /* 8540 80142138 01000000 */  .word      0x00000001                    # INVALID    $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 8544 8014213C 01000000 */  .word      0x00000001                    # INVALID    $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 8548 80142140 01000000 */  .word      0x00000001                    # INVALID    $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 854C 80142144 01000000 */  .word      0x00000001                    # INVALID    $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 8550 80142148 01000000 */  .word      0x00000001                    # INVALID    $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 8554 8014214C 00000000 */  nop
    /* 8558 80142150 04000000 */  sllv       $zero, $zero, $zero
    /* 855C 80142154 00000000 */  nop
    /* 8560 80142158 10000000 */  mfhi       $zero
    /* 8564 8014215C 01000000 */  .word      0x00000001                    # INVALID    $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 8568 80142160 01000000 */  .word      0x00000001                    # INVALID    $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 856C 80142164 04000000 */  sllv       $zero, $zero, $zero
    /* 8570 80142168 01000000 */  .word      0x00000001                    # INVALID    $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 8574 8014216C 01000000 */  .word      0x00000001                    # INVALID    $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 8578 80142170 02000000 */  srl        $zero, $zero, 0
    /* 857C 80142174 00000000 */  nop
    /* 8580 80142178 01000000 */  .word      0x00000001                    # INVALID    $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 8584 8014217C 02000000 */  srl        $zero, $zero, 0
    /* 8588 80142180 01000000 */  .word      0x00000001                    # INVALID    $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 858C 80142184 02000000 */  srl        $zero, $zero, 0
    /* 8590 80142188 01000000 */  .word      0x00000001                    # INVALID    $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 8594 8014218C 01000000 */  .word      0x00000001                    # INVALID    $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 8598 80142190 02000000 */  srl        $zero, $zero, 0
    /* 859C 80142194 01000000 */  .word      0x00000001                    # INVALID    $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 85A0 80142198 01000000 */  .word      0x00000001                    # INVALID    $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 85A4 8014219C 01000000 */  .word      0x00000001                    # INVALID    $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 85A8 801421A0 01000000 */  .word      0x00000001                    # INVALID    $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 85AC 801421A4 04000000 */  sllv       $zero, $zero, $zero
    /* 85B0 801421A8 0A000000 */  movz       $zero, $zero, $zero
    /* 85B4 801421AC 01000000 */  .word      0x00000001                    # INVALID    $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 85B8 801421B0 01000000 */  .word      0x00000001                    # INVALID    $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 85BC 801421B4 02000000 */  srl        $zero, $zero, 0
    /* 85C0 801421B8 01000000 */  .word      0x00000001                    # INVALID    $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 85C4 801421BC 01000000 */  .word      0x00000001                    # INVALID    $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 85C8 801421C0 02000000 */  srl        $zero, $zero, 0
    /* 85CC 801421C4 04000000 */  sllv       $zero, $zero, $zero
    /* 85D0 801421C8 01000000 */  .word      0x00000001                    # INVALID    $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 85D4 801421CC 08000000 */  jr         $zero
    /* 85D8 801421D0 01000000 */   .word     0x00000001                     # INVALID   $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 85DC 801421D4 02000000 */  srl        $zero, $zero, 0
  .L801421D8:
    /* 85E0 801421D8 01000000 */  .word      0x00000001                    # INVALID    $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 85E4 801421DC 04000000 */  sllv       $zero, $zero, $zero
    /* 85E8 801421E0 01000000 */  .word      0x00000001                    # INVALID    $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 85EC 801421E4 01000000 */  .word      0x00000001                    # INVALID    $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 85F0 801421E8 01000000 */  .word      0x00000001                    # INVALID    $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 85F4 801421EC 04000000 */  sllv       $zero, $zero, $zero
    /* 85F8 801421F0 04000000 */  sllv       $zero, $zero, $zero
    /* 85FC 801421F4 01000000 */  .word      0x00000001                    # INVALID    $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
  .L801421F8:
    /* 8600 801421F8 10000000 */  mfhi       $zero
    /* 8604 801421FC 02000000 */  srl        $zero, $zero, 0
    /* 8608 80142200 01000000 */  .word      0x00000001                    # INVALID    $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 860C 80142204 01000000 */  .word      0x00000001                    # INVALID    $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 8610 80142208 01000000 */  .word      0x00000001                    # INVALID    $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 8614 8014220C 01000000 */  .word      0x00000001                    # INVALID    $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 8618 80142210 01000000 */  .word      0x00000001                    # INVALID    $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 861C 80142214 01000000 */  .word      0x00000001                    # INVALID    $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 8620 80142218 01000000 */  .word      0x00000001                    # INVALID    $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 8624 8014221C 01000000 */  .word      0x00000001                    # INVALID    $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 8628 80142220 10000000 */  mfhi       $zero
    /* 862C 80142224 01000000 */  .word      0x00000001                    # INVALID    $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 8630 80142228 01000000 */  .word      0x00000001                    # INVALID    $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 8634 8014222C 02000000 */  srl        $zero, $zero, 0
    /* 8638 80142230 01000000 */  .word      0x00000001                    # INVALID    $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 863C 80142234 01000000 */  .word      0x00000001                    # INVALID    $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
  .L80142238:
    /* 8640 80142238 01000000 */  .word      0x00000001                    # INVALID    $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 8644 8014223C 01000000 */  .word      0x00000001                    # INVALID    $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 8648 80142240 01000000 */  .word      0x00000001                    # INVALID    $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 864C 80142244 01000000 */  .word      0x00000001                    # INVALID    $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 8650 80142248 0F000000 */  sync
    /* 8654 8014224C 01000000 */  .word      0x00000001                    # INVALID    $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 8658 80142250 01000000 */  .word      0x00000001                    # INVALID    $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 865C 80142254 01000000 */  .word      0x00000001                    # INVALID    $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 8660 80142258 01000000 */  .word      0x00000001                    # INVALID    $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 8664 8014225C 01000000 */  .word      0x00000001                    # INVALID    $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 8668 80142260 01000000 */  .word      0x00000001                    # INVALID    $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 866C 80142264 02000000 */  srl        $zero, $zero, 0
    /* 8670 80142268 01000000 */  .word      0x00000001                    # INVALID    $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 8674 8014226C 01000000 */  .word      0x00000001                    # INVALID    $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 8678 80142270 0E000000 */  .word      0x0000000E                    # INVALID    $zero, $zero, 0xE # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 867C 80142274 04000000 */  sllv       $zero, $zero, $zero
    /* 8680 80142278 01000000 */  .word      0x00000001                    # INVALID    $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 8684 8014227C 01000000 */  .word      0x00000001                    # INVALID    $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 8688 80142280 01000000 */  .word      0x00000001                    # INVALID    $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 868C 80142284 01000000 */  .word      0x00000001                    # INVALID    $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 8690 80142288 01000000 */  .word      0x00000001                    # INVALID    $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 8694 8014228C 02000000 */  srl        $zero, $zero, 0
    /* 8698 80142290 01000000 */  .word      0x00000001                    # INVALID    $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 869C 80142294 01000000 */  .word      0x00000001                    # INVALID    $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 86A0 80142298 0E000000 */  .word      0x0000000E                    # INVALID    $zero, $zero, 0xE # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 86A4 8014229C 01000000 */  .word      0x00000001                    # INVALID    $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 86A8 801422A0 01000000 */  .word      0x00000001                    # INVALID    $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 86AC 801422A4 01000000 */  .word      0x00000001                    # INVALID    $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 86B0 801422A8 01000000 */  .word      0x00000001                    # INVALID    $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 86B4 801422AC 01000000 */  .word      0x00000001                    # INVALID    $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 86B8 801422B0 01000000 */  .word      0x00000001                    # INVALID    $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 86BC 801422B4 01000000 */  .word      0x00000001                    # INVALID    $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 86C0 801422B8 01000000 */  .word      0x00000001                    # INVALID    $zero, $zero, 0x1 # 00000000 <InstrIdType: CPU_SPECIAL>
    /* 86C4 801422BC 02000000 */  srl        $zero, $zero, 0
    /* 86C8 801422C0 08000000 */  jr         $zero
    /* 86CC 801422C4 00000000 */   nop
    /* 86D0 801422C8 00000000 */  nop
    /* 86D4 801422CC 00000000 */  nop
    /* 86D8 801422D0 00000000 */  nop
    /* 86DC 801422D4 FF000000 */  dsra32     $zero, $zero, 3
    /* 86E0 801422D8 00000000 */  nop
    /* 86E4 801422DC 00000000 */  nop
    /* 86E8 801422E0 00000000 */  nop
    /* 86EC 801422E4 00000000 */  nop
    /* 86F0 801422E8 00000000 */  nop
    /* 86F4 801422EC 00000000 */  nop
    /* 86F8 801422F0 00000000 */  nop
    /* 86FC 801422F4 00000000 */  nop
    /* 8700 801422F8 00000000 */  nop
    /* 8704 801422FC 00000000 */  nop
    /* 8708 80142300 00000000 */  nop
    /* 870C 80142304 00000000 */  nop
    /* 8710 80142308 00000000 */  nop
    /* 8714 8014230C 00000000 */  nop
    /* 8718 80142310 00000000 */  nop
    /* 871C 80142314 00000000 */  nop
    /* 8720 80142318 00000000 */  nop
    /* 8724 8014231C 00000000 */  nop
    /* 8728 80142320 00000000 */  nop
    /* 872C 80142324 00000000 */  nop
    /* 8730 80142328 00000000 */  nop
    /* 8734 8014232C 00000000 */  nop
    /* 8738 80142330 00000000 */  nop
    /* 873C 80142334 00000000 */  nop
    /* 8740 80142338 00000000 */  nop
    /* 8744 8014233C 00000000 */  nop
    /* 8748 80142340 00000000 */  nop
    /* 874C 80142344 00000000 */  nop
    /* 8750 80142348 00000000 */  nop
    /* 8754 8014234C 00000000 */  nop
    /* 8758 80142350 00000000 */  nop
    /* 875C 80142354 00000000 */  nop
    /* 8760 80142358 00000000 */  nop
    /* 8764 8014235C 00000000 */  nop
    /* 8768 80142360 00000000 */  nop
    /* 876C 80142364 00000000 */  nop
    /* 8770 80142368 00000000 */  nop
    /* 8774 8014236C 00000000 */  nop
    /* 8778 80142370 00000000 */  nop
    /* 877C 80142374 00000000 */  nop
    /* 8780 80142378 00000000 */  nop
    /* 8784 8014237C 00000000 */  nop
    /* 8788 80142380 00000000 */  nop
    /* 878C 80142384 00000000 */  nop
    /* 8790 80142388 00000000 */  nop
    /* 8794 8014238C 00000000 */  nop
    /* 8798 80142390 00000000 */  nop
    /* 879C 80142394 00000000 */  nop
    /* 87A0 80142398 00000000 */  nop
    /* 87A4 8014239C 00000000 */  nop
    /* 87A8 801423A0 00000000 */  nop
    /* 87AC 801423A4 00000000 */  nop
    /* 87B0 801423A8 00000000 */  nop
    /* 87B4 801423AC 00000000 */  nop
    /* 87B8 801423B0 00000000 */  nop
    /* 87BC 801423B4 00000000 */  nop
    /* 87C0 801423B8 00000000 */  nop
    /* 87C4 801423BC 00000000 */  nop
    /* 87C8 801423C0 00000000 */  nop
    /* 87CC 801423C4 00000000 */  nop
    /* 87D0 801423C8 00000000 */  nop
    /* 87D4 801423CC 00000000 */  nop
    /* 87D8 801423D0 00000000 */  nop
    /* 87DC 801423D4 00000000 */  nop
    /* 87E0 801423D8 00000000 */  nop
    /* 87E4 801423DC 00000000 */  nop
    /* 87E8 801423E0 00000000 */  nop
    /* 87EC 801423E4 00000000 */  nop
    /* 87F0 801423E8 00000000 */  nop
    /* 87F4 801423EC 00000000 */  nop
    /* 87F8 801423F0 00000000 */  nop
    /* 87FC 801423F4 00000000 */  nop
    /* 8800 801423F8 00000000 */  nop
    /* 8804 801423FC 00000000 */  nop
  .L80142400:
    /* 8808 80142400 00000000 */  nop
    /* 880C 80142404 00000000 */  nop
    /* 8810 80142408 00000000 */  nop
    /* 8814 8014240C 00000000 */  nop
    /* 8818 80142410 00000000 */  nop
    /* 881C 80142414 00000000 */  nop
    /* 8820 80142418 00000000 */  nop
    /* 8824 8014241C 00000000 */  nop
    /* 8828 80142420 00000000 */  nop
    /* 882C 80142424 00000000 */  nop
    /* 8830 80142428 00000000 */  nop
    /* 8834 8014242C 00000000 */  nop
    /* 8838 80142430 00000000 */  nop
    /* 883C 80142434 00000000 */  nop
    /* 8840 80142438 00000000 */  nop
    /* 8844 8014243C 00000000 */  nop
    /* 8848 80142440 00000000 */  nop
    /* 884C 80142444 00000000 */  nop
    /* 8850 80142448 00000000 */  nop
    /* 8854 8014244C 00000000 */  nop
    /* 8858 80142450 00000000 */  nop
    /* 885C 80142454 00000000 */  nop
    /* 8860 80142458 00000000 */  nop
    /* 8864 8014245C 00000000 */  nop
    /* 8868 80142460 00000000 */  nop
    /* 886C 80142464 00000000 */  nop
    /* 8870 80142468 00000000 */  nop
    /* 8874 8014246C 00000000 */  nop
    /* 8878 80142470 00000000 */  nop
    /* 887C 80142474 00000000 */  nop
    /* 8880 80142478 00000000 */  nop
    /* 8884 8014247C 00000000 */  nop
    /* 8888 80142480 00000000 */  nop
    /* 888C 80142484 00000000 */  nop
    /* 8890 80142488 00000000 */  nop
    /* 8894 8014248C 00000000 */  nop
    /* 8898 80142490 00000000 */  nop
    /* 889C 80142494 00000000 */  nop
    /* 88A0 80142498 00000000 */  nop
    /* 88A4 8014249C 00000000 */  nop
    /* 88A8 801424A0 00000000 */  nop
    /* 88AC 801424A4 00000000 */  nop
    /* 88B0 801424A8 00000000 */  nop
    /* 88B4 801424AC 00000000 */  nop
    /* 88B8 801424B0 00000000 */  nop
    /* 88BC 801424B4 00000000 */  nop
    /* 88C0 801424B8 00000000 */  nop
    /* 88C4 801424BC 00000000 */  nop
    /* 88C8 801424C0 00000000 */  nop
    /* 88CC 801424C4 00000000 */  nop
    /* 88D0 801424C8 00000000 */  nop
    /* 88D4 801424CC 00000000 */  nop
    /* 88D8 801424D0 00000000 */  nop
    /* 88DC 801424D4 00000000 */  nop
    /* 88E0 801424D8 00000000 */  nop
    /* 88E4 801424DC 00000000 */  nop
    /* 88E8 801424E0 00000000 */  nop
    /* 88EC 801424E4 00000000 */  nop
    /* 88F0 801424E8 00000000 */  nop
    /* 88F4 801424EC 00000000 */  nop
    /* 88F8 801424F0 00000000 */  nop
    /* 88FC 801424F4 00000000 */  nop
    /* 8900 801424F8 00000000 */  nop
    /* 8904 801424FC 00000000 */  nop
    /* 8908 80142500 00000000 */  nop
    /* 890C 80142504 00000000 */  nop
    /* 8910 80142508 00000000 */  nop
    /* 8914 8014250C 00000000 */  nop
    /* 8918 80142510 00000000 */  nop
    /* 891C 80142514 00000000 */  nop
    /* 8920 80142518 00000000 */  nop
    /* 8924 8014251C 00000000 */  nop
    /* 8928 80142520 00000000 */  nop
    /* 892C 80142524 00000000 */  nop
    /* 8930 80142528 00000000 */  nop
    /* 8934 8014252C 00000000 */  nop
    /* 8938 80142530 00000000 */  nop
    /* 893C 80142534 00000000 */  nop
    /* 8940 80142538 00000000 */  nop
    /* 8944 8014253C 00000000 */  nop
    /* 8948 80142540 00000000 */  nop
    /* 894C 80142544 00000000 */  nop
    /* 8950 80142548 00000000 */  nop
    /* 8954 8014254C 00000000 */  nop
    /* 8958 80142550 00000000 */  nop
    /* 895C 80142554 00000000 */  nop
    /* 8960 80142558 00000000 */  nop
    /* 8964 8014255C 00000000 */  nop
    /* 8968 80142560 00000000 */  nop
    /* 896C 80142564 00000000 */  nop
    /* 8970 80142568 00000000 */  nop
    /* 8974 8014256C 00000000 */  nop
    /* 8978 80142570 00000000 */  nop
    /* 897C 80142574 00000000 */  nop
    /* 8980 80142578 00000000 */  nop
    /* 8984 8014257C 00000000 */  nop
    /* 8988 80142580 00000000 */  nop
    /* 898C 80142584 00000000 */  nop
    /* 8990 80142588 00000000 */  nop
    /* 8994 8014258C 00000000 */  nop
    /* 8998 80142590 00000000 */  nop
    /* 899C 80142594 00000000 */  nop
    /* 89A0 80142598 00000000 */  nop
    /* 89A4 8014259C 00000000 */  nop
    /* 89A8 801425A0 00000000 */  nop
    /* 89AC 801425A4 00000000 */  nop
    /* 89B0 801425A8 00000000 */  nop
    /* 89B4 801425AC 00000000 */  nop
    /* 89B8 801425B0 00000000 */  nop
    /* 89BC 801425B4 00000000 */  nop
    /* 89C0 801425B8 00000000 */  nop
    /* 89C4 801425BC 00000000 */  nop
    /* 89C8 801425C0 00000000 */  nop
    /* 89CC 801425C4 00000000 */  nop
    /* 89D0 801425C8 00000000 */  nop
    /* 89D4 801425CC 00000000 */  nop
    /* 89D8 801425D0 00000000 */  nop
    /* 89DC 801425D4 00000000 */  nop
    /* 89E0 801425D8 00000000 */  nop
    /* 89E4 801425DC 00000000 */  nop
    /* 89E8 801425E0 00000000 */  nop
    /* 89EC 801425E4 00000000 */  nop
    /* 89F0 801425E8 00000000 */  nop
    /* 89F4 801425EC 00000000 */  nop
    /* 89F8 801425F0 00000000 */  nop
    /* 89FC 801425F4 00000000 */  nop
    /* 8A00 801425F8 00000000 */  nop
    /* 8A04 801425FC 00000000 */  nop
    /* 8A08 80142600 00000000 */  nop
    /* 8A0C 80142604 00000000 */  nop
    /* 8A10 80142608 00000000 */  nop
    /* 8A14 8014260C 00000000 */  nop
    /* 8A18 80142610 00000000 */  nop
    /* 8A1C 80142614 00000000 */  nop
    /* 8A20 80142618 00000000 */  nop
    /* 8A24 8014261C 00000000 */  nop
    /* 8A28 80142620 00000000 */  nop
    /* 8A2C 80142624 00000000 */  nop
    /* 8A30 80142628 00000000 */  nop
    /* 8A34 8014262C 00000000 */  nop
    /* 8A38 80142630 00000000 */  nop
    /* 8A3C 80142634 00000000 */  nop
    /* 8A40 80142638 00000000 */  nop
    /* 8A44 8014263C 00000000 */  nop
    /* 8A48 80142640 00000000 */  nop
    /* 8A4C 80142644 00000000 */  nop
    /* 8A50 80142648 00000000 */  nop
    /* 8A54 8014264C 00000000 */  nop
    /* 8A58 80142650 00000000 */  nop
    /* 8A5C 80142654 00000000 */  nop
    /* 8A60 80142658 00000000 */  nop
    /* 8A64 8014265C 00000000 */  nop
    /* 8A68 80142660 00000000 */  nop
    /* 8A6C 80142664 00000000 */  nop
    /* 8A70 80142668 00000000 */  nop
    /* 8A74 8014266C 00000000 */  nop
    /* 8A78 80142670 00000000 */  nop
    /* 8A7C 80142674 00000000 */  nop
    /* 8A80 80142678 00000000 */  nop
    /* 8A84 8014267C 00000000 */  nop
    /* 8A88 80142680 00000000 */  nop
    /* 8A8C 80142684 00000000 */  nop
    /* 8A90 80142688 00000000 */  nop
    /* 8A94 8014268C 00000000 */  nop
    /* 8A98 80142690 00000000 */  nop
    /* 8A9C 80142694 00000000 */  nop
    /* 8AA0 80142698 00000000 */  nop
    /* 8AA4 8014269C 00000000 */  nop
    /* 8AA8 801426A0 00000000 */  nop
    /* 8AAC 801426A4 00000000 */  nop
    /* 8AB0 801426A8 00000000 */  nop
    /* 8AB4 801426AC 00000000 */  nop
    /* 8AB8 801426B0 00000000 */  nop
    /* 8ABC 801426B4 00000000 */  nop
    /* 8AC0 801426B8 00000000 */  nop
    /* 8AC4 801426BC 00000000 */  nop
    /* 8AC8 801426C0 00000000 */  nop
    /* 8ACC 801426C4 00000000 */  nop
    /* 8AD0 801426C8 00000000 */  nop
    /* 8AD4 801426CC 00000000 */  nop
    /* 8AD8 801426D0 00000000 */  nop
    /* 8ADC 801426D4 00000000 */  nop
    /* 8AE0 801426D8 00000000 */  nop
    /* 8AE4 801426DC 00000000 */  nop
    /* 8AE8 801426E0 00000000 */  nop
    /* 8AEC 801426E4 00000000 */  nop
    /* 8AF0 801426E8 00000000 */  nop
    /* 8AF4 801426EC 00000000 */  nop
    /* 8AF8 801426F0 00000000 */  nop
    /* 8AFC 801426F4 00000000 */  nop
    /* 8B00 801426F8 00000000 */  nop
    /* 8B04 801426FC 00000000 */  nop
    /* 8B08 80142700 00000000 */  nop
    /* 8B0C 80142704 00000000 */  nop
    /* 8B10 80142708 00000000 */  nop
    /* 8B14 8014270C 00000000 */  nop
    /* 8B18 80142710 00000000 */  nop
    /* 8B1C 80142714 00000000 */  nop
    /* 8B20 80142718 00000000 */  nop
    /* 8B24 8014271C 00000000 */  nop
    /* 8B28 80142720 00000000 */  nop
    /* 8B2C 80142724 00000000 */  nop
    /* 8B30 80142728 00000000 */  nop
    /* 8B34 8014272C 00000000 */  nop
    /* 8B38 80142730 00000000 */  nop
    /* 8B3C 80142734 00000000 */  nop
    /* 8B40 80142738 00000000 */  nop
    /* 8B44 8014273C 00000000 */  nop
    /* 8B48 80142740 00000000 */  nop
    /* 8B4C 80142744 00000000 */  nop
    /* 8B50 80142748 00000000 */  nop
endlabel Patterns
