.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.42.4 */

nonmatching VARCH35, 0x12

glabel VARCH35
    /* 7714 8014130C 02040200 */  srl        $zero, $v0, 16
    /* 7718 80141310 03080304 */  bgezl      $zero, .L80143320
    /* 771C 80141314 00068E00 */   .word     0x008E0600                     # sll       $zero, $t6, 24 # 00800000 <InstrIdType: CPU_SPECIAL>
    /* 7720 80141318 332A2F2C */  sltiu      $t7, $at, 0x2A33
    /* 7724 8014131C 00000000 */  nop
