.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.42.4 */

nonmatching VARCH36, 0x12

glabel VARCH36
    /* 7728 80141320 02040200 */  srl        $zero, $v0, 16
    /* 772C 80141324 03080304 */  bgezl      $zero, .L80143334
    /* 7730 80141328 00098E00 */   .word     0x008E0900                     # sll       $at, $t6, 4 # 00800000 <InstrIdType: CPU_SPECIAL>
    /* 7734 8014132C 332A2F2C */  sltiu      $t7, $at, 0x2A33
    /* 7738 80141330 00000000 */  nop
