.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.42.4 */

nonmatching VARCH26, 0x12

glabel VARCH26
    /* 7660 80141258 02040300 */  srl        $zero, $v1, 16
    /* 7664 8014125C 03040301 */  .word      0x01030403                    # sra        $zero, $v1, 16 # 01000000 <InstrIdType: CPU_SPECIAL>
    /* 7668 80141260 00083000 */  .word      0x00300800                    # sll        $at, $s0, 0 # 00200000 <InstrIdType: CPU_SPECIAL>
    /* 766C 80141264 33272F2C */  sltiu      $t7, $at, 0x2733
    /* 7670 80141268 00000000 */  nop
