.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.42.4 */

nonmatching HARCH30, 0xE

glabel HARCH30
    /* 795C 80141554 03020303 */  .word      0x03030203                    # sra        $zero, $v1, 8 # 03000000 <InstrIdType: CPU_SPECIAL>
    /* 7960 80141558 00050210 */  beq        $zero, $v0, .L8014295C
    /* 7964 8014155C 312E0028 */   slti      $zero, $zero, 0x2E31
    /* 7968 80141560 2D000000 */  daddu      $zero, $zero, $zero
