.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.42.4 */

nonmatching HARCH40, 0xE

glabel HARCH40
    /* 79FC 801415F4 03020103 */  .word      0x03010203                    # sra        $zero, $at, 8 # 03000000 <InstrIdType: CPU_SPECIAL>
    /* 7A00 801415F8 0009050E */  jal        func_88142400
    /* 7A04 801415FC 8C2E0028 */   slti      $zero, $zero, 0x2E8C
    /* 7A08 80141600 2D000000 */  daddu      $zero, $zero, $zero
