.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.42.4 */

nonmatching func_80139BF8, 0x4

glabel func_80139BF8
    /* 0 80139BF8 0B000000 */  movn       $zero, $zero, $zero
endlabel func_80139BF8
