.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.42.4 */

nonmatching func_800B031C, 0x4

glabel func_800B031C
    /* A031C 800B031C 05000000 */  .word      0x00000005                    # INVALID    $zero, $zero, 0x5 # 00000000 <InstrIdType: CPU_SPECIAL>
endlabel func_800B031C
