/* GLIBDEV/SOURCE/GAL.C — linked skeleton generated by tools/gen_skeleton.py from DIABPSX.SYM (70 functions).
 * Each function: SYM signature/registers, INCLUDE_ASM of the retail oracle (links byte-identical),
 * then the m2c and Hex-Rays drafts under #if 0.  Replace one INCLUDE_ASM at a time with C. */
#include "common.h"

/* ---- 0x800212D4  GAL_SetErrorChecking  GAL.C:175-176  seg lib  fsize 0 ---- */
/* void GAL_SetErrorChecking(unsigned char OnOff)
 *   OnOff=$a0
 */
/* linked from build/src/lib.c.o (segment lib mixes several source files) — INCLUDE_ASM("asm/nonmatchings/lib", GAL_SetErrorChecking) */
#if 0 /* m2c */
void GAL_SetErrorChecking(s8 arg0) {
    D_8011C9DC = arg0;
}
#endif
#if 0 /* ida */
void __fastcall GAL_SetErrorChecking(char a1)
{
  MEMORY[0x8011C9DC] = a1;
}
#endif

/* ---- 0x800212E4  GAL_SplitBlock  GAL.C:195-247  seg lib  fsize 40 ---- */
/* long GAL_SplitBlock(long CurBlock, unsigned long Size)
 *   CurBlock=$s0 Size=$s2 M=$s3 MemHdr=$s1 SplitBlock=$s0
 *   blocks: {1 }53
 */
/* linked from build/src/lib.c.o (segment lib mixes several source files) — INCLUDE_ASM("asm/nonmatchings/lib", GAL_SplitBlock) */
#if 0 /* m2c */
u16 GAL_SplitBlock(s32 arg0, M2C_UNK arg1) {
    M2C_UNK var_a0;
    u32 temp_v0_3;
    void *temp_s1;
    void *temp_v0;
    void *temp_v0_2;

    if (!(IsActiveValidHandle() & 0xFF)) {
        var_a0 = 5;
        goto block_7;
    }
    temp_s1 = (arg0 * 0x1C) + &D_801325D0;
    temp_v0_2 = GetMemInitInfoBlockFromType(M2C_FIELD(temp_s1, u16 *, 0x12));
    var_a0 = 4;
    if (temp_v0_2 != NULL) {
        temp_v0_3 = AlignSize(arg1, M2C_FIELD(temp_v0_2, u16 *, 0x10));
        if (temp_v0_3 < (u32) M2C_FIELD(temp_s1, u32 *, 0xC)) {
            temp_v0 = GetFreeMemHdrBlock();
            if (temp_v0 != NULL) {
                M2C_FIELD(temp_v0, s16 *, 0x14) = 1;
                M2C_FIELD(temp_v0, u16 *, 0x12) = (u16) M2C_FIELD(temp_s1, u16 *, 0x12);
                M2C_FIELD(temp_v0, s32 *, 8) = (s32) (temp_v0_3 + M2C_FIELD(temp_s1, s32 *, 8));
                M2C_FIELD(temp_v0, s32 *, 0xC) = (s32) (M2C_FIELD(temp_s1, u32 *, 0xC) - temp_v0_3);
                M2C_FIELD(temp_v0, u16 *, 0x10) = (u16) M2C_FIELD(temp_s1, u16 *, 0x10);
                SetBlockName(temp_v0, temp_s1 + 0x18);
                AttachHdrToList(temp_v0_2 + 0x24, temp_v0);
                M2C_FIELD(temp_s1, u32 *, 0xC) = temp_v0_3;
                return M2C_FIELD(temp_v0, u16 *, 0x16);
            }
            var_a0 = 1;
            goto block_7;
        }
        /* Duplicate return node #8. Try simplifying control flow for better match */
        return -1U;
    }
block_7:
    GSetError(var_a0);
    return -1U;
}
#endif
#if 0 /* ida */
int __fastcall GAL_SplitBlock(unsigned int a1, unsigned int a2)
{
  int v4; // $a0
  int v5; // $s1
  int v6; // $v0
  int v7; // $s3
  unsigned int v8; // $s2
  int result; // $v0
  int v10; // $s0
  __int16 v11; // $v1

  if ( IsActiveValidHandle(a1) )
  {
    v5 = 28 * a1 - 2146228784;
    v6 = GetMemInitInfoBlockFromType(*(unsigned __int16 *)(28 * a1 - 2146228766));
    v7 = v6;
    v4 = 4;
    if ( v6 != 0 )
    {
      v8 = AlignSize(a2, *(unsigned __int16 *)(v6 + 16));
      result = -1;
      if ( v8 >= *(_DWORD *)(28 * a1 - 2146228772) )
        return result;
      v10 = GetFreeMemHdrBlock();
      if ( v10 != 0 )
      {
        v11 = *(_WORD *)(v5 + 18);
        *(_WORD *)(v10 + 20) = 1;
        *(_WORD *)(v10 + 18) = v11;
        *(_DWORD *)(v10 + 8) = v8 + *(_DWORD *)(v5 + 8);
        *(_DWORD *)(v10 + 12) = *(_DWORD *)(v5 + 12) - v8;
        *(_WORD *)(v10 + 16) = *(_WORD *)(v5 + 16);
        SetBlockName(v10, (_BYTE *)(v5 + 24));
        AttachHdrToList((_DWORD **)(v7 + 36), (_DWORD *)v10);
        *(_DWORD *)(v5 + 12) = v8;
        return *(unsigned __int16 *)(v10 + 22);
      }
      v4 = 1;
    }
  }
  else
  {
    v4 = 5;
  }
  GSetError(v4);
  return -1;
}
#endif

/* ---- 0x80021404  GAL_InitModule  GAL.C:255-277  seg lib  fsize 32 ---- */
/* void GAL_InitModule(void)
 *   f=$s1
 *   blocks: {1 }23
 */
/* linked from build/src/lib.c.o (segment lib mixes several source files) — INCLUDE_ASM("asm/nonmatchings/lib", GAL_InitModule) */
#if 0 /* m2c */
void GAL_InitModule(void) {
    M2C_UNK *var_s2;
    s16 var_s1;
    s32 var_s0;

    D_8011C9CC = 0;
    D_8011C9D0 = 0;
    D_8011C9EC = 0;
    GAL_SetVerbosity(0);
    GAL_SetTimeStamp(0);
    D_8011C9D4 = 0;
    GAL_SetErrorChecking(0);
    var_s1 = 0;
    var_s2 = &D_801325D0;
    var_s0 = 0;
    do {
        *(&D_801325D0 + var_s0) = 0;
        *(&D_801325D4 + var_s0) = 0;
        *(&D_801325E6 + var_s0) = var_s1;
        ReleaseMemHdrBlock(var_s2);
        var_s2 += 0x1C;
        var_s1 += 1;
        var_s0 += 0x1C;
    } while (var_s1 < 0xC8);
}
#endif
#if 0 /* ida */
BOOL GAL_InitModule()
{
  int v0; // $s1
  int v1; // $s2
  int v2; // $s0
  BOOL result; // $v0

  MEMORY[0x8011C9CC] = 0;
  MEMORY[0x8011C9D0] = 0;
  MEMORY[0x8011C9EC] = 0;
  GAL_SetVerbosity(0);
  GAL_SetTimeStamp(0);
  MEMORY[0x8011C9D4] = 0;
  GAL_SetErrorChecking(0);
  v0 = 0;
  v1 = -2146228784;
  v2 = 0;
  do
  {
    *(_DWORD *)(v2 - 2146228784) = 0;
    *(_DWORD *)(v2 - 2146228780) = 0;
    *(_WORD *)(v2 - 2146228762) = v0;
    ReleaseMemHdrBlock((_DWORD *)v1);
    v1 += 28;
    result = ++v0 < 200;
    v2 += 28;
  }
  while ( v0 < 200 );
  return result;
}
#endif

/* ---- 0x800214BC  GAL_AddMemType  GAL.C:290-360  seg lib  fsize 32 ---- */
/* unsigned char GAL_AddMemType(struct MEM_INIT_INFO *M)
 *   M=$s0 P=$a0 FreeMemHdr=$s1 Addr1=$a1 Addr2=$v1
 *   blocks: {1 }71
 */
/* linked from build/src/lib.c.o (segment lib mixes several source files) — INCLUDE_ASM("asm/nonmatchings/lib", GAL_AddMemType) */
#if 0 /* m2c */
s32 GAL_AddMemType(void *arg0, u32 arg1) {
    M2C_UNK var_a0_2;
    s32 temp_v0_3;
    u32 temp_v1;
    u32 var_a1;
    void *temp_v0;
    void *temp_v0_2;
    void *var_a0;

    var_a1 = arg1;
    var_a0 = D_8011C9CC;
    if (var_a0 != NULL) {
        var_a1 = M2C_FIELD(arg0, u32 *, 0);
loop_2:
        temp_v1 = M2C_FIELD(var_a0, u32 *, 0);
        if ((var_a1 >= (u32) (temp_v1 + M2C_FIELD(var_a0, s32 *, 4))) || ((u32) (var_a1 + M2C_FIELD(arg0, s32 *, 4)) < temp_v1)) {
            if (M2C_FIELD(var_a0, s32 *, 8) != M2C_FIELD(arg0, s32 *, 8)) {
                var_a0 = M2C_FIELD(var_a0, void **, 0x18);
                if (var_a0 == NULL) {
                    goto block_6;
                }
                goto loop_2;
            }
            return 2;
        }
        var_a0_2 = 3;
        goto block_11;
    }
block_6:
    temp_v0 = D_8011C9CC;
    D_8011C9CC = arg0;
    M2C_FIELD(arg0, s16 *, 0x1C) = 0;
    M2C_FIELD(arg0, s32 *, 0x24) = 0;
    M2C_FIELD(arg0, s32 *, 0x20) = 0;
    M2C_FIELD(arg0, void **, 0x18) = temp_v0;
    temp_v0_2 = GetFreeMemHdrBlock(var_a0, var_a1);
    if (temp_v0_2 != NULL) {
        AttachHdrToList(arg0 + 0x20, temp_v0_2);
        temp_v0_3 = AlignPtr(M2C_FIELD(arg0, u32 *, 0), M2C_FIELD(arg0, u16 *, 0x10));
        M2C_FIELD(temp_v0_2, s32 *, 8) = temp_v0_3;
        M2C_FIELD(temp_v0_2, s32 *, 0xC) = (s32) (M2C_FIELD(arg0, s32 *, 4) - (temp_v0_3 - M2C_FIELD(arg0, u32 *, 0)));
        return 1;
    }
    var_a0_2 = 1;
block_11:
    GSetError(var_a0_2);
    return 0;
}
#endif
#if 0 /* ida */
int __fastcall GAL_AddMemType(int a1)
{
  _DWORD *v2; // $a0
  unsigned int v3; // $a1
  int v4; // $v0
  _DWORD *v5; // $v0
  _DWORD *v6; // $s1
  unsigned int v7; // $a1
  int v9; // $a0

  v2 = (_DWORD *)MEMORY[0x8011C9CC];
  if ( MEMORY[0x8011C9CC] != 0 )
  {
    v3 = *(_DWORD *)a1;
    while ( 1 )
    {
      if ( v3 < *v2 + v2[1] && v3 + *(_DWORD *)(a1 + 4) >= *v2 )
      {
        v9 = 3;
        goto LABEL_12;
      }
      if ( v2[2] == *(_DWORD *)(a1 + 8) )
        return 2;
      v2 = (_DWORD *)v2[6];
      if ( v2 == nullptr )
        goto LABEL_7;
    }
  }
  else
  {
LABEL_7:
    v4 = MEMORY[0x8011C9CC];
    MEMORY[0x8011C9CC] = a1;
    *(_WORD *)(a1 + 28) = 0;
    *(_DWORD *)(a1 + 36) = 0;
    *(_DWORD *)(a1 + 32) = 0;
    *(_DWORD *)(a1 + 24) = v4;
    v5 = (_DWORD *)GetFreeMemHdrBlock();
    v6 = v5;
    if ( v5 != nullptr )
    {
      AttachHdrToList((_DWORD **)(a1 + 32), v5);
      v7 = AlignPtr(*(_DWORD *)a1, *(unsigned __int16 *)(a1 + 16));
      v6[2] = v7;
      v6[3] = *(_DWORD *)(a1 + 4) - (v7 - *(_DWORD *)a1);
      return 1;
    }
    else
    {
      v9 = 1;
LABEL_12:
      GSetError(v9);
      return 0;
    }
  }
}
#endif

/* ---- 0x800215DC  GAL_Alloc  GAL.C:375-452  seg lib  fsize 64 ---- */
/* long GAL_Alloc(unsigned long Size, unsigned long Type, char *Name)
 *   Size=$s5 Type=$s1 Name=$s6 Block=$s0 M=$s2 FullSize=$s3 FRoute=$s4 High=$s7
 *   blocks: {1 {68 }75 }78
 */
/* linked from build/src/lib.c.o (segment lib mixes several source files) — INCLUDE_ASM("asm/nonmatchings/lib", GAL_Alloc) */
#if 0 /* m2c */
s32 GAL_Alloc(s32 arg0, u32 arg1, s32 arg2) {
    s32 temp_s1;
    s32 temp_s7;
    s32 var_a2;
    s32 var_v0;
    u32 temp_s3;
    void *(*var_s4)(s32, u32);
    void *temp_v0;
    void *var_a0;
    void *var_s0;

    temp_s7 = (arg1 >> 0xF) & 1;
    temp_s1 = arg1 & 0xFFFF7FFF;
    var_s4 = FindLowestMemBlock;
    if (temp_s7 & 0xFF) {
        var_s4 = FindHighestMemBlock;
    }
    D_8011C9E0 = arg0;
    D_8011C9F0 = temp_s1;
    temp_v0 = GetMemInitInfoBlockFromType(temp_s1);
    if (temp_v0 == NULL) {
        GSetError(4);
        goto block_4;
    }
    temp_s3 = AlignSize(arg0, M2C_FIELD(temp_v0, u16 *, 0x10));
    if (D_8011C9F4 != NULL) {
        D_8011C9F4(temp_s1, temp_s3, arg2);
    }
    var_s0 = var_s4(M2C_FIELD(temp_v0, s32 *, 0x20), temp_s3);
    var_a0 = temp_v0 + 0x20;
    if (var_s0 == NULL) {
        var_v0 = -1;
        if (GAL_GetFreeMem(temp_s1) >= temp_s3) {
            var_v0 = -1;
            if (GAL_DefragMem(temp_s1) & 0xFF) {
                var_s0 = var_s4(M2C_FIELD(temp_v0, s32 *, 0x20), temp_s3);
                var_a0 = temp_v0 + 0x20;
                if (var_s0 != NULL) {
                    goto block_11;
                }
block_4:
                return -1;
            }
        }
        /* Duplicate return node #15. Try simplifying control flow for better match */
        return var_v0;
    }
block_11:
    DetachHdrFromList(var_a0, var_s0);
    if (!(temp_s7 & 0xFF)) {
        var_a2 = M2C_FIELD(var_s0, s32 *, 8);
    } else {
        var_a2 = (M2C_FIELD(var_s0, s32 *, 8) + M2C_FIELD(var_s0, s32 *, 0xC)) - temp_s3;
    }
    var_v0 = LoAlloc(temp_v0, var_s0, var_a2, arg0);
    return var_v0;
}
#endif
#if 0 /* ida */
int __fastcall GAL_Alloc(unsigned int a1, int a2, _BYTE *a3)
{
  bool v5; // $s7
  unsigned int v6; // $s1
  _DWORD *(__fastcall *v7)(_DWORD *, unsigned int); // $s4
  int v8; // $v0
  int v9; // $s2
  int result; // $v0
  int v11; // $v0
  unsigned int v12; // $s3
  _DWORD *v13; // $s0
  _DWORD *v14; // $a0
  bool v15; // dc

  v5 = (a2 & 0x8000) != 0;
  v6 = a2 & 0xFFFF7FFF;
  v7 = FindLowestMemBlock;
  if ( (a2 & 0x8000) != 0 )
    v7 = FindHighestMemBlock;
  MEMORY[0x8011C9E0] = a1;
  MEMORY[0x8011C9F0] = a2 & 0xFFFF7FFF;
  v8 = GetMemInitInfoBlockFromType(a2 & 0xFFFF7FFF);
  v9 = v8;
  if ( v8 == 0 )
  {
    GSetError(4);
    return -1;
  }
  v11 = AlignSize(a1, *(unsigned __int16 *)(v8 + 16));
  v12 = v11;
  if ( MEMORY[0x8011C9F4] != nullptr )
    MEMORY[0x8011C9F4](v6, v11, a3);
  v13 = v7(*(_DWORD **)(v9 + 32), v12);
  v14 = (_DWORD *)(v9 + 32);
  if ( v13 != nullptr )
    goto LABEL_12;
  v15 = GAL_GetFreeMem(v6) < v12;
  result = -1;
  if ( !v15 )
  {
    v15 = (unsigned __int8)GAL_DefragMem(v6) == 0;
    result = -1;
    if ( !v15 )
    {
      v13 = v7(*(_DWORD **)(v9 + 32), v12);
      v14 = (_DWORD *)(v9 + 32);
      if ( v13 == nullptr )
        return -1;
LABEL_12:
      DetachHdrFromList(v14, v13);
      if ( v5 )
        return LoAlloc(v9, (int)v13, v13[2] + v13[3] - v12, a1, a3);
      else
        return LoAlloc(v9, (int)v13, v13[2], a1, a3);
    }
  }
  return result;
}
#endif

/* ---- 0x80021774  GAL_Lock  GAL.C:466-488  seg lib  fsize 24 ---- */
/* void * GAL_Lock(long Handle)
 *   Handle=$s0 MemHdr=$v1
 *   blocks: {1 }23
 */
/* linked from build/src/lib.c.o (segment lib mixes several source files) — INCLUDE_ASM("asm/nonmatchings/lib", GAL_Lock) */
#if 0 /* m2c */
s32 GAL_Lock(s32 arg0) {
    void *temp_v1;

    if (IsActiveValidHandle() & 0xFF) {
        temp_v1 = (arg0 * 0x1C) + &D_801325D0;
        M2C_FIELD(temp_v1, u16 *, 0x14) = (u16) (M2C_FIELD(temp_v1, u16 *, 0x14) + 1);
        return M2C_FIELD(temp_v1, s32 *, 8);
    }
    GSetError(5);
    return 0;
}
#endif
#if 0 /* ida */
int __fastcall GAL_Lock(unsigned int a1)
{
  int result; // $v0

  if ( IsActiveValidHandle(a1) )
  {
    result = *(_DWORD *)(28 * a1 - 2146228776);
    ++*(_WORD *)(28 * a1 - 2146228764);
  }
  else
  {
    GSetError(5);
    return 0;
  }
  return result;
}
#endif

/* ---- 0x800217DC  GAL_Unlock  GAL.C:501-532  seg lib  fsize 24 ---- */
/* unsigned char GAL_Unlock(long Handle)
 *   Handle=$s0 MemHdr=$a0
 *   blocks: {1 }32
 */
/* linked from build/src/lib.c.o (segment lib mixes several source files) — INCLUDE_ASM("asm/nonmatchings/lib", GAL_Unlock) */
#if 0 /* m2c */
s32 GAL_Unlock(s32 arg0) {
    M2C_UNK var_a0;
    void *temp_a0;

    if (!(IsActiveValidHandle() & 0xFF)) {
        var_a0 = 5;
        goto block_5;
    }
    temp_a0 = (arg0 * 0x1C) + &D_801325D0;
    if (M2C_FIELD(temp_a0, u16 *, 0x14) != 0) {
        M2C_FIELD(temp_a0, u16 *, 0x14) = (u16) (M2C_FIELD(temp_a0, u16 *, 0x14) - 1);
        return 1;
    }
    var_a0 = 6;
block_5:
    GSetError(var_a0);
    return 0;
}
#endif
#if 0 /* ida */
int __fastcall GAL_Unlock(unsigned int a1)
{
  int v2; // $a0
  int result; // $v0

  if ( IsActiveValidHandle(a1) )
  {
    result = 1;
    if ( *(_WORD *)(28 * a1 - 2146228764) != 0 )
    {
      --*(_WORD *)(28 * a1 - 2146228764);
      return result;
    }
    v2 = 6;
  }
  else
  {
    v2 = 5;
  }
  GSetError(v2);
  return 0;
}
#endif

/* ---- 0x80021860  GAL_Free  GAL.C:544-583  seg lib  fsize 32 ---- */
/* unsigned char GAL_Free(long Handle)
 *   Handle=$s0 M=$s0 MemHdr=$s1
 *   blocks: {1 }40
 */
/* linked from build/src/lib.c.o (segment lib mixes several source files) — INCLUDE_ASM("asm/nonmatchings/lib", GAL_Free) */
#if 0 /* m2c */
s32 GAL_Free(s32 arg0) {
    M2C_UNK var_a0;
    s32 temp_v0;
    void *temp_s1;

    if (!(IsActiveValidHandle() & 0xFF)) {
        var_a0 = 5;
        goto block_5;
    }
    temp_s1 = (arg0 * 0x1C) + &D_801325D0;
    temp_v0 = GetMemInitInfoBlockFromType(M2C_FIELD(temp_s1, u16 *, 0x12));
    if (temp_v0 != 0) {
        D_8011C9E4 = M2C_FIELD(temp_s1, s32 *, 0xC);
        DetachHdrFromList(temp_v0 + 0x24, temp_s1);
        MergeToEmptyList(temp_v0, temp_s1);
        return 1;
    }
    var_a0 = 4;
block_5:
    GSetError(var_a0);
    return 0;
}
#endif
#if 0 /* ida */
int __fastcall GAL_Free(unsigned int a1)
{
  int v2; // $a0
  _DWORD *v3; // $s1
  int v4; // $s0

  if ( IsActiveValidHandle(a1) )
  {
    v3 = (_DWORD *)(28 * a1 - 2146228784);
    v4 = GetMemInitInfoBlockFromType(*(unsigned __int16 *)(28 * a1 - 2146228766));
    if ( v4 != 0 )
    {
      MEMORY[0x8011C9E4] = v3[3];
      DetachHdrFromList((_DWORD *)(v4 + 36), v3);
      MergeToEmptyList(v4, v3);
      return 1;
    }
    v2 = 4;
  }
  else
  {
    v2 = 5;
  }
  GSetError(v2);
  return 0;
}
#endif

/* ---- 0x80021908  GAL_GetFreeMem  GAL.C:596-620  seg lib  fsize 24 ---- */
/* unsigned long GAL_GetFreeMem(unsigned long Type)
 *   Type=$a0 FreeMem=$s0 M=$v0 Block=$v1
 *   blocks: {1 {11 }20 }25
 */
/* linked from build/src/lib.c.o (segment lib mixes several source files) — INCLUDE_ASM("asm/nonmatchings/lib", GAL_GetFreeMem) */
#if 0 /* m2c */
s32 GAL_GetFreeMem(s32 arg0) {
    s32 temp_v0_2;
    s32 var_s0;
    void *temp_v0;
    void *var_v1;

    var_s0 = 0;
    temp_v0 = GetMemInitInfoBlockFromType(arg0 & 0xFFFF7FFF);
    if (temp_v0 != NULL) {
        var_v1 = M2C_FIELD(temp_v0, void **, 0x20);
        if (var_v1 != NULL) {
            do {
                temp_v0_2 = M2C_FIELD(var_v1, s32 *, 0xC);
                var_v1 = M2C_FIELD(var_v1, void **, 4);
                var_s0 += temp_v0_2;
            } while (var_v1 != NULL);
            return var_s0;
        }
        /* Duplicate return node #5. Try simplifying control flow for better match */
        return 0;
    }
    GSetError(4);
    return 0;
}
#endif
#if 0 /* ida */
int __fastcall GAL_GetFreeMem(int a1)
{
  int v1; // $s0
  int v2; // $v0
  int v3; // $v1
  int result; // $v0
  int v5; // $v0

  v1 = 0;
  v2 = GetMemInitInfoBlockFromType(a1 & 0xFFFF7FFF);
  if ( v2 != 0 )
  {
    v3 = *(_DWORD *)(v2 + 32);
    result = 0;
    if ( v3 != 0 )
    {
      do
      {
        v5 = *(_DWORD *)(v3 + 12);
        v3 = *(_DWORD *)(v3 + 4);
        v1 += v5;
      }
      while ( v3 != 0 );
      return v1;
    }
  }
  else
  {
    GSetError(4);
    return 0;
  }
  return result;
}
#endif

/* ---- 0x8002197C  GAL_GetUsedMem  GAL.C:634-658  seg lib  fsize 24 ---- */
/* unsigned long GAL_GetUsedMem(unsigned long Type)
 *   Type=$a0 FreeMem=$s0 M=$v0 Block=$v1
 *   blocks: {1 {11 }20 }25
 */
/* linked from build/src/lib.c.o (segment lib mixes several source files) — INCLUDE_ASM("asm/nonmatchings/lib", GAL_GetUsedMem) */
#if 0 /* m2c */
s32 GAL_GetUsedMem(s32 arg0) {
    s32 temp_v0_2;
    s32 var_s0;
    void *temp_v0;
    void *var_v1;

    var_s0 = 0;
    temp_v0 = GetMemInitInfoBlockFromType(arg0 & 0xFFFF7FFF);
    if (temp_v0 != NULL) {
        var_v1 = M2C_FIELD(temp_v0, void **, 0x24);
        if (var_v1 != NULL) {
            do {
                temp_v0_2 = M2C_FIELD(var_v1, s32 *, 0xC);
                var_v1 = M2C_FIELD(var_v1, void **, 4);
                var_s0 += temp_v0_2;
            } while (var_v1 != NULL);
            return var_s0;
        }
        /* Duplicate return node #5. Try simplifying control flow for better match */
        return 0;
    }
    GSetError(4);
    return 0;
}
#endif
#if 0 /* ida */
int __fastcall GAL_GetUsedMem(int a1)
{
  int v1; // $s0
  int v2; // $v0
  int v3; // $v1
  int result; // $v0
  int v5; // $v0

  v1 = 0;
  v2 = GetMemInitInfoBlockFromType(a1 & 0xFFFF7FFF);
  if ( v2 != 0 )
  {
    v3 = *(_DWORD *)(v2 + 36);
    result = 0;
    if ( v3 != 0 )
    {
      do
      {
        v5 = *(_DWORD *)(v3 + 12);
        v3 = *(_DWORD *)(v3 + 4);
        v1 += v5;
      }
      while ( v3 != 0 );
      return v1;
    }
  }
  else
  {
    GSetError(4);
    return 0;
  }
  return result;
}
#endif

/* ---- 0x800219F0  GAL_LargestFreeBlock  GAL.C:673-699  seg lib  fsize 24 ---- */
/* unsigned long GAL_LargestFreeBlock(unsigned long Type)
 *   Type=$a0 Largest=$a1 Index=$v1 MI=$v0
 *   blocks: {1 }27
 */
/* linked from build/src/lib.c.o (segment lib mixes several source files) — INCLUDE_ASM("asm/nonmatchings/lib", GAL_LargestFreeBlock) */
#if 0 /* m2c */
u32 GAL_LargestFreeBlock(s32 arg0) {
    u32 temp_a0;
    u32 var_a1;
    void *temp_v0;
    void *var_v1;

    temp_v0 = GetMemInitInfoBlockFromType(arg0 & 0xFFFF7FFF);
    if (temp_v0 == NULL) {
        GSetError(4);
        return 0U;
    }
    var_v1 = M2C_FIELD(temp_v0, void **, 0x20);
    var_a1 = 0;
    if (var_v1 != NULL) {
        do {
            temp_a0 = M2C_FIELD(var_v1, u32 *, 0xC);
            if (var_a1 < temp_a0) {
                var_a1 = temp_a0;
            }
            var_v1 = M2C_FIELD(var_v1, void **, 4);
        } while (var_v1 != NULL);
    }
    return var_a1;
}
#endif
#if 0 /* ida */
unsigned int __fastcall GAL_LargestFreeBlock(int a1)
{
  int v1; // $v0
  int v3; // $v1
  unsigned int i; // $a1

  v1 = GetMemInitInfoBlockFromType(a1 & 0xFFFF7FFF);
  if ( v1 != 0 )
  {
    v3 = *(_DWORD *)(v1 + 32);
    for ( i = 0; v3 != 0; v3 = *(_DWORD *)(v3 + 4) )
    {
      if ( i < *(_DWORD *)(v3 + 12) )
        i = *(_DWORD *)(v3 + 12);
    }
    return i;
  }
  else
  {
    GSetError(4);
    return 0;
  }
}
#endif

/* ---- 0x80021A6C  AttachHdrToList  GAL.C:711-717  seg lib  fsize 0 ---- */
/* void AttachHdrToList(struct MEM_HDR **Head, struct MEM_HDR *Block)
 *   Head=$a0 Block=$a1
 */
/* linked from build/src/lib.c.o (segment lib mixes several source files) — INCLUDE_ASM("asm/nonmatchings/lib", AttachHdrToList) */
#if 0 /* m2c */
void AttachHdrToList(M2C_UNK **arg0, M2C_UNK *arg1) {
    M2C_UNK *temp_v0;

    M2C_FIELD(arg1, M2C_UNK **, 0) = NULL;
    temp_v0 = *arg0;
    M2C_FIELD(arg1, M2C_UNK **, 4) = temp_v0;
    if (temp_v0 != NULL) {
        *temp_v0 = arg1;
    }
    *arg0 = arg1;
}
#endif
#if 0 /* ida */
_DWORD *__fastcall AttachHdrToList(_DWORD **a1, _DWORD *a2)
{
  _DWORD *result; // $v0
  bool v3; // dc

  *a2 = 0;
  result = *a1;
  v3 = *a1 == nullptr;
  a2[1] = *a1;
  if ( !v3 )
    *result = a2;
  *a1 = a2;
  return result;
}
#endif

/* ---- 0x80021A8C  DetachHdrFromList  GAL.C:731-738  seg lib  fsize 0 ---- */
/* void DetachHdrFromList(struct MEM_HDR **Head, struct MEM_HDR *Block)
 *   Head=$a0 Block=$a1
 */
/* linked from build/src/lib.c.o (segment lib mixes several source files) — INCLUDE_ASM("asm/nonmatchings/lib", DetachHdrFromList) */
#if 0 /* m2c */
void DetachHdrFromList(void ***arg0, void *arg1) {
    void **temp_v1_2;
    void *temp_v1;

    temp_v1 = M2C_FIELD(arg1, void **, 0);
    if (temp_v1 != NULL) {
        M2C_FIELD(temp_v1, void ***, 4) = (void **) M2C_FIELD(arg1, void ***, 4);
    } else {
        *arg0 = M2C_FIELD(arg1, void ***, 4);
    }
    temp_v1_2 = M2C_FIELD(arg1, void ***, 4);
    if (temp_v1_2 != NULL) {
        *temp_v1_2 = M2C_FIELD(arg1, void **, 0);
    }
}
#endif
#if 0 /* ida */
int __fastcall DetachHdrFromList(_DWORD *a1, _DWORD *a2)
{
  int result; // $v0
  _DWORD *v3; // $v1

  result = a2[1];
  if ( *a2 != 0 )
    *(_DWORD *)(*a2 + 4) = result;
  else
    *a1 = result;
  v3 = (_DWORD *)a2[1];
  if ( v3 != nullptr )
  {
    result = *a2;
    *v3 = *a2;
  }
  return result;
}
#endif

/* ---- 0x80021AD8  IsActiveValidHandle  GAL.C:753-766  seg lib  fsize 0 ---- */
/* unsigned char IsActiveValidHandle(long Handle)
 *   Handle=$a0
 *   blocks: {2 }14
 */
/* linked from build/src/lib.c.o (segment lib mixes several source files) — INCLUDE_ASM("asm/nonmatchings/lib", IsActiveValidHandle) */
#if 0 /* m2c */
s32 IsActiveValidHandle(u32 arg0) {
    if (arg0 >= 0xC8U) {
        return 0;
    }
    return *(&D_801325D8 + (arg0 * 0x1C)) != 0;
}
#endif
#if 0 /* ida */
BOOL __fastcall IsActiveValidHandle(unsigned int a1)
{
  return a1 < 0xC8 && *(_DWORD *)(28 * a1 - 2146228776) != 0;
}
#endif

/* ---- 0x80021B10  AlignPtr  GAL.C:780-790  seg lib  fsize 0 ---- */
/* void * AlignPtr(void *P, unsigned long Align)
 *   P=$a0 Align=$a1 Addr=$a0 Temp=$v0
 *   blocks: {2 }11
 */
/* linked from build/src/lib.c.o (segment lib mixes several source files) — INCLUDE_ASM("asm/nonmatchings/lib", AlignPtr) */
#if 0 /* m2c */
u32 AlignPtr(u32 arg0, u32 arg1) {
    s32 temp_v0;
    u32 var_a0;

    var_a0 = arg0;
    temp_v0 = arg1 - (var_a0 % arg1);
    if (temp_v0 != arg1) {
        var_a0 += temp_v0;
    }
    return var_a0;
}
#endif
#if 0 /* ida */
unsigned int __fastcall AlignPtr(unsigned int a1, unsigned int a2)
{
  if ( a2 - a1 % a2 != a2 )
    a1 += a2 - a1 % a2;
  return a1;
}
#endif

/* ---- 0x80021B40  AlignSize  GAL.C:803-804  seg lib  fsize 0 ---- */
/* unsigned long AlignSize(unsigned long Size, unsigned long Align)
 *   Size=$a0 Align=$a1
 */
/* linked from build/src/lib.c.o (segment lib mixes several source files) — INCLUDE_ASM("asm/nonmatchings/lib", AlignSize) */
#if 0 /* m2c */
u32 AlignSize(u32 arg0, u32 arg1) {
    u32 temp_hi;
    u32 var_v0;

    temp_hi = arg0 % arg1;
    var_v0 = arg0;
    if (temp_hi != 0) {
        var_v0 = arg0 + (arg1 - temp_hi);
    }
    return var_v0;
}
#endif
#if 0 /* ida */
int __fastcall AlignSize(unsigned int a1, unsigned int a2)
{
  int result; // $v0

  result = a1;
  if ( a1 % a2 != 0 )
    return a1 + a2 - a1 % a2;
  return result;
}
#endif

/* ---- 0x80021B70  FindClosestSizedBlock  GAL.C:818-843  seg lib  fsize 0 ---- */
/* struct MEM_HDR * FindClosestSizedBlock(struct MEM_HDR *Head, unsigned long Size)
 *   Head=$a0 Size=$a1 Closest=$a2 Index=$a0
 *   blocks: {2 }26
 */
/* linked from build/src/lib.c.o (segment lib mixes several source files) — INCLUDE_ASM("asm/nonmatchings/lib", FindClosestSizedBlock) */
#if 0 /* m2c */
void *FindClosestSizedBlock(void *arg0, u32 arg1) {
    u32 temp_v1;
    void *var_a0;
    void *var_a2;

    var_a0 = arg0;
    var_a2 = NULL;
    if (var_a0 != NULL) {
        do {
            temp_v1 = M2C_FIELD(var_a0, u32 *, 0xC);
            if ((temp_v1 >= arg1) && ((var_a2 == NULL) || ((u32) (temp_v1 - arg1) < (u32) (M2C_FIELD(var_a2, s32 *, 0xC) - arg1)))) {
                var_a2 = var_a0;
            }
            var_a0 = M2C_FIELD(var_a0, void **, 4);
        } while (var_a0 != NULL);
    }
    return var_a2;
}
#endif

/* ---- 0x80021BC8  FindHighestMemBlock  GAL.C:855-888  seg lib  fsize 0 ---- */
/* struct MEM_HDR * FindHighestMemBlock(struct MEM_HDR *Head, unsigned long Size)
 *   Head=$a0 Size=$a1 Closest=$a2 Index=$a0 Highest=$a3
 *   blocks: {2 }34
 */
/* linked from build/src/lib.c.o (segment lib mixes several source files) — INCLUDE_ASM("asm/nonmatchings/lib", FindHighestMemBlock) */
#if 0 /* m2c */
void *FindHighestMemBlock(void *arg0, u32 arg1) {
    u32 temp_v1;
    u32 var_a3;
    void *var_a0;
    void *var_a2;

    var_a0 = arg0;
    var_a2 = NULL;
    var_a3 = 0;
    if (var_a0 != NULL) {
        do {
            if ((u32) M2C_FIELD(var_a0, u32 *, 0xC) >= arg1) {
                if (var_a2 != NULL) {
                    temp_v1 = M2C_FIELD(var_a0, u32 *, 8);
                    if (var_a3 < temp_v1) {
                        var_a2 = var_a0;
                        var_a3 = temp_v1;
                    }
                } else {
                    var_a2 = var_a0;
                    var_a3 = M2C_FIELD(var_a0, u32 *, 8);
                }
            }
            var_a0 = M2C_FIELD(var_a0, void **, 4);
        } while (var_a0 != NULL);
    }
    return var_a2;
}
#endif
#if 0 /* ida */
_DWORD *__fastcall FindHighestMemBlock(_DWORD *a1, unsigned int a2)
{
  _DWORD *v2; // $a2
  unsigned int i; // $a3

  v2 = nullptr;
  for ( i = 0; a1 != nullptr; a1 = (_DWORD *)a1[1] )
  {
    if ( a1[3] >= a2 )
    {
      if ( v2 != nullptr )
      {
        if ( i < a1[2] )
        {
          v2 = a1;
          i = a1[2];
        }
      }
      else
      {
        v2 = a1;
        i = a1[2];
      }
    }
  }
  return v2;
}
#endif

/* ---- 0x80021C30  FindLowestMemBlock  GAL.C:899-934  seg lib  fsize 0 ---- */
/* struct MEM_HDR * FindLowestMemBlock(struct MEM_HDR *Head, unsigned long Size)
 *   Head=$a0 Size=$a1 Closest=$a2 Index=$a0 Lowest=$a3
 *   blocks: {2 }36
 */
/* linked from build/src/lib.c.o (segment lib mixes several source files) — INCLUDE_ASM("asm/nonmatchings/lib", FindLowestMemBlock) */
#if 0 /* m2c */
void *FindLowestMemBlock(void *arg0, u32 arg1) {
    u32 temp_v1;
    u32 var_a3;
    void *var_a0;
    void *var_a2;

    var_a0 = arg0;
    var_a2 = NULL;
    var_a3 = -1U;
    if (var_a0 != NULL) {
        do {
            if ((u32) M2C_FIELD(var_a0, u32 *, 0xC) >= arg1) {
                if (var_a2 != NULL) {
                    temp_v1 = M2C_FIELD(var_a0, u32 *, 8);
                    if (temp_v1 < var_a3) {
                        var_a2 = var_a0;
                        var_a3 = temp_v1;
                    }
                } else {
                    var_a2 = var_a0;
                    var_a3 = M2C_FIELD(var_a0, u32 *, 8);
                }
            }
            var_a0 = M2C_FIELD(var_a0, void **, 4);
        } while (var_a0 != NULL);
    }
    return var_a2;
}
#endif
#if 0 /* ida */
_DWORD *__fastcall FindLowestMemBlock(_DWORD *a1, unsigned int a2)
{
  _DWORD *v2; // $a2
  unsigned int i; // $a3

  v2 = nullptr;
  for ( i = -1; a1 != nullptr; a1 = (_DWORD *)a1[1] )
  {
    if ( a1[3] >= a2 )
    {
      if ( v2 != nullptr )
      {
        if ( a1[2] < i )
        {
          v2 = a1;
          i = a1[2];
        }
      }
      else
      {
        v2 = a1;
        i = a1[2];
      }
    }
  }
  return v2;
}
#endif

/* ---- 0x80021C98  GetMemInitInfoBlockFromType  GAL.C:946-967  seg lib  fsize 0 ---- */
/* struct MEM_INIT_INFO * GetMemInitInfoBlockFromType(unsigned long Type)
 *   Type=$a0 P=$v1
 *   blocks: {2 }22
 */
/* linked from build/src/lib.c.o (segment lib mixes several source files) — INCLUDE_ASM("asm/nonmatchings/lib", GetMemInitInfoBlockFromType) */
#if 0 /* m2c */
void *GetMemInitInfoBlockFromType(s32 arg0) {
    void *var_v0;
    void *var_v1;

    var_v1 = D_8011C9CC;
    var_v0 = NULL;
    if (var_v1 != NULL) {
loop_1:
        var_v0 = var_v1;
        if (M2C_FIELD(var_v1, s32 *, 8) != arg0) {
            var_v1 = M2C_FIELD(var_v1, void **, 0x18);
            var_v0 = NULL;
            if (var_v1 != NULL) {
                goto loop_1;
            }
        }
    }
    return var_v0;
}
#endif
#if 0 /* ida */
int __fastcall GetMemInitInfoBlockFromType(int a1)
{
  int v1; // $v1
  int result; // $v0

  v1 = MEMORY[0x8011C9CC];
  for ( result = 0; v1 != 0; result = 0 )
  {
    result = v1;
    if ( *(_DWORD *)(v1 + 8) == a1 )
      break;
    v1 = *(_DWORD *)(v1 + 24);
  }
  return result;
}
#endif

/* ---- 0x80021CD4  MergeToEmptyList  GAL.C:980-1033  seg lib  fsize 48 ---- */
/* void MergeToEmptyList(struct MEM_INIT_INFO *MI, struct MEM_HDR *M)
 *   MI=$s4 M=$s1 Index=$s0 NextIndex=$s2 Start=$s3 End=$s5 ThisStart=$v0 ThisEnd=$a0
 *   blocks: {1 {21 }50 }54
 */
/* linked from build/src/lib.c.o (segment lib mixes several source files) — INCLUDE_ASM("asm/nonmatchings/lib", MergeToEmptyList) */
#if 0 /* m2c */
void MergeToEmptyList(void *arg0, void *arg1) {
    s32 temp_a0;
    s32 temp_s3;
    s32 temp_s5;
    s32 temp_v0;
    s32 temp_v1;
    void *temp_s2;
    void *var_s0;

    temp_s3 = M2C_FIELD(arg1, s32 *, 8);
    var_s0 = M2C_FIELD(arg0, void **, 0x20);
    temp_s5 = temp_s3 + M2C_FIELD(arg1, s32 *, 0xC);
    if (var_s0 != NULL) {
        do {
            temp_v0 = M2C_FIELD(var_s0, s32 *, 8);
            temp_v1 = M2C_FIELD(var_s0, s32 *, 0xC);
            temp_s2 = M2C_FIELD(var_s0, void **, 4);
            temp_a0 = temp_v0 + temp_v1;
            if ((temp_s3 == temp_a0) || (temp_s5 == temp_v0)) {
                M2C_FIELD(arg1, s32 *, 0xC) = (s32) (M2C_FIELD(arg1, s32 *, 0xC) + temp_v1);
                if (temp_s3 == temp_a0) {
                    M2C_FIELD(arg1, s32 *, 8) = (s32) M2C_FIELD(var_s0, s32 *, 8);
                }
                DetachHdrFromList(arg0 + 0x20, var_s0);
                ReleaseMemHdrBlock(var_s0);
            }
            var_s0 = temp_s2;
        } while (var_s0 != NULL);
    }
    AttachHdrToList(arg0 + 0x20, arg1);
}
#endif
#if 0 /* ida */
_DWORD *__fastcall MergeToEmptyList(int a1, _DWORD *a2)
{
  int v4; // $s3
  _DWORD *v5; // $s0
  int v6; // $s5
  int v7; // $v0
  int v8; // $v1
  _DWORD *v9; // $s2

  v4 = a2[2];
  v5 = *(_DWORD **)(a1 + 32);
  v6 = v4 + a2[3];
  if ( v5 != nullptr )
  {
    do
    {
      v7 = v5[2];
      v8 = v5[3];
      v9 = (_DWORD *)v5[1];
      if ( v4 == v7 + v8 || v6 == v7 )
      {
        a2[3] += v8;
        if ( v4 == v7 + v8 )
          a2[2] = v5[2];
        DetachHdrFromList((_DWORD *)(a1 + 32), v5);
        ReleaseMemHdrBlock(v5);
      }
      v5 = v9;
    }
    while ( v9 != nullptr );
  }
  return AttachHdrToList((_DWORD **)(a1 + 32), a2);
}
#endif

/* ---- 0x80021DA8  GAL_AllocAt  GAL.C:1055-1085  seg lib  fsize 48 ---- */
/* long GAL_AllocAt(unsigned long Size, void *Addr, unsigned long Type, char *Name)
 *   Size=$s3 Addr=$s2 Type=$a2 Name=$s4 Block=$s0 M=$s1
 *   blocks: {1 }31
 */
/* linked from build/src/lib.c.o (segment lib mixes several source files) — INCLUDE_ASM("asm/nonmatchings/lib", GAL_AllocAt) */
#if 0 /* m2c */
s32 GAL_AllocAt(s32 arg0, M2C_UNK arg1, s32 arg2, s32 arg3) {
    s32 temp_s2;
    s32 temp_v0_2;
    void *temp_v0;

    temp_v0 = GetMemInitInfoBlockFromType(arg2 & 0xFFFF7FFF);
    if (temp_v0 == NULL) {
        GSetError(4);
        return -1;
    }
    temp_s2 = AlignPtr(arg1, M2C_FIELD(temp_v0, u16 *, 0x10));
    temp_v0_2 = FindBlockInTheseBounds(M2C_FIELD(temp_v0, s32 *, 0x20), temp_s2, AlignSize(arg0, M2C_FIELD(temp_v0, u16 *, 0x10)));
    if (temp_v0_2 != 0) {
        DetachHdrFromList(temp_v0 + 0x20, temp_v0_2);
        return LoAlloc(temp_v0, temp_v0_2, temp_s2, arg0, arg3);
    }
    return -1;
}
#endif
#if 0 /* ida */
int __fastcall GAL_AllocAt(unsigned int a1, unsigned int a2, int a3, _BYTE *a4)
{
  int v7; // $v0
  int v8; // $s1
  unsigned int v10; // $s2
  int v11; // $v0
  _DWORD *v12; // $v0
  int v13; // $s0

  v7 = GetMemInitInfoBlockFromType(a3 & 0xFFFF7FFF);
  v8 = v7;
  if ( v7 != 0 )
  {
    v10 = AlignPtr(a2, *(unsigned __int16 *)(v7 + 16));
    v11 = AlignSize(a1, *(unsigned __int16 *)(v8 + 16));
    v12 = FindBlockInTheseBounds(*(_DWORD **)(v8 + 32), v10, v11);
    v13 = (int)v12;
    if ( v12 != nullptr )
    {
      DetachHdrFromList((_DWORD *)(v8 + 32), v12);
      return LoAlloc(v8, v13, v10, a1, a4);
    }
    else
    {
      return -1;
    }
  }
  else
  {
    GSetError(4);
    return -1;
  }
}
#endif

/* ---- 0x80021E84  LoAlloc  GAL.C:1109-1196  seg lib  fsize 48 ---- */
/* long LoAlloc(struct MEM_INIT_INFO *M, struct MEM_HDR *Block, void *Addr, unsigned long Size, char *Name)
 *   M=$s2 Block=$s1 Addr=$s3 Size=$s5 SplitBlock=$s0 PhysSize=$s4
 *   blocks: {1 }88
 */
/* linked from build/src/lib.c.o (segment lib mixes several source files) — INCLUDE_ASM("asm/nonmatchings/lib", LoAlloc) */
#if 0 /* m2c */
u16 LoAlloc(void *arg0, void *arg1, s32 arg2, M2C_UNK arg3, s32 arg4) {
    u32 temp_s4;
    void *temp_v0;
    void *temp_v0_2;
    void *var_a0;

    temp_s4 = AlignSize(arg3, M2C_FIELD(arg0, u16 *, 0x10));
    if (M2C_FIELD(arg1, s32 *, 8) != arg2) {
        temp_v0 = GetFreeMemHdrBlock();
        if (temp_v0 != NULL) {
            M2C_FIELD(temp_v0, s32 *, 8) = (s32) M2C_FIELD(arg1, s32 *, 8);
            M2C_FIELD(temp_v0, s32 *, 0xC) = (s32) (arg2 - M2C_FIELD(arg1, s32 *, 8));
            M2C_FIELD(temp_v0, u16 *, 0x12) = (u16) M2C_FIELD(arg0, u16 *, 8);
            MergeToEmptyList(arg0, temp_v0);
            M2C_FIELD(arg1, s32 *, 8) = arg2;
            M2C_FIELD(arg1, u32 *, 0xC) = (u32) (M2C_FIELD(arg1, u32 *, 0xC) - M2C_FIELD(temp_v0, s32 *, 0xC));
            goto block_3;
        }
        goto block_5;
    }
block_3:
    var_a0 = arg0 + 0x24;
    if (temp_s4 < (u32) M2C_FIELD(arg1, u32 *, 0xC)) {
        temp_v0_2 = GetFreeMemHdrBlock(var_a0);
        if (temp_v0_2 == NULL) {
block_5:
            GSetError(1);
            return -1U;
        }
        M2C_FIELD(temp_v0_2, s32 *, 8) = (s32) (temp_s4 + M2C_FIELD(arg1, s32 *, 8));
        M2C_FIELD(temp_v0_2, s32 *, 0xC) = (s32) (M2C_FIELD(arg1, u32 *, 0xC) - temp_s4);
        M2C_FIELD(temp_v0_2, u16 *, 0x12) = (u16) M2C_FIELD(arg0, u16 *, 8);
        MergeToEmptyList(arg0, temp_v0_2);
        M2C_FIELD(arg1, u32 *, 0xC) = temp_s4;
        var_a0 = arg0 + 0x24;
        goto block_7;
    }
block_7:
    AttachHdrToList(var_a0, arg1);
    M2C_FIELD(arg1, s16 *, 0x14) = 0;
    M2C_FIELD(arg1, u16 *, 0x12) = (u16) M2C_FIELD(arg0, u16 *, 8);
    M2C_FIELD(arg1, u16 *, 0x10) = (u16) D_8011C9D8;
    if ((u32) D_8011C9E8 >= 2U) {
        DBG_SendMessage("Succesfully alloced block of %d", arg3);
        GAL_MemDump((s32) M2C_FIELD(arg0, u16 *, 8));
    }
    SetBlockName(arg1, arg4);
    return M2C_FIELD(arg1, u16 *, 0x16);
}
#endif
#if 0 /* ida */
int __fastcall LoAlloc(int a1, int a2, int a3, unsigned int a4, _BYTE *a5)
{
  unsigned int v8; // $s4
  int v9; // $v0
  int v10; // $s0
  int v11; // $v0
  _DWORD **v12; // $a0
  int v13; // $v0
  __int16 v15; // $a0
  BOOL v16; // $v1

  v8 = AlignSize(a4, *(unsigned __int16 *)(a1 + 16));
  if ( *(_DWORD *)(a2 + 8) != a3 )
  {
    v9 = GetFreeMemHdrBlock();
    v10 = v9;
    if ( v9 == 0 )
    {
LABEL_6:
      GSetError(1);
      return -1;
    }
    *(_DWORD *)(v9 + 8) = *(_DWORD *)(a2 + 8);
    *(_DWORD *)(v9 + 12) = a3 - *(_DWORD *)(a2 + 8);
    *(_WORD *)(v9 + 18) = *(_WORD *)(a1 + 8);
    MergeToEmptyList(a1, (_DWORD *)v9);
    v11 = *(_DWORD *)(a2 + 12);
    *(_DWORD *)(a2 + 8) = a3;
    *(_DWORD *)(a2 + 12) = v11 - *(_DWORD *)(v10 + 12);
  }
  v12 = (_DWORD **)(a1 + 36);
  if ( v8 < *(_DWORD *)(a2 + 12) )
  {
    v13 = GetFreeMemHdrBlock();
    if ( v13 == 0 )
      goto LABEL_6;
    *(_DWORD *)(v13 + 8) = v8 + *(_DWORD *)(a2 + 8);
    *(_DWORD *)(v13 + 12) = *(_DWORD *)(a2 + 12) - v8;
    *(_WORD *)(v13 + 18) = *(_WORD *)(a1 + 8);
    MergeToEmptyList(a1, (_DWORD *)v13);
    *(_DWORD *)(a2 + 12) = v8;
    v12 = (_DWORD **)(a1 + 36);
  }
  AttachHdrToList(v12, (_DWORD *)a2);
  *(_WORD *)(a2 + 20) = 0;
  v15 = MEMORY[0x8011C9D8];
  v16 = MEMORY[0x8011C9E8] < 2u;
  *(_WORD *)(a2 + 18) = *(_WORD *)(a1 + 8);
  *(_WORD *)(a2 + 16) = v15;
  if ( !v16 )
  {
    DBG_SendMessage();
    GAL_MemDump(*(_DWORD *)(a1 + 8));
  }
  SetBlockName(a2, a5);
  return *(unsigned __int16 *)(a2 + 22);
}
#endif

/* ---- 0x8002201C  FindBlockInTheseBounds  GAL.C:1212-1239  seg lib  fsize 0 ---- */
/* struct MEM_HDR * FindBlockInTheseBounds(struct MEM_HDR *Head, void *Addr, unsigned long Size)
 *   Head=$a0 Addr=$a1 Size=$a2 Index=$a0 Done=$a3 ThisStart=$v1 ThisEnd=$v0 Start=$a1 End=$a2
 *   blocks: {2 }28
 */
/* linked from build/src/lib.c.o (segment lib mixes several source files) — INCLUDE_ASM("asm/nonmatchings/lib", FindBlockInTheseBounds) */
#if 0 /* m2c */
void *FindBlockInTheseBounds(void *arg0, u32 arg1, s32 arg2) {
    s32 var_a3;
    s32 var_v1;
    u32 temp_v1;
    void *var_a0;
    void *var_v0;

    var_a0 = arg0;
    var_a3 = 0;
    if (var_a0 != NULL) {
loop_1:
        temp_v1 = M2C_FIELD(var_a0, u32 *, 8);
        if ((arg1 >= temp_v1) && ((u32) (temp_v1 + M2C_FIELD(var_a0, s32 *, 0xC)) >= (u32) (arg1 + arg2))) {
            var_a3 = 1;
        } else {
            var_a0 = M2C_FIELD(var_a0, void **, 4);
        }
        var_v1 = var_a3 & 0xFF;
        if (var_a0 != NULL) {
            if (var_a3 & 0xFF) {
                goto block_7;
            }
            goto loop_1;
        }
    } else {
block_7:
        var_v1 = var_a3 & 0xFF;
    }
    var_v0 = var_a0;
    if (var_v1 == 0) {
        var_v0 = NULL;
    }
    return var_v0;
}
#endif
#if 0 /* ida */
_DWORD *__fastcall FindBlockInTheseBounds(_DWORD *a1, unsigned int a2, int a3)
{
  unsigned __int8 v3; // $a3
  unsigned int v4; // $a2
  unsigned int v5; // $v1
  int v6; // $v1
  _DWORD *result; // $v0

  v3 = 0;
  v4 = a2 + a3;
  if ( a1 != nullptr )
  {
    while ( 1 )
    {
      v5 = a1[2];
      if ( a2 < v5 || v5 + a1[3] < v4 )
        a1 = (_DWORD *)a1[1];
      else
        v3 = 1;
      v6 = v3;
      if ( a1 == nullptr )
        break;
      if ( v3 != 0 )
        goto LABEL_8;
    }
  }
  else
  {
LABEL_8:
    v6 = v3;
  }
  result = a1;
  if ( v6 == 0 )
    return nullptr;
  return result;
}
#endif

/* ---- 0x80022088  GetFreeMemHdrBlock  GAL.C:1251-1268  seg lib  fsize 24 ---- */
/* struct MEM_HDR * GetFreeMemHdrBlock(void)
 *   RetBlock=$s0
 *   blocks: {1 }18
 */
/* linked from build/src/lib.c.o (segment lib mixes several source files) — INCLUDE_ASM("asm/nonmatchings/lib", GetFreeMemHdrBlock) */
#if 0 /* m2c */
s32 GetFreeMemHdrBlock(void) {
    s32 temp_a0;
    s32 var_s0;

    var_s0 = 0;
    if (D_8011C9D0 != 0) {
        temp_a0 = D_8011C9EC - 1;
        D_8011C9EC = temp_a0;
        if ((D_8011C9E8 != 0) && (temp_a0 == 9)) {
            DBG_SendMessage("GAL: Warning Number of free headers < 10");
        }
        var_s0 = D_8011C9D0;
        DetachHdrFromList(&D_8011C9D0, var_s0);
    }
    return var_s0;
}
#endif
#if 0 /* ida */
int GetFreeMemHdrBlock()
{
  int v0; // $s0
  int v1; // $a0

  v0 = 0;
  if ( MEMORY[0x8011C9D0] != 0 )
  {
    v1 = --MEMORY[0x8011C9EC];
    if ( MEMORY[0x8011C9E8] != 0 && v1 == 9 )
      DBG_SendMessage();
    v0 = MEMORY[0x8011C9D0];
    DetachHdrFromList((_DWORD *)0x8011C9D0, MEMORY[0x8011C9D0]);
  }
  return v0;
}
#endif

/* ---- 0x80022110  ReleaseMemHdrBlock  GAL.C:1281-1283  seg lib  fsize 24 ---- */
/* void ReleaseMemHdrBlock(struct MEM_HDR *Index)
 *   Index=$a1
 */
/* linked from build/src/lib.c.o (segment lib mixes several source files) — INCLUDE_ASM("asm/nonmatchings/lib", ReleaseMemHdrBlock) */
#if 0 /* m2c */
void ReleaseMemHdrBlock(s32 arg0) {
    D_8011C9EC += 1;
    AttachHdrToList(&D_8011C9D0, arg0);
}
#endif
#if 0 /* ida */
_DWORD *__fastcall ReleaseMemHdrBlock(_DWORD *a1)
{
  ++MEMORY[0x8011C9EC];
  return AttachHdrToList((_DWORD **)0x8011C9D0, a1);
}
#endif

/* ---- 0x80022150  GAL_IterateEmptyMem  GAL.C:1295-1315  seg lib  fsize 32 ---- */
/* void GAL_IterateEmptyMem(unsigned long MemType, void *(Func)())
 *   MemType=$a0 Func=$s1 M=$v0 Block=$s0
 *   blocks: {1 {8 }17 }21
 */
/* linked from build/src/lib.c.o (segment lib mixes several source files) — INCLUDE_ASM("asm/nonmatchings/lib", GAL_IterateEmptyMem) */
#if 0 /* m2c */
void GAL_IterateEmptyMem(s32 arg0, M2C_UNK (*arg1)(s32, s32, void *)) {
    void *temp_v0;
    void *var_s0;

    temp_v0 = GetMemInitInfoBlockFromType(arg0 & 0xFFFF7FFF);
    if (temp_v0 != NULL) {
        var_s0 = M2C_FIELD(temp_v0, void **, 0x20);
        if (var_s0 != NULL) {
loop_2:
            arg1(M2C_FIELD(var_s0, s32 *, 8), M2C_FIELD(var_s0, s32 *, 0xC), var_s0 + 0x18);
            var_s0 = M2C_FIELD(var_s0, void **, 4);
            if (var_s0 != NULL) {
                goto loop_2;
            }
        }
    } else {
        GSetError(4);
    }
}
#endif
#if 0 /* ida */
int __fastcall GAL_IterateEmptyMem(int a1, int (__fastcall *a2)(_DWORD, _DWORD, _DWORD *))
{
  int result; // $v0
  _DWORD *i; // $s0

  result = GetMemInitInfoBlockFromType(a1 & 0xFFFF7FFF);
  if ( result == 0 )
    return GSetError(4);
  for ( i = *(_DWORD **)(result + 32); i != nullptr; i = (_DWORD *)i[1] )
    result = a2(i[2], i[3], i + 6);
  return result;
}
#endif

/* ---- 0x800221D4  GAL_IterateUsedMem  GAL.C:1325-1345  seg lib  fsize 40 ---- */
/* void GAL_IterateUsedMem(unsigned long MemType, void *(Func)())
 *   MemType=$a0 Func=$s1 M=$v0 Block=$s0
 *   blocks: {1 {8 }17 }21
 */
/* linked from build/src/lib.c.o (segment lib mixes several source files) — INCLUDE_ASM("asm/nonmatchings/lib", GAL_IterateUsedMem) */
#if 0 /* m2c */
void GAL_IterateUsedMem(s32 arg0, M2C_UNK (*arg1)(u16, s32, s32, void *, s32, s32)) {
    void *temp_v0;
    void *var_s0;

    temp_v0 = GetMemInitInfoBlockFromType(arg0 & 0xFFFF7FFF);
    if (temp_v0 != NULL) {
        var_s0 = M2C_FIELD(temp_v0, void **, 0x24);
        if (var_s0 != NULL) {
loop_2:
            arg1(M2C_FIELD(var_s0, u16 *, 0x16), M2C_FIELD(var_s0, s32 *, 8), M2C_FIELD(var_s0, s32 *, 0xC), var_s0 + 0x18, (s32) M2C_FIELD(var_s0, u16 *, 0x14), (s32) M2C_FIELD(var_s0, u16 *, 0x10));
            var_s0 = M2C_FIELD(var_s0, void **, 4);
            if (var_s0 != NULL) {
                goto loop_2;
            }
        }
    } else {
        GSetError(4);
    }
}
#endif
#if 0 /* ida */
int __fastcall GAL_IterateUsedMem(int a1, int (__fastcall *a2)(_DWORD, _DWORD, _DWORD, int, _DWORD, _DWORD))
{
  int result; // $v0
  int i; // $s0

  result = GetMemInitInfoBlockFromType(a1 & 0xFFFF7FFF);
  if ( result == 0 )
    return GSetError(4);
  for ( i = *(_DWORD *)(result + 36); i != 0; i = *(_DWORD *)(i + 4) )
    result = a2(
               *(unsigned __int16 *)(i + 22),
               *(_DWORD *)(i + 8),
               *(_DWORD *)(i + 12),
               i + 24,
               *(unsigned __int16 *)(i + 20),
               *(unsigned __int16 *)(i + 16));
  return result;
}
#endif

/* ---- 0x80022270  GAL_SetMemName  GAL.C:1356-1360  seg lib  fsize 32 ---- */
/* unsigned char GAL_SetMemName(long Hnd, char *Text)
 *   Hnd=$s0 Text=$s1
 */
/* linked from build/src/lib.c.o (segment lib mixes several source files) — INCLUDE_ASM("asm/nonmatchings/lib", GAL_SetMemName) */
#if 0 /* m2c */
s32 GAL_SetMemName(s32 arg0, M2C_UNK arg1) {
    if (IsActiveValidHandle() & 0xFF) {
        SetBlockName((arg0 * 0x1C) + &D_801325D0, arg1);
        return 1;
    }
    GSetError(5);
    return 0;
}
#endif
#if 0 /* ida */
int __fastcall GAL_SetMemName(unsigned int a1, _BYTE *a2)
{
  if ( IsActiveValidHandle(a1) )
  {
    SetBlockName(28 * a1 - 2146228784, a2);
    return 1;
  }
  else
  {
    GSetError(5);
    return 0;
  }
}
#endif

/* ---- 0x800222E0  GAL_TotalMem  GAL.C:1380-1394  seg lib  fsize 24 ---- */
/* unsigned long GAL_TotalMem(unsigned long Type)
 *   Type=$a0 TotalMem=$s0 M=$v0
 *   blocks: {1 }15
 */
/* linked from build/src/lib.c.o (segment lib mixes several source files) — INCLUDE_ASM("asm/nonmatchings/lib", GAL_TotalMem) */
#if 0 /* m2c */
s32 GAL_TotalMem(s32 arg0) {
    void *temp_v0;

    temp_v0 = GetMemInitInfoBlockFromType(arg0 & 0xFFFF7FFF);
    if (temp_v0 != NULL) {
        return M2C_FIELD(temp_v0, s32 *, 4);
    }
    GSetError(4);
    return 0;
}
#endif
#if 0 /* ida */
int __fastcall GAL_TotalMem(int a1)
{
  int v1; // $v0

  v1 = GetMemInitInfoBlockFromType(a1 & 0xFFFF7FFF);
  if ( v1 != 0 )
    return *(_DWORD *)(v1 + 4);
  GSetError(4);
  return 0;
}
#endif

/* ---- 0x80022334  GAL_MemBase  GAL.C:1408-1424  seg lib  fsize 24 ---- */
/* void * GAL_MemBase(unsigned long Type)
 *   Type=$a0 Ret=$s0 M=$v0
 *   blocks: {1 }17
 */
/* linked from build/src/lib.c.o (segment lib mixes several source files) — INCLUDE_ASM("asm/nonmatchings/lib", GAL_MemBase) */
#if 0 /* m2c */
s32 GAL_MemBase(s32 arg0) {
    s32 *temp_v0;

    temp_v0 = GetMemInitInfoBlockFromType(arg0 & 0xFFFF7FFF);
    if (temp_v0 != NULL) {
        return *temp_v0;
    }
    GSetError(4);
    return 0;
}
#endif
#if 0 /* ida */
int __fastcall GAL_MemBase(int a1)
{
  int v1; // $v0

  v1 = GetMemInitInfoBlockFromType(a1 & 0xFFFF7FFF);
  if ( v1 != 0 )
    return *(_DWORD *)v1;
  GSetError(4);
  return 0;
}
#endif

/* ---- 0x80022388  GAL_DefragMem  GAL.C:1438-1455  seg lib  fsize 24 ---- */
/* unsigned char GAL_DefragMem(unsigned long type)
 *   type=$s0
 *   blocks: {1 }18
 */
/* linked from build/src/lib.c.o (segment lib mixes several source files) — INCLUDE_ASM("asm/nonmatchings/lib", GAL_DefragMem) */
#if 0 /* m2c */
s32 GAL_DefragMem(s32 arg0) {
    s32 var_v0;

    if (D_8011C9E8 != 0) {
        DBG_SendMessage("GAL: Attempting defrag");
    }
    GazDefragMem(arg0);
    if ((D_8011C9DC == 0) || (var_v0 = 0, ((GAL_CheckMem(arg0) & 0xFF) != 0))) {
        D_8011C9EC = CountFreeBlocks();
        var_v0 = 1;
    }
    return var_v0;
}
#endif
#if 0 /* ida */
int __fastcall GAL_DefragMem(int a1)
{
  bool v2; // dc
  int result; // $v0

  if ( MEMORY[0x8011C9E8] != 0 )
    DBG_SendMessage();
  GazDefragMem(a1);
  if ( MEMORY[0x8011C9DC] == 0 || (v2 = (unsigned __int8)GAL_CheckMem(a1) == 0, result = 0, !v2) )
  {
    MEMORY[0x8011C9EC] = CountFreeBlocks();
    return 1;
  }
  return result;
}
#endif

/* ---- 0x8002240C  GSetError  GAL.C:1468-1473  seg lib  fsize 24 ---- */
/* unsigned char GSetError(enum GAL_ERROR_CODE Err)
 *   Err=$s0
 */
/* linked from build/src/lib.c.o (segment lib mixes several source files) — INCLUDE_ASM("asm/nonmatchings/lib", GSetError) */
#if 0 /* m2c */
s32 GSetError(s32 arg0) {
    if (D_8011C9E8 != 0) {
        DBG_SendMessage("GAL Error: %s ", *(&GalErrors + (arg0 * 4)));
    }
    D_8011C9D4 = arg0;
    return 0;
}
#endif
#if 0 /* ida */
int __fastcall GSetError(int a1)
{
  if ( MEMORY[0x8011C9E8] != 0 )
    DBG_SendMessage();
  MEMORY[0x8011C9D4] = a1;
  return 0;
}
#endif

/* ---- 0x80022468  GAL_CheckMem  GAL.C:1488-1540  seg lib  fsize 32 ---- */
/* unsigned char GAL_CheckMem(unsigned long Type)
 *   Type=$a0 M=$s1 MemHdr=$s0 TotalMem=$s2
 *   blocks: {1 }53
 */
/* linked from build/src/lib.c.o (segment lib mixes several source files) — INCLUDE_ASM("asm/nonmatchings/lib", GAL_CheckMem) */
#if 0 /* m2c */
s32 GAL_CheckMem(s32 arg0) {
    M2C_UNK var_a0;
    s32 temp_v0_2;
    s32 temp_v0_3;
    s32 var_s2;
    void *temp_v0;
    void *var_s0;
    void *var_s0_2;

    var_s2 = 0;
    temp_v0 = GetMemInitInfoBlockFromType(arg0 & 0xFFFF7FFF);
    if (temp_v0 == NULL) {
        GSetError(4);
        return 0;
    }
    var_s0 = M2C_FIELD(temp_v0, void **, 0x20);
    if (var_s0 != NULL) {
loop_3:
        var_a0 = 7;
        if (!(CheckCollisions(temp_v0, var_s0) & 0xFF)) {
            temp_v0_2 = M2C_FIELD(var_s0, s32 *, 0xC);
            var_s0 = M2C_FIELD(var_s0, void **, 4);
            var_s2 += temp_v0_2;
            if (var_s0 == NULL) {
                goto block_5;
            }
            goto loop_3;
        }
        goto block_10;
    }
block_5:
    var_s0_2 = M2C_FIELD(temp_v0, void **, 0x24);
    if (var_s0_2 != NULL) {
loop_6:
        var_a0 = 7;
        if (!(CheckCollisions(temp_v0, var_s0_2) & 0xFF)) {
            temp_v0_3 = M2C_FIELD(var_s0_2, s32 *, 0xC);
            var_s0_2 = M2C_FIELD(var_s0_2, void **, 4);
            var_s2 += temp_v0_3;
            if (var_s0_2 == NULL) {
                goto block_8;
            }
            goto loop_6;
        }
        goto block_10;
    }
block_8:
    var_a0 = 8;
    if (M2C_FIELD(temp_v0, s32 *, 4) == var_s2) {
        return 1;
    }
block_10:
    return GSetError(var_a0) & 0xFF;
}
#endif
#if 0 /* ida */
int __fastcall GAL_CheckMem(int a1)
{
  int v1; // $s2
  int v2; // $v0
  int v3; // $s1
  int v5; // $s0
  char v6; // $v0
  int v7; // $a0
  int v8; // $v0
  int v9; // $s0
  char v10; // $v0
  int v11; // $v0

  v1 = 0;
  v2 = GetMemInitInfoBlockFromType(a1 & 0xFFFF7FFF);
  v3 = v2;
  if ( v2 == 0 )
  {
    GSetError(4);
    return 0;
  }
  v5 = *(_DWORD *)(v2 + 32);
  if ( v5 != 0 )
  {
    while ( 1 )
    {
      v6 = CheckCollisions(v3, v5);
      v7 = 7;
      if ( v6 != 0 )
        break;
      v8 = *(_DWORD *)(v5 + 12);
      v5 = *(_DWORD *)(v5 + 4);
      v1 += v8;
      if ( v5 == 0 )
        goto LABEL_6;
    }
  }
  else
  {
LABEL_6:
    v9 = *(_DWORD *)(v3 + 36);
    if ( v9 != 0 )
    {
      while ( 1 )
      {
        v10 = CheckCollisions(v3, v9);
        v7 = 7;
        if ( v10 != 0 )
          break;
        v11 = *(_DWORD *)(v9 + 12);
        v9 = *(_DWORD *)(v9 + 4);
        v1 += v11;
        if ( v9 == 0 )
          goto LABEL_9;
      }
    }
    else
    {
LABEL_9:
      v7 = 8;
      if ( *(_DWORD *)(v3 + 4) == v1 )
        return 1;
    }
  }
  return (unsigned __int8)GSetError(v7);
}
#endif

/* ---- 0x80022564  CheckCollisions  GAL.C:1555-1580  seg lib  fsize 32 ---- */
/* unsigned char CheckCollisions(struct MEM_INIT_INFO *M, struct MEM_HDR *MemHdr)
 *   M=$s2 MemHdr=$s1 CheckHdr=$s0
 *   blocks: {1 }26
 */
/* linked from build/src/lib.c.o (segment lib mixes several source files) — INCLUDE_ASM("asm/nonmatchings/lib", CheckCollisions) */
#if 0 /* m2c */
s32 CheckCollisions(void *arg0, s32 arg1) {
    s32 var_v0;
    void *var_s0;
    void *var_s0_2;

    var_s0 = M2C_FIELD(arg0, void **, 0x24);
    if (var_s0 != NULL) {
loop_1:
        if ((var_s0 == arg1) || (var_v0 = 1, ((AreBlocksColliding(arg1, var_s0) & 0xFF) == 0))) {
            var_s0 = M2C_FIELD(var_s0, void **, 4);
            if (var_s0 == NULL) {
                goto block_4;
            }
            goto loop_1;
        }
    } else {
block_4:
        var_s0_2 = M2C_FIELD(arg0, void **, 0x20);
        var_v0 = 0;
        if (var_s0_2 != NULL) {
loop_5:
            if ((var_s0_2 == arg1) || (var_v0 = 1, ((AreBlocksColliding(arg1, var_s0_2) & 0xFF) == 0))) {
                var_s0_2 = M2C_FIELD(var_s0_2, void **, 4);
                var_v0 = 0;
                if (var_s0_2 != NULL) {
                    goto loop_5;
                }
            }
        }
    }
    return var_v0;
}
#endif
#if 0 /* ida */
int __fastcall CheckCollisions(int a1, int a2)
{
  int v3; // $s0
  bool v5; // dc
  int result; // $v0
  int v7; // $s0

  v3 = *(_DWORD *)(a1 + 36);
  if ( v3 != 0 )
  {
    while ( 1 )
    {
      if ( v3 != a2 )
      {
        v5 = AreBlocksColliding(a2, v3);
        result = 1;
        if ( v5 )
          break;
      }
      v3 = *(_DWORD *)(v3 + 4);
      if ( v3 == 0 )
        goto LABEL_5;
    }
  }
  else
  {
LABEL_5:
    v7 = *(_DWORD *)(a1 + 32);
    for ( result = 0; v7 != 0; result = 0 )
    {
      if ( v7 != a2 )
      {
        v5 = AreBlocksColliding(a2, v7);
        result = 1;
        if ( v5 )
          break;
      }
      v7 = *(_DWORD *)(v7 + 4);
    }
  }
  return result;
}
#endif

/* ---- 0x80022610  AreBlocksColliding  GAL.C:1593-1608  seg lib  fsize 0 ---- */
/* unsigned char AreBlocksColliding(struct MEM_HDR *Hdr1, struct MEM_HDR *Hdr2)
 *   Hdr1=$a0 Hdr2=$a1 Addr1=$a1 Addr2=$a2
 *   blocks: {2 }16
 */
/* linked from build/src/lib.c.o (segment lib mixes several source files) — INCLUDE_ASM("asm/nonmatchings/lib", AreBlocksColliding) */
#if 0 /* m2c */
s32 AreBlocksColliding(void *arg0, void *arg1) {
    s32 var_v0;
    u32 temp_a1;
    u32 temp_a2;

    temp_a2 = M2C_FIELD(arg1, u32 *, 8);
    temp_a1 = M2C_FIELD(arg0, u32 *, 8);
    if ((temp_a1 < (u32) (temp_a2 + M2C_FIELD(arg1, s32 *, 0xC))) && (temp_a1 >= temp_a2)) {
        return 1;
    }
    var_v0 = 0;
    if (temp_a2 < (u32) (temp_a1 + M2C_FIELD(arg0, s32 *, 0xC))) {
        var_v0 = temp_a2 >= temp_a1;
    }
    return var_v0;
}
#endif
#if 0 /* ida */
BOOL __fastcall AreBlocksColliding(int a1, int a2)
{
  unsigned int v2; // $a2
  int v3; // $v0
  unsigned int v4; // $a1
  BOOL result; // $v0

  v2 = *(_DWORD *)(a2 + 8);
  v3 = *(_DWORD *)(a2 + 12);
  v4 = *(_DWORD *)(a1 + 8);
  if ( v4 < v2 + v3 && v4 >= v2 )
    return true;
  result = false;
  if ( v2 < v4 + *(_DWORD *)(a1 + 12) )
    return v2 >= v4;
  return result;
}
#endif

/* ---- 0x80022668  GAL_GetErrorText  GAL.C:1620-1622  seg lib  fsize 0 ---- */
/* char * GAL_GetErrorText(enum GAL_ERROR_CODE Err)
 *   Err=$a0
 */
/* linked from build/src/lib.c.o (segment lib mixes several source files) — INCLUDE_ASM("asm/nonmatchings/lib", GAL_GetErrorText) */
#if 0 /* m2c */
M2C_UNK *GAL_GetErrorText(u32 arg0) {
    if (arg0 < 0xAU) {
        return *(&GalErrors + (arg0 * 4));
    }
    return "Invalid error code";
}
#endif
#if 0 /* ida */
const char *__fastcall GAL_GetErrorText(unsigned int a1)
{
  if ( a1 >= 0xA )
    return "Invalid error code";
  else
    return (const char *)GalErrors[a1];
}
#endif

/* ---- 0x80022698  GAL_GetLastErrorCode  GAL.C:1635-1636  seg lib  fsize 0 ---- */
/* enum GAL_ERROR_CODE GAL_GetLastErrorCode(void)
 */
/* linked from build/src/lib.c.o (segment lib mixes several source files) — INCLUDE_ASM("asm/nonmatchings/lib", GAL_GetLastErrorCode) */
#if 0 /* m2c */
s32 GAL_GetLastErrorCode(void) {
    return D_8011C9D4;
}
#endif

/* ---- 0x800226A8  GAL_GetLastErrorText  GAL.C:1647-1648  seg lib  fsize 24 ---- */
/* char * GAL_GetLastErrorText(void)
 */
/* linked from build/src/lib.c.o (segment lib mixes several source files) — INCLUDE_ASM("asm/nonmatchings/lib", GAL_GetLastErrorText) */
#if 0 /* m2c */
void GAL_GetLastErrorText(void) {
    GAL_GetErrorText(D_8011C9D4);
}
#endif
#if 0 /* ida */
const char *GAL_GetLastErrorText()
{
  return GAL_GetErrorText(MEMORY[0x8011C9D4]);
}
#endif

/* ---- 0x800226D0  GAL_HowManyEmptyRegions  GAL.C:1660-1687  seg lib  fsize 24 ---- */
/* int GAL_HowManyEmptyRegions(unsigned long Type)
 *   Type=$a0 m=$v0 Count=$v1 mh=$v0
 *   blocks: {1 {9 }20 }28
 */
/* linked from build/src/lib.c.o (segment lib mixes several source files) — INCLUDE_ASM("asm/nonmatchings/lib", GAL_HowManyEmptyRegions) */
#if 0 /* m2c */
s32 GAL_HowManyEmptyRegions(s32 arg0) {
    s32 var_v1;
    void *temp_v0;
    void *var_v0;

    temp_v0 = GetMemInitInfoBlockFromType(arg0 & 0xFFFF7FFF);
    if (temp_v0 != NULL) {
        var_v0 = M2C_FIELD(temp_v0, void **, 0x20);
        var_v1 = 0;
        if (var_v0 != NULL) {
            do {
                var_v0 = M2C_FIELD(var_v0, void **, 4);
                var_v1 += 1;
            } while (var_v0 != NULL);
            return var_v1;
        }
        goto block_5;
    }
    GSetError(4);
    var_v1 = -1;
block_5:
    return var_v1;
}
#endif
#if 0 /* ida */
int __fastcall GAL_HowManyEmptyRegions(int a1)
{
  int v1; // $v0
  int v2; // $v0
  int v3; // $v1

  v1 = GetMemInitInfoBlockFromType(a1 & 0xFFFF7FFF);
  if ( v1 == 0 )
  {
    GSetError(4);
    return -1;
  }
  v2 = *(_DWORD *)(v1 + 32);
  v3 = 0;
  if ( v2 == 0 )
    return v3;
  do
  {
    v2 = *(_DWORD *)(v2 + 4);
    ++v3;
  }
  while ( v2 != 0 );
  return v3;
}
#endif

/* ---- 0x80022738  GAL_HowManyUsedRegions  GAL.C:1697-1722  seg lib  fsize 24 ---- */
/* int GAL_HowManyUsedRegions(unsigned long Type)
 *   Type=$a0 m=$v0 Count=$v1 mh=$v0
 *   blocks: {1 {9 }18 }26
 */
/* linked from build/src/lib.c.o (segment lib mixes several source files) — INCLUDE_ASM("asm/nonmatchings/lib", GAL_HowManyUsedRegions) */
#if 0 /* m2c */
s32 GAL_HowManyUsedRegions(s32 arg0) {
    s32 var_v1;
    void *temp_v0;
    void *var_v0;

    temp_v0 = GetMemInitInfoBlockFromType(arg0 & 0xFFFF7FFF);
    if (temp_v0 != NULL) {
        var_v0 = M2C_FIELD(temp_v0, void **, 0x24);
        var_v1 = 0;
        if (var_v0 != NULL) {
            do {
                var_v0 = M2C_FIELD(var_v0, void **, 4);
                var_v1 += 1;
            } while (var_v0 != NULL);
            return var_v1;
        }
        goto block_5;
    }
    GSetError(4);
    var_v1 = -1;
block_5:
    return var_v1;
}
#endif
#if 0 /* ida */
int __fastcall GAL_HowManyUsedRegions(int a1)
{
  int v1; // $v0
  int v2; // $v0
  int v3; // $v1

  v1 = GetMemInitInfoBlockFromType(a1 & 0xFFFF7FFF);
  if ( v1 == 0 )
  {
    GSetError(4);
    return -1;
  }
  v2 = *(_DWORD *)(v1 + 36);
  v3 = 0;
  if ( v2 == 0 )
    return v3;
  do
  {
    v2 = *(_DWORD *)(v2 + 4);
    ++v3;
  }
  while ( v2 != 0 );
  return v3;
}
#endif

/* ---- 0x800227A0  GAL_SetTimeStamp  GAL.C:1731-1732  seg lib  fsize 0 ---- */
/* void GAL_SetTimeStamp(int Time)
 *   Time=$a0
 */
/* linked from build/src/lib.c.o (segment lib mixes several source files) — INCLUDE_ASM("asm/nonmatchings/lib", GAL_SetTimeStamp) */
#if 0 /* m2c */
void GAL_SetTimeStamp(s32 arg0) {
    D_8011C9D8 = arg0;
}
#endif
#if 0 /* ida */
void __fastcall GAL_SetTimeStamp(int a1)
{
  MEMORY[0x8011C9D8] = a1;
}
#endif

/* ---- 0x800227B0  GAL_IncTimeStamp  GAL.C:1742-1743  seg lib  fsize 0 ---- */
/* void GAL_IncTimeStamp(void)
 */
/* linked from build/src/lib.c.o (segment lib mixes several source files) — INCLUDE_ASM("asm/nonmatchings/lib", GAL_IncTimeStamp) */
#if 0 /* m2c */
void GAL_IncTimeStamp(void) {
    D_8011C9D8 += 1;
}
#endif

/* ---- 0x800227D0  GAL_GetTimeStamp  GAL.C:1752-1753  seg lib  fsize 0 ---- */
/* int GAL_GetTimeStamp(void)
 */
/* linked from build/src/lib.c.o (segment lib mixes several source files) — INCLUDE_ASM("asm/nonmatchings/lib", GAL_GetTimeStamp) */
#if 0 /* m2c */
s32 GAL_GetTimeStamp(void) {
    return D_8011C9D8;
}
#endif

/* ---- 0x800227E0  GAL_AlignSizeToType  GAL.C:1769-1780  seg lib  fsize 24 ---- */
/* long GAL_AlignSizeToType(unsigned long Size, unsigned long MemType)
 *   Size=$s0 MemType=$a1 Mi=$v0
 *   blocks: {1 }12
 */
/* linked from build/src/lib.c.o (segment lib mixes several source files) — INCLUDE_ASM("asm/nonmatchings/lib", GAL_AlignSizeToType) */
#if 0 /* m2c */
s32 GAL_AlignSizeToType(s32 arg0, s32 arg1) {
    void *temp_v0;

    temp_v0 = GetMemInitInfoBlockFromType(arg1 & 0xFFFF7FFF);
    if (temp_v0 == NULL) {
        return -1;
    }
    return AlignSize(arg0, M2C_FIELD(temp_v0, u16 *, 0x10));
}
#endif
#if 0 /* ida */
int __fastcall GAL_AlignSizeToType(unsigned int a1, int a2)
{
  int v3; // $v0

  v3 = GetMemInitInfoBlockFromType(a2 & 0xFFFF7FFF);
  if ( v3 != 0 )
    return AlignSize(a1, *(unsigned __int16 *)(v3 + 16));
  else
    return -1;
}
#endif

/* ---- 0x80022830  GAL_AllocMultiStruct  GAL.C:1800-1805  seg lib  fsize 32 ---- */
/* long GAL_AllocMultiStruct(struct GAL_STRUCT *G, unsigned long Type, char *Name)
 *   G=$a0 Type=$s0 Name=$s1
 *   blocks: {1 }6
 */
/* linked from build/src/lib.c.o (segment lib mixes several source files) — INCLUDE_ASM("asm/nonmatchings/lib", GAL_AllocMultiStruct) */
#if 0 /* m2c */
void GAL_AllocMultiStruct(s32 arg1, M2C_UNK arg2) {
    GAL_Alloc(GAL_ProcessMultiStruct(arg1 & 0xFFFF7FFF), arg1, arg2);
}
#endif
#if 0 /* ida */
int __fastcall GAL_AllocMultiStruct(unsigned int *a1, int a2, _BYTE *a3)
{
  unsigned int v5; // $v0

  v5 = GAL_ProcessMultiStruct(a1, a2 & 0xFFFF7FFF);
  return GAL_Alloc(v5, a2, a3);
}
#endif

/* ---- 0x80022880  GAL_ProcessMultiStruct  GAL.C:1820-1837  seg lib  fsize 48 ---- */
/* unsigned int GAL_ProcessMultiStruct(struct GAL_STRUCT *G, unsigned long Type)
 *   G=$s4 Type=$s3 TotalMem=$s1 f=$s2
 *   blocks: {1 }18
 */
/* linked from build/src/lib.c.o (segment lib mixes several source files) — INCLUDE_ASM("asm/nonmatchings/lib", GAL_ProcessMultiStruct) */
#if 0 /* m2c */
s32 GAL_ProcessMultiStruct(s32 *arg0, s32 arg1) {
    s32 *var_s0;
    s32 temp_a0;
    s32 var_s1;
    s32 var_s2;

    var_s1 = 0;
    var_s2 = 0;
    if (*arg0 != -1) {
        var_s0 = arg0;
        do {
            temp_a0 = M2C_FIELD(var_s0, s32 *, 0);
            M2C_FIELD(var_s0, s32 *, 4) = var_s1;
            var_s0 += 8;
            var_s2 += 1;
            var_s1 += GAL_AlignSizeToType(temp_a0, arg1 & 0xFFFF7FFF);
        } while (*var_s0 != -1);
    }
    M2C_FIELD(((var_s2 * 8) + arg0), s32 *, 4) = var_s1;
    return var_s1;
}
#endif
#if 0 /* ida */
unsigned int __fastcall GAL_ProcessMultiStruct(unsigned int *a1, int a2)
{
  unsigned int v3; // $s1
  unsigned int v4; // $s3
  int v5; // $s2
  unsigned int *v6; // $s0
  unsigned int v7; // $a0

  v3 = 0;
  v4 = a2 & 0xFFFF7FFF;
  v5 = 0;
  if ( *a1 != -1 )
  {
    v6 = a1;
    do
    {
      v7 = *v6;
      v6[1] = v3;
      v6 += 2;
      ++v5;
      v3 += GAL_AlignSizeToType(v7, v4);
    }
    while ( *v6 != -1 );
  }
  a1[2 * v5 + 1] = v3;
  return v3;
}
#endif

/* ---- 0x8002292C  GAL_GetSize  GAL.C:1848-1859  seg lib  fsize 24 ---- */
/* long GAL_GetSize(long hnd)
 *   hnd=$s0
 *   blocks: {1 }12
 */
/* linked from build/src/lib.c.o (segment lib mixes several source files) — INCLUDE_ASM("asm/nonmatchings/lib", GAL_GetSize) */
#if 0 /* m2c */
s32 GAL_GetSize(s32 arg0) {
    if (IsActiveValidHandle() & 0xFF) {
        return *(&D_801325DC + (arg0 * 0x1C));
    }
    GSetError(5);
    return -1;
}
#endif
#if 0 /* ida */
int __fastcall GAL_GetSize(unsigned int a1)
{
  if ( IsActiveValidHandle(a1) )
    return *(_DWORD *)(28 * a1 - 2146228772);
  GSetError(5);
  return -1;
}
#endif

/* ---- 0x80022988  GazDefragMem  GAL.C:1873-1965  seg lib  fsize 56 ---- */
/* unsigned char GazDefragMem(unsigned long MemType)
 *   MemType=$s4 LockedBlocks@sp-0x20 M=$s1 Reg@sp-0x28 NewEmptyBlock=$a1 ListOfBlocksInRegion@sp-0x1c ShuffledSize=$s2 GapSize=$s0
 *   blocks: {1 {50 }83 }93
 */
/* linked from build/src/lib.c.o (segment lib mixes several source files) — INCLUDE_ASM("asm/nonmatchings/lib", GazDefragMem) */
#if 0 /* m2c */
s32 GazDefragMem(s32 arg0) {
    s32 sp10;
    s32 sp18;
    s32 sp1C;
    M2C_UNK var_a0;
    s16 temp_s4;
    s32 temp_s0;
    s32 temp_v0_2;
    void *temp_v0;
    void *temp_v0_3;
    void *var_a0_2;

    temp_s4 = arg0 & 0xFFFF7FFF;
    temp_v0 = GetMemInitInfoBlockFromType(temp_s4);
    var_a0 = 4;
    if (temp_v0 != NULL) {
        if (M2C_FIELD(temp_v0, s32 *, 0x14) == 0) {
            var_a0 = 9;
            goto block_4;
        }
        sp18 = 0;
        PutAllLockedBlocksOntoList(&sp18, temp_v0 + 0x24);
        SortMemHdrListByAddr(&sp18);
        DeleteEmptyBlocks(temp_v0);
        sp10 = 0;
loop_6:
loop_7:
        if (GetRegion(&sp10, sp18, temp_v0) & 0xFF) {
            if (sp14 != 0) {
                sp1C = 0;
                PutBlocksInRegionIntoList(&sp10, &sp1C, temp_v0 + 0x24);
                SortMemHdrListByAddr(&sp1C);
                temp_v0_2 = ShuffleBlocks(sp1C, &sp10, temp_v0);
                temp_s0 = sp14 - temp_v0_2;
                var_a0_2 = temp_v0 + 0x24;
                if (temp_s0 != 0) {
                    temp_v0_3 = GetFreeMemHdrBlock(var_a0_2);
                    if (temp_v0_3 != NULL) {
                        M2C_FIELD(temp_v0_3, s32 *, 0xC) = temp_s0;
                        M2C_FIELD(temp_v0_3, s16 *, 0x12) = temp_s4;
                        M2C_FIELD(temp_v0_3, s32 *, 8) = (s32) (temp_v0_2 + sp10);
                        MergeToEmptyList(temp_v0, temp_v0_3);
                        var_a0_2 = temp_v0 + 0x24;
                        goto block_12;
                    }
                    var_a0 = 1;
                    goto block_4;
                }
block_12:
                GraftMemHdrList(var_a0_2, &sp1C);
                goto loop_7;
            }
            goto loop_6;
        }
        PutAllLockedBlocksOntoList(temp_v0 + 0x24, &sp18);
        return 1;
    }
block_4:
    GSetError(var_a0);
    return 0;
}
#endif
#if 0 /* ida */
int __fastcall GazDefragMem(int a1)
{
  __int16 v1; // $s4
  int v2; // $v0
  int v3; // $s1
  int v4; // $a0
  int v6; // $s2
  int v7; // $s0
  _DWORD **v8; // $a0
  int v9; // $a1
  int v10; // $v0
  int v11; // [sp+10h] [-10h] BYREF
  int v12; // [sp+14h] [-Ch]
  int *v13; // [sp+18h] [-8h] BYREF
  int *v14; // [sp+1Ch] [-4h] BYREF

  v1 = a1 & 0x7FFF;
  v2 = GetMemInitInfoBlockFromType(a1 & 0xFFFF7FFF);
  v3 = v2;
  v4 = 4;
  if ( v2 == 0 )
    goto LABEL_5;
  if ( *(_DWORD *)(v2 + 20) == 0 )
  {
    v4 = 9;
LABEL_5:
    GSetError(v4);
    return 0;
  }
  v13 = nullptr;
  PutAllLockedBlocksOntoList(&v13, (int *)(v2 + 36));
  SortMemHdrListByAddr(&v13);
  DeleteEmptyBlocks(v3);
  v11 = 0;
  while ( (unsigned __int8)GetRegion((unsigned int *)&v11, (int)v13, (unsigned int *)v3) != 0 )
  {
    if ( v12 != 0 )
    {
      v14 = nullptr;
      PutBlocksInRegionIntoList(&v11, &v14, (int *)(v3 + 36));
      SortMemHdrListByAddr(&v14);
      v6 = ShuffleBlocks(v14, &v11, v3);
      v7 = v12 - v6;
      v8 = (_DWORD **)(v3 + 36);
      if ( v12 != v6 )
      {
        v9 = GetFreeMemHdrBlock();
        if ( v9 == 0 )
        {
          v4 = 1;
          goto LABEL_5;
        }
        v10 = v11;
        *(_DWORD *)(v9 + 12) = v7;
        *(_WORD *)(v9 + 18) = v1;
        *(_DWORD *)(v9 + 8) = v6 + v10;
        MergeToEmptyList(v3, (_DWORD *)v9);
        v8 = (_DWORD **)(v3 + 36);
      }
      GraftMemHdrList(v8, (int)&v14);
    }
  }
  PutAllLockedBlocksOntoList((_DWORD **)(v3 + 36), (int *)&v13);
  return 1;
}
#endif

/* ---- 0x80022AF0  PutBlocksInRegionIntoList  GAL.C:1978-2002  seg lib  fsize 48 ---- */
/* void PutBlocksInRegionIntoList(struct MEM_REG *Reg, struct MEM_HDR **ToList, struct MEM_HDR **FromList)
 *   Reg=$s3 ToList=$s4 FromList=$s2 ThisBlock=$s0 NextBlock=$s1 MemReg@sp-0x20
 *   blocks: {1 {9 }23 }25
 */
/* linked from build/src/lib.c.o (segment lib mixes several source files) — INCLUDE_ASM("asm/nonmatchings/lib", PutBlocksInRegionIntoList) */
#if 0 /* m2c */
void PutBlocksInRegionIntoList(s32 arg0, M2C_UNK arg1, void **arg2) {
    s32 sp10;
    s32 sp14;
    void *temp_s1;
    void *var_s0;

    var_s0 = *arg2;
    if (var_s0 != NULL) {
        do {
            temp_s1 = M2C_FIELD(var_s0, void **, 4);
            sp10 = M2C_FIELD(var_s0, s32 *, 8);
            sp14 = M2C_FIELD(var_s0, s32 *, 0xC);
            if (CollideRegions(arg0, &sp10) & 0xFF) {
                DetachHdrFromList(arg2, var_s0);
                AttachHdrToList(arg1, var_s0);
            }
            var_s0 = temp_s1;
        } while (var_s0 != NULL);
    }
}
#endif
#if 0 /* ida */
void __fastcall PutBlocksInRegionIntoList(_DWORD *a1, _DWORD **a2, int *a3)
{
  int v5; // $s0
  int v7; // $s1
  __int64 v8; // [sp+10h] [-8h] BYREF

  v5 = *a3;
  if ( *a3 != 0 )
  {
    do
    {
      v7 = *(_DWORD *)(v5 + 4);
      v8 = *(_QWORD *)(v5 + 8);
      if ( CollideRegions(a1, &v8) )
      {
        DetachHdrFromList(a3, (_DWORD *)v5);
        AttachHdrToList(a2, (_DWORD *)v5);
      }
      v5 = v7;
    }
    while ( v7 != 0 );
  }
}
#endif

/* ---- 0x80022B94  CollideRegions  GAL.C:2015-2021  seg lib  fsize 0 ---- */
/* unsigned char CollideRegions(struct MEM_REG *Reg1, struct MEM_REG *Reg2)
 *   Reg1=$a0 Reg2=$a1
 */
/* linked from build/src/lib.c.o (segment lib mixes several source files) — INCLUDE_ASM("asm/nonmatchings/lib", CollideRegions) */
#if 0 /* m2c */
s32 CollideRegions(void *arg0, void *arg1) {
    s32 var_v0;
    u32 temp_a2;
    u32 temp_v1;

    temp_a2 = M2C_FIELD(arg0, u32 *, 0);
    temp_v1 = M2C_FIELD(arg1, u32 *, 0);
    var_v0 = 0;
    if (temp_v1 < (u32) (temp_a2 + M2C_FIELD(arg0, s32 *, 4))) {
        var_v0 = temp_a2 < (u32) (temp_v1 + M2C_FIELD(arg1, s32 *, 4));
    }
    return var_v0;
}
#endif
#if 0 /* ida */
BOOL __fastcall CollideRegions(_DWORD *a1, _DWORD *a2)
{
  BOOL result; // $v0

  result = false;
  if ( *a2 < (unsigned int)(*a1 + a1[1]) )
    return *a1 < (unsigned int)(*a2 + a2[1]);
  return result;
}
#endif

/* ---- 0x80022BC8  DeleteEmptyBlocks  GAL.C:2034-2044  seg lib  fsize 32 ---- */
/* void DeleteEmptyBlocks(struct MEM_INIT_INFO *M)
 *   M=$s1 ThisBlock=$s0
 *   blocks: {1 {4 }6 }11
 */
/* linked from build/src/lib.c.o (segment lib mixes several source files) — INCLUDE_ASM("asm/nonmatchings/lib", DeleteEmptyBlocks) */
#if 0 /* m2c */
void DeleteEmptyBlocks(void *arg0) {
    s32 temp_s0;

    if (M2C_FIELD(arg0, s32 *, 0x20) != 0) {
        do {
            temp_s0 = M2C_FIELD(arg0, s32 *, 0x20);
            DetachHdrFromList(arg0 + 0x20, temp_s0);
            AttachHdrToList(&D_8011C9D0, temp_s0);
        } while (M2C_FIELD(arg0, s32 *, 0x20) != 0);
    }
}
#endif
#if 0 /* ida */
int __fastcall DeleteEmptyBlocks(int a1)
{
  int result; // $v0
  _DWORD *v3; // $s0

  for ( result = *(_DWORD *)(a1 + 32); result != 0; result = *(_DWORD *)(a1 + 32) )
  {
    v3 = *(_DWORD **)(a1 + 32);
    DetachHdrFromList((_DWORD *)(a1 + 32), v3);
    AttachHdrToList((_DWORD **)0x8011C9D0, v3);
  }
  return result;
}
#endif

/* ---- 0x80022C34  GetRegion  GAL.C:2062-2097  seg lib  fsize 40 ---- */
/* unsigned char GetRegion(struct MEM_REG *Reg, struct MEM_HDR *LockedBlocks, struct MEM_INIT_INFO *M)
 *   Reg=$s1 LockedBlocks=$s2 M=$s0 FirstBlock=$v1 SecondBlock=$v0 NewReg@sp-0x18
 *   blocks: {1 }36
 */
/* linked from build/src/lib.c.o (segment lib mixes several source files) — INCLUDE_ASM("asm/nonmatchings/lib", GetRegion) */
#if 0 /* m2c */
s32 GetRegion(void *arg0, M2C_UNK arg1, void *arg2) {
    s32 sp10;
    s32 sp14;
    s32 var_v0;
    s32 var_v0_2;
    s32 var_v0_3;
    void *temp_v0;
    void *temp_v0_2;

    temp_v0 = FindNextBlock(M2C_FIELD(arg0, s32 *, 0));
    if (temp_v0 != NULL) {
        var_v0_2 = M2C_FIELD(temp_v0, s32 *, 8) + M2C_FIELD(temp_v0, s32 *, 0xC);
        goto block_4;
    }
    var_v0 = 0;
    if (M2C_FIELD(arg0, s32 *, 0) == 0) {
        var_v0_2 = M2C_FIELD(arg2, s32 *, 0);
block_4:
        sp10 = var_v0_2;
        temp_v0_2 = FindNextBlock(sp10, arg1);
        if (temp_v0_2 != NULL) {
            var_v0_3 = M2C_FIELD(temp_v0_2, s32 *, 8) - sp10;
        } else {
            var_v0_3 = (M2C_FIELD(arg2, s32 *, 0) + M2C_FIELD(arg2, s32 *, 4)) - sp10;
        }
        sp14 = var_v0_3;
        if (!(CollideRegions(arg0, &sp10) & 0xFF) || (var_v0 = 0, (M2C_FIELD(arg0, s32 *, 0) == 0))) {
            M2C_FIELD(arg0, s32 *, 0) = sp10;
            var_v0 = 1;
            M2C_FIELD(arg0, s32 *, 4) = sp14;
        }
    }
    return var_v0;
}
#endif
#if 0 /* ida */
int __fastcall GetRegion(unsigned int *a1, int a2, unsigned int *a3)
{
  int v5; // $v0
  unsigned int v7; // $v0
  int result; // $v0
  int v9; // $v0
  unsigned int v10; // $v0
  unsigned int v11; // [sp+10h] [-8h] BYREF
  unsigned int v12; // [sp+14h] [-4h]

  v5 = FindNextBlock(*a1, a2);
  if ( v5 != 0 )
  {
    v7 = *(_DWORD *)(v5 + 8) + *(_DWORD *)(v5 + 12);
  }
  else
  {
    result = 0;
    if ( *a1 != 0 )
      return result;
    v7 = *a3;
  }
  v11 = v7;
  v9 = FindNextBlock(v7, a2);
  if ( v9 != 0 )
    v10 = *(_DWORD *)(v9 + 8) - v11;
  else
    v10 = *a3 + a3[1] - v11;
  v12 = v10;
  if ( !CollideRegions(a1, &v11) || (result = 0, *a1 == 0) )
  {
    *a1 = v11;
    a1[1] = v12;
    return 1;
  }
  return result;
}
#endif

/* ---- 0x80022D2C  FindNextBlock  GAL.C:2136-2155  seg lib  fsize 0 ---- */
/* struct MEM_HDR * FindNextBlock(void *Addr, struct MEM_HDR *Blocks)
 *   Addr=$a0 Blocks=$a1 BlockAddr=$v0
 *   blocks: {2 {6 }15 }20
 */
/* linked from build/src/lib.c.o (segment lib mixes several source files) — INCLUDE_ASM("asm/nonmatchings/lib", FindNextBlock) */
#if 0 /* m2c */
void *FindNextBlock(u32 arg0, void *arg1) {
    void *var_a1;
    void *var_v0;

    var_a1 = arg1;
    var_v0 = NULL;
    if ((arg0 != 0) && (var_a1 != NULL)) {
loop_2:
        var_v0 = var_a1;
        if ((u32) M2C_FIELD(var_a1, u32 *, 8) < arg0) {
            var_a1 = M2C_FIELD(var_a1, void **, 4);
            var_v0 = NULL;
            if (var_a1 != NULL) {
                goto loop_2;
            }
        }
    }
    return var_v0;
}
#endif
#if 0 /* ida */
int __fastcall FindNextBlock(unsigned int a1, int a2)
{
  int result; // $v0

  result = 0;
  if ( a1 != 0 && a2 != 0 )
  {
    do
    {
      result = a2;
      if ( *(_DWORD *)(a2 + 8) >= a1 )
        break;
      a2 = *(_DWORD *)(a2 + 4);
      result = 0;
    }
    while ( a2 != 0 );
  }
  return result;
}
#endif

/* ---- 0x80022D68  ShuffleBlocks  GAL.C:2169-2198  seg lib  fsize 40 ---- */
/* unsigned long ShuffleBlocks(struct MEM_HDR *Blocks, struct MEM_REG *Reg, struct MEM_INIT_INFO *M)
 *   Blocks=$a0 Reg=$a1 M=$s3 NewSize=$s2 MemBase=$s1 ThisBlock=$s0
 *   blocks: {1 }30
 */
/* linked from build/src/lib.c.o (segment lib mixes several source files) — INCLUDE_ASM("asm/nonmatchings/lib", ShuffleBlocks) */
#if 0 /* m2c */
s32 ShuffleBlocks(void *arg0, s32 *arg1, void *arg2) {
    s32 temp_a1;
    s32 temp_a2;
    s32 temp_v0;
    s32 temp_v1;
    s32 var_s1;
    s32 var_s2;
    void *var_s0;

    var_s0 = arg0;
    var_s1 = *arg1;
    var_s2 = 0;
    if (var_s0 != NULL) {
        do {
            temp_a2 = M2C_FIELD(var_s0, s32 *, 0xC);
            temp_a1 = M2C_FIELD(var_s0, s32 *, 8);
            var_s2 += temp_a2;
            if (var_s1 != temp_a1) {
                M2C_FIELD(arg2, M2C_UNK (**)(s32, s32, s32), 0x14)(var_s1, temp_a1, temp_a2);
                M2C_FIELD(var_s0, s32 *, 8) = var_s1;
            }
            temp_v1 = M2C_FIELD(var_s0, s32 *, 8);
            temp_v0 = M2C_FIELD(var_s0, s32 *, 0xC);
            var_s0 = M2C_FIELD(var_s0, void **, 4);
            var_s1 = temp_v1 + temp_v0;
        } while (var_s0 != NULL);
    }
    return var_s2;
}
#endif
#if 0 /* ida */
int __fastcall ShuffleBlocks(_DWORD *a1, int *a2, int a3)
{
  _DWORD *v4; // $s0
  int v5; // $s1
  int i; // $s2
  int v7; // $v1
  int v8; // $v0

  v4 = a1;
  v5 = *a2;
  for ( i = 0; v4 != nullptr; v5 = v7 + v8 )
  {
    i += v4[3];
    if ( v5 != v4[2] )
    {
      (*(void (__fastcall **)(int))(a3 + 20))(v5);
      v4[2] = v5;
    }
    v7 = v4[2];
    v8 = v4[3];
    v4 = (_DWORD *)v4[1];
  }
  return i;
}
#endif

/* ---- 0x80022DF8  PutAllLockedBlocksOntoList  GAL.C:2210-2229  seg lib  fsize 40 ---- */
/* void PutAllLockedBlocksOntoList(struct MEM_HDR **ToHead, struct MEM_HDR **FromHead)
 *   ToHead=$s3 FromHead=$s2 CurHdr=$s0 NextCurHdr=$s1
 *   blocks: {1 {8 }18 }20
 */
/* linked from build/src/lib.c.o (segment lib mixes several source files) — INCLUDE_ASM("asm/nonmatchings/lib", PutAllLockedBlocksOntoList) */
#if 0 /* m2c */
void PutAllLockedBlocksOntoList(s32 arg0, void **arg1) {
    void *temp_s1;
    void *var_s0;

    var_s0 = *arg1;
    if (var_s0 != NULL) {
        do {
            temp_s1 = M2C_FIELD(var_s0, void **, 4);
            if (M2C_FIELD(var_s0, u16 *, 0x14) != 0) {
                DetachHdrFromList(arg1, var_s0);
                AttachHdrToList(arg0, var_s0);
            }
            var_s0 = temp_s1;
        } while (var_s0 != NULL);
    }
}
#endif
#if 0 /* ida */
_DWORD *__fastcall PutAllLockedBlocksOntoList(_DWORD **a1, int *a2)
{
  int v3; // $s0
  _DWORD *result; // $v0
  int v6; // $s1

  v3 = *a2;
  if ( *a2 != 0 )
  {
    do
    {
      result = (_DWORD *)*(unsigned __int16 *)(v3 + 20);
      v6 = *(_DWORD *)(v3 + 4);
      if ( *(_WORD *)(v3 + 20) != 0 )
      {
        DetachHdrFromList(a2, (_DWORD *)v3);
        result = AttachHdrToList(a1, (_DWORD *)v3);
      }
      v3 = v6;
    }
    while ( v6 != 0 );
  }
  return result;
}
#endif

/* ---- 0x80022E74  SortMemHdrListByAddr  GAL.C:2242-2292  seg lib  fsize 0 ---- */
/* void SortMemHdrListByAddr(struct MEM_HDR **Head)
 *   Head=$a0 DidASwap=$a3 CurHdr=$a1 NextHdr=$a2 OldPrev=$v1
 *   blocks: {2 {22 }41 }51
 */
/* linked from build/src/lib.c.o (segment lib mixes several source files) — INCLUDE_ASM("asm/nonmatchings/lib", SortMemHdrListByAddr) */
#if 0 /* m2c */
void SortMemHdrListByAddr(void **arg0) {
    s32 var_a3;
    void *temp_a2;
    void *temp_v0;
    void *temp_v0_2;
    void *temp_v1;
    void *var_a1;

    temp_v0 = *arg0;
    if ((temp_v0 != NULL) && (M2C_FIELD(temp_v0, s32 *, 4) != 0)) {
        do {
            var_a3 = 0;
            var_a1 = *arg0;
loop_3:
            temp_a2 = M2C_FIELD(var_a1, void **, 4);
            if ((u32) M2C_FIELD(temp_a2, u32 *, 8) < (u32) M2C_FIELD(var_a1, u32 *, 8)) {
                temp_v1 = M2C_FIELD(var_a1, void **, 0);
                M2C_FIELD(var_a1, void **, 0) = temp_a2;
                M2C_FIELD(var_a1, void **, 4) = (void *) M2C_FIELD(temp_a2, void **, 4);
                M2C_FIELD(temp_a2, void **, 4) = var_a1;
                temp_v0_2 = M2C_FIELD(var_a1, void **, 4);
                if (temp_v0_2 != NULL) {
                    M2C_FIELD(temp_v0_2, void **, 0) = var_a1;
                    M2C_FIELD(temp_a2, void **, 4) = var_a1;
                }
                M2C_FIELD(temp_a2, void **, 0) = temp_v1;
                if (temp_v1 != NULL) {
                    M2C_FIELD(temp_v1, void **, 4) = temp_a2;
                } else {
                    *arg0 = temp_a2;
                }
                var_a3 = 1;
            } else {
                var_a1 = temp_a2;
            }
            if (M2C_FIELD(var_a1, s32 *, 4) != 0) {
                goto loop_3;
            }
        } while (var_a3 & 0xFF);
    }
}
#endif
#if 0 /* ida */
int *__fastcall SortMemHdrListByAddr(int **a1)
{
  int *result; // $v0
  unsigned __int8 v2; // $a3
  int *v3; // $a1
  int *v4; // $a2
  int v5; // $v1
  int v6; // $v0
  int **v7; // $v0

  result = *a1;
  if ( *a1 != nullptr )
  {
    result = (int *)result[1];
    if ( result != nullptr )
    {
      do
      {
        v2 = 0;
        v3 = *a1;
        do
        {
          v4 = (int *)v3[1];
          if ( v4[2] >= (unsigned int)v3[2] )
          {
            v3 = (int *)v3[1];
          }
          else
          {
            v5 = *v3;
            v6 = v4[1];
            *v3 = (int)v4;
            v3[1] = v6;
            v4[1] = (int)v3;
            v7 = (int **)v3[1];
            if ( v7 != nullptr )
            {
              *v7 = v3;
              v4[1] = (int)v3;
            }
            *v4 = v5;
            if ( v5 != 0 )
              *(_DWORD *)(v5 + 4) = v4;
            else
              *a1 = v4;
            v2 = 1;
          }
          result = (int *)v2;
        }
        while ( v3[1] != 0 );
      }
      while ( v2 != 0 );
    }
  }
  return result;
}
#endif

/* ---- 0x80022F28  GraftMemHdrList  GAL.C:2303-2326  seg lib  fsize 0 ---- */
/* void GraftMemHdrList(struct MEM_HDR **ToList, struct MEM_HDR **FromList)
 *   ToList=$a0 FromList=$a1 OldFirst=$a2 LastHdr=$v1
 *   blocks: {2 {8 }23 }24
 */
/* linked from build/src/lib.c.o (segment lib mixes several source files) — INCLUDE_ASM("asm/nonmatchings/lib", GraftMemHdrList) */
#if 0 /* m2c */
void GraftMemHdrList(M2C_UNK **arg0, M2C_UNK **arg1) {
    M2C_UNK *temp_a2;
    M2C_UNK *temp_v0;
    M2C_UNK *var_v1;

    temp_v0 = *arg1;
    temp_a2 = *arg0;
    if (temp_v0 != NULL) {
        *arg0 = temp_v0;
        var_v1 = *arg1;
        if (M2C_FIELD(var_v1, s32 *, 4) != 0) {
            do {
                var_v1 = M2C_FIELD(var_v1, M2C_UNK **, 4);
            } while (M2C_FIELD(var_v1, s32 *, 4) != 0);
        }
        M2C_FIELD(var_v1, M2C_UNK **, 4) = temp_a2;
        if (temp_a2 != NULL) {
            *temp_a2 = var_v1;
        }
        *arg1 = NULL;
    }
}
#endif
#if 0 /* ida */
_DWORD *__fastcall GraftMemHdrList(_DWORD **a1, int a2)
{
  _DWORD *result; // $v0
  _DWORD *v3; // $a2
  _DWORD *v4; // $v1

  result = *(_DWORD **)a2;
  v3 = *a1;
  if ( *(_DWORD *)a2 != 0 )
  {
    *a1 = result;
    v4 = *(_DWORD **)a2;
    for ( result = *(_DWORD **)(*(_DWORD *)a2 + 4); result != nullptr; result = (_DWORD *)v4[1] )
      v4 = (_DWORD *)v4[1];
    v4[1] = v3;
    if ( v3 != nullptr )
      *v3 = v4;
    *(_DWORD *)a2 = 0;
  }
  return result;
}
#endif

/* ---- 0x80022F84  GAL_MemDump  GAL.C:2337-2342  seg lib  fsize 24 ---- */
/* void GAL_MemDump(unsigned long Type)
 *   Type=$s0
 */
/* linked from build/src/lib.c.o (segment lib mixes several source files) — INCLUDE_ASM("asm/nonmatchings/lib", GAL_MemDump) */
#if 0 /* m2c */
void GAL_MemDump(s32 arg0) {
    s32 temp_s0;

    temp_s0 = arg0 & 0xFFFF7FFF;
    DBG_SendMessage("%d : mem left", GAL_GetFreeMem(temp_s0));
    DBG_SendMessage("%d : largest block", GAL_GetFreeMem(temp_s0));
    DBG_SendMessage("%d : Last attempted alloc", D_8011C9E0);
}
#endif
#if 0 /* ida */
void __fastcall GAL_MemDump(int a1)
{
  unsigned int v1; // $s0

  v1 = a1 & 0xFFFF7FFF;
  GAL_GetFreeMem(a1 & 0xFFFF7FFF);
  DBG_SendMessage();
  GAL_GetFreeMem(v1);
  DBG_SendMessage();
  DBG_SendMessage();
}
#endif

/* ---- 0x80022FF8  GAL_SetVerbosity  GAL.C:2356-2357  seg lib  fsize 0 ---- */
/* void GAL_SetVerbosity(enum GAL_VERB_LEV G)
 *   G=$a0
 */
/* linked from build/src/lib.c.o (segment lib mixes several source files) — INCLUDE_ASM("asm/nonmatchings/lib", GAL_SetVerbosity) */
#if 0 /* m2c */
void GAL_SetVerbosity(s32 arg0) {
    D_8011C9E8 = arg0;
}
#endif
#if 0 /* ida */
void __fastcall GAL_SetVerbosity(int a1)
{
  MEMORY[0x8011C9E8] = a1;
}
#endif

/* ---- 0x80023008  CountFreeBlocks  GAL.C:2370-2384  seg lib  fsize 0 ---- */
/* int CountFreeBlocks(void)
 *   RetBlock=$v1 Count=$v0
 *   blocks: {2 }15
 */
/* linked from build/src/lib.c.o (segment lib mixes several source files) — INCLUDE_ASM("asm/nonmatchings/lib", CountFreeBlocks) */
#if 0 /* m2c */
void CountFreeBlocks(void) {
    void *var_v1;

    var_v1 = D_8011C9D0;
    if (var_v1 != NULL) {
        do {
            var_v1 = M2C_FIELD(var_v1, void **, 4);
        } while (var_v1 != NULL);
    }
}
#endif
#if 0 /* ida */
int CountFreeBlocks()
{
  int v0; // $v1
  int result; // $v0

  v0 = MEMORY[0x8011C9D0];
  for ( result = 0; v0 != 0; ++result )
    v0 = *(_DWORD *)(v0 + 4);
  return result;
}
#endif

/* ---- 0x80023034  SetBlockName  GAL.C:2396-2408  seg lib  fsize 8 ---- */
/* void SetBlockName(struct MEM_HDR *MemHdr, char *NewName)
 *   MemHdr=$a0 NewName=$a1 IndexSoFar=$a2
 *   blocks: {1 }13
 */
/* linked from build/src/lib.c.o (segment lib mixes several source files) — INCLUDE_ASM("asm/nonmatchings/lib", SetBlockName) */
#if 0 /* m2c */
void SetBlockName(s32 arg0, s8 *arg1) {
    s32 var_a2;
    s8 *var_a1;
    s8 temp_v0;

    var_a1 = arg1;
    var_a2 = 0;
    if (var_a1 != NULL) {
loop_2:
        temp_v0 = *var_a1;
        if (temp_v0 != 0) {
            M2C_FIELD((arg0 + var_a2), s8 *, 0x18) = temp_v0;
            var_a2 += 1;
            var_a1 += 1;
            if (var_a2 != 3) {
                goto loop_2;
            }
        }
    }
    M2C_FIELD((arg0 + var_a2), s8 *, 0x18) = 0;
}
#endif
#if 0 /* ida */
int __fastcall SetBlockName(int a1, _BYTE *a2)
{
  int v2; // $a2

  v2 = 0;
  if ( a2 != nullptr )
  {
    do
    {
      if ( *a2 == 0 )
        break;
      *(_BYTE *)(a1 + v2++ + 24) = *a2++;
    }
    while ( v2 != 3 );
  }
  *(_BYTE *)(a1 + v2 + 24) = 0;
  return a1 + v2;
}
#endif

/* ---- 0x8002307C  GAL_GetNumFreeHeaders  GAL.C:2417-2418  seg lib  fsize 0 ---- */
/* int GAL_GetNumFreeHeaders(void)
 */
/* linked from build/src/lib.c.o (segment lib mixes several source files) — INCLUDE_ASM("asm/nonmatchings/lib", GAL_GetNumFreeHeaders) */
#if 0 /* m2c */
s32 GAL_GetNumFreeHeaders(void) {
    return D_8011C9EC;
}
#endif

/* ---- 0x8002308C  GAL_GetLastTypeAlloced  GAL.C:2422-2423  seg lib  fsize 0 ---- */
/* unsigned long GAL_GetLastTypeAlloced(void)
 */
/* linked from build/src/lib.c.o (segment lib mixes several source files) — INCLUDE_ASM("asm/nonmatchings/lib", GAL_GetLastTypeAlloced) */
#if 0 /* m2c */
s32 GAL_GetLastTypeAlloced(void) {
    return D_8011C9F0;
}
#endif

/* ---- 0x8002309C  GAL_SetAllocFilter  GAL.C:2433-2440  seg lib  fsize 0 ---- */
/* void *()() GAL_SetAllocFilter(void *(NewFilter)())
 *   NewFilter=$a0 OldFilter=$v0
 *   blocks: {2 }8
 */
/* linked from build/src/lib.c.o (segment lib mixes several source files) — INCLUDE_ASM("asm/nonmatchings/lib", GAL_SetAllocFilter) */
#if 0 /* m2c */
s32 GAL_SetAllocFilter(s32 arg0) {
    s32 temp_v0;

    temp_v0 = D_8011C9F4;
    D_8011C9F4 = arg0;
    return temp_v0;
}
#endif

/* ---- 0x800230B4  GAL_SortUsedRegionsBySize  GAL.C:2449-2461  seg lib  fsize 24 ---- */
/* unsigned char GAL_SortUsedRegionsBySize(unsigned long MemType)
 *   MemType=$a0 M=$v0
 *   blocks: {1 }13
 */
/* linked from build/src/lib.c.o (segment lib mixes several source files) — INCLUDE_ASM("asm/nonmatchings/lib", GAL_SortUsedRegionsBySize) */
#if 0 /* m2c */
s32 GAL_SortUsedRegionsBySize(s32 arg0) {
    s32 temp_v0;

    temp_v0 = GetMemInitInfoBlockFromType(arg0 & 0xFFFF7FFF);
    if (temp_v0 != 0) {
        SortMemHdrList(temp_v0 + 0x24, &SortSize);
        return 1;
    }
    GSetError(4);
    return 0;
}
#endif
#if 0 /* ida */
int __fastcall GAL_SortUsedRegionsBySize(int a1)
{
  int v1; // $v0

  v1 = GetMemInitInfoBlockFromType(a1 & 0xFFFF7FFF);
  if ( v1 != 0 )
  {
    SortMemHdrList((int **)(v1 + 36), (unsigned __int8 (__fastcall *)(int *, int *))SortSize);
    return 1;
  }
  else
  {
    GSetError(4);
    return 0;
  }
}
#endif

/* ---- 0x80023108  SortSize  GAL.C:2464-2465  seg lib  fsize 0 ---- */
/* unsigned char SortSize(struct MEM_HDR *B1, struct MEM_HDR *B2)
 *   B1=$a0 B2=$a1
 */
/* linked from build/src/lib.c.o (segment lib mixes several source files) — INCLUDE_ASM("asm/nonmatchings/lib", SortSize) */
#if 0 /* m2c */
s32 SortSize(void *arg0, void *arg1) {
    return (u32) M2C_FIELD(arg0, u32 *, 0xC) < (u32) M2C_FIELD(arg1, u32 *, 0xC);
}
#endif
#if 0 /* ida */
BOOL __fastcall SortSize(int a1, int a2)
{
  return *(_DWORD *)(a1 + 12) < *(_DWORD *)(a2 + 12);
}
#endif

/* ---- 0x80023118  GAL_SortUsedRegionsByAddress  GAL.C:2477-2489  seg lib  fsize 24 ---- */
/* unsigned char GAL_SortUsedRegionsByAddress(unsigned long MemType)
 *   MemType=$a0 M=$v0
 *   blocks: {1 }13
 */
/* linked from build/src/lib.c.o (segment lib mixes several source files) — INCLUDE_ASM("asm/nonmatchings/lib", GAL_SortUsedRegionsByAddress) */
#if 0 /* m2c */
s32 GAL_SortUsedRegionsByAddress(s32 arg0) {
    s32 temp_v0;

    temp_v0 = GetMemInitInfoBlockFromType(arg0 & 0xFFFF7FFF);
    if (temp_v0 != 0) {
        SortMemHdrList(temp_v0 + 0x24, &SortAddr);
        return 1;
    }
    GSetError(4);
    return 0;
}
#endif
#if 0 /* ida */
int __fastcall GAL_SortUsedRegionsByAddress(int a1)
{
  int v1; // $v0

  v1 = GetMemInitInfoBlockFromType(a1 & 0xFFFF7FFF);
  if ( v1 != 0 )
  {
    SortMemHdrList((int **)(v1 + 36), (unsigned __int8 (__fastcall *)(int *, int *))SortAddr);
    return 1;
  }
  else
  {
    GSetError(4);
    return 0;
  }
}
#endif

/* ---- 0x8002316C  SortAddr  GAL.C:2492-2493  seg lib  fsize 0 ---- */
/* unsigned char SortAddr(struct MEM_HDR *B1, struct MEM_HDR *B2)
 *   B1=$a0 B2=$a1
 */
/* linked from build/src/lib.c.o (segment lib mixes several source files) — INCLUDE_ASM("asm/nonmatchings/lib", SortAddr) */
#if 0 /* m2c */
s32 SortAddr(void *arg0, void *arg1) {
    return (u32) M2C_FIELD(arg0, u32 *, 8) < (u32) M2C_FIELD(arg1, u32 *, 8);
}
#endif
#if 0 /* ida */
BOOL __fastcall SortAddr(int a1, int a2)
{
  return *(_DWORD *)(a1 + 8) < *(_DWORD *)(a2 + 8);
}
#endif

/* ---- 0x8002317C  SortMemHdrList  GAL.C:2507-2556  seg lib  fsize 40 ---- */
/* void SortMemHdrList(struct MEM_HDR **Head, unsigned char *(CompFunc)())
 *   Head=$s3 CompFunc=$s4 DidASwap=$s2 CurHdr=$s0 NextHdr=$s1 OldPrev=$v1
 *   blocks: {1 {21 }40 }50
 */
/* linked from build/src/lib.c.o (segment lib mixes several source files) — INCLUDE_ASM("asm/nonmatchings/lib", SortMemHdrList) */
#if 0 /* m2c */
void SortMemHdrList(void **arg0, s32 (*arg1)(void *, void *)) {
    s32 var_s2;
    void *temp_s1;
    void *temp_v0;
    void *temp_v0_2;
    void *temp_v1;
    void *var_s0;

    temp_v0 = *arg0;
    if (temp_v0 != NULL) {
        var_s2 = 0;
        if (M2C_FIELD(temp_v0, s32 *, 4) != 0) {
            do {
                var_s0 = *arg0;
loop_3:
                temp_s1 = M2C_FIELD(var_s0, void **, 4);
                if (arg1(var_s0, temp_s1) & 0xFF) {
                    temp_v1 = M2C_FIELD(var_s0, void **, 0);
                    M2C_FIELD(var_s0, void **, 0) = temp_s1;
                    M2C_FIELD(var_s0, void **, 4) = (void *) M2C_FIELD(temp_s1, void **, 4);
                    M2C_FIELD(temp_s1, void **, 4) = var_s0;
                    temp_v0_2 = M2C_FIELD(var_s0, void **, 4);
                    if (temp_v0_2 != NULL) {
                        M2C_FIELD(temp_v0_2, void **, 0) = var_s0;
                        M2C_FIELD(temp_s1, void **, 4) = var_s0;
                    }
                    M2C_FIELD(temp_s1, void **, 0) = temp_v1;
                    if (temp_v1 != NULL) {
                        M2C_FIELD(temp_v1, void **, 4) = temp_s1;
                    } else {
                        *arg0 = temp_s1;
                    }
                    var_s2 = 1;
                } else {
                    var_s0 = M2C_FIELD(var_s0, void **, 4);
                }
                if (M2C_FIELD(var_s0, s32 *, 4) != 0) {
                    goto loop_3;
                }
                var_s2 = 0;
            } while (var_s2 & 0xFF);
        }
    }
}
#endif
#if 0 /* ida */
int *__fastcall SortMemHdrList(int **a1, unsigned __int8 (__fastcall *a2)(int *, int *))
{
  int *result; // $v0
  unsigned __int8 i; // $s2
  int *v6; // $s0
  int *v7; // $s1
  int v8; // $v1
  int v9; // $v0
  int **v10; // $v0

  result = *a1;
  if ( *a1 != nullptr )
  {
    result = (int *)result[1];
    for ( i = 0; result != nullptr; i = 0 )
    {
      v6 = *a1;
      do
      {
        v7 = (int *)v6[1];
        if ( a2(v6, v7) != 0 )
        {
          v8 = *v6;
          v9 = v7[1];
          *v6 = (int)v7;
          v6[1] = v9;
          v7[1] = (int)v6;
          v10 = (int **)v6[1];
          if ( v10 != nullptr )
          {
            *v10 = v6;
            v7[1] = (int)v6;
          }
          *v7 = v8;
          if ( v8 != 0 )
            *(_DWORD *)(v8 + 4) = v7;
          else
            *a1 = v7;
          i = 1;
        }
        else
        {
          v6 = (int *)v6[1];
        }
        result = (int *)i;
      }
      while ( v6[1] != 0 );
    }
  }
  return result;
}
#endif
