/* GLIBDEV/SOURCE/GMAIN.C — linked skeleton generated by tools/gen_skeleton.py from DIABPSX.SYM (1 functions).
 * Each function: SYM signature/registers, INCLUDE_ASM of the retail oracle (links byte-identical),
 * then the m2c and Hex-Rays drafts under #if 0.  Replace one INCLUDE_ASM at a time with C. */
#include "common.h"

/* ---- 0x80020E04  main  GMAIN.C:31-39  seg lib  fsize 24 ---- */
/* void main(void)
 */
/* linked from build/src/lib.c.o (segment lib mixes several source files) — INCLUDE_ASM("asm/nonmatchings/lib", main) */
#if 0 /* m2c */
void main(void) {
    __main();
    GSYS_InitMachine();
    GAL_InitModule();
    TICK_InitModule();
    GU_InitModule();
    AppMain();
loop_1:
    goto loop_1;
}
#endif
#if 0 /* ida */
void __noreturn main()
{
  __main();
  GSYS_InitMachine();
  GAL_InitModule();
  TICK_InitModule();
  GU_InitModule();
  AppMain();
}
#endif
