name: Diablo (Japan) overlay PREGAME (SYM id $c) - rom/PREGAME.BIN
options:
  base_path: ..
  basename: pregame
  target_path: rom/PREGAME.BIN
  platform: psx
  compiler: GCC
  asm_path: asm
  src_path: src
  build_path: build
  ld_script_path: linkers/pregame.ld
  gp_value: 0x8011A780
  global_vram_start: 0x80010000
  global_vram_end: 0x80200000
  use_legacy_include_asm: False
  asm_function_macro: glabel
  asm_jtbl_label_macro: jlabel
  asm_data_macro: dlabel
  generate_asm_macros_files: False
  symbol_addrs_path:
    - configs/symbol_addrs.txt
    - configs/symbol_addrs_pregame.txt
  undefined_funcs_auto_path: linkers/undefined_funcs_auto_pregame.txt
  undefined_syms_auto_path: linkers/undefined_syms_auto_pregame.txt
  section_order: [.text, .data, .rodata, .sdata, .sbss, .bss]
  find_file_boundaries: False
  disasm_unknown: True

segments:
  - name: pregame
    type: code
    subalign: 4
    start: 0x0
    vram: 0x80139BF8
    subsegments:
      - [0x000000, data, pregame_hdr]
      - [0x000004, c, pregame]
      - [0x00002C, rodata, drlg_l1_rodata_80139c24]
      - [0x00055C, rodata, drlg_l1_rodata_8013a154]
      - [0x00062C, rodata, drlg_l1_rodata_8013a224]
      - [0x0006FC, rodata, drlg_l1_rodata_8013a2f4]
      - [0x000720, rodata, drlg_l1_rodata_8013a318]
      - [0x000744, rodata, drlg_l1_rodata_8013a33c]
      - [0x000760, rodata, drlg_l1_rodata_8013a358]
      - [0x00076C, rodata, drlg_l1_rodata_8013a364]
      - [0x0007B8, rodata, drlg_l1_rodata_8013a3b0]
      - [0x0020B8, c, drlg_l1]
      - [0x0072FC, rodata, drlg_l2_rodata_80140ef4]
      - [0x007344, rodata, drlg_l2_rodata_80140f3c]
      - [0x0073E8, rodata, drlg_l2_rodata_80140fe0]
      - [0x00748C, rodata, drlg_l2_rodata_80141084]
      - [0x0074A0, rodata, drlg_l2_rodata_80141098]
      - [0x0074B4, rodata, drlg_l2_rodata_801410ac]
      - [0x0074C8, rodata, drlg_l2_rodata_801410c0]
      - [0x0074DC, rodata, drlg_l2_rodata_801410d4]
      - [0x0074F0, rodata, drlg_l2_rodata_801410e8]
      - [0x007504, rodata, drlg_l2_rodata_801410fc]
      - [0x007518, rodata, drlg_l2_rodata_80141110]
      - [0x00752C, rodata, drlg_l2_rodata_80141124]
      - [0x007540, rodata, drlg_l2_rodata_80141138]
      - [0x007554, rodata, drlg_l2_rodata_8014114c]
      - [0x007568, rodata, drlg_l2_rodata_80141160]
      - [0x00757C, rodata, drlg_l2_rodata_80141174]
      - [0x007590, rodata, drlg_l2_rodata_80141188]
      - [0x0075A4, rodata, drlg_l2_rodata_8014119c]
      - [0x0075B8, rodata, drlg_l2_rodata_801411b0]
      - [0x0075CC, rodata, drlg_l2_rodata_801411c4]
      - [0x0075DC, rodata, drlg_l2_rodata_801411d4]
      - [0x0075EC, rodata, drlg_l2_rodata_801411e4]
      - [0x0075FC, rodata, drlg_l2_rodata_801411f4]
      - [0x00760C, rodata, drlg_l2_rodata_80141204]
      - [0x00761C, rodata, drlg_l2_rodata_80141214]
      - [0x00762C, rodata, drlg_l2_rodata_80141224]
      - [0x00763C, rodata, drlg_l2_rodata_80141234]
      - [0x00764C, rodata, drlg_l2_rodata_80141244]
      - [0x007660, rodata, drlg_l2_rodata_80141258]
      - [0x007674, rodata, drlg_l2_rodata_8014126c]
      - [0x007688, rodata, drlg_l2_rodata_80141280]
      - [0x00769C, rodata, drlg_l2_rodata_80141294]
      - [0x0076B0, rodata, drlg_l2_rodata_801412a8]
      - [0x0076C4, rodata, drlg_l2_rodata_801412bc]
      - [0x0076D8, rodata, drlg_l2_rodata_801412d0]
      - [0x0076EC, rodata, drlg_l2_rodata_801412e4]
      - [0x007700, rodata, drlg_l2_rodata_801412f8]
      - [0x007714, rodata, drlg_l2_rodata_8014130c]
      - [0x007728, rodata, drlg_l2_rodata_80141320]
      - [0x00773C, rodata, drlg_l2_rodata_80141334]
      - [0x007750, rodata, drlg_l2_rodata_80141348]
      - [0x007764, rodata, drlg_l2_rodata_8014135c]
      - [0x007778, rodata, drlg_l2_rodata_80141370]
      - [0x00778C, rodata, drlg_l2_rodata_80141384]
      - [0x00779C, rodata, drlg_l2_rodata_80141394]
      - [0x0077AC, rodata, drlg_l2_rodata_801413a4]
      - [0x0077BC, rodata, drlg_l2_rodata_801413b4]
      - [0x0077CC, rodata, drlg_l2_rodata_801413c4]
      - [0x0077DC, rodata, drlg_l2_rodata_801413d4]
      - [0x0077EC, rodata, drlg_l2_rodata_801413e4]
      - [0x0077FC, rodata, drlg_l2_rodata_801413f4]
      - [0x00780C, rodata, drlg_l2_rodata_80141404]
      - [0x00781C, rodata, drlg_l2_rodata_80141414]
      - [0x00782C, rodata, drlg_l2_rodata_80141424]
      - [0x00783C, rodata, drlg_l2_rodata_80141434]
      - [0x00784C, rodata, drlg_l2_rodata_80141444]
      - [0x00785C, rodata, drlg_l2_rodata_80141454]
      - [0x00786C, rodata, drlg_l2_rodata_80141464]
      - [0x00787C, rodata, drlg_l2_rodata_80141474]
      - [0x00788C, rodata, drlg_l2_rodata_80141484]
      - [0x00789C, rodata, drlg_l2_rodata_80141494]
      - [0x0078AC, rodata, drlg_l2_rodata_801414a4]
      - [0x0078BC, rodata, drlg_l2_rodata_801414b4]
      - [0x0078CC, rodata, drlg_l2_rodata_801414c4]
      - [0x0078DC, rodata, drlg_l2_rodata_801414d4]
      - [0x0078EC, rodata, drlg_l2_rodata_801414e4]
      - [0x0078FC, rodata, drlg_l2_rodata_801414f4]
      - [0x00790C, rodata, drlg_l2_rodata_80141504]
      - [0x00791C, rodata, drlg_l2_rodata_80141514]
      - [0x00792C, rodata, drlg_l2_rodata_80141524]
      - [0x00793C, rodata, drlg_l2_rodata_80141534]
      - [0x00794C, rodata, drlg_l2_rodata_80141544]
      - [0x00795C, rodata, drlg_l2_rodata_80141554]
      - [0x00796C, rodata, drlg_l2_rodata_80141564]
      - [0x00797C, rodata, drlg_l2_rodata_80141574]
      - [0x00798C, rodata, drlg_l2_rodata_80141584]
      - [0x00799C, rodata, drlg_l2_rodata_80141594]
      - [0x0079AC, rodata, drlg_l2_rodata_801415a4]
      - [0x0079BC, rodata, drlg_l2_rodata_801415b4]
      - [0x0079CC, rodata, drlg_l2_rodata_801415c4]
      - [0x0079DC, rodata, drlg_l2_rodata_801415d4]
      - [0x0079EC, rodata, drlg_l2_rodata_801415e4]
      - [0x0079FC, rodata, drlg_l2_rodata_801415f4]
      - [0x007A0C, rodata, drlg_l2_rodata_80141604]
      - [0x007A30, rodata, drlg_l2_rodata_80141628]
      - [0x007A54, rodata, drlg_l2_rodata_8014164c]
      - [0x007A78, rodata, drlg_l2_rodata_80141670]
      - [0x007A98, rodata, drlg_l2_rodata_80141690]
      - [0x007AA4, rodata, drlg_l2_rodata_8014169c]
      - [0x007AB0, rodata, drlg_l2_rodata_801416a8]
      - [0x007ABC, rodata, drlg_l2_rodata_801416b4]
      - [0x007AC8, rodata, drlg_l2_rodata_801416c0]
      - [0x007AD4, rodata, drlg_l2_rodata_801416cc]
      - [0x009810, c, drlg_l2]
      - [0x00EAAC, rodata, drlg_l3_rodata_801486a4]
      - [0x00EACC, rodata, drlg_l3_rodata_801486c4]
      - [0x00EADC, rodata, drlg_l3_rodata_801486d4]
      - [0x00EAEC, rodata, drlg_l3_rodata_801486e4]
      - [0x00EB5C, rodata, drlg_l3_rodata_80148754]
      - [0x00EB80, rodata, drlg_l3_rodata_80148778]
      - [0x00EBA4, rodata, drlg_l3_rodata_8014879c]
      - [0x00EBD0, rodata, drlg_l3_rodata_801487c8]
      - [0x00EC30, rodata, drlg_l3_rodata_80148828]
      - [0x00EC40, rodata, drlg_l3_rodata_80148838]
      - [0x00EC50, rodata, drlg_l3_rodata_80148848]
      - [0x00EC60, rodata, drlg_l3_rodata_80148858]
      - [0x00EC6C, rodata, drlg_l3_rodata_80148864]
      - [0x00F3A0, c, drlg_l3]
      - [0x013C00, rodata, drlg_l4_rodata_8014d7f8]
      - [0x01575C, rodata, drlg_l4_rodata_8014f354]
      - [0x015788, rodata, drlg_l4_rodata_8014f380]
      - [0x0158B0, c, drlg_l4]
      - [0x01B6E0, c, setmaps]
      - [0x01BE0C, c, choosem]
      - [0x01C3E0, c, preobj]
      - [0x0202E4, c, gendung]
      - [0x022014, c, themes]
      - [0x024B84, c, preport]
      - [0x024BE4, c, prequest]
      - [0x025878, c, preinv]
      - [0x0258CC, c, preauto]
      - [0x025AF0, c, premon]
      - [0x0283E4, c, premiss]
      - [0x0285B4, c, pretrigs]
      - [0x0290E4, c, prestore]
      - [0x0293DC, c, premsg]
  - [0x029DCC]
