"""Rebuild town tables from Hellfire source with explicit retail-verified PSX deltas.

--write emits a header; default is a read-only byte audit. This verifies
initializer payloads, not native placement or pointer relocations.
"""
import argparse
from pathlib import Path
import re
import struct
from gen_drlg_l2_tables import flatten, initializer, c_initializer

ROOT = Path(__file__).resolve().parents[1]
TABLES = [
    ('char','AnimOrder',[6,148],0x800CF7E4),
    ('int','TownCowX',[3],0x800CFB5C),
    ('int','TownCowY',[3],0x800CFB68),
    ('int','TownCowDir',[3],0x800CFB74),
    ('int','cowoffx',[8],0x800CFB80),
    ('int','cowoffy',[8],0x800CFBA0),
    ('int','Qtalklist',[11,16],0x800CFBC0),
]


def psx_values(name, value):
    if name == 'TownCowDir':
        if value != [1,3,4]:
            raise ValueError('gold cow directions changed')
        return [1,0,2]  # Retail PSX: southwest, south, west.
    if name == 'Qtalklist':
        if len(value) != 14 or any(len(row) != 24 for row in value):
            raise ValueError('gold Hellfire dialogue matrix changed')
        # Base-game NPCs and quests only; the eleventh PSX row is zero-filled.
        return [row[:16] for row in value[:10]]
    return value


def collect():
    folder = ROOT.parent/'refs/diablo-hellfire/src'
    gold = (folder/'TOWNERS.CPP').read_text(encoding='latin-1')
    gold = re.sub(r'/\*.*?\*/|//[^\n]*','',gold,flags=re.S)
    headers = '\n'.join((folder/name).read_text(encoding='latin-1') for name in ('PLAYER.H','TEXTDAT.H'))
    constants = dict(re.findall(r'^\s*#define\s+(\w+)\s+(-?(?:0x[0-9a-fA-F]+|\d+))\b',headers,re.M))
    gold = re.sub(r'\b[A-Za-z_]\w*\b',lambda m:constants.get(m[0],m[0]),gold)
    retail = (ROOT/'rom/DIABPSX.BIN').read_bytes()
    rows = []
    for typ,name,shape,va in TABLES:
        matches = list(re.finditer(r'\b'+name+r'\s*(?:\[[^]]*\]\s*)+=\s*(\{.*?\})\s*;',gold,re.S))
        if len(matches) != 1:
            raise ValueError(f'{name}: gold initializer ambiguous/missing')
        value = psx_values(name,initializer(matches[0][1]))
        numbers = flatten(value,shape)
        data = struct.pack('<'+('b' if typ=='char' else 'i')*len(numbers),*numbers)
        at = va-0x80010000
        if data != retail[at:at+len(data)]:
            raise ValueError(f'{name}: source values differ from retail')
        rows.append(f'/* Retail 0x{va:08X}, {len(data)} bytes. */\n{typ} {name}'+''.join(f'[{d}]' for d in shape)+' = '+c_initializer(value)+';')
    return rows


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--write',action='store_true')
    args = parser.parse_args()
    rows = collect()
    if args.write:
        text = ('/* Generated by tools/gen_towner_tables.py from original Hellfire TOWNERS.CPP.\n'
                ' * PSX deltas: cow directions 1/0/2; ten base-game NPC rows and sixteen\n'
                ' * quests, with the eleventh Qtalklist row implicitly zero-filled. */\n\n')
        (ROOT/'recon/source/gen/tables_towners.h').write_text(text+'\n\n'.join(rows)+'\n',encoding='utf-8')
    print('7 town tables match 1692 retail bytes; header '+('written' if args.write else 'not modified'))


if __name__ == '__main__':
    main()
