"""Recover GLUE's typed player texture table from the immutable retail image.

Only data is decoded. The generated initializer owns its strings and numeric
texture IDs; no retail instructions or compiled object bytes are copied.
"""
from pathlib import Path
import struct
import sys

ROOT = Path(__file__).resolve().parent.parent


def decode(image):
    rows = []
    for index in range(81):
        offset = 0x800CBF98 - 0x80010000 + index * 12
        pointer, game, town, two, padding = struct.unpack_from('<I4H', image, offset)
        if pointer != 0x8011AEAC + index * 4 or padding:
            raise ValueError('unexpected PlayerInfo pointer/padding at row ' + str(index))
        text = image[pointer - 0x80010000:pointer - 0x80010000 + 4]
        if len(text) != 4 or text[3] or not all(65 <= byte <= 90 for byte in text[:3]):
            raise ValueError('unexpected player texture identifier')
        rows.append((text[:3].decode('ascii'), game, town, two))
    return rows


def main():
    if sys.argv[1:] == ['--verify']:
        return verify()
    if sys.argv[1:]:
        raise SystemExit('usage: gen_glue_player_info.py [--verify]')
    rows = decode((ROOT / 'rom/DIABPSX.BIN').read_bytes())
    header = '/* Retail GLUE PlayerInfo: 81 PInf records, 972 bytes at 0x800CBF98.\n'
    header += ' * Strings occupy 0x8011AEAC..0x8011AFEF. Generated by gen_glue_player_info.py. */\n'
    header += 'PInf PlayerInfo[81] = {\n'
    header += ''.join('    {"%s", 0x%X, 0x%X, 0x%X},\n' % row for row in rows)
    header += '};\n'
    (ROOT / 'recon/psxsrc/gen/table_glue_player_info.h').write_text(header)
    print('Generated 81 typed PlayerInfo rows with 81 checked identifiers')


def verify():
    import build as B
    from data_gate import Elf
    image = (ROOT / 'rom/DIABPSX.BIN').read_bytes()
    decode(image)
    elf = Elf(B.compile_any(ROOT / 'recon/psxsrc/glue.cpp'))
    data_index, strings_index = elf.indices['.data'], elf.indices['.sdata']
    symbols = [s for entries in elf.symbols.values() for s in entries if s[0] == 'PlayerInfo']
    if len(symbols) != 1 or symbols[0][1] != 0 or symbols[0][-1] != data_index:
        raise ValueError('PlayerInfo does not own the expected source data section')
    data = bytearray(elf.bytes(data_index))
    if len(data) != 972:
        raise ValueError('unexpected PlayerInfo section extent')
    strings = elf.bytes(strings_index)[:324]
    if strings != image[0x10AEAC:0x10AFF0]:
        raise ValueError('source texture-name pool differs from retail')
    if elf.bytes(strings_index) != image[0x10AEAC:0x10B010]:
        raise ValueError('GLUE small-data payload/order differs from retail')
    seen = set()
    for index, section in enumerate(elf.sections):
        if section[1] != 9 or section[7] != data_index:
            continue
        for offset, info in struct.iter_unpack('<II', elf.bytes(index)):
            if info & 255 != 2 or offset in seen or offset % 12 or offset >= 972:
                raise ValueError('unexpected PlayerInfo relocation')
            symbol = elf.symbols[section[6]][info >> 8]
            if symbol[-1] != strings_index:
                raise ValueError('texture pointer does not target the owned string pool')
            target = symbol[1] + struct.unpack_from('<I', data, offset)[0]
            if target != offset // 12 * 4:
                raise ValueError('texture pointer has the wrong pool offset')
            struct.pack_into('<I', data, offset, 0x8011AEAC + target)
            seen.add(offset)
    if seen != set(range(0, 972, 12)) or data != image[0xBBF98:0xBC364]:
        raise ValueError('relocated source table differs from retail')
    print('PlayerInfo: DATA PASS (972 bytes, 81 relocations, 324 owned string bytes)')
    if elf.bytes(elf.indices['.rodata']) != image[0x100B34:0x100B72]:
        raise ValueError('GLUE header/filename/weapon pool differs from retail')
    bss = elf.indices['.sbss']
    if elf.sections[bss][1] != 8 or elf.sections[bss][5] != 24:
        raise ValueError('GLUE small BSS must be exactly 24 zero-initialized bytes')
    expected = {'GlueFinished': 0, 'DoHomingScroll': 4, 'TownerGfx': 8,
                'CurrentMonsterList': 12, 'QuakeTime': 16, 'QuakeAmount': 20}
    for name, offset in expected.items():
        matches = [s for entries in elf.symbols.values() for s in entries if s[0] == name]
        if len(matches) != 1 or matches[0][1] != offset or matches[0][-1] != bss:
            raise ValueError('GLUE small-BSS placement differs: ' + name)
    print('GLUE pool/BSS: DATA PASS (62 readonly bytes, six globals in 24 zero BSS bytes)')


if __name__ == '__main__':
    main()
