#!/usr/bin/env python3
"""gen_ld.py — linker script in TRUE ROM ORDER from a splat yaml (splat's own script groups input
sections by type, which breaks an image whose text/data/rodata interleave).  Every subsegment is
pinned with `. = <vram>;` so a wrong-sized object fails the link at the culprit instead of
shifting everything after it.

    python tools/gen_ld.py [diabpsx|frontend|pregame|game|fmv ...]   -> linkers/<name>.ld

Object naming follows splat: c -> build/src/<name>.c.o, asm -> build/asm/<name>.s.o,
data/rodata/sdata/bss -> build/asm/data/<name>.<kind>.s.o.  A c subsegment contributes .text,
and — when a reconstructed TU provides them — .rodata/.data/.sdata are taken from the same object
in place of the splat data object (that swap is done here per subsegment name)."""
import re, sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
import json
_sm = ROOT / "skel" / "segments.json"
SKEL_MAP = json.loads(_sm.read_text()) if _sm.exists() else {}   # seg -> skeleton file (1:1 link units)
SECT = {"data": ".data", "rodata": ".rodata", "sdata": ".sdata", "bss": ".bss", "sbss": ".sbss"}

def gen(name: str):
    y = (ROOT / "configs" / f"{name}.yaml").read_text()
    vram = int(re.search(r"^\s+vram: (0x[0-9A-F]+)", y, re.M).group(1), 16)
    gp = re.search(r"gp_value: (0x[0-9A-F]+)", y).group(1)
    subs = [(int(o, 16), k, n) for o, k, n in re.findall(r"^\s+- \[0x([0-9A-F]+), (\w+), (\w+)\]", y, re.M)]
    end = int(re.search(r"^\s+- \[0x([0-9A-F]+)\]\s*$", y, re.M).group(1), 16)
    bss = re.search(r"bss_size: (0x[0-9A-F]+)", y)
    out = ["/* generated by tools/gen_ld.py: true ROM order, every subsegment pinned to its retail address */",
           "SECTIONS", "{", f"    _gp = {gp};", f"    __romPos = 0;",
           f"    .{name} 0x{vram:08X} : AT(0) SUBALIGN(4)", "    {"]
    for i, (off, kind, n) in enumerate(subs):
        va = vram + off
        out.append(f"        . = 0x{off:X};   /* 0x{va:08X} */")   # inside an output section `.` is the offset from its start
        if kind == "c":
            skel = SKEL_MAP.get(n)
            out.append(f"        build/skel/{skel}.o(.text);" if skel else f"        build/src/{n}.c.o(.text);")
        elif kind == "asm":
            out.append(f"        build/asm/{n}.s.o(.text);")
        elif kind in SECT:
            out.append(f"        build/asm/data/{n}.{kind}.s.o({SECT[kind]});")
        else:
            sys.exit(f"{name}: unknown subsegment kind {kind} ({n})")
    out.append(f"        . = 0x{end:X};   /* image end 0x{vram + end:08X} */")
    if bss:
        out.append(f"        {name}_BSS_START = .;")
        out.append(f"        . += {bss.group(1)};   /* .sbss + .bss zero fill (not in the file) */")
    out += ["    }", "    /DISCARD/ : { *(.reginfo) *(.mdebug*) *(.comment) *(.pdr) *(.gnu.attributes) *(.MIPS.abiflags) }", "}"]
    (ROOT / "linkers" / f"{name}.ld").write_text("\n".join(out) + "\n")
    print(f"{name}: {len(subs)} subsegments -> linkers/{name}.ld")

if __name__ == "__main__":
    for n in (sys.argv[1:] or ["diabpsx", "frontend", "pregame", "game", "fmv"]):
        gen(n)
