"""Emit DRLG_L2's initialized tables from gold PC source, only after retail comparison.

Default is a read-only audit; --write updates the generated source header.
ROM supplies verification bytes only, never initializer values. This does not
verify compiled section placement, padding, SYM or relocations.
"""
import argparse
import ast
import math
from pathlib import Path
import re
import struct

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / 'recon/source/gen/tables_drlg_l2.h'


def flatten(value, dims):
    if not dims:
        if isinstance(value, list):
            if len(value) != 1:
                raise ValueError('invalid scalar initializer')
            value = value[0]
        if type(value) is not int:
            raise ValueError('initializer must contain integer constants')
        return [value]
    if not isinstance(value, list) or len(value) > dims[0]:
        raise ValueError('invalid aggregate shape')
    result = []
    for row in value:
        result.extend(flatten(row, dims[1:]))
    return result + [0] * ((dims[0] - len(value)) * math.prod(dims[1:]))


def initializer(text):
    text = re.sub(r'/\*.*?\*/|//[^\n]*', '', text, flags=re.S)
    return ast.literal_eval(text.replace('{', '[').replace('}', ']'))


def c_initializer(value):
    if not isinstance(value, list):
        return str(value)
    if any(isinstance(v, list) for v in value):
        return '{\n    ' + ',\n    '.join(c_initializer(v) for v in value) + '\n}'
    return '{\n    ' + ',\n    '.join(', '.join(map(str, value[i:i+16]))
                                      for i in range(0, len(value), 16)) + '\n}'


def collect():
    goldpath = ROOT.parent / 'refs/diablo-hellfire/src/DRLG_L2.CPP'
    gold = re.sub(r'/\*.*?\*/|//[^\n]*', '', goldpath.read_text(encoding='latin-1'), flags=re.S)
    constants = dict(re.findall(r'^\s*#define\s+(\w+)\s+(-?(?:0x[0-9a-fA-F]+|\d+))\b',
                               goldpath.with_suffix('.H').read_text(encoding='latin-1'), re.M))
    gold = re.sub(r'\b[A-Za-z_]\w*\b', lambda m: constants.get(m[0], m[0]), gold)
    overlay = (ROOT/'rom/PREGAME.BIN').read_bytes()
    main = (ROOT/'rom/DIABPSX.BIN').read_bytes()
    declarations = (ROOT/'recon/source/gen/externs_drlg_l2.h').read_text()
    rows = []
    pattern = r'extern (unsigned char|int|struct ShadowStruct) (\w+)((?:\[\d+\])+);\s*/\* @0x([0-9A-F]+)'
    for typ, name, dims, va in re.findall(pattern, declarations):
        address = int(va, 16)
        if not (0x80140EF4 <= address < 0x80143408 or 0x8011BE88 <= address <= 0x8011BEC0):
            continue
        # PC predungeon is uninitialized, unlike these source initializers.
        if name == 'predungeon':
            continue
        matches = list(re.finditer(r'\b'+re.escape(name)+r'\s*(?:\[[^]]*\]\s*)+=\s*(\{.*?\})\s*;', gold, re.S))
        if len(matches) != 1:
            raise ValueError(f'{name}: expected one gold initializer')
        value = initializer(matches[0][1])
        shape = [int(n) for n in re.findall(r'\d+', dims)] + ([7] if typ == 'struct ShadowStruct' else [])
        values = flatten(value, shape)
        data = struct.pack('<'+('i' if typ == 'int' else 'B')*len(values), *values)
        image, base = (overlay, 0x80139BF8) if address >= 0x80140000 else (main, 0x80010000)
        expected = image[address-base:address-base+len(data)]
        if data != expected:
            raise ValueError(f'{name}: gold initializer differs from retail')
        rows.append((typ, name, dims, value, address, len(data)))
    if len(rows) != 117 or sum(row[5] for row in rows) != 6082:
        raise ValueError('table census changed; review coverage before emitting')
    return rows


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--write', action='store_true')
    parser.add_argument('--verify', action='store_true', help='also verify source-emitted ELF data and SDB array extents')
    args = parser.parse_args()
    rows = collect()
    text = ('/* Generated by tools/gen_drlg_l2_tables.py from original Hellfire DRLG_L2.CPP/H.\n'
            ' * All 117 initializers independently compared with retail PSX bytes. */\n')
    text += '\n\n'.join(f'/* Retail 0x{va:08X}, {size} bytes. */\n{typ} {name}{dims} = {c_initializer(value)};'
                        for typ, name, dims, value, va, size in rows) + '\n'
    if args.write:
        OUTPUT.write_text(text, encoding='utf-8')
    print(f'117 gold initializers match 6082 retail bytes; header {"written" if args.write else "not modified"}')
    if args.verify:
        verify_compiled(rows)


def verify_compiled(rows):
    import build as B
    from data_gate import Elf
    import symlane as S
    source = ROOT/'recon/source/drlg_l2.cpp'
    elf = Elf(B.compile_any(source))
    receipt = S.link(S.compile_g(source)).read_text(errors='replace')
    for typ, name, dims, value, va, wanted_size in rows:
        matches = [s for group in elf.symbols.values() for s in group if s[0] == name]
        if len(matches) != 1:
            raise ValueError(f'{name}: ambiguous/missing compiled symbol')
        _, offset, size, info, _, index = matches[0]
        if index <= 0 or index >= len(elf.sections) or info & 15 not in (0, 1):
            raise ValueError(f'{name}: not a defined data symbol')
        section = elf.sections[index]
        if section[1] != 1 or elf.names[index] not in ('.data', '.sdata', '.rdata', '.rodata'):
            raise ValueError(f'{name}: not initialized data')
        sizes = re.findall(r'^\w+:\s+\$\w+\s+\d+ Def2 class (?:EXT|STAT) type ARY.*? size (\d+).*? name '+re.escape(name)+r'\s*$', receipt, re.M)
        if sizes != [str(wanted_size)] or size not in (0, wanted_size) or offset + wanted_size > section[5]:
            raise ValueError(f'{name}: incorrect compiled extent')
        for i, rel in enumerate(elf.sections):
            if rel[1] not in (4, 9) or rel[7] != index:
                continue
            stride = 12 if rel[1] == 4 else 8
            entries = elf.bytes(i)
            if len(entries) % stride:
                raise ValueError('malformed relocation section')
            for at in range(0, len(entries), stride):
                where, relocation = struct.unpack_from('<II', entries, at)
                width = 8 if relocation & 255 == 18 else 4
                if where < offset + wanted_size and where + width > offset:
                    raise ValueError(f'{name}: unexpected relocation')
        shape = [int(n) for n in re.findall(r'\d+', dims)] + ([7] if typ == 'struct ShadowStruct' else [])
        values = flatten(value, shape)
        expected = struct.pack('<'+('i' if typ == 'int' else 'B')*len(values), *values)
        if elf.bytes(index)[offset:offset+wanted_size] != expected:
            raise ValueError(f'{name}: compiled bytes differ')
    print('117 compiled tables: bytes and SDB extents match; no overlapping relocations')


if __name__ == '__main__':
    main()
