#!/usr/bin/env python3
"""Attribute checkpoint data names to explicit retail MAP object boundaries.

An enclosing section is not proof of an individual object's type or size.
Merged small-data/BSS pools are deliberately not assigned a guessed source owner.
"""
import re
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def build():
    checkpoint = (ROOT / 'docs/SOURCE_DEFINITIONS_CHECKPOINT_143.md').read_text(encoding='utf-8')
    names = re.findall(r'^\| `([^`]+)` \| `(0x[0-9A-F]+)` \|', checkpoint, re.M)
    map_text = (ROOT / 'rom/DIABPSX.MAP').read_text(encoding='latin-1')
    symbols = {}
    for address, name in re.findall(r'^\s*([0-9A-F]{8})\s+(\S+)\s*$', map_text, re.M):
        symbols.setdefault(name, set()).add(int(address, 16))
    regions = []
    for name, addresses in symbols.items():
        match = re.fullmatch(r'__(.+)_(data|rdata|text|bss|sbss|sdata)_obj', name)
        if not match:
            continue
        ends = symbols.get(name + 'end', set())
        if len(addresses) == len(ends) == 1:
            origin = name[:-3] + 'org'
            if (symbols.get(origin) != addresses
                    or symbols.get(origin + 'end') != ends):
                raise ValueError(f'{name}: object and origin bounds disagree')
            start, end = next(iter(addresses)), next(iter(ends))
            if end > start:
                regions.append((start, end, match[1], match[2]))
    sym_text = (ROOT / 'rom/DIABPSX-SYM.txt').read_text(encoding='latin-1')
    records = {}
    for address, declaration, name in re.findall(
            r'^\w+: \$([0-9a-fA-F]+) 9[46] (Def2? class .*?) name (\S+)\s*$',
            sym_text, re.M):
        records.setdefault((name, int(address, 16)), set()).add(declaration)
    inventory = json.loads((ROOT / 'build/native_program/inventory.json').read_text())
    if inventory['scope'] != 'complete':
        raise ValueError('ownership status requires a complete raw inventory')
    restored = {name for name, address in names} - set(inventory['missing_source_definitions'])
    lines = ['# Retail MAP ownership of missing-source checkpoint', '',
             'Generated by `python tools/map_source_owners.py` from retail MAP/SYM and',
             'the preserved 143-name checkpoint. Explicit object bounds prove section',
             'candidate ownership; they do not establish initializer values or individual extents.',
             'Shared pools without object bounds remain unassigned. Multiple enclosing',
             'objects are shown, not silently disambiguated by address alone.', '',
             f'{len(restored)} checkpoint names are resolved in the complete raw inventory;',
             f'{len(inventory["missing_source_definitions"])} missing source references remain.',
             '59 of the 60 single-MAP-candidate task entries are resolved; the TONY',
             'literal alias D_80110B24 remains open. Native ownership receipts are',
             'isolated proofs, not a strict whole-program native link seal.', '',
             '| Name | Retail VA | MAP object/section candidates | Retail typed SYM | Status |',
             '| --- | --- | --- | --- | --- |']
    assigned = 0
    unique = 0
    for name, address in names:
        va = int(address, 16)
        if name in symbols and va not in symbols[name]:
            raise ValueError(f'{name}: checkpoint address differs from retail MAP')
        owners = [f'{owner}.{section} (`0x{start:08X}`–`0x{end:08X}`, exclusive end)'
                  for start, end, owner, section in sorted(regions) if start <= va < end]
        assigned += bool(owners)
        unique += len(owners) == 1
        declaration = '; '.join(sorted(records.get((name, va), set()))) or 'No same-name typed record'
        status = 'Resolved; native owner verified' if name in restored else 'Current unresolved'
        lines.append(f'| `{name}` | `{address}` | {"; ".join(owners) or "No explicit object boundary"} | {declaration} | {status} |')
    lines += ['', f'{assigned}/{len(names)} checkpoint names have explicit enclosing MAP object boundaries;',
              f'{unique} have one candidate and {assigned - unique} have ambiguous overlapping candidates.', '']
    output = ROOT / 'docs/REMAINING_SOURCE_OWNERS.md'
    output.write_text('\n'.join(lines), encoding='utf-8')
    print(f'{assigned}/{len(names)} names attributed; report: {output}')


if __name__ == '__main__':
    build()
